### ISSUE TITLE
Permissions fail to create actions list entry if setting all of them at once

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyCDapp#1008]
I noticed this while working on #1004 whoever if seems very flaky and hard to reproduce.

- if you set all of the permissions to a new address they get set, and action shows up in the list
- if you then remove all of the permissions from that address they get removed, however the action does not show up in the list
- If you then try to set / remove permissions individually (ie: one permission at a time), they start showing up in the list

I think this is more to do with the Block Ingestor, rather than the UI.

So considerations / notes:
- Same behavior either with metatransactions on or off
- only noticed this developing locally
- no errors shown in the console, both client or server
- permissions always get set/removed and reflected accordingly to the transaction you've sent, just the entry in the actions list fails to get created

**Comment by willm30** [comment]
I am working on this, but can confirm it's flaky. Hopefully I'll be able to pinpoint exact cause, but in the meantime I have noticed one potential clue:

> 2023-09-21T11:21:14.367Z Could not execute mutation CreateColonyAction. Error:  [
>   {
>     message: 'Variable "$input" got invalid value { id: "0x0db85b75370a474004bfbc973859077dc4a2d67b909b0ae6035529fc8410dd36", colonyId: "0x5083264f2AEC01bd6cC2Fc4bC3785C2B92BcBb9A", blockNumber: 1028, createdAt: "2023-09-21T11:21:13.000Z", showInActionsList: true, type: "SET_USER_ROLES", fromDomainId: "0x5083264f2AEC01bd6cC2Fc4bC3785C2B92BcBb9A_1", recipientAddress: "0x9dF24e73f40b2a911Eb254A8825103723E13209C", roles: { role_0: false, role_1: false, role_2: false, role_3: false, role_5: false }, individualEvents: "[{\\"id\\":\\"0x0db85b75370a474004bfbc973859077dc4a2d67b909b0ae6035529fc8410dd36_0\\",\\"type\\":\\"RecoveryRoleSet\\",\\"setTo\\":false},{\\"id\\":\\"0x0db85b75370a474004bfbc973859077dc4a2d67b909b0ae6035529fc8410dd36_1\\",\\"type\\":\\"ColonyRoleSet\\",\\"role\\":0,\\"setTo\\":false},{\\"id\\":\\"0x0db85b75370a474004bfbc973859077dc4a2d67b909b0ae6035529fc8410dd36_2\\",\\"type\\":\\"ColonyRoleSet\\",\\"role\\":1,\\"setTo\\":false},{\\"id\\":\\"0x0db85b75370a474004bfbc973859077dc4a2d67b909b0ae6035529fc8410dd36_3\\",\\"type\\":\\"ColonyRoleSet\\",\\"role\\":2,\\"setTo\\":false},{\\"id\\":\\"0x0db85b75370a474004bfbc973859077dc4a2d67b909b0ae6035529fc8410dd36_4\\",\\"type\\":\\"ColonyRoleSet\\",\\"role\\":3,\\"setTo\\":false},{\\"id\\":\\"0x0db85b75370a474004bfbc973859077dc4a2d67b909b0ae6035529fc8410dd36_5\\",\\"type\\":\\"ColonyRoleSet\\",\\"role\\":5,\\"setTo\\":false}]" }; Field "initiatorAddress" of required type "ID!" was not provided.',
>     locations: [ [Object] ]
>   }
> ]


If the initiator address is not provided, it means the msg.sender is not being included in the event args... which would be weird. Maybe an ethers bug?

**Comment by willm30** [comment]
Yes, caught it. See the first part of the log, which is the event args. It's missing the initiator / msg.sender()

> 
> 2023-09-21T12:03:12.098Z Block 1039 added to the queue
> PERMISSIONS [
>   '0x27fF0C145E191C22C75cD123C679C3e1F58a4469',
>   true,
>   user: '0x27fF0C145E191C22C75cD123C679C3e1F58a4469',
>   setTo: true
> ] {"eventFragment":{"name":"RecoveryRoleSet","anonymous":false,"inputs":[{"name":"user","type":"address","indexed":true,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"address","_isParamType":true},{"name":"setTo","type":"bool","indexed":false,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"bool","_isParamType":true}],"type":"event","_isFragment":true},"name":"RecoveryRoleSet","signature":"RecoveryRoleSet(address,bool)","topic":"0x3af0c2ca023ed54860a0e58d41464c90cd7ff48f9d7ec1058275852d585cd144","args":["0x27fF0C145E191C22C75cD123C679C3e1F58a4469",true],"blockNumber":1038,"transactionHash":"0x79726468a522a9c70c0f8e49c696a82df315fca373b0c3c038540e3806cb3b42","logIndex":0,"contractAddress":"0x5083264f2AEC01bd6cC2Fc4bC3785C2B92BcBb9A","blockHash":"0xae4d73c699d19096961d8d04a623ca9c906014f11335d7977e12f6ac6c187fa7","timestamp":1695297789}
> 2023-09-21T12:03:12.171Z Update the Roles entry for 0x27fF0C145E191C22C75cD123C679C3e1F58a4469 in colony 0x5083264f2AEC01bd6cC2Fc4bC3785C2B92BcBb9A, under domain 1
> 2023-09-21T12:03:12.198Z Create new Historic Roles entry for 0x27fF0C145E191C22C75cD123C679C3e1F58a4469 in colony 0x5083264f2AEC01bd6cC2Fc4bC3785C2B92BcBb9A, under domain 1 at block 1038
> 2023-09-21T12:03:12.209Z Action SET_USER_ROLES took place in Colony: 0x5083264f2AEC01bd6cC2Fc4bC3785C2B92BcBb9A
> 2023-09-21T12:03:12.220Z Could not execute mutation CreateColonyAction. Error:  [
>   {
>     message: 'Variable "$input" got invalid value { id: "0x79726468a522a9c70c0f8e49c696a82df315fca373b0c3c038540e3806cb3b42", colonyId: "0x5083264f2AEC01bd6cC2Fc4bC3785C2B92BcBb9A", blockNumber: 1038, createdAt: "2023-09-21T12:03:09.000Z", showInActionsList: true, type: "SET_USER_ROLES", fromDomainId: "0x5083264f2AEC01bd6cC2Fc4bC3785C2B92BcBb9A_1", recipientAddress: "0x27fF0C145E191C22C75cD123C679C3e1F58a4469", roles: { role_0: true, role_1: true, role_2: true, role_3: true, role_5: true }, individualEvents: "[{\\"id\\":\\"0x79726468a522a9c70c0f8e49c696a82df315fca373b0c3c038540e3806cb3b42_0\\",\\"type\\":\\"RecoveryRoleSet\\",\\"setTo\\":true},{\\"id\\":\\"0x79726468a522a9c70c0f8e49c696a82df315fca373b0c3c038540e3806cb3b42_1\\",\\"type\\":\\"ColonyRoleSet\\",\\"role\\":0,\\"setTo\\":true},{\\"id\\":\\"0x79726468a522a9c70c0f8e49c696a82df315fca373b0c3c038540e3806cb3b42_2\\",\\"type\\":\\"ColonyRoleSet\\",\\"role\\":1,\\"setTo\\":true},{\\"id\\":\\"0x79726468a522a9c70c0f8e49c696a82df315fca373b0c3c038540e3806cb3b42_3\\",\\"type\\":\\"ColonyRoleSet\\",\\"role\\":2,\\"setTo\\":true},{\\"id\\":\\"0x79726468a522a9c70c0f8e49c696a82df315fca373b0c3c038540e3806cb3b42_4\\",\\"type\\":\\"ColonyRoleSet\\",\\"role\\":3,\\"setTo\\":true},{\\"id\\":\\"0x79726468a522a9c70c0f8e49c696a82df315fca373b0c3c038540e3806cb3b42_5\\",\\"type\\":\\"ColonyRoleSet\\",\\"role\\":5,\\"setTo\\":true}]" }; Field "initiatorAddress" of required type "ID!" was not provided.',
>     locations: [ [Object] ]
>   }
> ]

**Comment by willm30** [comment]
Ah, it's caused by setting the recovery role.
