### ISSUE TITLE
Fix edit decision bug

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#1027]
Go to Decision preview. `colony/{colonyName}/decisions/preview`
Click "edit". 
Editing the description alone doesn't validate the form, meaning you can't confirm.

(Or maybe it's editing the title alone doesn't validate the form... please double check which one it is.) 

TL;DR: I'm pretty sure this form isn't working correctly if you try to make an edit to a decision.

**Comment by rdig** [comment]
Needs to be investigated to determine if it's still relevant in the context of the new UI

**Comment by rdig** [comment]
Closing as not relevant anymore
