### ISSUE TITLE
"Bundling" extensions in the UI

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#1032]
As a user, I want to have the ability to view, install, and manage a subset of extensions as if it was a single extension.

For example, "Advanced Payments" extension could include Staked Expenditure, Staged Expenditure and Streaming Payments, and it should be displayed as a single extension, with one-click installation.

It should be kept generic so that an arbitrary extensions can be "bundled" together.

A few considerations need to be made, e.g.:
- What happens if one of the transactions fails
- How to handle extensions that require initialization params
- What to do if one of the bundled extension is interacted with on the chain, while others aren't

@arrenv fyi

**Comment by rdig** [comment]
Is this relevant anymore ?

**Comment by arrenv** [comment]
It would be nice if we could bundle extensions.

Although, in terms of the specific extensions mentioned in this issue, we have had to work around this limitation and it seems fine.

Until we have another specific use case for it, I think it is safe to close it. Open to other opinions though.
