### ISSUE TITLE
Restrict username change to every 90 days

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1054]
### Story

As a USER, I would like to be able to change my username in Colony.

### Description

We would like to be able to make it possible for users to change their username. This however posses the potential for users to abuse this by being able to more easily others in a Colony. To counter this, we would like to restrict username changing to only be possible at least 90 days from the date of their last change.

Note: This is not an important feature, but has been requested as a nice to have for some, so if this proves to be difficult or take longer then a few hours, please let product know and the changing of usernames will be disabled altogether.

### Design

- [Figma link - Username change disabled with tooltip](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=2089%3A200300&mode=design&t=GvKpL41x9BZ7QxHz-1)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/4ca92c1c-45b9-41e6-b7ea-d6f045c93834)

### This issue is complete when...

- [x] Ability to change username within a 90 day window from last change has been disabled.

**Comment by rdig** [comment]
We need to talk about these.

I'm not happy about "small" feature requests like these showing up in here without prior discussion and agreement.

There needs to be a proper avenue for stuff like this.

**Comment by willm30** [comment]
Closing this issue as it's been completed. @rdig I suggest we discuss your comment in Monday's team meeting
