### ISSUE TITLE
Add functionality for custom titles for Actions, Motions, and Advanced Payments

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1055]
### Story

As a USER, I would like to be able to add my own titles to Actions, Motions, and Advanced Payments.

### Description

To help better identify the purpose of actions being created, we need to include the ability to add custom titles to Actions, Motions, and Advanced Payments.

The max character limit for titles should be 60 characters. It should be text only and strip out excessive white space and tags.

### Design

- [Figma link - Empty title field](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=2729%3A244356&mode=design&t=GvKpL41x9BZ7QxHz-1)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/8df86e39-ffc9-47a6-8c00-7bb2b12e4930)

- [Figma link - Complete title field](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=2729%3A244356&mode=design&t=GvKpL41x9BZ7QxHz-1)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/b3024888-46bd-479d-a80a-b4b711332540)

- [Figma link - length error](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=2729%3A248940&mode=design&t=GvKpL41x9BZ7QxHz-1)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/0ca1436c-4e40-47f8-b87b-8b394f044a79)

### This issue is complete when...

- [ ] When creating Actions, Motions, and Advanced Payments you can add a custom title.
- [ ] When viewing Actions, Motions, and Advanced Payments you can see the custom title.

**Comment by rdig** [comment]
This is similar to #1054 and I have the same complaint

**Comment by rdig** [comment]
@ArmandoGraterol this was done correct ?

**Comment by rdig** [comment]
Closing as done
