### ISSUE TITLE
Port balance info and manage tokens for `AvatarDropdownPopoverMobile`

### ISSUE THREAD

**Issue by Julianahlk** [JoinColony/colonyCDapp#108]
Make sure the `AvatarDropdownPopoverMobile` is mobile responsive like in the DApp and once tokens are ready add the Manage Tokens button and other missing details. 

<img width="195" alt="Screen Shot 2022-11-29 at 6 32 47 PM" src="https://user-images.githubusercontent.com/71563622/204672827-918dcc06-217f-4214-9aa0-89eff2ed28d4.png">

**Comment by rdig** [comment]
Closing as no longer relevant _(plus the underlying issue has been fixed tangentially by other changes)_
