### ISSUE TITLE
Port over other extensions

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#113]
#95 will only port the OneTxPayment extension to avoid blocking others for too long so this issue is to port other extensions:
 - Voting Extension
 - Reputation Voting Extension

Blocked by #95

**Comment by jakubcolony** [comment]
@rdig Can you check I listed the correct extensions to be ported? I couldn't remember exactly which one to omit

**Comment by rdig** [comment]
Nope, there's just one more: `ReputationVoting`, we won't be supporting whitelist for the time being

**Comment by jakubcolony** [comment]
#123 has been merged, and there are other issues to port various bits needed for having full support for `VotingReputation`
