### ISSUE TITLE
Issues with installing, enabling, and deprecating extensions

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1192]
## Steps to reproduce

1. Install and enable the Reputation extension.
2. Deprecate it, then re-enable it, uninstall it, install it again, enable it, deprecate, repeat.
3. I did this sequence for a couple of minutes in which I got to a state where the UI was stuck in a state of enabled and would not register that the extension was deprecated. The deprecateExtension transaction succeeds and can continually be triggered.
4. I was able to replicate in 3 colonies, and can now no longer manage those extensions in each of the Colonies. These are the 3 Colonies and extension addresses on QA:
  - Colony 1:
      - Colony: 0x170F9074bfe682b17f8166FC626e5Aee3a9C496f
      - Extension: 0xa67aF1CB6be8260B8f7754e5fc5278f9abB14faC
  - Colony 2:
      - Colony: 0x0Ff30691A48A5656B20121cb75E45DCE0F0a1dE1
      - Extension: 0x6bBf5725Cf43193c1D68e50203823E4Cb189De7c
  - Colony 3:
      - Colony: 0x1Cc30d731f5cff524F781bF97b6dC76014f0838f
      - Extension: 0xf92c6a6ff5C7be8B4c6F8A5608371e60b48db2a5

## Expected behaviour

* The UI should be able to show the correct state of an extension as it is on chain.

## Actual behaviour

* The UI is not showing the correct state of the extension as it is on chain.
* This error has appeared on the extension page.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/5e85a323-3a58-4136-bafe-f54664b07a95)

* After installing and enabling an extension, deprecate and uninstalling, I then went to install and enable again, however, enabling did not trigger the pending pill or the loader and clicking again did not do anything. I could just repeatedly click enable.

* After reloading I saw the permission missing info banner with the text: "This extension is missing some or all of the permissions it needs to work."

* On clicking "Enable permissions" I saw the TODO banner with the text: "The required permissions have been updated. TODO: Wire this in with Actions / Motions"

* The following errors were also seen during this testing.

When trying to deprecate an existing extension:
```
{
    "code": -32603,
    "message": "Internal JSON-RPC error.",
    "data": {
        "code": -32000,
        "message": "method handler crashed"
    },
    "stack": "{\n  "code": -32603,\n  "message": "Internal JSON-RPC error.",\n  "data": {\n    "code": -32000,\n    "message": "method handler crashed"\n  },\n  "stack": "Error: Internal JSON-RPC error.\n    at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44665)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45664\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935"\n}\n  at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44665)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45664\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935"
}
```

After moving to another Colony and trying to enable a new extension:

```
{
    "code": -32603,
    "message": "Internal JSON-RPC error.",
    "data": {
        "code": -32000,
        "message": "block has less receipts than expected: 0 <= 0, block: 11326079"
    },
    "stack": "{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32000,\n    \"message\": \"block has less receipts than expected: 0 <= 0, block: 11326079\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44665)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45664\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935\"\n}\n  at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44665)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45664\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935"
}
```

**Comment by willm30** [comment]
Aside from various rpc issues, I've also had the experience of deprecating an extension, only for the event not to be picked up correctly in the block ingestor. This causes the ui to fall out of sync with the chain. To investigate...

**Comment by willm30** [comment]
@arrenv Can we close?
