### ISSUE TITLE
Port `ExtensionDetails`

### ISSUE THREAD

**Issue by danbr** [JoinColony/colonyCDapp#124]
Building on #95 & #123 Port Extensions: ExtensionDetails & ExtensionSetup

**Comment by jakubcolony** [comment]
Please make sure to spin this branch off #121 as I've already ported a bit of `ExtensionDetails` component

**Comment by danbr** [comment]
> Please make sure to spin this branch off #121 as I've already ported a bit of `ExtensionDetails` component

@jakubcolony thanks for the heads-up.

**Comment by jakubcolony** [comment]
Restricting the scope of this issue to just `ExtensionDetails` component, `ExtensionSetup` is being ported as part of #130
