### ISSUE TITLE
Update design of app 404 page

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1245]
### Story

As a *user*, I want to know what happened when I try to access a URL that doesn't exist.
As a *user*, I want an easy way to navigate away if I visit a URL that doesn't exist.

### Description
With the updated app design, we want to show an updated 404 page that includes links to help the user with what they were looking for.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/5fd569b4-0145-4122-a3ea-db1ceccf4162)

- Report a bug
   - Opens the report a bug form of Beamer.
   - `useBeamer({tab: 'ideas', form: true})` not yet merged.
- Go to app home
   - Returns to app main landing page.
   - `/`
- Colony Docs
   - Navigates to Colony docs in a new tab.
   - `https://docs.colony.io/`
- User account
   - Navigates to the users account
   - /create-colony/
- Create a colony
   - Starts create a colony flow
   - `/create-colony/`

[Design - 404 page design- Figma](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=11978%3A380548&mode=dev)

### Acceptance criteria
- 404 page is updated to match the new design.

**Comment by AKHIL-DyC** [comment]
can i work on it

**Comment by AKHIL-DyC** [comment]
I am done with design but when i run ,the changes are not seen ,i am new to open source and docker images .what should i do.

**Comment by rdig** [comment]
> can i work on it

Sure you can, just let me know when you'll have it done by, so that I don't assign it to anyone else

> I am done with design but when i run ,the changes are not seen ,i am new to open source and docker images .what should i do.

Did you start both the dev environment and the frontend? Make sure you follow the readme file on how to set it up, configure it and start it. Note that there are two separate commands you need to run in two separate terminal windows, in order to get everything up and running

**Comment by AKHIL-DyC** [comment]
ya i tried running npm run dev and in new terminal npm run webpack but changes are not reflecting!!,feel free to assign to someone else,but i would love know the reason for this
