### ISSUE TITLE
Callout banner component alignment

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1254]
## Steps to reproduce

1. In the header click the `More` menu button.
2. Click on the `Create new action` button at the bottom of the popover.
3. With the create action side panel, select the `Unlock token` action type.
4. Notice the callout banner, and how it does not align with the design.

## Expected behaviour

* The text and button should center align in the same row at larger rows. 2 columns to 1 breakpoint happens at a banner width of 650px
* The text color should be `text-gray-900` and not the colors used. (Note: this has been addressed in feature/private-user-invites)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/456e4623-bae7-44cf-9bf3-698786cf5bfe)

[Design - Figma link](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=1034-54764&mode=design&t=gxRretbqyxZSE5IM-4)

## Actual behaviour

* The button wraps to a new row incorrectly.
* The text color does not match the design.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/bfa6c8e2-c57c-4a7d-b17e-987906a90911)

**Comment by wuocanhhh** [comment]
How i can join project?

**Comment by AryushGupta** [comment]
Hey , I want to join in
