### ISSUE TITLE
App route and title updates

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1261]
### Story

As a User, I want to be able to easily navigate to pages within the app.
As a User, I want URLs to be intuitive to help identify where I am.
As a User, I want shared URLs to easily discernable, so that I can see where they may go just by reading them.
As a User, I want title tags to be relevant to the page I am on.

### Description

With the new app, we want to have the routes updated to better represent the pages within the app, and to also ensure new pages have the correct routes.

### Route changes

We would like to simplify the URLs for the app and colonies by removing the redundant "colony" route path.

This will include changing the routing of colonies for the new UI from:

- [x]  app.colony.io/colony/meta -> app.colony.io/meta
   - [x]  Page Title: Metacolony | Colony
- [x] app.colony.io/meta/extensions
   - [x]  Page Title: Extensions | Colony - Metacolony
- [x]  app.colony.io/meta/extensions/{extension_name}
   - [x]  Page Title: {extension_full_name} Extension | Colony - Metacolony
- [x]  app.colony.io/meta/extensions/{extension_name}/setup
   - [x]  Page Title: {extension_full_name} Extension Setup | Colony - Metacolony
- [x]  app.colony.io/meta/members
   - [x]  Page Title: Members | Colony - Metacolony
- [x]  app.colony.io/meta/contributors
   - [x]  Page Title: Contributors | Colony - Metacolony
- [x]  app.colony.io/meta/followers
   - [x]  Page Title: Followers | Colony - Metacolony
- [x]  app.colony.io/metacolony/verified
   - [x]  Page Title: Verified Members | Colony - Metacolony
- [x]  app.colony.io/meta/teams
   - [x]  Page Title: Teams | Colony - Metacolony
- [ ]  app.colony.io/meta/agreements **Not yet implemented**
   - [ ]  Page Title: Agreements | Colony - Metacolony
- [ ]  app.colony.io/meta/activity **Not yet implemented**
   - [ ]  Page Title: Activity | Colony - Metacolony
- [x]  app.colony.io/meta/details
   - [x]  Page Title: Metacolony Details | Colony - Metacolony
- [x]  app.colony.io/meta/reputation
   - [x]  Page Title: Reputation | Colony - Metacolony
- [x]  app.colony.io/meta/permissions
   - [x]  Page Title: Permissions | Colony - Metacolony
- [x]  app.colony.io/meta/integrations
   - [x]  Page Title: Integrations | Colony - Metacolony
- [x]  app.colony.io/meta/incorporation
   - [x]  Page Title: Incorporation | Colony - Metacolony
- [x]  app.colony.io/meta/advanced
   - [x]  Page Title: Advanced | Colony - Metacolony
- [ ]  app.colony.io/meta/finances **Not yet implemented**
   - [ ]  Page Title: Financial overview | Colony - Metacolony
- [ ]  app.colony.io/meta/balances **Not yet implemented**
   - [ ]  Page Title: Balances | Colony - Metacolony
- [ ]  app.colony.io/meta/incoming **Not yet implemented**
   - [ ]  Page Title: Incoming | Colony - Metacolony
- [ ]  app.colony.io/meta/transactions **Not yet implemented**
   - [ ]  Page Title: Transactions | Colony - Metacolony
- [ ]  app.colony.io/meta/streaming **Not yet implemented**
   - [ ] Page Title: Streaming | Colony - Metacolony

For transactions:

- [x]  app.colony.io/meta/:route/?tx={trasaction_hash}
   - [x]  Page Title: {action_title} - {action_type} | Colony - Metacolony **Colony name not present on all routes, therefore omitting**
- [ ]  app.colony.io/metacolony/:route/?tx={trasaction_hash}
   - [ ]  Page Title: {action_title} - {action_type} | Colony - Metacolony

For any non-colony specific routes changed with the following patterns:

- [x]  app.colony.io/landing -> app.colony.io/
   - [x] Page Title: Welcome to Colony
- [x]  app.colony.io/edit-profile -> app.colony.io/account/profile
   - [x]  Page Title: Account Profile | Colony
- [x]  app.colony.io/edit-profile for preferences -> app.colony.io/account/preferences
   - [x]  Page Title: Account Preferences | Colony
- [x]  app.colony.io/edit-profile for advanced -> app.colony.io/account/advanced
   - [x]  Page Title: Advanced settings | Colony
- [x]  app.colony.io/create-colony **No change**
   - [x]  Page Title: Create a Colony | Colony
- [x]  app.colony.io/create-profile 
   - [x]  Page Title: Create a Profile | Colony
- [x]  app.colony.io/404 **No change**
   - [x] Page Title: 404 - Not Found | Colony

Fallback Page Title (if any page title is not specifically mentioned above):
- [x]  Page Title: Colony App

Note that where you see {extension_name}, {extension_full_name}, {action_title}, {action_type}, and {trasaction_hash}, these should be replaced with the relevant specific information when the URL is used.

### This issue is complete when...

- [ ] Routes have been updated as of the provided spec.
- [ ] Page titles match the route updates.

**Comment by rdig** [comment]
@willm30 didn't your #1288 close this PR? Otherwise is this still relevant ?

**Comment by rdig** [comment]
Closing as done
