### ISSUE TITLE
Issue when making Simple Payments and new UI

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1262]
## Steps to reproduce

1. Try to make a Simple payment in a Colony.
2. Notice if the error happens for you `Payment token decimals not set for OneTxPayment transaction`

Note:
- I have tested on QA server and was not able to replicate.
- Locally though, this is happening on every branch tested, have tried clearing docker, restarting, etc.

## Expected behaviour

* You should be able to make a Simple payment.

## Actual behaviour

* You are not able to make a Simple payment.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/32e0f7b8-7b96-4eef-b2f1-6f3766e7fc1d)

**Comment by rdig** [comment]
Closing as no longer relevant
