### ISSUE TITLE
Team colour token refinements 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1266]
## Description

The old schema for team colours within the CDapp is outdated and needs to be updated to match the team colours spec'd in Figma. Currently, when I am creating a new team, I see the old team colours which have accessibility and contrast issues. 

Current colours showing in the new UI:
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/09d8549c-2de5-4d0b-959c-a1bd46b3a89a)

Correct colour tokens shown in the team colour component:
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/8449c9e8-0f23-4baa-a161-7bae65befe27)

The team pills that show across actions and motions and through the CDapp should also be updated accordingly:

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/1124f506-014c-4ece-bbea-ad392d7c6ce7)

## Figma links

- Colour tokens for teams within the Design System: https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-V3-(2023)?type=design&node-id=1621%3A7209&mode=dev&t=jCCTeXiLm0aOyEFW-1
- Links to Figma components: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=1417%3A103591&mode=dev&t=AN0G6jueg7SpC3sS-1

**Comment by rdig** [comment]
Closing as this was fixed by #1418
