### ISSUE TITLE
Colony/Team Switch Header UI Issues

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1306]
## Description

A Colony/ Team switcher has been added to the header. However, the tracking (letter spacing) doesn't match our Design System as per Figma below. 

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/5f067592-20c3-491a-aaff-efcbcaadaad1)

The change should not impact the hover state or the team switcher dropdown

## Figma links

Design system: https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-V3-(2023)?type=design&node-id=1694-6412&mode=design&t=SUFRzL15jPakSJfW-4

Example of the text use in the interface: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=11899-215716&mode=design&t=brqRb02uKRH5EEbq-4

**Comment by AlexVCS** [comment]
Hi there, I'd like to work on this issue. Do you typically assign folks to issues for this project? I would need to request access to see the Figma files, which I could do of course! Thanks

**Comment by melyndav** [comment]
Hey @AlexVCS! Thanks for your interest in helping with this issue. 

Here's what you'll need for the update. 

color: var(--light-gray-900, #101828);

/* Treatments/Page Title */
font-family: Inter;
font-size: 12px;
font-style: normal;
font-weight: 500;
line-height: 18px; /* 150% */
letter-spacing: 1.2px;
text-transform: uppercase;


There are three separate functions with different context's in this header component.

1. When a user is in inside the context of a colony they will see the following variation which includes:

- The Colony name which acts as a quicklink back to the colony's dashboard and;
- A team switch dropdown. 

Both of these need the letter spacing applied.

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/54d13e42-4cf2-4458-948c-48cdde062efd)

2. When the user is in  area of the colony where no team switcher is needed, then only the colony name shows.

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/7a7b026c-51e6-409a-b727-54ffa64fc262)


3. When the user is outside of the context of a colony, then they see a placeholder. This also needs to be updated for consistency.
