### ISSUE TITLE
Extension upgrades not detecting latest versions

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1320]
## Description

The app currently does not support upgrading a Colony extension to the latest version.

Currently on QA the `OneTxPayment` extension is showing `v4`, however, the latest deployed version of the extension is `v5` released in May.

We need to be able to support the latest version and extension upgrades.

**Comment by chmanie** [comment]
I'm snatching this one.

**Comment by chmanie** [comment]
@arrenv Can this be closed now? The issue was that the ingestor did not pick up the latest versions of extensions

**Comment by arrenv** [comment]
> @arrenv Can this be closed now? The issue was that the ingestor did not pick up the latest versions of extensions

I don't think we've tested and confirmed that it does now though, right?

Also, can we upgrade or does it need to be updated manually?

**Comment by chmanie** [comment]
Not sure. Somehow the versions got updated. Maybe @rdig or @bogdan-1337 know. I'll unassign myself from this though as it seems to be related to the block ingestor.

**Comment by rdig** [comment]
Yep, @chmanie is right. This is not something that we can "fix", it's a case to ensure the block ingestor works always. If it goes down during a version update, the phenomenon you described happens. 

A fix for this, is to re-seed the database with the correct versions from the chain, for which the block ingestor already has a script for.

In the mean time, both production and the (new) QA have been updated to the correct versions
