### ISSUE TITLE
Connect action custom title and metadata to user hub stakes tab

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#1337]
Once available, the stakes tab should display custom title and metadata title of the action associated with a stake:
![image](https://github.com/JoinColony/colonyCDapp/assets/112586815/2707daa1-2b8a-48ac-a035-8dd5d955b9c6)

If custom title is not available, metadata title should be used as a fallback. Metadata title will be inferred from the action values (we are waiting for that functionality to be implemented in activity feed).

@arrenv fyi

**Comment by rdig** [comment]
Closing as this was done
