### ISSUE TITLE
Consolidate UserAvatar components

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyCDapp#1372]
Currently we have (at least) two user avatar components:

- Avatar.tsx
- UserAvatar.tsx

Furthermore there are things like

- AvatarUser.tsx
- UserAvatarDetails.tsx

and then v5 versions of some of those. I'll leave [this search](https://github.com/search?q=repo%3AJoinColony%2FcolonyCDapp+path%3AAvatar&type=code) here as a pointer.

The goal would be to consolidate all of that as much as possible and to delete unneeded code.

**Comment by rdig** [comment]
@jakubcolony @bassgeta this is another good candidate for the "refactor basket" we are planning for Q1

**Comment by jakubcolony** [comment]
A couple of more components to consider during this refactor: `UserInfo`, `UserPopover`, `ColonyAvatar`, `TokenAvatar`. We should aim to achieve consistency of all different types of avatar components. Ideally, consumers would simply pass the relevant object (whether it's a user, colony, token, etc.) or contract address if we don't have more details. Many of the components mentioned here accept too many props at the moment.

**Comment by jakubcolony** [comment]
- There should be a base `Avatar` component accepting 3 main props: avatar URL, address* and size* (in pixels). (* means required)
- For each entity (such as Token, Colony, User), there should be a wrapper component that takes responsibility for fetching the avatar URL and any other details.
