### ISSUE TITLE
Adding the token pop over on native Colony token widget 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1383]
## Current interactions:

On hover of the locked icon only, a tool tip appears (as below)

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/d32dfe98-4360-47f4-b684-34d29414c63a)

## Scope of this issue:

1. On hover/select or press (on mobile) of the token text, please trigger the token pop up which allows the user to see the toke information and copy the wallet address.

**Token popover:**
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/3c05c143-ad71-4d2b-8b45-fae25ec51576)

2. Token pop over needs to be on the balance table as well, when users select the token in the table the token name should change to text-blue-400 and show the new token when selected and replace the current one shown. 

<img width="481" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/b7d5f526-70f7-4503-8683-9df8c261f61a">

Current version showing:
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/0a7bfd5a-bac0-4ffa-ace0-9008d2125578)

**Comment by rdig** [comment]
I remember seeing something similar to this in one of your PRs @bassgeta 

Is this issue by any change already done ?

**Comment by bassgeta** [comment]
> I remember seeing something similar to this in one of your PRs @bassgeta
> 
> Is this issue by any change already done ?

Sorry for the late reply, I have added a new token popover, but I haven't used it on this component, so I can hook it up!

**Comment by bassgeta** [comment]
> I don't really understand what you mean. Is this issue done then? Can it be closed?

It is not done, I just wanted to add that it's doable. We need to wrap this component in the `TokenPopover` component. So we can tackle it easily, but it's not yet done
