### ISSUE TITLE
Annotating Transactions is Failing on actions

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1451]
## Steps to reproduce
- Create a Minting tokens or Edit colony details action
- Be sure to include a Description.
- Check the Description after completing the transaction.
- Check the transactions in the UserHub transactions list.

This was noticed on both Minting tokens & Edit colony details actions, however all actions should be tested.

## Expected behaviour
- You should be able to annotate transactions, i.e. fill out the description and it works correctly.

## Actual behaviour
- You are not able to  annotate transactions and thus no descriptions are working.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/49a3ff2b-74be-4bc8-a0d9-a2f7f28ec926)

**Comment by chmanie** [comment]
Currently it doesn't really fail, it just never finishes.
