### ISSUE TITLE
Fix React intl error in Extensions

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#146]
We have a React intl error on the Governance Extension copy.

## Original comment

I'm also seeing the following react intl error:

![intlerror](https://user-images.githubusercontent.com/64402732/207369005-0ac43dd8-a87a-46e6-99ec-960e1f6238c6.png)

_Originally posted by @willm30 in https://github.com/JoinColony/colonyCDapp/pull/121#pullrequestreview-1215698098_

**Comment by jakubcolony** [comment]
I'm not sure if a separate issue is necessary as I'm expecting Dan to fix this in #133.
I also left a todo comment in code but will remind him in the PR separately.

**Comment by willm30** [comment]
@jakubcolony Sometimes when you come across a todo in the code, it's not immediately obvious to you if resolving it belongs in the pr you're working on or if it's someone else's intention to resolve it. An issue at least allows us to make explicit to other team members who's responsible (i.e the person assigned to the issue), and I think makes it less likely that it just gets left there. For instance, in this case, if I wanted to know if others had seen the console warning, it'd be easier for me to search for the issue in the project than for the todo in the code, and thus I'd know that it was being handled. There are cases in the dapp of warnings going unresolved and todos becoming long-term members of the code base, so I see an issue as a way of maintaining visibility over things like that. 

It also helps to keep track of outstanding work at a glance when viewing the project on github. 

I'd be interested to know what you think.

**Comment by jakubcolony** [comment]
I still think this is part of #124, and can't imagine someone opening a PR for it without fixing the issue in question.
It's good that you picked this up but I don't think it's an independent bug, but rather one of the steps needed to call #124 completed
