### ISSUE TITLE
Improving the UX of action error states

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1463]
## Description

Currently, the error states shown to the user within the actions panel are vague and unhelpful to users. Improving the UX writing of these will help to ensure users understand what issues they are experiencing and what actions they can take to resolve them.

All error states for each action type should be improved as per the product specs. 

**Simple Payments:**
decisionMethod must be defined -> Please select a decision method 
from is a required field -> Please select the team the payment is from 
recipient is a required field -> Please select a member to receive the payment 
Amount must be greater than zero. -> The payment amount must be more than zero

*Create a decision:*
decisionMethod must be defined > Please select a decision method 
description must be defined > Please enter a description for your agreement 

**Transfer funds:**
Cannot move to same team pot. - > The recipient team must be different from the team sending the funds
description must be defined - > This shouldn't show
decisionMethod must be defined -> Please select a decision method 
Field is required -> The amount of funds to transfer must be more than zero

**Mint tokens:**
description must be defined - > This shouldn't show
decisionMethod must be defined -> Please select a decision method
Value of tokens to mint must be greater than zero -> The value of tokens to mint must be more than zero

**Unlock token**
Decision method has no validation message so please add -> Please select a decision method

**Manage tokens:**
annotation must be defined - > this should not be required 
decisionMethod must be defined -> Please select a decision method

**Create new team:**
decisionMethod must be defined -> Please select a decision method
Team name required. -> Please provide a team name
Team colour has no validation so please add - > Please select a colour for this team 
Team purpose also has no validation so please add  -> Please enter a description about this team's purpose 

**Edit a team**
decisionMethod must be defined -> Please select a decision method
Team name required. -> Please provide a team name
team must be defined -> Please select a team 
Team colour has no validation so please add - > Please select a colour for this team 
Team purpose also has no validation so please add  -> Please enter a description about this team's purpose 

**Manage Permissions:**
description must be defined -> this should not be required
decisionMethod must be defined -> Please select a decision method
authority is a required field - > Please select an authority type
role is a required field ->Please select a permission type
team is a required field -> Please select a team 
member is a required field -> Please select a member for the permission change

**Edit Colony Details:"
Add validation to the Colony name field -> Please enter a Colony name 
decisionMethod must be defined -> Please select a decision method

**Upgrade Colony Version:**
annotation must be defined -> this should not be required
decisionMethod must be defined -> Please select a decision method

**Manage Colony Objective:**
Colony objective title is required -> Please enter a title for the objective
Colony objective description is required -> Please enter a short description for the objective
Colony objective progress is required -> This should be allowed to be set as 0% so no error here 
decisionMethod must be defined -> Please select a decision method
description must be defined -> this should not be required

**Comment by rdig** [comment]
@arrenv you're still assigned to this. 

Is this still relevant, or was it implemented already ?

**Comment by arrenv** [comment]
@rdig this is still relevant. I held off due to a lot of PRs touching validation. I will review and pick it up again now, or close.

**Comment by melyndav** [comment]
@arrenv this needs to be picked up again but with new actions included.

**Comment by rdig** [comment]
I don't think this is relevant still, but I've added to the cycle so we can check it

**Comment by iamsamgibbs** [comment]
I came across some of these this morning actually on simple payment, but given how old the original issue is, it is probably worth a fresh check across all actions.

**Comment by rdig** [comment]
So what you're saying is we're closing this and opening a new one ?
