### ISSUE TITLE
Manage Colony objective action type validation issues

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1464]
## Description

The Manage Colony Objective active type has validation issues. As seen in the screenshot below, I have entered a objective title, objective description and a percentage value all in their respective fields. However, the error is showing as these inputs are missing. 

For the title and objective description, the actual error is that both fields exceed the character limits defined in the product specs. This correct validation error should show to users.

For the percentage, the user should not be shown the input is missing. The user should also be able to change other parts of the objective and leave an existing percentage value untouched or at 0%. 

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/a829d094-9666-4625-b994-cc2f4da116d4)

**Comment by rdig** [comment]
@melyndav I think this is one for @JoinColony/pagepro

**Comment by arrenv** [comment]
> @melyndav I think this is one for @JoinColony/pagepro

Pagepro never estimated or worked on this, this was done by Thomas.
