### ISSUE TITLE
Track "Manage token" changes when using Permissions

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1467]
## Description
In order to be able to view changes made to `Manage tokens` in passed transactions that used Permissions, it should be possible see the `added` & `removed` tokens i.e. changes. Currently, if you view previous `Manage tokens` actions that used permissions, you will always see the current state of the Colony's tokens, not what was actually changed.

Currently, we support this functionality if the decision method is `Reputation` (i.e. Motions) using this query:

```
  getColonyAction {
    pendingColonyMetadata {
      modifiedTokenAddresses {
        added
        removed
      }
    }
  }
```

This could likely be generalised to being usable for both `Motions` & `Actions`.

**Comment by rdig** [comment]
What's the status of this ?

**Comment by ArmandoGraterol** [comment]
@rdig At the time, I didn't go too far with this one since it would require refactoring manage tokens a bit and I remember we were planning on refactoring completely anyway, which is what is happening this quarter.

**Comment by rdig** [comment]
Correct. Close it since he have a whole feature for this, and we'll re-create this when we get to that, in the new context
