### ISSUE TITLE
Opening a tokens modal while within action sidebar causes the action form to reset

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#1471]
Steps to reproduce:
1. Open action sidebar. 
2. From the user hub inside action sidebar, open tokens modal (either activation or withdrawal).
3. The action form resets and jumps in front of the tokens modal:

https://github.com/JoinColony/colonyCDapp/assets/112586815/a917a374-3980-45ae-b0ad-b96554d3c507

**Comment by arrenv** [comment]
This seems to break the UI and requires a reload to fix.

**Comment by jakubcolony** [comment]
Closing this issue as it seems to be fixed in latest master.
