### ISSUE TITLE
Remove obsolete colony metaData whitelist

### ISSUE THREAD

**Issue by thomassdk** [JoinColony/colonyCDapp#1472]
# Description

This PR should remove the whitelist functionality in the meta data of the colony model.

We are now using the contributors model via the `isVerified` boolean to track whether a user is verified or not so the old code introduces a second source of truth for whether users are verified.

## Definition of done

- [x] All code related to whitelist should be removed both in the schema and throughout the app
- [x] This code should also be removed from the block ingestor 
- [x] Where ever applicable it should be replaced with the `isVerified` boolean on the colony contributors (this should mostly be done via #1390 but extra checks need to take place)  
- [ ] How users become verified needs to be reworked especially with regards to authentication

**Comment by rdig** [comment]
Closing as this will be handled by @bassgeta 's [Verified Members](https://github.com/orgs/JoinColony/projects/47) feature
