### ISSUE TITLE
Motions UI issues #3

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1479]
## Description

When QA'ing motion flows, a number of UI issues have been identified that require fixing. These include: 

9. User-names should trigger a hover state & when selected, show the user pop-over in the staking information -
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/f47219ca-33b4-449e-b52a-a9687972a1d2)

15. Top pill in the motion header is missing for passed and failed states.
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/c5f77448-9e72-4292-9a51-417d6737020b)

Figma link passed: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=3111-335567&mode=design&t=NYFSA78C4UJjlZY1-4

Figma link for failed: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=14102-371050&mode=design&t=NYFSA78C4UJjlZY1-4

**Comment by rdig** [comment]
@jakubcolony or @melyndav is this issue still relevant? Or were the problems outlined here fixed by the various "Fix Motion UI" PRs that were raised?

My question is if I can close it or not

**Comment by melyndav** [comment]
I don't believe these have been resolved unless you added in the passed and failed states headers to motions @rdig?
I have yet to see a PR that covers this particular issue unless it was completed while I was on leave in December.

**Comment by jakubcolony** [comment]
I closed the old PR as it had a bunch of conflicts and unrelated stuff and will work on this issue from scratch.
