### ISSUE TITLE
Header changes height when side panel is triggered

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1497]
## Description

When the side panel is triggered, the header changes height, causing the content to jump. Content height should change when the side panel is opened. All headers within the Colony context should not change. 

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/0bc6fd7a-fb8e-4207-9d18-6158577baa75)

**Comment by thomassdk** [comment]
Hi @melyndav Im not seeing this error on master could this have been fixed via a different PR?

[Screencast from 2023-12-07 12-33-57.webm](https://github.com/JoinColony/colonyCDapp/assets/32598350/f41cd1fb-d395-41d4-8d24-ecd5d8d1f14a)

**Comment by melyndav** [comment]
Closing this issue since it seems to have been resolved in production.
