### ISSUE TITLE
Create a separate block-ingestor for extensions

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#150]
Following a discussion with @rdig, there's a good case for spinning out a separate block-ingestor that would only be responsible for handling extensions related events.

We decided to put it on hold for now, until the final architecture of the CDapp becomes clearer.

**Comment by rdig** [comment]
I'm going to close this as it's not either relevant right now, nor a priority. When/if we revisit this, we'll open a new issue to track it.
