### ISSUE TITLE
Focus on key inputs

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1511]
# Description

Adding focus to inputs is a best practice that we would like to add to the UI in order to help improve the user experience and accessibility when using Colony.

The following are a list of input focuses that we would like to have working along:

1. Focus on `Enter title` when creating a new action.
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/30b874f0-430f-48f9-8070-3d621e49877b)

2. Focus on `Enter a description` after expanding the Description field on creation.
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/17285232-2979-449d-af60-893b0a4752b3)

3. Focus on `Search` when opening the filter dropdowns.
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/ff15767a-41c6-498c-b788-8aa5f7f296cb)

4. Focus on first input on each step of Profile creation and Colony creation.
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/7040e923-6705-4174-960d-49987eac0461)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/3f6026d0-7883-43b1-b109-f609229ba86a)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/27c7a720-06cd-4157-9c8e-9ae34d9b4c95)

**Comment by rdig** [comment]
Also fix the React console warning about "RichText" not accepting `_ref`'s
