### ISSUE TITLE
Refactor colony home route

### ISSUE THREAD

**Issue by bassgeta** [JoinColony/colonyCDapp#1517]
Currently the home route does not have its own context provider, so a lot of things are mixed left and right.
We should create a context provider for it, so we can handle opening the leave colony modal there, simplifying the dashboard header component, use composition instead of using this config approach.
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/f81ac7f5-3960-43f2-b9c8-bb22a9504c12)

**Comment by bassgeta** [comment]
It would be nice to have [this PR](https://github.com/JoinColony/colonyCDapp/pull/1566) merged in first

**Comment by arrenv** [comment]
@bassgeta As discussed, please also include the update to change the heading used in the dashboard teams donut chart from "Influence by team" to "Top teams by influence", to better represent the new chart.

Figma link to component - https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-11731&mode=design&t=jCVitGw2TLuAmLn3-11
