### ISSUE TITLE
Manage Colony Objective changes during to a different action type during transaction

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1524]
## Description

When updating the Manage Colony Objective action type, on submit and the transaction triggers, the action loads in the Edit Colony Details action incorrectly. This shouldn't happen, and the completed Manage Colony Objective state should show with the correct details. 

I triggered the Manage Colony objective action type from the Colony details page, as shown in the screenshot to the left.

<img width="1151" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f5566563-a761-447d-b344-7dacbaa87376">

**Comment by bassgeta** [comment]
We can fix this with the refactor that's going to happen on https://github.com/JoinColony/colonyCDapp/pull/1608
We can start showing the `CompletedAction` view after the form is successfully submitted!

**Comment by bassgeta** [comment]
That comment was way too optimistic, I've found the issue in our `useGetActionData.ts` hook, it's not using the correct types of an action.
So we can fix this separately and keep the solution in mind when working on [this issue](https://github.com/JoinColony/colonyCDapp/issues/1646) :)
