### ISSUE TITLE
Maybe use `break-word` instead of `break-all`in the dashboard widgets?

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyCDapp#1525]
![image](https://github.com/JoinColony/colonyCDapp/assets/2174084/a30fc800-07c4-4872-985b-6bc8cdef26e5)

**Comment by melyndav** [comment]
Adding to @chmanie's issue, please make sure both the objective and agreement widgets (when both have content) on the dashboard are updated. This does not impact the Team reputation widget. 

Example of both widgets in the completed state that need updating:

<img width="355" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/b7059262-fe68-4097-bd88-bc7a125d0543">

**Comment by chmanie** [comment]
I can quickly get this done
