### ISSUE TITLE
Consistent blockies during Colony creation onboarding flow

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1532]
## Description

When I am creating a new colony, I get shown two different blockies in two steps right after each other.

The first blockie shows in the native token set up page in the token avatar upload section. 

<img width="414" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/a78f6f72-fe06-4e86-ad53-14cc59b59c19">

And the following step is the confirmation, asking the user to confirm their details. This step shows the blockie, but it's different from the first. 

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/b2af8b7c-721a-4bc9-892c-274a16ac05cc)

And this is the blockie I got for the token once the Colony was created:

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/98fe2923-625e-44d4-929d-8f4478f73a2c)

## Scope of the issue

Add a placeholder image for steps 1 and 2 of the Colony creation flow. If the user does not change the token avatar at this step, a random blockie will be assigned upon submit of the creation flow which will then be displayed consistently across the CDapp on balance pages and actions etc.

The instructional text should also be updated in the creation flow to inform the user that a random blockie will be assigned if the user chooses to change the colony avatar via actions at a later date. 

## Figma links
https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=11978-122583&mode=design&t=1qGl0QLV8pEYWg9b-4

Avatar placeholder component: https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=2187-17&mode=design&t=zP0RKfWVnPr3PwRY-4

_*Edited to update scope as per discussions with @iamsamgibbs

**Comment by rdig** [comment]
This is not a bug, but actually a "mini-feature" in the sense that we have to teach this to the onboarding wizard.

If the TokenAvatar component doesn't get an contract address it renders a random value. Only after you've created the token / colony is where the final address is available.

This needs to be spec'd out a bit, as to make this work, all the new token avatars, when creating a new colony, for **all** users that create a new colony will have to be the same ever, until the token is created, after which it will default to the value of the contract, meaning it'll change, as it does currently _(this is for the blockie flow)_

If the user sets a custom token avatar, this is no longer a issue
