### ISSUE TITLE
Fix persistent transactions in Userhub in production

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1534]
## Steps to reproduce
- Create transactions in a Colony.
- Check the Transactions tab in the Userhub.
- Likely you will see them.
- Reload the app and check the tab again.
- You should see no transactions appearing.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/c23a7143-b37c-42a2-b034-4449e8bd4a23)

This is happening only in production, however in local, testing both Dev wallet and Metamask seems to show the transactions showing correctly. This seems to be an issue with the `GetUserTransactions` query.

# Expected behaviour
- Transactions should be persistent in the UserHub in production.

# Actual behaviour
- Transactions are not appearing in the UserHub in Production

### Production response to `GetUserTransactions`
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/25d7bafa-453b-4475-8b93-32b4838e3fe9)

### Local response to `GetUserTransactions`
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/12e16649-647b-4171-933d-ffdf9a59de52)

**Comment by rdig** [comment]
This is just a query issue, as Arren demostrates above, so the data is still on the server. Once this is fixed, everything will show up correctly
