### ISSUE TITLE
Terms of use and Privacy Policy

### ISSUE THREAD

**Issue by naynovi** [JoinColony/colonyCDapp#1539]
### Text Corrections and additions

**1. Mention of Section on User relationships, but then there is no corresponding section.** 
![image](https://github.com/JoinColony/colonyCDapp/assets/23479095/c2103b5e-8081-44f4-b2fd-d22a0f5cab0e)

**2. Rights and Data**
![image](https://github.com/JoinColony/colonyCDapp/assets/23479095/c4cb5306-2ab1-4dde-89cc-916f76293f84)

- 2a. Click here hyperlink is missing.
- 2b. Clause is also misleading. As there is unidentifiable information about users, we cannot accurately remove information at a user's request if we do not know it is attributable to them. 
- 2c. We do not disclose what information we hold on users and what specific information can be removed under GDPR rules. 

### Updates and missing 

**3. Cookies**

- 3a. Should include Google Tag manager-- ie Google Tag Manager: We use Google Tag Manager to manage website tags and tracking tools. This may involve the collection of certain user data. For more information, please review Google's Privacy Policy.
- 3b. No mention of Web3 providers who access site and wallet information ie: When interacting with a web3 provider (such as MetaMask, and other supported wallets) information such as your wallet address and transaction details are submitted. The information you disclose to the Web3 provider is subject to their privacy practices and policies, please review their policies for more information.
- 3c. Missing automatic Cookie pop up and data handling when site loaded for the first time. 
- 3d. Currently there is a loaded cookie for "Doubleclick" on the app site that we do not disclose in these terms. 

**4. Data security responsibilities and GDPR**

- 4a. need to include the right to: Opt out of receiving marketing communications/newsletters, how and if cookies can be disabled, as well as the procedure to access, update, or delete your personal information. 
- 4b. We indicate how third parties use the data, but not how we use the data. 
- 4c. ![image](https://github.com/JoinColony/colonyCDapp/assets/23479095/80cced2c-7050-431e-8c96-0d539aa68b79)
Here we must indicate the format of how we would update changes to the users especially those who have not opted in receiving communications from us. Currently this is not enforceable. 

**5. Personal Risks and Liabilities**

- 5a. Addition of user restrictions for the app. At a minimum, app should not be used to facilitate any illegitimate or criminal activity or the proceeds of criminal or fraudulent activity. It should not be used in any way that violates any laws in the jurisdiction of the user.
- 5b. Use of the app is at the sole risk of the user and user takes responsibility for actions that they and the Colonies they are party to are are compliant with international and national laws. 
- 5c. We can and should include detail on user responsibility, for example, users are responsible for reporting and paying any applicable taxes associated with usage. 
- 5d. Indication that application is in Beta with minimal restrictions enabled. Further highlight that users must take responsibility to abide by local, state, and federal laws. Please check laws and confirm prior to usage. Users should use the app at their own discretion.
- 5e. If there are any limitations on usage in certain jurisdictions and why. For example, if the terms have any restrictions on other entities if they are in jurisdictions in Panama? 
- 5f. User takes responsibility for missed transactions, or loss due to app instability or bugs. 
- 5g. Third party Services: Should we allow third party access or integrations, must indicate to the users it is their sole responsibility to ensure that any plug-ins or other third party services used and installed in its applications and results created using the Service does not create a breach of this Agreement nor violate any applicable laws and regulations. Any use of a plug-in or any other third party services is at their own risk and responsibility.

**6. Sanctions, and blocklisting for fraudulent or malicious behaviour**

- 6a. We must indicate our procedure for persons, entities and addresses that may act in ways that go against our terms and use the service maliciously. For example, addresses may be blocked from using the protocol if they are sanctioned or added to a block list.

**7. Fees, limits and overages**

- 7a. We should indicate if there are any limits on transaction volume, etc.. as well as responsibility for fees or overage charges for exceeding limits. Currently this is not disclosed.

**Comment by rdig** [comment]
This is mostly a issue for marketing as they are in control of the public facing website.

We cannot implement any of the mentioned changes
