### ISSUE TITLE
Avatar upload form not working across all areas

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1543]
## Description

**Issue 1**

In production when trying to upload an avatar across all points in the app (profile area, edit colony details, create-colony onboarding flow etc) when using Brave, I am unable to complete the upload and receive the same error each time.

User profile area:

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/a3041988-ef60-4195-9b48-f5717ab5ec54)

Edit Colony action type:

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/3b43b236-8822-4ead-b2d8-fd15dc179a96)
 

**Issue 2**

Also, when I select the trash can Icon in the error, the upload breaks, and I am no longer able to use the form unless I reload. 

**Expected behaviour:**

I should be able to use the upload form across all areas of the CDapp without being road blocked by these errors UI problems.

**Comment by ArmandoGraterol** [comment]
@melyndav after investigating and debugging for a bit, the issue seems to come from Brave's Shield:
https://github.com/nodeca/pica/issues/213

The fix is to disable `Shields`, at least when uploading an avatar :) This is unfortunately something that we can't fix from our side.
