### ISSUE TITLE
WebSocket connection - bootstrap Error issue

### ISSUE THREAD

**Issue by naynovi** [JoinColony/colonyCDapp#1550]
![image](https://github.com/JoinColony/colonyCDapp/assets/23479095/e3b6ceb0-cd20-409b-9274-337d982e2df0)

![image](https://github.com/JoinColony/colonyCDapp/assets/23479095/7be8cbf8-be3f-41b1-92a1-8f7cbc29cfe4)

I'm not sure how big of an issue any of these are, but unlike the lockdown install error (that is in the metamask chrome extension) wanted to raise these in case you were unaware.

**Comment by rdig** [comment]
Closing as not relevant. This is (was) a devops config issue
