### ISSUE TITLE
Selection button extends beyond window

### ISSUE THREAD

**Issue by naynovi** [JoinColony/colonyCDapp#1551]
![image](https://github.com/JoinColony/colonyCDapp/assets/23479095/ed64be97-9178-450b-997e-6dd29c853ef3)

When sidepanel is open, and the screen window is small, the selection buttons extend beyond the confines of their respective fields.

**Comment by melyndav** [comment]
Hey @naynovi - I'm going to close this issue as all responsive work will be done in the new year, including the landing and onboarding flows that our team built along with the PagePro deliverables. Mobile work hasn't started on this section yet.

**Comment by melyndav** [comment]
Closing this issue, since mobile work hasn't started and is not a priority until all bugs are resolved in beta.
