### ISSUE TITLE
Tabs on the extension page now break the app

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1554]
## Steps to reproduce
- Install and enable the Reputation weighted extension.
- Click on the `Extension Settings` tab.

This looks to be a result of tabs being added to the `Account` and `Members` pages that update the route path, the simplest solution to this would be to add route paths to the Extensions page as well with the path `/{colony_name}/{extension_name}/settings`.

## Expected behaviour
- You should be able to navigate to the extension settings tab to be able to view the settings.

## Actual behaviour
- When trying to view the extension settings, the app crashes and needs to be reloaded.
![extension-tabs](https://github.com/JoinColony/colonyCDapp/assets/33682027/65a2c612-eb6f-4c4d-bbd9-fa82c01ea601)

**Comment by AdrianDudko** [comment]
@arrenv, this Issue is going to @CzarekDryl
