### ISSUE TITLE
Actions: As a user I can MANAGE REPUTATION to award or take away member's reputation

### ISSUE THREAD

**Issue by AdrianDudko** [JoinColony/colonyCDapp#1564]
**Teamwork task:** https://tw.auroracreation.com/#/tasks/15701090
**Created by:** @AdrianDudko 
**Accepted by:** @arrenv 

**Description**
It's an existing funcionality in old UI. Go to Actions -> Manage Reputation -> Award/Smite reputation.

As a user, I want the ability to create action to award or remove reputation points for specific Colony member in selected team.

**Acceptance criteria**

Creating Action:
- User can add a Custom Title to the action.
    - This is a required field.
- Metadata updates when user makes changes in the form as of the provided pattern.
- User can select "Team".
    - This is the team in which reputation should be added or removed from.
    - This is a required field.
- User can select a "Member "
    - This is the reputation holder who’s reputation is being removed or awarded.
    - Member to show:
        - If removing, it should only show reputation holders.
        - If adding, any member should appear in the list of members to choose from.
        - Should also allow search and an address to be added.
    - This is a required field.
- User can choose a "Modification"
    - Options:
        - Award reputation
            - Gives reputation to the user in the selected team.
        - Remove reputation
            - Removes reputation from the user in the selected team.
    - This is a required field.
- User can set "Decision Method".
    - This is a required field.
    - Options available are based on available permission methods.
- User can set "Created In" field
    - Awarding reputation can only be done in the Root domain.
        - Hover on pill: display tooltip
            - Tooltip: \"The decision to award reputation to a recipient can only be done in the Root domain. This is to prevent reputation attacks in child domains.\"
    - Removing reputation can be done in the team where the user is having their reputation removed from or a parent team.
    - This field is visible only if the Reputation decision method is selected.
- User can add a rich text "Description".
    - Not required.

Reputation preview table:
* By default it's shows an empty state as of the design.
* Only the "Change" column can be edited.
* If a "Member" is selected, the "Current reputation" column should be updated with the chosen member's current reputation.
* If the "Award reputation" modification is chosen
	* Current reputation + Change = New reputation
* If "Remove reputation" modification is chosen,
	* Current reputation - Change = New reputation

After creating an action: 
* All fields should be read only
* Fields with no values should be hidden e.g. no description.
* All creation buttons should be hidden from the footer.

**Out of scope**
	-

**Design**
https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=9964-270708&mode=design&t=LtcCc3gByNYW0NlR-4
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/79e0ea3fe7b523ee680d8e8a0d21762f.png)
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/79e1e4fbc0d27b250a8d03d345a8b9d2.png)
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/79e34325d1226a12f795fada76665142.png)
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/79e54d20bdb5ed3d9fcd074d8279ac36.png)

Tooltip on Root team:
https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=18229-351836&mode=design&t=LfNtlHsVjLahPjzH-4
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/ae26b208c843d59a88d2bda18b06aacd.png)

**Comment by AdrianDudko** [comment]
@arrenv This one is waiting to be done by our team.

**Comment by AdrianDudko** [comment]
This issue is being handled in https://github.com/JoinColony/colonyCDapp/pull/1981

**Comment by AdrianDudko** [comment]
@arrenv @joanna-pagepro 

We need information about how the form should work if we should show only members with reputation when we want to remove reputation to proceed with this task. 

There are cases like:
- user selects award reputation modification, selects a member with no reputation points and then changes modification to remove reputation
- user selects a member with no reputation points first, then selects a modification - remove reputation

Also, should we set a limit to the amount value? Right now, if the number is too big there's an [error](https://github.com/JoinColony/colonyCDapp/pull/1981#pullrequestreview-1904305827).

**Comment by arrenv** [comment]
> * user selects award reputation modification, selects a member with no reputation points and then changes modification to remove reputation
> * user selects a member with no reputation points first, then selects a modification - remove reputation

Confirming here based on our call: The member/address field should reset if the modification type field is changed.

In terms of a max number, from a contract perspective I believe the max is 78 digits, Armando in the linked example shows 60 digits, so. So, that needs to be tested, but, yes, we should limit the amount value number of digits.

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/1981
