### ISSUE TITLE
Metadata is showing the Colony creator and not the author of the transaction 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1567]
## Description

Currently, in production, when I open a transaction from the activity feed, it's showing the Colony creator in the metadata which doesn't match the metadata in the activity which shows the correct username of the user who created the transaction.

<img width="1413" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/2150c82a-49ed-42e8-ad21-bf04960cc94b">

The expected behaviour is for the action or motion when triggered in the side panel to show the correct user who created the transaction as per the activity feed.

**Comment by bassgeta** [comment]
This issue is quite more complex than initially estimated, we render a form with prefilled values and we never fetch existing action data properly, thus never having actual recipient data, we always fallback to the logged in user.
Upping estimation to a 12, scope creep is real :D

**Comment by TomaszChmielPagepro** [comment]
@bassgeta FYI this is fixed here https://github.com/JoinColony/colonyCDapp/pull/1483

**Comment by bassgeta** [comment]
> @bassgeta FYI this is fixed here #1483
> 
> https://github.com/JoinColony/colonyCDapp/pull/1483/files#diff-63f2b4c12ac4f6ad0fb63607585773757eb1d2d0b2fda51899516aefd88bc8c4R89

Nice, in that case, maybe we can keep this ticket as it is, and create a new one for the work I've done on this, which was mostly refactoring
