### ISSUE TITLE
Port Simple Decisions

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#161]
Initial porting of Simple Decisions.
More issues to be added as we go.

## Issues

- [x] #165
- [x] #166
- [x] #167
- [x] #168
- [x] #169
- [x] #170
- [ ] #171

**Comment by willm30** [comment]
@rdig Is the plan to port Simple Decisions as well? I created a project for it assuming it was but want to check.

**Comment by rdig** [comment]
Yup, everything's to be ported eventually. That includes Simple Decisions as well. Good thinking.
