### ISSUE TITLE
Actions: Description field

### ISSUE THREAD

**Issue by AdrianDudko** [JoinColony/colonyCDapp#1611]
**Teamwork task:** https://tw.auroracreation.com/app/tasks/15646129
**Created by:** @melyndav 

**Description**

**Issue 1: Issues with formatting using WYSIWYG - Numbered list styling (colors, padding) doesn't match Figma**

![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/65c46534938dc92d949bad9271e23a6d.png)

**Issue 2: Issues with unordered list formatting using the WYSIWYG - colours and padding do not match Figma.**

![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/667e949702292de71331ad5da1458b75.png)

**Issue 3: Reduce the line height padding. Currently it's at 1.25em. Please reduce to 0.5em for regular text and options like Bold, underlined, italics etc). Keep the larger line ehights for heading fonts**

![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/67dc0374d2e976a020f33e2df1e65f88.png)

**Issue 4: The description field doesn't allow more than 4000 characters even when I try to add more. However, when I try to submit the action, I recieve an error with max characters even though I meet the 4000 limit.**

![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/6db9419fcbd6ca058312ecad4dcebd00.png)

**Issue 5: The expand field randomly shows in the right side:**

![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/3d286ee6f480e9ef17941f4d6b97faa9.png)

**Comment by joanna-pagepro** [comment]
@AdrianDudko @arrenv  how should the text from the description look like when collapsed and when you have for example a line with a paragraph and then the next one with a list, or just a list, etc.?

**Comment by melyndav** [comment]
> the next one with a list, or just a list, etc.?

Hi @joanna-pagepro if you go to this section here in Figma, there is a full breakdown of all the different actions and interactions just for the description section - https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=2890-251758&mode=design&t=tNPlPx6z1LBhFzf9-4
