### ISSUE TITLE
Global: UI issue with rounded corners on tables

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1627]
**Teamwork task:** https://tw.auroracreation.com/#/tasks/15730698

## Description

In production, the rounded corners within the header of the tables on the following pages are not showing correctly due to the coloured background not having rounded corners applied. 

It appears to be both left and right top corners across all tables. 

- Dashboard activity feed
- Activity feed
- Balance
- All tables within actions (Edit Colony details, Manage tokens)

Example of the dashboard table:
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/db45adbf-f68a-4844-b9ca-606682b8351f)

Example of the balance table:
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/0da29acc-f3c8-4ff8-872d-c1515cf1f0f4)

Example of the activity feed table:
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/e0bfe362-3b21-4381-a38d-21dfb121bd58)

Example of a table within the actions - Edit Colony details action type:
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/10ccd1ac-156e-40b4-8872-cf88da6a4d20)

## Expected outcome
Expected UI as per Figma:
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/f088b77f-c36c-4ec2-a165-6e15d92801e2)

## Figma

Link to Figma for an example: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=11846-72482&mode=design&t=V9WB8knufbS8936p-4

**Comment by AdrianDudko** [comment]
@melyndav It was fixed in this PR: https://github.com/JoinColony/colonyCDapp/pull/1619. I'm closing this issue.

**Comment by AdrianDudko** [comment]
@melyndav It was fixed in this PR: https://github.com/JoinColony/colonyCDapp/pull/1619. I'm closing this issue.
