### ISSUE TITLE
Actions: Edit Colony details missing information 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1628]
## Description

When selecting the 'Edit Colony details' action type, the Colony name and Colony description should be prefilled upon load of the action type. 

Here you can see that the Colony description and name is existing but isn't being loaded into the action as default.

If no description has been provided to date, this field should remain in its default state. 

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/5fa94a50-77ea-4346-9a61-693ca6d983f0)

## Expected behaviour: 

As shown below, this information should be prefilled when loading the action type if the content is available:

<img width="600" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/3fb55c9d-fce6-4ad6-8297-5187b48ba935">

## Figma link

Link to Figma for example: 

https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=3487-329307&mode=design&t=V9WB8knufbS8936p-4

**Comment by AdrianDudko** [comment]
@melyndav I'm not sure when it was fixed, but it seems to be fine now 

![Image](https://github.com/JoinColony/colonyCDapp/assets/112850454/b200e338-90b4-4644-bee1-6f1388b23c25)

**Comment by AdrianDudko** [comment]
Fixed.
