### ISSUE TITLE
Actions: Paragraph input fields within action types 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1629]
**Teamwork task:** [Actions: Paragraph input fields within action types](https://tw.auroracreation.com/#/tasks/15782295)

## Descriptions

The objective description works as exactly the same as the Colony description in the 'Edit Colony details' action. I.e the content should wrap and the chevron should be ignored.

## Figma

Link to example action type: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=3487-329307&mode=design&t=V9WB8knufbS8936p-4

**Comment by KornelKwiatkowski** [comment]
hi @melyndav I'm a bit confused about this task :D

If we want to add a chevron to "Colony description", shouldn't this field behave like the "Description" field? I think as a user I would expect the fields that have chevron to work the same way. What do you think?

Just like in the video below:

https://github.com/JoinColony/colonyCDapp/assets/90605528/38ea6b20-cc61-4b5b-8e05-1c2134d8a094

**Comment by arrenv** [comment]
> If we want to add a chevron to "Colony description", shouldn't this field behave like the "Description" field? I think as a user I would expect the fields that have chevron to work the same way. What do you think?

Let's go with the same as you have demonstrated in the video. We should still have the max length of 200 characters though i.e. `MAX_OBJECTIVE_DESCRIPTION_LENGTH`.

**Comment by KornelKwiatkowski** [comment]
@arrenv At this moment, the maximum number of characters for the objective description field is 200. Is there a chance that the API will return a default value for this field with more characters? If so, should the text be cut to 200 characters?

**Comment by arrenv** [comment]
> @arrenv At this moment, the maximum number of characters for the objective description field is 200. Is there a chance that the API will return a default value for this field with more characters? If so, should the text be cut to 200 characters?

Thank you for confirming, 200 should be fine, I will update the spec.

There is a chance that the API can return more characters, but it is hopefully unlikely. But in terms of the UI, showing more characters, it will break parts of the UI. So, yes please, perhaps the frontend can limit to a max of 250 characters?

**Comment by KornelKwiatkowski** [comment]
@arrenv  So, should I change the `MAX_OBJECTIVE_DESCRIPTION_LENGTH` from 200 to 250?

**Comment by KornelKwiatkowski** [comment]
I opened PR. Let me know if you want to change the maximum number of characters you wrote about :) I can do it on a separate branch

**Comment by arrenv** [comment]
> @arrenv I opened PR. Let me know if you want to change the maximum number of characters you wrote about :) I can do it on a separate branch

@KornelKwiatkowski, let's leave it at 200. Apologies for the confusion.
