### ISSUE TITLE
Actions: Changes to 'Create a decision' action type

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1631]
## Description 

The 'Create a decision' action type required renaming. As part of this change, a number of menus and dropdown items also need to be updated accordingly as part of this PR's scope

## Scope of changes required

1. Update the title of the 'Create a decision' action to 'Create agreement' 

<img width="334" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/ce69489a-32d4-4803-839e-b84b88cd99f7">

2. Update the metadata content of the action from 'New decision...' to 'New agreement'

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/2793f034-156c-447f-bd79-18ccb9199e7c)

3. Within the main action dropdown menu, make two changes:
 a. Change the 'Decisions' title to 'Agreements'
 b. Change the 'Create a decision' menu item to 'Create agreement'

<img width="468" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/c4f24de6-64ea-4f41-bab9-3f2412333c92">

**Comment by rdig** [comment]
@ArmandoGraterol why did you start working on this, as this wasn't planned for this cycle: https://github.com/orgs/JoinColony/projects/40 ?

And there were more priority issues left in the "Todo" stack
