### ISSUE TITLE
Actions: Closing Model & Global Cancel buttons

### ISSUE THREAD

**Issue by AdrianDudko** [JoinColony/colonyCDapp#1640]
**Teamwork task:** https://tw.auroracreation.com/#/tasks/15667585
**Created by:** @melyndav 

**Description**

A couple of UI issues with the closing model:

~~1. icon in the top left should be 20x20px. It's currently too big.~~
2. The border on the cancel button should be text-gray-300. This should be updated for all global cancel buttons. They are too light. 

![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/39903e64c54610d50b1da03afd2de840.png)

**Design**

https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=3536-727121&mode=design&t=BeIw3LrWaM6ZCNdP-4

**Comment by AdrianDudko** [comment]
@melyndav @arrenv  Could you please confirm that the icon should be 20x20px? In Figma it has 24x24px 

![image](https://github.com/JoinColony/colonyCDapp/assets/112850454/bb44c6a4-3a8c-44f6-8eb6-0074949928d9)
https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=3536-727121&mode=design&t=BeIw3LrWaM6ZCNdP-4

**Comment by melyndav** [comment]
Hey @AdrianDudko no need to touch this icon. I just checked production and it looks like it's been updated along the way since November and it's good as it is now.

**Comment by AdrianDudko** [comment]
@melyndav It's fixed 

![Image](https://github.com/JoinColony/colonyCDapp/assets/112850454/2ae48c94-b449-482a-a8c3-9c541f148fa4)
![Image](https://github.com/JoinColony/colonyCDapp/assets/112850454/8da3b709-6628-4451-8e1a-2ab995a9209a)
