### ISSUE TITLE
Actions: Selecting an action type from the dropdown triggers close model 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1641]
## Description 

When attempting to create a new action in production from the dropdown menu after adding a title, the confirmation model is triggered. The scope of the PR is to remove this model from being triggered to allow the user to first complete the title field before selecting the action type from the dropdown. 

The model does not trigger if a title has not been added. 

### Correct behaviour: 

The close model should only trigger once the user has selected an action type and has added or changed any content inside the action (not the title) and then uses the dropdown to change the action type. 

### Issue experienced:

![modelforces](https://github.com/JoinColony/colonyCDapp/assets/82127904/38434298-8b0d-4f27-ae4a-408d4c40d1f0)

**Comment by melyndav** [comment]
Hey @CzarekDryl I think this issue I just raised above is being covered in #1592 correct. Should I close this one?

**Comment by CzarekDryl** [comment]
Hey @melyndav, that's right, you can close this one. I was merged by me today :)

**Comment by melyndav** [comment]
Closing this one since it's been resolved in #1592 by Czarek! :)
