### ISSUE TITLE
Manage permission options in child teams

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1655]
## Steps to reproduce
- Open the Create a new action panel.
- Select a team to give the member permissions.
- You will see that you have the option to give `Owner` permissions to a member in a team. This should not be possible, as the `Owner` permissions should only give assignable in the Root/General.
- At the moment, doing so will give the following contract error `colony-bad-domain-for-role`.

## Expected behavior
- The `Owner` permission should not be a selectable option when you are awarding permissions in a child team.
- When selecting `Custom permissions`, `Root` and `Recovery` should not be options when within a child team

Figma Design - https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v3?type=design&node-id=7292-382616&mode=design&t=GiZWxOFvBz8MwL40-11

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/72d1f54c-f4e4-4eb5-972a-6b0efc21e68e)

## Actual behavior
- You are able to select the `Owner` permission option when giving permissions in a child team.
- You are able to select the `Root` and `Recovery` permission option when giving `Custom` permissions in a child team.
- The transaction is failing without any feedback to the user.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/694d6174-26ca-472b-8766-dbbb290565bd)

**Comment by rdig** [comment]
@ArmandoGraterol why did you start working on this, as this wasn't planned for this cycle: https://github.com/orgs/JoinColony/projects/40 ?

And there were more priority issues left in the "Todo" stack
