### ISSUE TITLE
Track "Manage Verified Members" changes when using Permissions

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1660]
## Description
In order to be able to view changes made to `Manage Verified Members` in passed transactions that used Permissions, it should be possible see the `Added` or `Removed` members i.e. changes. Currently, you are only able to see the current list of verified members, not what was actually changed.

Currently, we support this functionality if the decision method is `Reputation` (i.e. Motions) using this query:

```
query MyQuery {
  getActionsByColony(colonyId: "0xa6Ee101fe6D2C220e373B2D1DE70A905Aa03bf41") {
    items {
      id
      pendingColonyMetadata {
        whitelistedAddresses
      }
    }
  }
}

```

This could likely be generalised to being usable for both `Motions` & `Actions` and could be bundled with Colony metadata differences as the same as mentioned in this issue - https://github.com/JoinColony/colonyCDapp/issues/1467

**Comment by rdig** [comment]
Closing as it's not relevant anymore _(to be tracked via this issue, not the feature request itself)_

This will be done as part of the Verified Members feature, for which you can find all the issues here: https://github.com/orgs/JoinColony/projects/47
