### ISSUE TITLE
Add coingecko attribution

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#1661]
> It's using the [CoinGecko](https://www.coingecko.com/api/documentation) api, which does not require an api key, allows 30 calls/minute from the client, is free and supports multichain.

Mel has added a design here for it - https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-3849&mode=design&t=Auc5dqwOVWhHVZnU-4

It should sit within the currency selection drop down.

Link should go to `https://www.coingecko.com/` as they require. Should open in a new tab.

_Originally posted by @arrenv in https://github.com/JoinColony/colonyCDapp/issues/1565#issuecomment-1875246371_
            
            
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/534dfbc5-2dc7-4737-b98e-12a04423bc96)

**Comment by arrenv** [comment]
@willm30 Given the rate limit, what is the fallback if the API requests fails due to exceeding it?

**Comment by willm30** [comment]
@arrenv If the calls fail, the conversion will just show as 0. 

There are paid services for increased requirements. Production may need higher call / rate limits (see https://www.coingecko.com/en/api/pricing), e.g. If someone changes their currency often or has lots of root balances. 

If we're paying for an api key, we may want to make these requests from a server to conceal it from network requests.

**Comment by rdig** [comment]
Correct on both counts @willm30 :+1: 

We're definitely not using a free tier API key, in which case, this will likely go through the Auth proxy

**Comment by arrenv** [comment]
> @arrenv If the calls fail, the conversion will just show as 0. 

It would be better to show as a "-" rather then a "0". Showing as a "0" incorrectly gives it a value.
