### ISSUE TITLE
Actions: Refactor the way our current form titles work

### ISSUE THREAD

**Issue by bassgeta** [JoinColony/colonyCDapp#1669]
Currently we display the form titles in the following flow:
1. the hook `useActionDescriptionMetadata` (after [this PR](https://github.com/JoinColony/colonyCDapp/pull/1608) is merged it's a component called `ActionDescriptionMetadata`) has a map of "getters":
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/86e049f2-a33d-4d18-bb47-c4868f16bfc1)
2. Then it calls the appropriate "getter", gets some modified action data
3. calls `ColonyActions/helpers/getActionTitleValues.ts`
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/ae9f9a1a-573b-434b-81a9-8e2c215d14c7)
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/eda8efbd-38b9-4fd4-b3e2-58ee004c4acb)
4. finally it overrides the initiator metadata
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/cc32f1d7-e5de-4dda-a822-16c352fde20c)

This is quite complicated, we should just return data from the "getter", format it there and return it.
Note that it may get tricky since we are reusing the forms for display of completed actions, but it shouldn't be much work.

**Comment by jakubcolony** [comment]
Based on our discussion, this could also look at refactoring/removing `AsyncText` component
