### ISSUE TITLE
Most active team logic is incorrect

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#1670]
As established in https://github.com/JoinColony/colonyCDapp/pull/1622#pullrequestreview-1797901753, the logic for most active team does not take into consideration motions that can be created in a particular domain, only actions that have a non-empty "from domain" field.

This issue is to ensure the most active team is decided based on both "from domain" and "motion domain" fields.

**Comment by rdig** [comment]
Please investigate this first, as the estimate might be wrong due to the hidden complexity that this issue might present

**Comment by bassgeta** [comment]
Was this by any chance fixed via [this commit](https://github.com/JoinColony/colonyCDapp/commit/1674b424e44acb8ddb2b191e0ecd4f02afb8ffbd)?

**Comment by ArmandoGraterol** [comment]
I've been testing the activity feed and it seems like it is taking into account motions that meet the staking requirement:
![Image](https://github.com/JoinColony/colonyCDapp/assets/18473896/3003d673-ebb3-40e4-b945-9c3568240b7d)

@jakubcolony @arrenv Seeing that you guys were the ones that initially noticed and created this issue, can any of you test `master` and let me know if you are able to replicate the issue and how?


There are other weird behaviors, for example, the feed seemed to reset after installing the reputation extension but in the case of the most active team section, it seems to be working as expected.

**Comment by jakubcolony** [comment]
Hey @ArmandoGraterol, thanks for looking into it, you are right as this seems to be counting motions properly too, I missed the fact block-ingestor sets `fromDomainId` to the created in domain.

Closing the issue.
