### ISSUE TITLE
Add copy to Administration permissions pill on Extension Installation Page

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#1672]
![image](https://github.com/JoinColony/colonyCDapp/assets/64402732/99b8e759-9ab5-4e09-8fcc-3ebb4a8d1859)

**Comment by arrenv** [comment]
There is Pagepro issue tracking this as well, here if you have access - https://tw.auroracreation.com/app/tasks/15670058

Basically, it should just be using the abstracted permission pills as well for consistency.

> Description
> Users should see updated permission/role pills in extension detail page. Currently when extension needs some roles in colony, it shows old permissions pills
> 
> Acceptance criteria
> 
> update pills to new ones:
> - Check roles as of the spec [https://tw.auroracreation.com/app/files/3809455](https://tw.auroracreation.com/#/files/3809455)
> - There should now be a Permissions label
> - Each pill should have the correct tooltip as of the design
> - The URL in tooltips should link to: https://docs.colony.io/learn/advanced-concepts/permissions/

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/412c2207-c21c-4936-b194-2a24bf8dc1f9)


https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=9707%3A62409&mode=design&t=I8pZIZ4PRTZV9xLG-1

**Comment by AdrianDudko** [comment]
@arrenv Thanks for reminding me about this task 😅

I've created a new issue https://github.com/JoinColony/colonyCDapp/issues/1694 and we will handle this. 

This one can be closed or linked to PR which will solve it.

**Comment by arrenv** [comment]
Closing this, as it is being addressed here - https://github.com/JoinColony/colonyCDapp/issues/1694
