### ISSUE TITLE
Upgrade nodeJS to version 20

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyCDapp#1673]
The CDapp still uses NodeJS 16, which is out of maintenance since October 2023:

![Image](https://github.com/JoinColony/colonyCDapp/assets/2174084/d6fb7cf7-8532-461b-961f-2bb8ffa109dd)

For the move away from webpack to tsup/esbuild we will need to upgrade it and I assume it is generally a good idea to not work with a version of Node that doesn't get security updates anymore. Furthermore adding/upgrading dependencies will be a pain as a lot of them will require node 18 rather sooner than later.

This issue tracks the upgrading of all relevant nodeJS versions to 20 (including the server ones).

**Comment by rdig** [comment]
This was completed by #1714 right @chmanie  ?

**Comment by chmanie** [comment]
Yes exactly!
