### ISSUE TITLE
Incoming funds: UI issues

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1695]
**Teamwork task:** https://tw.auroracreation.com/#/tasks/15741061

## Description

A couple of UI require fixing on the incoming funds page.

1. Pagination should not show by default when there are less than ten results to show. This aligns the incoming funds table pagination with the other pagination approaches.

2. The hover/active states for the search input field within the filter dropdown do not match the other inputs. This input should be a globally used component so it looks and acts as the others. 

<img width="1327" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/ad8c6124-2959-4963-b39d-4b3f75432f54">

3. Where there are no funds to display, the empty state should show as per the other table states. Currently it's showing like the screenshot below 

<img width="1353" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/2f06a984-1195-448a-b87a-e5dc91893412">

## Figma

Link to Figma to check designs: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=5226-353525&mode=design&t=IdkhxLk8vZ1WXkYb-4

**Comment by AdrianDudko** [comment]
@melyndav thanks for creating an issue for this. I will take care of this from now on.  :)

**Comment by CzarekDryl** [comment]
@melyndav I'm not able to reproduce bug with empty content, it's showing for me everytime.
![image](https://github.com/JoinColony/colonyCDapp/assets/76940796/7ec1a6fb-3e08-4ebf-92fc-e209205ca7df)
