### ISSUE TITLE
Refactor / remove existing Table react library

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#1707]
Currently we have 4 different table components (`Table`, `TableWithActionsHeader`, `TableWithMeatballMenu`, `TableWithHeaderAndMeatballMenu`, all with a pretty complicated API.

We should aim to simplify all of this and remove the `@tanstack/react-table` library, since it's too complicated for our simple use cases.

### What should we do?

Remove the library and build a simple to use table. 
The table component should just apply styles via a Table element and render all the children.
So the way we use it could be something like

```JSX
<Table>
  <thead>
    <tr>
      <th>Heading 1</th>
      <th>Heading 2</th>
      <th>Heading 3</th>
    </tr>
  </thead>
  <tbody>
    {rows.map(row => (
      <tr>
        <td>{row.name}</td>
        <td>{row.someProperty}</td>
        <td><MeatBallMenu ... /></td>
      </tr>
    ))}
  </tbody>
</Table>
````
We will also need reusable/customizable pagination components to go along with the table too.

We can add in some complex `data grid` libraries when we actually get complex data to load.

**Comment by bassgeta** [comment]
Closed, as it's way too much work and we'll be doing #1784 instead
