### ISSUE TITLE
Activity feed skeleton loader height is incorrect

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1718]
## Steps to reproduce

1. Navigate to the Activity feed page.

## Expected behaviour

* Skeleton loader should be consistent with the content it is loading.
* Note, the height of the activity table is different on the dashboard, so they should not impact each other.

## Actual behaviour

* Skeleton loader is not consistent with the content it is loading.

![activity-feed-loader](https://github.com/JoinColony/colonyCDapp/assets/33682027/1d769241-b9a6-43c6-80d3-601d252c3f64)

**Comment by AdrianDudko** [comment]
@arrenv  This was raised on TW some time ago and should be fixed in this PR https://github.com/JoinColony/colonyCDapp/pull/1483. I will close this issue once the mentioned PR is closed.

**Comment by AdrianDudko** [comment]
Fixed in PR: https://github.com/JoinColony/colonyCDapp/pull/1756
