### ISSUE TITLE
No permissions tooltip gets clipped 

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#1720]
**Teamwork task:** [No permissions tooltip gets clipped](https://tw.auroracreation.com/#/tasks/15753997)

## Steps to reproduce

1. Navigate to a colony as a user with no permissions.
2. Open action sidebar and hover over any of the exclamation marks until a tooltip is shown.

## Expected behaviour

* The tooltip shows nicely

## Actual behaviour

* Tooltip is clipped near the borders of the action type dropdown:
![image](https://github.com/JoinColony/colonyCDapp/assets/112586815/e3b46a84-49f9-4143-b125-fd661d06f3ad)

**Comment by jakubcolony** [comment]
@arrenv fyi

**Comment by arrenv** [comment]
Thanks @jakubcolony, this was being tracked in Pagepro's system I believe, but good to have it here now.
