### ISSUE TITLE
[Verified members] Feature: Block ingestor can parse and handle the Add verified members event - Permissions

### ISSUE THREAD

**Issue by bassgeta** [JoinColony/colonyCDapp#1722]
### Story

The block ingestor must be able to parse the new event which corresponds to adding verified members via permissions.
Then it needs to call the graphql mutation for adding verified members.

### Description

The client will send out a `Metadata delta` event where they will pass through the pseudocode language a la `ADD {userAddress} VERIFIED {colonyAddress}` and the block ingestor needs to parse it and handle it.

## Implementation

Create a new handler in the event handlers folder and handle it in `eventProcessor`.
We need to parse the passed in string, so we know which users are being added to which colony.

### This issue is complete when...

- [ ] Block ingestor can successfully handle the event and discern it being an `Add` event not anything else 
- [ ] The gql mutation is called and the database table is updated

**Comment by rdig** [comment]
I think this needs to be opened (moved) on the [block ingestor](https://github.com/JoinColony/block-ingestor) side, as all the work will be done in that repo

**Comment by bassgeta** [comment]
closing as this is going to be done via https://github.com/JoinColony/block-ingestor/issues/160
