### ISSUE TITLE
[Verified members] Feature: Block ingestor can parse and handle the Remove verified members motion

### ISSUE THREAD

**Issue by bassgeta** [JoinColony/colonyCDapp#1725]
### Story

The block ingestor must be able to parse the new event which corresponds to removing verified members via motions.
When it's finalized it needs to apply the result (or not apply it if it failed).

### Description

The client will send out a `Metadata delta` motion event where they will pass through the pseudocode language a la `REMOVE {userAddress} VERIFIED {colonyAddress}` and the block ingestor needs to parse it and handle it.

## Implementation

Create a new handler in the `motions/motionCreated` folder and handle it in `motionCreated.ts` file.
We need to parse the passed in string, so we know which user is being removed from which colony's verified members.

### This issue is complete when...

- [ ] Block ingestor can successfully handle the motion event and discern it being `Remove` event not anything else 
- [ ] Block ingestor successfully creates a motion
- [ ] If the motion passes, we remove the verified members via the gql mutation
- [ ] If the motion fails the members don't get removed

**Comment by rdig** [comment]
I think this needs to be opened (moved) on the [block ingestor](https://github.com/JoinColony/block-ingestor) side, as all the work will be done in that repo

**Comment by bassgeta** [comment]
closed since it will be resolved by https://github.com/JoinColony/block-ingestor/issues/163
