### ISSUE TITLE
Actions: Styling of error states 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1735]
**Teamwork task:** [Actions: Styling of error states](https://tw.auroracreation.com/#/tasks/15750753)

## Description

The field label of the error state doesn't match Figma designs and should be color-negative-400 to match the icon and input field. The scope of this PR is to fix this across all action types to ensure alignment with Figma and consistency in the UI. 

**How it currently shows:**
<img width="363" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/af03990e-419a-422d-a3b4-1bdc5627a4e7">

**Figma:**
<img width="1342" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/8be7da8c-a134-4fad-a9a7-50ef54437b6e">

## Figma links

Example of error states: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=10070-268264&mode=design&t=vUqwuYYcWBGj21pv-4

**Comment by AdrianDudko** [comment]
@melyndav thanks, it goes to "TO DO"
