### ISSUE TITLE
Remove one of clipboard copy hooks

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#1736]
Currently, we have two separate clipboard copy hooks:
- `useCopyToClipboard`
- `useClipboardCopy`

One of which can be removed.

**Comment by jakubzajac** [comment]
Please keep `useCopyToClipboard`

**Comment by rdig** [comment]
@n4vn337 please let us know if you intend on working on this issue, so that we can assign it to you

**Comment by n4vn337** [comment]
I would be happy to help, but I might need some help setting up this on my system. If I encounter any issues I will drop it here, hope that works.

**Comment by rdig** [comment]
Sounds good. Thank you for your help

**Comment by chmanie** [comment]
Really sorry, but I snatched this as part of my monster refactor #1744. @n4vn337 please feel free to take another issue, happy to help you set up the environment :)
