### ISSUE TITLE
Incorrect input placeholder for teams dropdown

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1738]
**Teamwork task:** https://tw.auroracreation.com/#/tasks/15750738

## Steps to reproduce

1. Test any of the team dropdowns in the action creator. Including the `Created in` field.
2. Review the search input placeholder.

## Expected behaviour

* The search input placeholder of the team dropdown should only have "Search" in it.
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/c026a434-9bee-4c74-9d9e-c9ba1bd4f240)

## Actual behaviour

* The search input placeholder of the team dropdown includes the text "Search or add wallet address", which is not accurate.
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/1aa6ad3b-f29f-4f48-95c3-c461ef361713)

**Comment by AdrianDudko** [comment]
@arrenv Thanks, it goes to "TO DO"
