### ISSUE TITLE
Update `USER_ROLE` const to enum

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyCDapp#1739]
We should change `USER_ROLE`:
```
export const USER_ROLE = {
  Mod: 'mod',
  Payer: 'payer',
  Admin: 'admin',
  Owner: 'owner',
  Custom: 'custom',
} as const;
```

To an enum so it is easier to read and feels less hacky.

**Comment by jakubcolony** [comment]
Hey @ArmandoGraterol, thanks for opening this issue, I will close it however as it's a duplicate of a draft we've already got on the maintenance list - `Use enums instead of as const objects`
