### ISSUE TITLE
Maintenance: upgrade to the newest version of TypeScript

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyCDapp#1745]
Upgrade TypeScript to the newest 5.x version available. I did an upgrade of TS to 5.0.4 in #1744 but this is not the latest version.

Any version higher than that will yield > 100 errors that need to be fixed. I assume that they are all of similar nature so it's probably not as much work as it sounds.

**Comment by rdig** [comment]
Closing as not relevant anymore

**Comment by chmanie** [comment]
No? Are we updated to the latest version already?
