### ISSUE TITLE
Maintenance: replace draft-js with something that is maintained

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyCDapp#1747]
`draft-js` got the last update 3 years ago and is fully abandoned.

Please evaluate if something like `draft-js` is really necessary or if we can get away with less (I don't even know what it is used for atm).

If we think that we need to replace it, consider https://github.com/facebook/lexical

**Comment by jakubcolony** [comment]
Hey @chmanie, I noticed `draft-js` isn't actually used anywhere so removed it as a dependency in #1708

**Comment by rdig** [comment]
Hmmm. I think we _might_ need to add that back in _(or an alternative to it)_. As I remember it `draft-js` was being used for Decisions. But that's in the old UI though.

**Comment by jakubcolony** [comment]
That was the old UI (which was deleted) and now we're using `tiptap` for rich text. I think this issue can be closed

**Comment by chmanie** [comment]
Great! Thanks for the clarifiction @jakubcolony
