### ISSUE TITLE
Change default app page title

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1758]
## Description

In order to avoid confusion and maintain consistency with naming, we would like to have the app's default page title updated.

- Current default page title is:  "Colony CDapp".
- Change default page title to:  "Colony App"

**Current title**

![2023-11-27 13_04_55-](https://github.com/JoinColony/colonyCDapp/assets/33682027/9dae0299-4c3c-4522-96c3-de7f67cb9349)

**Comment by saimkhan065** [comment]
Hello, I would love to work on this issue!

**Comment by rdig** [comment]
Sounds great @saimkhan065, I've assigned it to.

**Comment by n4vn337** [comment]
Hi, I was trying to setup this and came across some error, if possible could you help me setting it up so I can help fix this.
I have set up the npm version using nvm as mentioned in the README

command
```npm install```
error: for rest i got something similar ```npm WARN deprecated ganache-core@2.13.2: ganache-core is now ganache; visit https://trfl.io/g7 for details```
and at the end:
```> colony-cdapp@5.0.0-alpha.0 postinstall
> ./scripts/lambda-functions-dependencies.sh && scripts/generate-amplify-local-config.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code 1
npm ERR! path D:\contributers\colonyCDapp
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c ./scripts/lambda-functions-dependencies.sh && scripts/generate-amplify-local-config.sh

npm ERR! A complete log of this run can be found in: C:\Users\n4nav\AppData\Local\npm-cache\_logs\2024-01-19T18_00_22_027Z-debug-0.log```

**Comment by saimkhan065** [comment]
@rdig Requested change is to be done on the file src/templates/index.html on the <title> tag right?
I am sorry if this is a stupid question... I just wanted to make sure before opening a PR.

**Comment by n4vn337** [comment]
@rdig thanks for the heads up, will switch to linux and give it another try.

**Comment by n4vn337** [comment]
I have initiated a Pull Request for this issue, please check.
