### ISSUE TITLE
[Manage tokens] Implement the graphql backend and update the database with a new entity

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1759]
_Note: Adapted from @bassgeta's https://github.com/JoinColony/colonyCDapp/issues/1721_

### Story

When the block ingestor receives events for adding/removing a Colony's managed tokens, it will need to modify that data in the database. The client will also need to be able to fetch managed tokens.

### Description
We need a new entity which will store pairs of `colonyAddress` and `tokenAddress`. Additionally, we need a gql query for fetching managed tokens and a gql mutation for adding them. 

We need mutations for adding and removing managed tokens, they cannot be called outside the block ingestor, so the auth proxy will need to be modified too.

### This issue is complete when...

- [ ] You can fetch managed tokens via graphql.
- [ ] You can create managed tokens via graphql, but only via block ingestor.
- [ ] You can remove managed tokens via graphql, but only via block ingestor.
- [ ] The new entity is created in our database.

**Comment by rdig** [comment]
Why do we need a new entity for this? 

We already have this: https://github.com/JoinColony/colonyCDapp/blob/master/amplify/backend/api/colonycdapp/schema.graphql#L1248

Also, while similar to Verified Members this can not work exactly the same, meaning this needs new specs, especially when it comes to authentication.

As a last note, as this is not planned for this Quarter, we'll need to find a way to squeeze it in

**Comment by arrenv** [comment]
Thank you for clarifying, I had assumed it was similar. Happy to close this if there is another approach.

My main goal here was to being able to display the changes to Manage token actions in both actions and motions, and to unblock this PR - https://github.com/JoinColony/colonyCDapp/pull/1430

**Comment by rdig** [comment]
Makes sense, but I fear that PR will stay blocked at least until we iron out the actual spec of the delta log format as that's the basis for this, verified members, safe control _(or anything else we put in)_ to actually work.

So for now we can keep it open, however with a `on-hold` tag on it

**Comment by iamsamgibbs** [comment]
Closing now that #2464 has been merged!
