### ISSUE TITLE
Refactor core Button component framework

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#1765]
Refactor `Button` and related components to simplify their usage and align them with [Figma designs](https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-45010&mode=design)

**Comment by rdig** [comment]
@jakubcolony since this in progress can you please provide an estimate ?

**Comment by jakubcolony** [comment]
@rdig estimating 6 hours, there's at least 60 files using this component.

**Comment by jakubcolony** [comment]
As discussed with @rdig, the scope of this issue was seriously underestimated and considering the limited value it brings to the user, I'm gonna pause work on this issue to focus on higher priority tasks.
