### ISSUE TITLE
Move UpdateDomainMetadata's address extraction and treatment to a lambda function

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyCDapp#1779]
Right now, in https://github.com/JoinColony/colonyCDappAuthProxy/blob/master/src/routes/graphql/mutations.ts, in the `CreateDomainMetadata/UpdateDomainMetadata` handler, we are extracting colony addresses using a pattern that is compatible with regular ids and pending domain metadata IDs, to check if the request should pass or not. This extraction and treatment of the address depending on what format it has should not happen in the proxy:

> The auth proxy shouldn't know (or care about) the format the data (address) is being passed in, it should just forward (or block) responses that it receives

Therefore, we should move the treating of IDs for actions like this one to a lambda function, do the necessary checks, and create the metadata from there.

**Comment by jakubcolony** [comment]
As per discussion in the dev chat, we are abandoning the idea of moving those checks to lambda, so I'm closing this issue.
