### ISSUE TITLE
Actions: Verified & non-verified users 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1780]
## Description

When selecting a user from any dropdown field across supporting action types in master, there is a problem with the verification of users where both icons (the verified blue icon and the orange alert icon) are displaying on the front end at the same time.

<img width="469" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/8e5e8e52-3ac4-44dc-9587-5d8f08a5ab81">

This is a recent regression introduced to master. I am not able to reproduce this in production. 

The expected behavior is for only one icon to show matching the correct users validation type. 

## Correct UI behaviors

Example of correct unverified member:
<img width="169" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/9a73ba3d-2f20-414f-b30d-642f444a97a6">

Example of correct verified member: 
<img width="235" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/bddcf26d-38de-4d6f-a644-21d5471601bc">

**Comment by rdig** [comment]
I think this should be tackled later during the Verified Members feature implementation.

Unless you want us to do a quick patch to fix the icons now, in production.

**Comment by melyndav** [comment]
@rdig I think this is worth resolving now and having it go out in the next deployment.
