### ISSUE TITLE
Teams: Editing a team not prefilling data

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1793]
Teamwork task: [Teams: Editing a team not prefilling data](https://tw.auroracreation.com/#/tasks/15763105)

## Description

Issue one: 
On the new Teams page recently deployed to production, when selecting the kebab menu and then 'Edit team' on a team, the side panel does not pre-fill the existing teams data (name and description). 

The scope of this issue is to prefill the associated data when a user selects to edit a specific team via the teams kebab menu icon. 

## Steps to reproduce

- In production, navigate to the teams page.
- Select the kebab menu icon on a team card.
- From the dropdown menu, select edit a team.
- The sidepanel should trigger but will display empty. 

Issue two:

The error state for the team name is showing inline as well as the error notification box at the bottom of the action. Please remove this inline error state so the error only shows in the main notification box at the bottom when the field has been left empty.

<img width="417" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/8e632132-688a-4537-a5ca-5f56111c5995">

**Comment by melyndav** [comment]
@AdrianDudko I just picked up another issue relating to Editing a team action type. Do you want me to create a new issue or merge it into here given it's the same action? 

It's the error state for the team name is showing outside of the notification box dedicated to errors. We keep getting regressions, so I have no idea why this has popped up again as I think we've fixed it a few times :(

<img width="417" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/8e632132-688a-4537-a5ca-5f56111c5995">

**Comment by AdrianDudko** [comment]
@melyndav Let's keep what you have found in the scope of this Issue :) Will you update the description? I've already informed @mksawic to have this fixed.

**Comment by melyndav** [comment]
@AdrianDudko thank you! Description updated 👍
