### ISSUE TITLE
Avatars: Updating component as part of Q12024 CDapp Maintenance

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1821]
## Description 

As part of Q12024 CDapp Maintenance, the avatars used in the CDapp are being optimized to reduce the number of options and remove any old/ unused variations left over from the Dapp.

A audit of the avatars used across components in the Design System was completed and 9 main sizes identified. However, there are three random sizes used in components that will be changed as part of this issues scope which bundles these into the 9 main sizes moving forward for the CDapp.  

The approach was discussed in collaboration with Jakub.

## Issue scope
In preparation for this maintenance item , three components need to be changed. 

### 1. Motion widgets user avatars
The user avatars in the motion widgets change from 28x28px to 26x26px. Nothing else changes except this size. All sizes including desktop and mobile variations of this component need to be updated. 

This widget and variations of this widget appear in the following motion stages.

- Voting stage
- Escalation stage
- Finalise stage

<img width="769" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/e159777f-49f6-44bd-a966-df23235f85bf">

<img width="497" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/5413f62b-81ba-4cea-ba55-27448b288489">

<img width="686" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/19790473-0f98-4d20-94ba-c3781cc63f6c">

Figma links: https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-148499&mode=design&t=cTPtDzMaecaNiCpZ-4

https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-94621&mode=design&t=cTPtDzMaecaNiCpZ-4

### 2. Edit Colony details - Colony avatar upload modal

In the Edit Colony details action type, when a user selects to change the Colony avatar, a modal is displayed with an upload form. This avatar size is currently 54x54px and needs to change to 60x60px on desktop, tablet and mobile and in all stages of the upload process.

<img width="517" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/c8dff420-2328-4bbc-96c9-20a7c01c31bd">

Desktop flow: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=3495-500043&mode=design&t=tkoTdlIzrQJ0LxXV-4 

Mobile flow: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=3495-549397&mode=design&t=tkoTdlIzrQJ0LxXV-4 
 

### 3. User account - User upload avatar

Within the users account, the user avatar in the upload area needs to be changed from 64x64px to 60x60px across desktop, table and mobile sizing during all stages of the upload process.

<img width="967" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/a6a76d1a-6d37-436f-8a0f-f4ce1d0db5c3">

Desktop flow: https://www.figma.com/file/qDsNDWdiEfbFMqCGnCP2qp/User-Account?type=design&node-id=1-2185&mode=design&t=Rd2v1B33wuVA7P1t-4 

Upload flow: https://www.figma.com/file/qDsNDWdiEfbFMqCGnCP2qp/User-Account?type=design&node-id=1-4266&mode=design&t=Rd2v1B33wuVA7P1t-4

**Comment by rdig** [comment]
@bassgeta is this issue still relevant now that we have #2066 ? Can you find out ?
