### ISSUE TITLE
title not showing after action creation

### ISSUE THREAD

**Issue by warrencolliver** [JoinColony/colonyCDapp#1826]
## Steps to reproduce

1. Create an action (I've been able to replicate this with manage permissions / edit team)
2. Fill in the fields
3. submit the form

## Expected behaviour

* All of the form fields are displayed correctly as to what the user had entered

## Actual behaviour

* The title of the action is displayed as empty. if the page is refreshed the title of the action appears however this shouldn't be necessary
* This is occurring in multiple action types
![Screenshot 2024-01-31 at 10 29 33](https://github.com/JoinColony/colonyCDapp/assets/155957480/9a9c4f61-ec40-4ba1-9f45-a60d2c3c31be)

**Comment by rdig** [comment]
However picks this up make sure it's not affected by the same thing as #1774
