### ISSUE TITLE
Handle User switching chain in metamask

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#183]
Currently, if a user switches from one chain to another chain, or switches account in metamask, the browser needs to be reloaded for the changes to show up. Really we should be listening for this provider event, so we can update the ui instantly. For example, if the user switches from gnosis to abc chain, we want the `useCanInteractWithColony` to re-run and correctly prevent the relevant parts of the Cdapp from being interacted with.

**Comment by Walletsuppport** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by willm30** [comment]
Fix: e140b74227eb81dfdf58e369d404eb64f4b9f600
