### ISSUE TITLE
Actions: Manage token action table styling 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1833]
## Description

The styling of the manage token action table does not match the Figma SOT designs. 

The three issues of the table include:

1. Font colours do not match Figma (desktop and mobile) 
2. Horizontal rules should not show (desktop and mobile)
3. Table row heights do not match Figma 
4. Styling of a new row isn't consistent with the others (mobile)

Desktop issues:
<img width="666" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/c123ad7e-71d0-457f-ab4b-a4b673290bb6">

Mobile issues:
<img width="353" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/5f48fb25-f9f1-475c-9444-a0174f2ba6c4">

<img width="454" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/73897c81-32bd-4373-94c8-55f62e159204">

## Figma link

Manage token action table: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=5708-399460&mode=design&t=Osqv7BKgty0XpmYu-4

**Comment by AdrianDudko** [comment]
@melyndav 

We can resolve this issue as the token management has been reworked since the problem was reported.

**Comment by melyndav** [comment]
> @melyndav
> 
> We can resolve this issue as the token management has been reworked since the problem was reported.

Great, thanks @AdrianDudko! 🙌
