### ISSUE TITLE
Inconsistent versions of Colony network and extensions

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1838]
## Steps to reproduce

There are various inconsistencies with Colony network versions and extension versions that are shown or are being picked up in the UI.

## Expected behaviour

* Versions should be consistent and accurate to what is installed or available to upgrade to.

## Actual behaviour

* Versions are inconsistent or are hardcoded and not correct.

### Showing version 14 is available when 13 was available, and it says you are on the latest version
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/c7c64227-fd2c-442f-b20f-cb54fbc5deb9)

### Showing version 6 and 10
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/888c2544-71bb-4199-a0cd-977f2dd4e5e3)

### Showing version 9 when it shows 10 on the previous screen
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/8933f642-6e14-4334-aa66-5abdad897178)

### Showing version 5 when it shows 6 on the previous screen
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/c481467b-9404-407f-9d82-f7837af1fb62)

**Comment by rdig** [comment]
Note that this is blocked by JoinColony/block-ingestor#169 

That needs to be handled first, and only after that, we can fix this properly
