### ISSUE TITLE
Actions: All action tables 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1854]
## Description

Currently, all actions that have a supporting table, need the styling to be updated to align with the SOT in Figma.

Each table in each action needs to be checked and the issues resolved below.

### 1.  All desktop and mobile row heights need to match Figma so there is consistency across every action. 
<img width="261" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/a30bb6dd-6223-47ad-a352-2997d7a39cef">

### 2. All fonts need to match Figma's colours as shown below correctly including font weights 
<img width="659" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f39b13eb-4357-45c4-b674-2b0729784734">

### 3. All horizontal rules need to be removed on desktop. This should not impact tables outside of actions. 
<img width="676" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/24bca2ed-e847-45d1-9424-9d423e618e60">

### 4. The correct dividers on mobile need to be implemented and not each row as per the screenshot
<img width="372" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/1b4144b9-b0d1-4e4d-91e9-b175c036d14d">

### 5. Mobile kebab menus go full width to the content container and not small as per the screenshot
<img width="369" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/390d3777-0f5b-4c66-8ce2-1ea3aa33d1b9">

6. Any row that shows a meatball menu needs to be center aligned within the row to match the content 

## Action types with tables

1. Simple payments
2. Edit colony details
3. Manage tokens 
4. Custom table in Permissions 
5. Verified members

**Comment by AdrianDudko** [comment]
@melyndav I believe we can close this issue :)
