### ISSUE TITLE
Not able to "Finalize" agreements

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1876]
## Steps to reproduce

1. Create a new Agreement.
2. Go through the whole process of supporting the Agreement.
3. Click on the "Finalize" button.
4. You won't be able to finalize or return stakes, and there will be an error in the console.

Note: There is no transaction that is being performed or needing to be performed other then the returning of stakes. The usage of the "Finalize" text here is keep it consistent with other actions.

## Expected behaviour

* When in the "Finalize" step, clicking the "Finalize" button should only return all user stakes.
* When all stakes have been returned, there should not be a finalize button anymore. 
* This should be the same process when the Agreement has failed. i.e. stakes can be returned when clicking "Finalize".

## Actual behaviour

* You are not able to finalize the agreement and stakes are not able to be returned.
* If you claim back stakes via the Userhub stakes tab and return to the finalize step of the agreement, the finalize button will still be visible despite there being no stakes left to be returned.

**Comment by rdig** [comment]
So this needs some discussions, b/c as far as I have knowledge of, Agreements have no support in the ingestor at all. I have no idea why they're even enabled in the UI

This might actually explain why finalize is not working, since it's a different way of handling that event.

So if this is needed, we'll consider it a new feature, and we can estimate it and schedule it accordingly.

**Comment by arrenv** [comment]
> So this needs some discussions, b/c as far as I have knowledge of, Agreements have no support in the ingestor at all. I have no idea why they're even enabled in the UI
> 
> This might actually explain why finalize is not working, since it's a different way of handling that event.
> 
> So if this is needed, we'll consider it a new feature, and we can estimate it and schedule it accordingly.

Just to clarify, this is the renaming of "Simple decisions". Was this not migrated to CDApp?

**Comment by rdig** [comment]
Not as far as I know of, at least not on the ingestor side. I'll look into it to know for sure.

**Comment by arrenv** [comment]
> @arrenv Upon investigation it looks like it's not possible to finalise agreements due to the contracts - it would be a wasted transaction so we just skip it.
> 
> We need to find a different approach to handle this

Yes, that is correct. There are no transactions that needs to be finalized. The expected behaviour is just to return stakes in the finalize step. It could change the button text to "Return stakes", but if that is not built in, then the finalize is fine.

**Comment by warrencolliver** [comment]
> > [@arrenv](https://github.com/arrenv) Upon investigation it looks like it's not possible to finalise agreements due to the contracts - it would be a wasted transaction so we just skip it.
> > We need to find a different approach to handle this
> 
> Yes, that is correct. There are no transactions that needs to be finalized. The expected behaviour is just to return stakes in the finalize step. It could change the button text to "Return stakes", but if that is not built in, then the finalize is fine.

I see, we can start working to implement this but it would be considered scope creep and will require more work than initially planned.

**Comment by rdig** [comment]
Yes, feel free to start on it, I'll make sure to amend it's estimate

If you run into any issues, let me know

**Comment by rdig** [comment]
How's this going? Any progress has been made since last week ?

**Comment by warrencolliver** [comment]
Got a call set up with Jakub to go through this today
