### ISSUE TITLE
Actions: Create agreement action issues

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1883]
## Description

Out of scope issues found on  feat: added agreements page #1853 that require fixing. 
 
 4. There are padding issues between the title/metadata area and the form in the agreement actions. 
 
<img width="718" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/4d85ded9-fd20-4cea-8550-7d97a8f6d8c1">

5. Please keep the decision method dropdown consistent as per the other action types.

<img width="505" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/ca0257ea-f592-4d94-8329-a11395a676ea">

8. The title isn't being saved when the action is completed and just shows 'create decision'
<img width="376" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/d9f3e219-c48b-4dd1-b07a-76cd51957323">

What it should say:
<img width="75" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/4e77b4e0-0dbb-4605-8f65-80731bd76cb3">

**Comment by AdrianDudko** [comment]
@melyndav It's a duplicate of https://github.com/JoinColony/colonyCDapp/issues/1873. Sorry, forgot to inform you

**Comment by melyndav** [comment]
Closing this since it was already opened by Adrian (thanks Adrian! :))
