### ISSUE TITLE
Mobile QA: Main Navigation 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1893]
**Teamwork task:** [Mobile QA: Main Navigation](https://tw.auroracreation.com/#/tasks/15787761)

## Description

This issue covers all issues identified during mobile QA on production for the **main navigation** section. 

Link to mobile navigation Design System component for all issues below: https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-8881&mode=dev

### Issues

1. Chain, user avatar and gear icon are incorrect sizing and should be 18x18px each. 
<img width="197" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/e4c8498e-bea5-4523-beb9-41dfeae0d5fd">

2. Colony switcher page has padding issues above the 'Current colony' top heading. Should be consistent with the main menu padding. 
<img width="467" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/eb3dfc9f-fd7c-48c2-91e2-dac290fb4e47">

3. Colony switcher menu has incorrect container padding. Also should be consistent with 24px. 
<img width="450" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/816406e3-59b1-4aa3-bec6-831931c7cba9">

**Comment by CzarekDryl** [comment]
@melyndav In figma user avatar is 20x20px, so what is the correct size?
![image](https://github.com/JoinColony/colonyCDapp/assets/76940796/7ec0e3da-b919-48ad-8c58-95ae5e7253e1)
