### ISSUE TITLE
Mobile QA: Activity Page 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1900]
**Teamwork task:** [Mobile QA: Activity Page](https://tw.auroracreation.com/#/tasks/15789329)

## Description

This covers all issues identified during mobile QA on production for the activity feed.

Link to mobile activity feed: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=8018-368664&mode=design&t=qsuzbFQLfedbIeGU-4

1. The mobile version of the activity feed has not been implemented.

<img width="437" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/3239e7b2-ec15-47ce-b999-3e3facbf953d">

Link to mobile table in the design system: https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-24644&mode=design&t=ZP2Up83HG0FlTMVM-4 

Further interactions for mobile: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=8193-384529&mode=design&t=qsuzbFQLfedbIeGU-4

2. Skeleton loader clips through to the main menu when the menu draw is activated:
<img width="512" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/bab8290f-0921-4590-9571-b79ff9797097">

2. Skeleton loader breaks and needs dedicated mobile version matching the correct table version.

<img width="456" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/edd213dc-bad5-4750-95fb-aa2d6b60d407">

**Comment by arrenv** [comment]
@joanna-pagepro To confirm, the arrows from the collapsed state should be pointing down, and when expanded, they should be pointing up. The design has been updated now.
