### ISSUE TITLE
Show joined colonies in the joined colonies list

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1901]
### Description

Currently, when you have the colony switcher open you see the current colony at the top and joined colonies in the joined colonies section below it. However, it currently works by excluding the current colony from the list of joined colonies regardless of whether the user is joined or not. This means the list is inaccurate, showing an empty state if you have only joined one Colony and are on that Colony.

We would like to ensure this list is accurate by not excluding the current colony from the list of joined colonies if the user has joined the colony.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/38ffc051-a79b-444c-bd6e-fe8bb2f36892)

### Acceptance criteria

- [ ] All a users joined colonies will show in the colony switcher joined colonies list.

**Comment by rdig** [comment]
This is actually a bug, as the joined colonies should show up
