### ISSUE TITLE
Joined Colonies not showing in production

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1904]
## Steps to reproduce

This seems to be a me only issue in production, others seems to be able to see their Colonies, but it may be worth looking into anyway as to the cause.
In production Joined colonies are not showing at all for me, this is the same for newly created and newly joined colonies. I have not been able to test leaving and rejoining due to this issue - https://github.com/JoinColony/colonyCDapp/issues/1902

## Expected behaviour

* Joined colonies should be showing.

## Actual behaviour

* No joined colonies are showing.

Running the following query:
```
query MyQuery {
  getProfile(id: "0x1FdA4692515dfd6f3c957d32825A8eFc08d6123c") {
    id
  }
  getContributorsByAddress(contributorAddress: "0x1FdA4692515dfd6f3c957d32825A8eFc08d6123c") {
    items {
      colonyAddress
      colony {
        name
      }
    }
  }
}
```

Results in this response:

```
{
  "data": {
    "getProfile": {
      "id": "0x1FdA4692515dfd6f3c957d32825A8eFc08d6123c"
    },
    "getContributorsByAddress": {
      "items": [
        {
          "colonyAddress": "0x3d529059baA06b792fB2CaCfC7E85A468Ab777e4",
          "colony": {
            "name": "animal"
          }
        },
        null,
        {
          "colonyAddress": "0xE19Ea092dc06f35c46cAAbeE2BAf1458513FA85e",
          "colony": {
            "name": "privaterc5"
          }
        },
        null,
        {
          "colonyAddress": "0x51547E3F1A895c4b6a7b408564BbE96F64844c87",
          "colony": {
            "name": "spacetravel"
          }
        },
        {
          "colonyAddress": "0xeB38458F4E88fCa8C69D39AC2D477009b5a3010D",
          "colony": {
            "name": "deed3labs"
          }
        },
        {
          "colonyAddress": "0x6c49Fe2beA3A0661587146E118878777A3510829",
          "colony": {
            "name": "beta"
          }
        }
      ]
    }
  },
  "errors": [
    {
      "path": [
        "getContributorsByAddress",
        "items",
        1,
        "colony"
      ],
      "locations": null,
      "message": "Cannot return null for non-nullable type: 'Colony' within parent 'ColonyContributor' (/getContributorsByAddress/items[1]/colony)"
    },
    {
      "path": [
        "getContributorsByAddress",
        "items",
        3,
        "colony"
      ],
      "locations": null,
      "message": "Cannot return null for non-nullable type: 'Colony' within parent 'ColonyContributor' (/getContributorsByAddress/items[3]/colony)"
    }
  ]
}

**Comment by rdig** [comment]
Isn't this basically the same as #1901 though? 

Just a heads up @iamsamgibbs since you're working on that, so that work might actually fix both these issues

**Comment by iamsamgibbs** [comment]
#1901 only shows the `No colonies joined` message when you are only in one colony (as the current colony doesn't show in the list).

Here it appears that arren is in 5 colonies, so there should still be 4 in the joined colonies list.

Regardless there may be some overlap so I'll look into this at the same time.

**Comment by iamsamgibbs** [comment]
This should be resolved now @arrenv - there were some unused colony addresses left over from an earlier deployment where the colony creation was not working correctly, this caused the `getContributorsByAddress` query to fail. The left over entries have been cleared up from the database and all should work correctly now.

**Comment by arrenv** [comment]
> This should be resolved now @arrenv - there were some unused colony addresses left over from an earlier deployment where the colony creation was not working correctly, this caused the `getContributorsByAddress` query to fail. The left over entries have been cleared up from the database and all should work correctly now.

Thank you! Yep, all showing now :)
