### ISSUE TITLE
Expenditure sagas should take into account selected token's decimals

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#1905]
The sagas listed below incorrectly use `DEFAULT_TOKEN_DECIMALS` instead of retrieving the decimals of the token the payout is in (note: this can be different from colony's native token):
 
- `createExpenditure`
- `editExpenditure`
- `createStakedExpenditure`

The issue is to refactor the sagas to accept token decimals for the selected token and use that when converting between units.

**Comment by warrencolliver** [comment]
On hold - Waiting to set up Truffle

**Comment by rdig** [comment]
This should no longer be on hold, as @jakubcolony 's #1946 got merged

Feel free to restart work on this
