### ISSUE TITLE
Hide empty permission types on Permissions page

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1908]
### Description

The permissions page currently shows all permission types listed out and shows an empty state where no permissions are held, however, this clutters the UI and makes it difficult to see just the most important information, i.e. the permission holders.

Therefore, instead of showing the empty state for permission types, we would like to hide the permission type altogether, you can see an updated design below.

Example of current issue:
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/45443d0e-7705-48c0-bdb7-ec7e1fbd55a4)

### Design

[Figma link](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=20117-28691&mode=design&t=aboxMif7pzbMx7B8-4)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/5e8b3689-3040-4a2e-973b-1e563736883c)

## Acceptance criteria

- [ ] Permission type empty states will no longer show on the permissions pages both by default and when filtering and searching.

**Comment by AdrianDudko** [comment]
@CzarekDryl Please connect this Issue with PR, which will include the described changes.
