### ISSUE TITLE
Permissions 404 error in production

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1920]
## Steps to reproduce

1. Go to colony in production.
2. Navigate in the main menu to 'Admin' > 'Permissions'
3. You will be directed to a 404 page.

NOTE: This is also happening with the agreements page.

## Expected behaviour

* The permissions route should direct to the permissions page.

## Actual behaviour

* The permissions route redirects to a 404 page. This happening on QA and Production, master seems fine.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/d5d0a89a-539c-492d-8562-01a3c4b98990)

**Comment by rdig** [comment]
Shouldn't this one go to Pagepro ?

**Comment by AdrianDudko** [comment]
@CzarekDryl Please connect this issue with PR that fixes this.
