### ISSUE TITLE
Colonies without a logo do not have a blockie in the colony switcher

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#1923]
## Steps to reproduce

1. Create a new colony
2. Open the colony switcher
3. The new colony without a logo will not have a blockie

## Expected behaviour

* The colony without a logo in the 'joined colonies' list should have a blockie (ensure it matches their colony blockie)

## Actual behaviour

* The colony without a logo in the 'joined colonies' list has no logo or blockie at all

![Screenshot 2024-02-16 at 10 22 38](https://github.com/JoinColony/colonyCDapp/assets/34915414/c594e6dd-0a2c-48d7-9f6d-7e269e100fa4)

**Comment by melyndav** [comment]
I just found this @iamsamgibbs you beat me to the punch! Thanks for raising this issue 👍
