### ISSUE TITLE
Issue with SVG on contributors card

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1938]
## Description

Users on the contributors page that don't have a label have an issue with the SVG where it is showing with a `?` on their avatar, this was noticed in production here - https://app.colony.io/beta/members/contributors and QA here - https://qa-app.colony.io/pageproqa/members/contributors

## Expected behaviour

* There should not be a `?` icon showing on members on the contributor page.

## Actual behaviour

* There is a `?` icon that is appearing on some members on the contributor page.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/f2f38e26-07af-4ed6-a690-e86e323160e7)

**Comment by rdig** [comment]
This might be due to @chmanie 's icon refactors in #1861

**Comment by chmanie** [comment]
Let me take a look!

**Comment by AdrianDudko** [comment]
@chmanie I've assigned this issue to you :)
