### ISSUE TITLE
Activity feed actions status showing as 'Unknown'

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1943]
**NOTE:** This was seen in production during a user call, maybe not easy to replicate in local. This is low priority given we are not yet supporting other chains, but still could be worth figuring out why it is working in the action panel, but not the activity feed.

## Steps to reproduce

1. Ensure that you are connected with a chain other then Gnosis Chain.
2. Check the actions in the dashboard and activity page, navigating through the pages.
3. Check the status pills to see if the "Unknown" status pill shows.

## Expected behaviour

* Activity items should be able to show the correct status, no matter the chain.

## Actual behaviour

* Activity items are showing with "Unknown" status when connected on another chain.
* I have not yet noticed a pattern to it, but it is consistently happening.

![unknown-status](https://github.com/JoinColony/colonyCDapp/assets/33682027/55c81aef-347c-411e-bbd3-b3a3d54bdd68)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/e30433cd-2a40-4bf5-92d0-cd6aab5084e7)

**Comment by rdig** [comment]
What's the status of this ?

**Comment by ArmandoGraterol** [comment]
@rdig I've tried several times already and I haven't been able to replicate this one. 

I've seen it while working on other issues but other than that, no luck.
