### ISSUE TITLE
Errors with changing permission

### ISSUE THREAD

**Issue by naynovi** [JoinColony/colonyCDapp#1944]
This is likely a known issue but just sharing this image and video incase it is helpful to someone.

https://github.com/JoinColony/colonyCDapp/assets/23479095/ec18571c-442d-4de8-bcec-9862588c66e5

## Steps to reproduce

1. I started a new colony https://app.colony.io/xyz/ I tried to pay myself some tokens, but the action did not go through. I thought I might not have the permission to pay myself. I then tried to update my permission level.
2. I initiated an action from the left menu button to update permissions and filled in available fields
3. Received error createdIn is a required field ![image](https://github.com/JoinColony/colonyCDapp/assets/23479095/0881c45e-694e-4376-8683-98124c4563ce)
4. Opened new action from side menu
5. Chose permission at the bottom
6. The window that opened had a number of missing items from it.

**Comment by melyndav** [comment]
Hi @naynovi this issue has been fixed in #1831. Closing this ticket.

**Comment by naynovi** [comment]
![image](https://github.com/JoinColony/colonyCDapp/assets/23479095/abd0db07-0c61-4b6a-b005-6602c7a8877b)

this is live now 👆

This is how it is supposed to look right?

**Comment by melyndav** [comment]
@naynovi this is waiting on a deployment to fix. You can only access it from the default side panel at the bottom and not main nav. This link block has been removed to make way for a new feature.

**Comment by rdig** [comment]
These should have been deployed with today's release. Please check if this is still an issue in production
