### ISSUE TITLE
Advanced Payments: Payment Builder

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1957]
## **Overview**

Provides the ability to create custom payments involving multiple recipients who can receive any number of different tokens, at different times. It uses the [Advanced Payment flow](https://github.com/JoinColony/colonyCDapp/issues/1956) for handling the creation, collective input, funding, and releasing of payments.

## **User stories**

- As a USER, I would like to be able to see the details of the payment, who has participated and what stage it is in.
- As a USER, I would like to be able to include a details such as a title and description to explain the purpose of the payment.
- As a USER, I would like to be able to see the types of payments being made and all the details of the payment including recipients, values and reasoning for a payment.
- As a USER, I would like to have time delays on payment claiming to allow payment scheduling and to serve as a security delay.
- As a USER, I would like to allow people to stake their own tokens to create an advanced payment if they don’t have the necessary permissions.
- As a USER, I would like to be able to make changes to the advanced payment during the governance process after receiving collective input.
- As a USER, I would like the payment approval process to be managed by the
available governance processes.
- As a USER, I would like to be able to comment on and engage with other commenters who are participating in a payments governance process.

## Design

**Payment builder create**

Figma design - https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=3569-472657&mode=design&t=jLgdXbqtPVm8eGRx-4

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/487c2e09-bda0-4899-a002-3f99f08810b5)

**Payment builder complete**

Figma design - https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=3010-279395&mode=design&t=jLgdXbqtPVm8eGRx-4

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/cbf5580a-51ab-49fc-bcfc-6d9b2bb06775)

## Acceptance Criteria

- Includes acceptance criteria of Advanced Features - [https://www.notion.so/colony/Advanced-Payments-c0c4ee0436394146a23e305180e6ae21](https://www.notion.so/Advanced-Payments-c0c4ee0436394146a23e305180e6ae21?pvs=21)
- User can select the “Payment Builder” option from the “Action type” options.
    - This should update the action creator with the relevant fields.
- Fund from
    - Select the team to fund the payment from.
    - Uses the team drop down.
- Payments table
    - Select a recipient
        - User can select a recipient from the select member column.
        - User is able to manually enter an address as a recipient.
        - List of members should include all members and be searchable.
        - Verified members should be shown with their icon.
        - If an address is entered that is not in the verified list, then a warning should be shown.
    - Token and amount
        - User can select from the available tokens in the Colony to make the payment in.
        - User can enter a value for the amount of tokens to pay the recipient.
        - Clicking the token selection should include available funds for that token in the fund from team.
        - Entering multiple amounts should sum for the same token and validate available funds.
    - Claim delay
        - User can enter a claim delay value for each recipient.
        - User can select the period for the claim delay.
        - The claim delay input only allows a positive input value.
        - There is a max of 4 digits possible for the claim delay.
    - Kebab menu
        - Click on the kebab icon provides a dropdown with the following options:
            - Add token
                - Allows the user to add another token to the recipient.
                - This adds a duplicate row with the recipient selected and the same claim delay but an empty amount field.
            - Duplicate row
                - Allow the user to duplicate the recipient row, adding another row with the exact same details.
            - Delete row
                - Allow the user to delete the enter row.
    - Add recipient
        - A button to be able to add another row to the table. No details other then token should be pre-fields.
    - Multiple tokens
        - You can pay in multiple different tokens. From a contract perspective, these are grouped per recipient, however, from a UI perspective we are treating each row separately.
        
        
<html>
<body>
<ul>
<li>
<p>Action Label Tooltips</p>

Action | Label | Tooltip text
-- | -- | --
Payment builder | Fund from | Team source of the payment.
  | Recipient (table header) | Member or address designated to receive the funds.
  | Amount (table header) | Quantity and type of funds of the payment.
  | Claim delay (table header) | Time interval between the approved release of funds and being able to claim the funds, it works as a security delay or a way to schedule payments.

</li>

</ul>

</body>
</html>

<html>
<body>
<ul>
<li>
<p>Action Metadata</p>

Action | Default e.g. | Completed e.g. | Alternative states  e.g.
-- | -- | -- | --
Payment builder | Payment with multiple recipients and tokens by CaptainPlanet | Payment to 3 recipients with 5 tokens by CaptainPlanet | --

</li>

</ul>

</body>
</html>

<html>
<body>
<ul>
<li>
<p>“Create …” button text</p>

Action | Text
-- | --
Payment builder | Create payment

</li>
</ul>

</body>
</html>

**Comment by AdrianDudko** [comment]
@arrenv I had to split this into smaller chunks.

Story [#2003](https://github.com/JoinColony/colonyCDapp/issues/2003) 
Subtask https://github.com/JoinColony/colonyCDapp/issues/2004 
Subtask https://github.com/JoinColony/colonyCDapp/issues/2005

If you feel that this will introduce confusion to the Backlog, let me know.
