### ISSUE TITLE
Notifications: As a user with connected wallet I can check NOTIFICATIONS and interact with them

### ISSUE THREAD

**Issue by AdrianDudko** [JoinColony/colonyCDapp#1960]
**Teamwork task** [[FINANCE] As a user with connected wallet I can check NOTIFICATIONS and interact with them](https://tw.auroracreation.com/#/tasks/15579282)

**Description**
A user with a connected wallet can access the notifications section from the main navigation. The user can view recent notifications and click on them to go to the respective action/motion/page. There is an option to mark all notifications as read and see the new notification counter.

**Acceptance criteria**
- Number of notifications
	- The number of new and unread notifications shows in the side menu of the main dropdown
- Mark all as read text button
	- When selected, changes the states of any new and unread notifications to the read state 
- New/unread notifications 
	- New notifications are denoted by the blue circle on the right side of a single notification and a grey background. 
	- When a user selects a notification, the respective action or motion sidepanel is triggered and the notification box is hidden 
		- or they are directed to the page that is relevant to the selected notification. 
- Read notifications
	- Any notifications that are in the read state show without any state change.
- Empty state

**Out of scope**
- Wiring, just UI 

**Design**

Notifications:
https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=6305-375959&mode=design&t=ursEoe3OGEQIXdl8-4
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/9a175da7f1eed09c52e5a75e06ef644c.png)
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/9a19112797d0b939dd0aba4b5b9ceabb.png)
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/9a1a39ddd453484915571066e6ae6d7a.png)
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/9a1bf8af0d4d740592de2620251ed8c7.png)
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/9a1d47cff5b5d595cabf5d93c72811ff.png)

**Comment by rdig** [comment]
@arrenv We'll have to talk about notifications then as our "current" spec / implementation doesn't support this UI

**Comment by rdig** [comment]
Yeah, that PR is exactly what I was referring to.
- it's experimental
- it's not properly implemented
- it has no support for what I see in the above visuals

So let's have some time together and figure out the spec, so that I can decide if I salvage something out of that PR, or I scrap it entirely

**Comment by arrenv** [comment]
Thanks @AdrianDudko, yes, we need to hold off on this for the time being.

**Comment by AdrianDudko** [comment]
Will be handled by Colony team.
