### ISSUE TITLE
Able to submit empty descriptions on action types

### ISSUE THREAD

**Issue by warrencolliver** [JoinColony/colonyCDapp#1974]
## Steps to reproduce

1. Go to create an action
2. fill in all fields apart from description
3. submit form

## Expected behaviour

On submission the action form  should give a validation error that the description can't be empty.

## Actual behaviour

Currently the action can be submitted with an empty description with no problems / error message being shown

It looks like this issue is across all action types apart from agreements due to changes made in #1964 

## Suggestions (optional)

This may be worth looking into: Sam's suggestion under #1964 and the commits made by Czarek 
![Screenshot 2024-02-23 at 15 25 25](https://github.com/JoinColony/colonyCDapp/assets/155957480/9f5b5802-1e5b-4596-a01e-95ffb5c1b306)

**Comment by jakubcolony** [comment]
I think this is intentional, in case of agreements the description field is the contents of the actual agreement so it must be non-empty, but for other action types the description is optional.

One for @arrenv to confirm (or @rdig in his absence?)

**Comment by rdig** [comment]
Yeah, description can be empty. It's basically an optional field.

Although I do agree with Sam here, that it might need to be better highlighted / marked as being an optional field.

Closing for now, but thank you Sam for noticing this. It shows you pay attention :)
