### ISSUE TITLE
Agreements: update page after adding item

### ISSUE THREAD

**Issue by CzarekDryl** [JoinColony/colonyCDapp#1989]
@iamsamgibbs Mentioned in this [comment](https://github.com/JoinColony/colonyCDapp/pull/1927#pullrequestreview-1897816557).

Ensure that when a new agreement is created while on the agreements page, the page should update automatically without requiring a manual refresh. This enhancement would improve user experience by providing real-time updates upon saving. Implementing this change involves adjusting the wiring and implementing a mechanism to automatically refetch the agreements query upon saving.

**Comment by AdrianDudko** [comment]
Done, when a new agreement is created while on the agreements page, the page update automatically without requiring a manual refresh.
