### ISSUE TITLE
Not able to load extension pages directly in production

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1995]
## Steps to reproduce

1. Go to a Colony in production.
2. Go to an extension page and reload the page, you can also load URL directly.
3. The page redirects to a 404.

## Expected behaviour

* The extension pages should load directly.

## Actual behaviour

* Loading extension pages redirect to a 404.

**Comment by rdig** [comment]
This is mostly likely something new, that appeared after Tuesday's deployment: https://github.com/JoinColony/colonyCDapp/actions/runs/8067058179

So the problem most likely was introduced by something in this range of commits: https://github.com/JoinColony/colonyCDapp/compare/f783eeef37e7dfc21b0d9eb2140a2c3d365d801f...51e5a2e62dc940157a956a69dd976f163a68a81c

**Comment by CzarekDryl** [comment]
@rdig I think this PR ruined it, because after loading there is no data yet and the page goes straight to 404. [https://github.com/JoinColony/colonyCDapp/pull/1906](https://github.com/JoinColony/colonyCDapp/pull/1906)
