### ISSUE TITLE
Mobile: UI Regression issues

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2027]
**Teamwork task:** [Mobile: UI Regression issues](https://tw.auroracreation.com/#/tasks/15825815)

## Description

A couple of core UI issues have been introduced to master and need to be addressed before the next deployment as they break mobile sidepanel action functionality.

**Issue 1: Sidepanel headers have been changed to inside page headers**

On mobile, the header is not the correct action header component and is displaying the inside page version across all action types on mobile. It's not in production. Users can no longer close the side panel or see the status pill of the motion.

<img width="458" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/78569e75-540d-425d-a6c4-6e1c1d5b4b48">

**Issue 2: Main CTA buttons are no longer full width**

On mobile, the main CTA block within each action side panel have been impacted across all action types in production and need correcting. 

**Currently in production:** 
<img width="480" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/5fc4dd09-7325-4c37-aa6c-fe25bbd9a11a">

**As per Figma:**
<img width="372" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/dccdd728-ef05-4314-ae0d-a6260105e14c">
 
 
 Any action sidepanel design in figma can be used for both issues - https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=2977-258469&mode=design&t=BNXdv8DRozb21TVR-4

**Comment by AdrianDudko** [comment]
@melyndav It goes to TO-DO for today :)

**Comment by melyndav** [comment]
> @melyndav It goes to TO-DO for today :)

You're a superstar, thank you! I've also updated with a Figma link as well.
