### ISSUE TITLE
Create Actions Model (Schema)

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyCDapp#203]
- No comments (will be handled separately)
- Keep simple for now, can be amended as we implement more actions (only handle Actions that we care about for now, no generics)
- Should be tied to a chain, transaction hash and a colony

### Actions Data Flow

Below is a rough outline of how the Actions Data Flow should work

![cdapp-actions-data-flow](https://user-images.githubusercontent.com/1193222/213923691-9f7f6512-861d-4e0a-97d3-4997f7e0d0cf.png)

**Comment by jakubcolony** [comment]
Will be resolved by #232
