### ISSUE TITLE
[Manage Reputation] Get old reputation and calculate change percentage on action side panel

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyCDapp#2033]
The manage reputation actions (Smite/Award reputation) show a percentage of how much of the user's reputation changed with the action:

![Image](https://github.com/JoinColony/colonyCDapp/assets/18473896/3603780b-2384-4fb8-96da-cac749935aa1)
![Image](https://github.com/JoinColony/colonyCDapp/assets/18473896/73298378-bf1b-4be7-ad97-dbd421c2cf37)

Currently, there's no way of calculating this percentage as for that we would need the reputation of the user by the time the action was made. Therefore, I suggest that we should move the `rootHash` prop we currently have on `motionData` to the action model and always store the `rootHash` by the time the action/motion was created. This way we should be able to get the previous reputation not only on motions, but on actions too.

Once the `rootHash` is available we can use `useUserReputation`, for example, to get the reputation and then calculate the percentage based on that.

**Comment by arrenv** [comment]
Is this one closeable @ArmandoGraterol

**Comment by ArmandoGraterol** [comment]
@arrenv Yes, it is!
