### ISSUE TITLE
Handle Mint Action Events (via Block Ingestor)

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyCDapp#204]
This issue is to be handled in the Block ingestor, just adding it here for Project completion.

- Relevant events for the Mint action are: `TokensMinted`, `ColonyFundsClaimed`, `Annotation` _(the last one might need more research)_ -- later edit: `ColonyFundsClaimed` might not need to be handled in the ingestor at all
- Save relevant data for this Action Type (type, amount minted, token, annotation -- again, might need more reserach)
- This also needs to save the contract events that we handle here as their own separate entry _(to be later displayed in the Transactions Log)_ https://github.com/JoinColony/colonyCDapp/blob/port/39-funds-page/amplify/backend/api/colonycdapp/schema.graphql#L277-L293

### Actions Data Flow

Below is a rough outline of how the Actions Data Flow should work

![cdapp-actions-data-flow](https://user-images.githubusercontent.com/1193222/213923691-9f7f6512-861d-4e0a-97d3-4997f7e0d0cf.png)

**Comment by rdig** [comment]
Don't handle Annotations for now

**Comment by jakubcolony** [comment]
Will be resolved by [block-ingestor#11](https://github.com/JoinColony/block-ingestor/pull/11)
