### ISSUE TITLE
Advanced Payments - Action: Payment builder - Action preview

### ISSUE THREAD

**Issue by CzarekDryl** [JoinColony/colonyCDapp#2044]
### Acceptance criteria

Action - Preview - Form

- The user should not be able to change anything in the form
  - All fields should be disabled
  - Action - Preview - Table

- The user should not be able to change anything in the table

  - All fields should be disabled
  - Kebab menu should be hidden

- "Add recipient" button should be hidden

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2039
