### ISSUE TITLE
Actions: All actions with member selections 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2052]
Teamwork task: [Actions: All actions with member selections](https://tw.auroracreation.com/#/tasks/15838923)

## Description

All member selection dropdowns in every action type should including the main action inputs and any tables should show the verification (no alert) in the dropdown and the input.

Currently, any select member dropdown does not show this verification  and only shows once a member is selected. 

### Scope

This issue should be resolved on desktop and mobile across all action types in the top main action input fields and also in the table fields where a select member option is shown. Any select member input or table row should show the user verification status in the dropdown. 

Figma example of the dropdown showing the verification status:
<img width="480" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/ff915a67-a4d8-4758-913e-a33f77b6fd54">

**Currently the verified icon is not showing in any select member type dropdowns and only shows after a user has been selected**
<img width="652" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/a8558c9d-67a1-4e4e-9947-02d1abdf1eec">

**Comment by joanna-pagepro** [comment]
@melyndav how should the item in the dropdown look like with alert status? I could only find designs with verified status.

**Comment by melyndav** [comment]
Hey @joanna-pagepro @AdrianDudko updating the issue to remove the alert icon from showing within any member dropdowns. Just to confirm in the dropdown only the verified icon should show and then any users who are not verified show normal without a badge as per the original Figma designs. So the scope is to have any select member dropdown show the verified icon for appropriate users which is currently missing from most action types and tables. 

The unverified alert shows only once they have been selected. Sorry for any confusion!
