### ISSUE TITLE
Global: User popovers

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2054]
Teamwork task: [Global: User popovers](https://tw.auroracreation.com/#/tasks/15839237)

## Description

In production, there are a number of UI issues with the user popover cards. The user popovers can be triggered by selecting a user names across various points of the CDapp. 

All issues below should be resolved and tested on all responsive sizes including mobile.

**Issue 1: Usernames that are wallets have broken padding inside the popover compared to pre-set usernames:**

Wallet address username with broken padding:
<img width="349" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/d9068e08-0b1c-43b3-b852-4114e8026626">

Username with correct padding:
<img width="349" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/a5cc619a-a1bc-434a-814e-98b892a6c156">
 
 **Issue 2: Usernames with a wallet address are missing the full wallet address showing the in the alert status within the pop over. The full wallet address should show in this block:**
 
<img width="349" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/9c5eed52-3994-4f73-8881-a16bb6536c0f">

**Issue 3: Popovers that do not have a description break padding when the alert box is shown for non-verified members.** 

As you can see int he screenshot below, this user does not have a description and is tagged as the 'top' member type. The correct padding inside the card should be present if a user does or does not provide a custom description.

<img width="373" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/5dc9e8f4-e462-4a4e-8a75-b58461d11cba">

Correct padding when a description is shown:
<img width="341" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/d7372f3e-2469-4898-ad2d-526fe87b3ab4">

## Figma 
Figma component for reference for all issues:  https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-42685&mode=design&t=pjBfl9vi2n9SXfxZ-4

**Comment by AdrianDudko** [comment]
According to @CzarekDryl  comment, reported issues have been fixed in https://github.com/JoinColony/colonyCDapp/pull/2066
