### ISSUE TITLE
Actions: Staking widget UI Issues

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2055]
Teamwork task: [Actions: Staking widget UI Issues](https://tw.auroracreation.com/#/tasks/15839355)

## Description

Across all action types, the staking widget has the support and oppose button colours are incorrect for all states (default, selected etc). This issue should be resolved and tested across all responsive types including mobile.

The issue shows across all the staking steps including when a choice is selected by the user and the change state is available. 

<img width="341" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/5d8598f2-21db-4f89-9320-b2e34caec9df">
 
**As per Figma:**
 
<img width="572" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/1c121b89-a281-41fe-813d-5a6fc0707dd0">

## Figma
Figma link for SOT: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=3154-357025&mode=design&t=GU7PGCjsxu5u5B0A-4

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2060
