### ISSUE TITLE
Mobile: Motion stepped navigation tooltips

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2057]
Teamwork task: [Mobile: Motion stepped navigation tooltips](https://tw.auroracreation.com/#/tasks/15839358)

## Description

On mobile, all pills part of the motion flow process are displaying each individual tooltip broken impacting the user experience on mobile.

<img width="470" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/966f8db8-3ced-42a7-910a-83ede2afb4ae">

The placement of these tooltips should display as per Figma in it's full state to allow users to select the pill and show the tooltip. 

Correct placement as per Figma including interaction annotation: 
<img width="1331" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/1e7f0fc4-19a4-42c2-9aa1-b3a3f9caf244">

## Figma
Link to component showing correct placement: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=3276-313835&mode=design&t=GU7PGCjsxu5u5B0A-4

**Comment by AdrianDudko** [comment]
Resolved by [@https://github.com/JoinColony/colonyCDapp/pull/2076](https://github.com/JoinColony/colonyCDapp/pull/2076)
