### ISSUE TITLE
Advanced Payments: floating point number precision impacts the payment amount

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#2059]
## Steps to reproduce

You need to be checked out on `feat/advanced-payments-2` to follow these steps.

1. Create a payment with a specific amount (I witnessed it with `5342534`).
2. Run a GraphQL query to see what amount was saved in the DB:
```gql
query ListExpenditures {
  listExpenditures {
    items {
      nativeId
      slots {
        payouts {
          amount
        }
      }
    }
  }
}
```

## Expected behaviour

The amount should be `5342534000000000000000000`, or `5342534 * 10^18`, provided your colony's native token decimals are 18.

## Actual behaviour

The amount is stored as `5342534000000000000000001`.

## Suggestions (optional)

This can be an issue with the `createExpenditure` saga or a relevant block-ingestor handler.

**Comment by iamsamgibbs** [comment]
Closed after further investigation with Jakub
