### ISSUE TITLE
Fix decimal point crashing CDapp on manage reputation form

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyCDapp#2067]
## Steps to reproduce

1. Open the action side panel.
2. Select the manage reputation action.
3. Fill the required fields to enable the amount field.
4. Input a decimal point in the amount input first thing and watch the CDapp crash.

## Expected behaviour

* Inputting a `.` should count as a `0` to the validation

## Actual behaviour

* The CDapp crashes

**Comment by rdig** [comment]
I've moved it to the todo pile, and estimated it.

Are you going to start work on this ?

**Comment by ArmandoGraterol** [comment]
@rdig Sure I can take a dig at this!
