### ISSUE TITLE
Onboard.js modal UI issues

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2073]
## Description

There's some UI issues with the onboard.js modal as shown below. Resolving the issues is dependent on whether we move away from onboard.js or not. 

<img width="788" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/53044f4f-e1de-46d6-814f-bfedeaff2e5c">

**To replicate the issue:**

1. Disconnect any connected wallets
2. Trigger the connect wallet pill from the top right header 
3. The onboard.js modal will display

**Comment by rdig** [comment]
Good catch. This is a regression introduced by one of the recent major merges.

Either @chmanie 's #1748 or @iamsamgibbs 's #2041 as they either upgraded the lib packages, or messed with our custom styles. And I'm willing to bet it's the latter PR that's to blame here.

This has not been deployed in production yet, and I'll hold off deployments until we do.

Here's how prod looks like:
![Screenshot from 2024-03-20 12-09-30](https://github.com/JoinColony/colonyCDapp/assets/1193222/63d382c0-229b-4aa3-836d-d295e0001303)

As a side note, this will be somewhat changed once my #992 gets done, but nothing that should affect styles

**Comment by melyndav** [comment]
Thanks @rdig. 👍
