### ISSUE TITLE
Install and enable Staked Expenditure extension at colony creation

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#2074]
### Story

As a user creating colony, I want the Staked Expenditure extension to be installed and enabled automatically as part of the creation flow, so that I can make staked payments without having to install anything manually.

### Description

This should happen in the same way as OneTxPayment installation.

To save gas, we should bundle OneTxPayment and StakedExpenditure `installExtension` transactions using multicall, then proceed with initialisation when we know their addresses.

Staked Expenditure accepts a single parameter, stake fraction, which should be set to: `1%`

### Subtasks

- [ ] Consider the flow for existing colonies which did not have Staked Expenditure installed at creation
- [ ] #2200

**Comment by arrenv** [comment]
We can set it as the current default for motions at 1%.

Something to note is handling the stake amount of there is 0 reputation. At the moment you just can't create a motion in this case, so, we'll likely need to do the same using the same banner.

**Comment by rdig** [comment]
Does this issue still need to be open ? Or can we close it ?
