### ISSUE TITLE
Mobile: User account area 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2079]
Teamwork task: [Mobile: User account area](https://tw.auroracreation.com/#/tasks/15854539)

## Description

On mobile in the user account areas, there are a number of UI/UX that need fixing to align with the Figma responsive designs. The issues cover delivered elements. Desktop should be tested to ensure no impacts are made during these mobile updates.

### Across all three tabs:

**Issue 1: Toasts placements are broken and appear off the screen.**
<img width="553" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/b2dd95d9-dec3-49b4-9995-daca1fd5e746">

### User Account tab

**Issue 1: Padding between section and the input forms should be 8px as per Figma.**
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/0914e1b4-f83c-47ce-b505-8da8c3812d86)

https://www.figma.com/file/0Fi3AaDlr3LAXBfsOXBGyk/User-Account?type=design&node-id=6401-11457&mode=design&t=l3tY0f61GL1RlNbo-4

### Preferences tab

**Issue 1: Wallet component doesn't match the Figma design with the layout of content.**
<img width="463" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/b3cb104a-05dd-4aef-b46c-8419d362f12b">

Per Figma:
<img width="743" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/95d15ee5-ad99-4de6-af2d-699485c015ec">

https://www.figma.com/file/0Fi3AaDlr3LAXBfsOXBGyk/User-Account?type=design&node-id=6401-11782&mode=design&t=l3tY0f61GL1RlNbo-4

**Issue 2: Layout of email address in the default state doesn't match Figma design:**
<img width="517" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/3a91209a-f7d1-4e7f-84bb-031255e552b9">

As per Figma:
<img width="698" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/34713d20-b1a6-44a9-b8ed-125d4d35c528">

Issue 3: Email edit state does not match Figma with issues on the error state.

<img width="490" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/0a3f15e3-3843-48ab-80a4-fb785bed0d5d">

<img width="243" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/cb29039b-0b83-4812-ad3f-f7fb8f693d26">

As per Figma: 
<img width="938" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/57ad39ca-365a-415f-8298-bef1d82241a7">

https://www.figma.com/file/0Fi3AaDlr3LAXBfsOXBGyk/User-Account?type=design&node-id=6475-7698&mode=design&t=l3tY0f61GL1RlNbo-4

**Comment by joanna-pagepro** [comment]
@melyndav in the app there's a `Cancel` button added next to the `Save changes` one when the Edit email input is visible. It's used to close the form and go back to the previous view. On the design, I can't see the `Cancel` button. Should I remove it?
