### ISSUE TITLE
Refactor (hopefully remove) the actions/comments/motions transformer

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyCDapp#208]
Currently the actions/comments/motions are all merged into a single list via a spagetti monster of a transformer: https://github.com/JoinColony/colonyDapp/blob/master/src/modules/dashboard/transformers/transformers.ts#L46

This needs to be refactored to support the new data model format, or, if we're lucky, we can remove it outright, as the data coming to should already be properly formatted for display

### Actions Data Flow

Below is a rough outline of how the Actions Data Flow should work

![cdapp-actions-data-flow](https://user-images.githubusercontent.com/1193222/213923691-9f7f6512-861d-4e0a-97d3-4997f7e0d0cf.png)

**Comment by jakubcolony** [comment]
I'm handling this as part of #232
