### ISSUE TITLE
Agreements: Status displaying invalid status

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2080]
Teamwork task: [Agreements: Status displaying invalid status](https://tw.auroracreation.com/#/tasks/15854542)

## Description

In production, an agreement is showing with the status as 'invalid' with a 0 rendered in the card.

**_Important note: motions shouldn't be tested on production in the BetaColony_**

<img width="671" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/ff5a57fa-1c7e-44ea-87f0-fd55cc34d9a4">

The motion also didn't complete correctly and nothing is showing under each motion pill.
<img width="839" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/9ccb2ea6-5eba-4ca9-97ff-1e5d8ca08c64">

**Comment by CzarekDryl** [comment]
I'm not able to replicate this on local env

**Comment by rdig** [comment]
I think I know of a way to test this.

- Install Voting Reputation
- Create an agreement 
- Stake it, so that it shows up in the list
- Deprecate + Uninstall Voting Reputation

That should break the state of the agreement (motions, under the hood), and trigger this invalid state

**Comment by CzarekDryl** [comment]
@rdig Right after uninstalling extension motion state change to `0` when using `useGetMotionStateQuery`. Could you please check if it's something with DB?
<img width="365" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/76940796/d1f8cf03-0b2f-4e52-9587-1a5d4c85dea2">

**Comment by arrenv** [comment]
This likely requires us handling deprecated and uninstalled extensions in the database.

As it should still show the correct outcome, even if it was created with a previous version of the voting reputation contract.

**Comment by rdig** [comment]
@arrenv is correct. We cannot currently handle motions from voting rep extensions that have been uninstalled. So for now, the UI needs to account for this case and handle it appropriately

**Comment by arrenv** [comment]
@AdrianDudko For now, when this situation is detected, can we instead have the UI say "Uninstalled", instead of "Invalid".

**Comment by joanna-pagepro** [comment]
@arrenv what about displaying this action in the action sidebar? Right now it looks like this: 
![image](https://github.com/JoinColony/colonyCDapp/assets/44369011/d771badf-c77d-4012-8d1b-5a9af4e911da)

Motion steps are empty

**Comment by melyndav** [comment]
@joanna-pagepro I've created a widget similar to the permissions widget to display in the right motion sidebar when an extension is uninstalled. Same widget for mobile.

<img width="343" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f8694dad-e482-4338-9960-c232b1592607">


Mockup:
 https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=22857-221890&mode=design&t=05jdMV5HavMx1mkJ-4
 
 Component:
 https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=3303-19734&mode=design&t=Q8lpfWcaTt0sGPJZ-4

**Comment by AdrianDudko** [comment]
@melyndav @arrenv 

The pull request that @joanna-pagepro worked on has been closed. You can find it at https://github.com/JoinColony/colonyCDapp/pull/2235.

It has been taken over by @davecreaser 
Comment: https://github.com/JoinColony/colonyCDapp/pull/2235#issuecomment-2239433910
His PR: https://github.com/JoinColony/colonyCDapp/pull/2737

Let's close this one.
