### ISSUE TITLE
Adv payments: funding modal

### ISSUE THREAD

**Issue by CzarekDryl** [JoinColony/colonyCDapp#2084]
### Story

- Modal to reviewing the amount to be funded and select the decision method to use.

- Network fee needs to be added on top of the entered amount to ensure the recipient receives their expected funds without the network fee being deducted from their expected payment.

- Cancel closes the modal and does nothing. You can also click out to close the modal.

- Clicking on "Fund payment" will start the funding process, with the process dependent on the decision method chosen.

- Decision methods

    - Options
    - Permissions
    - Visible if the user holds the Payer permissions or Funding custom permission in the team.
    - Permissions will immediately fund and move to the release step.
        - Selecting a decision method will reveal a callout to explain the next step that will happen based on their selection.

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2085
