### ISSUE TITLE
Hamburger option menu icons are misaligned

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#2091]
## Steps to reproduce

Open the hamburger menu, and select one of the option submenus.

## Expected behaviour

The icons are aligned correctly as per the figma designs.

## Actual behaviour

The icons are misaligned.

## Suggestions (optional)

This was likely caused by the recent tailwind / vite changes. If tailwind, then check the classes are being properly applied. If vite, check the icons are being properly sized and positioned.

Desktop
https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-3849&mode=design&t=2a6SgcgvfnHCQhlS-4 

Mobile
https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-8881&mode=design&t=2a6SgcgvfnHCQhlS-4

<img width="415" alt="Screenshot 2024-03-26 at 09 15 17" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/e0be0e0e-44d4-4c83-ac8f-068c53919022">

<img width="415" alt="Screenshot 2024-03-26 at 09 15 28" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/c4584240-cd2a-41e6-afee-315361e61ddc">

<img width="409" alt="Screenshot 2024-03-26 at 09 15 34" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/b37fc252-92ff-4d1d-8513-344a293065a0">

<img width="415" alt="Screenshot 2024-03-26 at 09 15 44" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/6cca5471-413d-4c4c-984b-76dacf61d98f">

**Comment by melyndav** [comment]
FYI it's fine on the dashboard kebab in master which should use the same component @iamsamgibbs 

<img width="435" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/fa92b560-37f8-4631-b646-11970b89eeb1">
