### ISSUE TITLE
Cannot activate less than maximum amount of tokens

### ISSUE THREAD

**Issue by bassgeta** [JoinColony/colonyCDapp#2092]
1. Open the user hub
2. Click activate tokens and enter an amount less than the maximum
3. See how you get an error instead of it activating the tokens

![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/31166010-21b8-4640-9a8f-1cc8028b7904)

## Expected behaviour

* Any valid number of tokens should activate

## Actual behaviour

* User gets an error

**Comment by rdig** [comment]
Leaving  a note here as well, as I think both this and #2093 should be tackled together
