### ISSUE TITLE
Cannot stake less than maximum for support or oppose in motions

### ISSUE THREAD

**Issue by bassgeta** [JoinColony/colonyCDapp#2093]
1. Create any motion
2. Click support/oppose and enter a number less than the maximum
3. The `Stake` button stays disabled

![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/b6d7d046-a089-44b9-b3da-96a63fd50f98)

Upon clicking `Max`, it enables.

![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/72c67b2b-1a69-4a83-8f8c-df0cc344125a)

## Expected behaviour

* Any valid number of tokens should get staked

## Actual behaviour

* Stake button is disabled

**Comment by rdig** [comment]
I think this and #2092 should be tackled together

**Comment by bassgeta** [comment]
Closing manually, because it didn't automatically close with the PR
