### ISSUE TITLE
Mobile & Tablet: Colony creation and profile onboarding flows

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2111]
## Description

The current onboarding (colony and profile creation flows) flow simplified for the beta launch was only prioritized for desktop, so mobile and tablet optimizations need to be completed.

The current flows live on production need to be optimized for mobile and tablet. 

Current mobile: 
<img width="438" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/247edc7e-689c-44bb-80a4-5cec6e4654e4">

Current tablet:
<img width="732" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/441b20ec-f293-4903-8212-ffd5adfb3fa4">

## Figma
Important: The original designs are included here however, these should only be used for references (UI layout etc) since some of the UI and information has changed, so making the current version optimised is required  - 
https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=11899-486016&mode=design&t=MCnMNgnf920Kriy7-4

**Comment by AdrianDudko** [comment]
Waiting for estimate

**Comment by melyndav** [comment]
Hey @AdrianDudko we're going to pick up this issue. Thanks anyway! 👍

**Comment by melyndav** [comment]
@bassgeta tagging you in this issue since it's a great mobile responsive and a 'good first issue'. Our team did the desktop versions.

**Comment by bassgeta** [comment]
Bumped the estimation to a 10, due to scope increase with the mobile step indicators and some minor quality of life improvements along the way :)
