### ISSUE TITLE
"Add as verified member" button in "UserNotVerified" notification banner has not been wired up

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#2129]
## Steps to reproduce

1. Navigate to the members page
2. Click on a member who has not yet been verified to open the popover
3. Click on the "Add as verified member"

## Expected behaviour

* The action sidebar should open with the "Manage verified members" action selected, "Add members" selected with the selected member already populated.

## Actual behaviour

* No action

<img width="375" alt="Screenshot 2024-04-03 at 16 50 24" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/10e7af63-e75f-42a0-a9af-31411324795e">

**Comment by rdig** [comment]
I think @arrenv already opened a issue for this: https://github.com/JoinColony/colonyCDapp/issues/2117

I'm closing this in favor of his.
