### ISSUE TITLE
Handle Payment Action Event (via Block Ingestor)

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyCDapp#213]
This issue is to be handled in the Block ingestor, just adding it here for Project completion.

- Relevant events for the Mint action are: `OneTxPaymentMade`, `Annotation` - please check the subgraph to make sure nothing is missed since the payment action is a 7 event chain: https://github.com/JoinColony/subgraph/blob/master/src/mappings/oneTxPayment.ts
- Save relevant data for this Action Type (type, amount payed, token, annotation, destination, domain)
- This also needs to save the contract events that we handle here as their own separate entry _(to be later displayed in the Transactions Log)_ https://github.com/JoinColony/colonyCDapp/blob/port/39-funds-page/amplify/backend/api/colonycdapp/schema.graphql#L277-L293

### Actions Data Flow

Below is a rough outline of how the Actions Data Flow should work

![cdapp-actions-data-flow](https://user-images.githubusercontent.com/1193222/213923691-9f7f6512-861d-4e0a-97d3-4997f7e0d0cf.png)

**Comment by jakubcolony** [comment]
Will be resolved by [block-ingestor#14](https://github.com/JoinColony/block-ingestor/pull/14)
