### ISSUE TITLE
Scrolling on the action sidebar will scroll the entire page

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#2138]
Teamwork task: [Scrolling on the action sidebar will scroll the entire page](https://tw.auroracreation.com/#/tasks/15861673)

## Steps to reproduce

Open the action sidebar, position your cursor over the action sidebar and scroll.

Mac OS 14.4.1, Google Chrome version 123.0.6312.59, tablet screen size below 1000px

## Expected behaviour

* Only the action sidebar (or dropdown menus inside of it) should scroll

## Actual behaviour

* The rest of the page behind the action sidebar scrolls

https://github.com/JoinColony/colonyCDapp/assets/34915414/15487878-c454-4734-ad7d-a729fffdf2a7

**Comment by rdig** [comment]
@arrenv I think this one is for @JoinColony/pagepro right ?

**Comment by AdrianDudko** [comment]
@iamsamgibbs Thanks!
