### ISSUE TITLE
Blockies: Addresses don't have consistent blockies in the UI

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2149]
## Description

For usernames that are addresses, their corresponding blockies do not show consistently in the UI. It was resolved for custom usernames, however it's not consistent for users with wallet addresses as their display name.

Here on master in the screenshot below, you can see the one user with three different blockies. Two showing differently in the one side panel action in proximity to each other. This is confusing for users to ensure they are matching the user with the address in reference to the blockie.

The scope of this PR is to ensure that where possible across all responsive sizes, blockies show consistently for each address to avoid any confusion for users. 

<img width="1651" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/2dc0e4f0-bd6e-4d28-b538-5cd8b935b4ec">

**Comment by rdig** [comment]
This is most likely an avatar issue. @bassgeta does your #2066 address fix this issue by chance ?

**Comment by bassgeta** [comment]
> This is most likely an avatar issue. @bassgeta does your #2066 address fix this issue by chance ?

It does, the issue was that we didn't always send in lowercase address, and thus the seed was wrong, my PR fixes that by having the avatar component lowercasing the wallet address

**Comment by rdig** [comment]
Then feel free to close this one as well when merging #2066 :+1:
