### ISSUE TITLE
GraphQL subscriptions: test in production

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyCDapp#2175]
### Description

The GraphQL subscriptions require a setup that is a bit more involved. While this is covered for the dev environment in #2169, the production deployment and testing should be tracked with this issue.

This will require deploying and testing the new version of the auth proxy and the subscription-enabled CDapp to QA and test whether it works as expected

### Design

Not applicable

### This issue is complete when...

- [ ] The new version of the auth proxy as well as the subscription-enabled CDapp work in production (i.e. QA).

**Comment by rdig** [comment]
Closing this as the new versions are already deployed and have been for some time
