### ISSUE TITLE
Actions: Truncation of recipient in completed action states

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2177]
## Descriptions

A leftover issue from #2066 is the requirement to fix the recipient address and ensure they are truncated across all responsive states when an action is completed.

Issue from #2066 with the display of addresses shown below:

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/618d5a2c-c553-4fb8-a987-369f24fbb7a0)

How they correctly show on production:
<img width="1077" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/d46e9d33-f217-4c8a-9cfa-81954d53d4d9">

FYI @bassgeta

**Comment by melyndav** [comment]
@bassgeta @ArmandoGraterol commenting here from our Discord discussions. Also needing truncation is the addresses on the following cards:

1. Contributor cards
2. All members cards and permission cards (since these use the same component)

<img width="577" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/0699cbf5-1adc-47da-8c28-e8c28aa4cf86">

**Comment by melyndav** [comment]
@ArmandoGraterol I've approved #2181 but @bassgeta and I were discussing the scope of this PR before you picked it up, which includes the above global changes. Do you need me to create a new issue for this?

**Comment by ArmandoGraterol** [comment]
> I've approved https://github.com/JoinColony/colonyCDapp/pull/2181 but @bassgeta and I were discussing the scope of this PR before you picked it up, which includes the above global changes. Do you need me to create a new issue for this?

@melyndav Hello! Sorry, I didn't saw this until I merged the PR 😅 I can create an issue for this
