### ISSUE TITLE
[Multi-sig] feat: implement manage roles multi-sig motion

### ISSUE THREAD

**Issue by bassgeta** [JoinColony/colonyCDapp#2192]
### Story

As a *user moderating a colony*, I want to be able to create and finalize a multi-sig manage roles motion.

### Description

After the groundwork has been laid with #2150 , implement the manage roles motion.

### Permissions Issue

Whilst you're here, it'd also be great to fix an existing issue with manage permissions:

How the manage permissions saga is currently setup: In the root domain, only users with the root role can create a manage permissions action. In any subdomain, only users with the architecture role can create a manage permissions action.

`domainId === Id.RootDomain ? ColonyRole.Root : ColonyRole.Architecture`

How it should be setup:  In the root domain, only users with the root role can create a manage permissions action. In any subdomain, only users with the **root role OR architecture role** can create a manage permissions action.

It should be fairly straightforward to adapt the saga to check for either permission when in a sub domain. However, this change also affects `PERMISSIONS_NEEDED_FOR_ACTION`, `getPermissionsNeededForAction` and `addressHasRoles` which are primarily used to show an error validation message when attempting to create an action you do not have permissions for. These currently have an array of required permissions, they will need to be adjusted to accommodate an array of valid permission sets where any set is acceptable.

As for multi-sig specifically, changing `PERMISSIONS_NEEDED_FOR_ACTION` will have knock on effects to `useEligibleSignees` and `useDomainThresholds` which will need adjusting. If a user has either permission it should be possible for them to vote towards the motion (you will need to check the exact implementation on the contract to check if the permission in the multisig motion is created with holds any relevance).

This will likely also impact how approvals / rejections / thresholds are calculated.

### This issue is complete when...

- [ ] The manage roles multi-sig motion can be created
- [ ] The motion can be finalized
- [ ] Only users with [adequate permissions](https://www.notion.so/colony/Multi-sig-Permissions-6aaf0b95309f4754a243d54e8d9c4189?pvs=4#fec3699a5fd241a2925bd2809494b157) can create them
- [ ] The standard `Manage Permissions` saga has been updated to allow either root or architecture in sub domains
- [ ] The necessary knock on issues this will cause are addressed

**Comment by iamsamgibbs** [comment]
Just noting here it is no longer a requirement to be able to create (or vote on) a multi-sig manage permissions motion with the `root` permission in a sub-domain.

It is still required when using the permissions decision method.

I will see if anything can be simplified thanks to this change.
