### ISSUE TITLE
[Multi-sig] feat: handle assigning multi-sig roles via a voting reputation motion

### ISSUE THREAD

**Issue by bassgeta** [JoinColony/colonyCDapp#2198]
### Story

As a *user moderating a colony*, I want to be able to create a voting reputation motion to manage a user's multi-sig permissions.

### Description

We need to create a motion handler that will handle updating of a user's multi-sig role set via voting reputation motions.
Can be tackled after #2146 is done.

### This issue is complete when...

- [ ] The motion correctly updates a user's multi-sig roles upon finalization
- [ ] The motion can be cancelled and changes are not applied

**Comment by iamsamgibbs** [comment]
Doing as part of #2192
