### ISSUE TITLE
Allow modifying the stake fraction of Staked Expenditure extension

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#2200]
In the current UI, it is necessary to re-install the extension to update its initalization params. Staked Expenditure fraction can be updated without uninstalling, as long as the UI is modified to support such flow.

### Subtasks:
- Create a saga to update stake fraction
- Modify the extensions UI to allow editing fraction

**Comment by davecreaser** [comment]
Added issue: https://github.com/JoinColony/colonyCDapp/issues/2409 for the UI part
