### ISSUE TITLE
Truncate addresses on member and permission cards

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyCDapp#2204]
Per @melyndav comment: https://github.com/JoinColony/colonyCDapp/issues/2177#issuecomment-2046886112

We need truncation on the addresses of all member's cards and permission cards

<img width="577" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/0699cbf5-1adc-47da-8c28-e8c28aa4cf86">

How it currently looks:
![Screenshot 2024-04-10 at 15 25 11](https://github.com/JoinColony/colonyCDapp/assets/18473896/4f2b12e4-215c-4e03-9237-80bb8ba449c1)
![Screenshot 2024-04-10 at 15 25 18](https://github.com/JoinColony/colonyCDapp/assets/18473896/1fcc90b0-a2d4-4991-87ed-dafb0221c0e8)

**Comment by rdig** [comment]
Whoever ends up working on this be aware that we have a `splitAddress` specifically for this
