### ISSUE TITLE
Wrong chain connected tooltip

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2218]
## Description

When the user is connected to an unsupported chain, the chain pill in the top right-hand corner of the user header should be displayed to match the Figma design below, replacing the current red UI. 

**Desktop interactions:** On hover, a tooltip is shown. 
**Mobile interactions:** On select, the tooltip is shown (an interim measure until the multi-chain UI work is implemented).

Currently:

<img width="412" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/cc3b6c02-4c83-426d-9f76-b11aa7ecd7af">

As per FIgma:

<img width="1332" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/ee8a0bfc-1713-4ebe-ab45-f11d9c6985d6">
 
 
<img width="488" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/262cd3b7-aaaf-4baa-a464-19727a9d85da">

## Figma links
Designs sit within the Multi-chain file: https://www.figma.com/file/VObjjUqTC3gd2SoiwgH6N0/Multi-chain?type=design&node-id=9791-6194&mode=design&t=YAiKLqcJGptX7uzw-4

**Comment by rdig** [comment]
Closed by #2274
