### ISSUE TITLE
Action sidebar fields should be disabled when you don't have permissions

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#2221]
## Steps to reproduce

1. On a fresh environment, connect your wallet to Dev wallet 2.
2. In GraphiQL, run this query to get the member invite code:
```
query MyQuery {
  getColony(id: "0x6dfa816d05d8a2FCc3f90F7bDB76650fAE16ee8b") {
    colonyMemberInviteCode
  }
}
```
3. Navigate to http://localhost:9091/invite/planex/%7BINVITE_CODE%7D
4. Join the colony and create a new action.
5. Select either the "Create agreement" or "Manage verified members" action types.

## Expected behaviour

* Every field on the form (except action type and title) should be disabled.
* On "Manage verified members" the "You don't have the correct permissions" error message should show.

## Actual behaviour

* The description field is not disabled on either.
* On "Manage verified members" the "Decision method" field is not disabled.
* On "Manage verified members" the "You don't have the correct permissions" error message does not show.

<img width="676" alt="Screenshot 2024-04-11 at 11 36 30" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/bb3923b2-a5ff-47de-859e-723f71a7a469">

<img width="670" alt="Screenshot 2024-04-11 at 11 37 27" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/6ed065e1-9e46-4dff-b041-5706cedf8946">

## Suggestions (optional)

See the "Simple payment" action form for an example of how this should behave.

<img width="623" alt="Screenshot 2024-04-11 at 12 16 15" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/af09fcec-7cc3-4bc0-9e7b-b38815b5ee46">

A similar fix for the "Payment builder" action form is in progress in #2123

Be aware that "Create agreement" is slightly different to all the other action types as it is the only one which requires the "Reputation weighting" extension to be installed, so the logic for disabling fields / showing error messages on this form may be slightly different.

**Comment by melyndav** [comment]
@iamsamgibbs we have existing designs for the fields showing disabled if you'd like to update your 'suggested' images. Inputs should show as text-gray-300 and be disabled. https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=3536-687292&mode=design&t=yNwi4rqIR7fGE24s-4
