### ISSUE TITLE
Manage permissions action: Removing permissions state 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2241]
Teamwork task: [Manage permissions action: Removing permissions state](https://tw.auroracreation.com/#/tasks/15881119)

## Description 

When I select a user and remove their permissions, the frontend in the completed action state have a case to cover this and just shows 'custom' action as a fallback as shown in the screenshot below. 

The scope of this PR is to add a case where there are no permissions, then it shows removed. 

<img width="1061" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/28edcb19-f2cb-4c7d-a5a3-424b288cacd4">

You can replicate this issue by:

1. Open the Manage permissions action
2. Select a user with permissions
3. Select to remove the permissions option from the permissions dropdown
4. Complete the action and see that the UI doesn't handle showing the removal action

A secondary issue is to remove the extra space in the metadata
<img width="437" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/7ae22c45-7bbc-4741-b119-585c79ce1989">
 
 
 ## Figma
 
<img width="1097" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/2b14089a-2534-4c4e-9c66-dfab8aac42b5">

https://www.figma.com/file/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?type=design&node-id=20717-29092&mode=design&t=YMpH7KQuqTQqjAKA-4

**Comment by joanna-pagepro** [comment]
@melyndav how should removing look like for custom permissions or if there's more content inside the table for example when a user has `Owner` permissions? Where should this `Removed` pill go?
I think that the mobile view needs some changes as well - it may be hard to add this pill to the content of the table, next to the bullet list, it will take a lot of space

**Comment by joanna-pagepro** [comment]
@melyndav maybe we can add a `Remove` pill next to the table heading, instead of a role pill?
![image](https://github.com/JoinColony/colonyCDapp/assets/44369011/89d8d114-01b1-4dfa-a515-f7a884b301d0)

**Comment by joanna-pagepro** [comment]
@melyndav @arrenv I'm also not able to display the previous role in the completed state, because action data doesn't contain such information

**Comment by AdrianDudko** [comment]
Close by  https://github.com/JoinColony/colonyCDapp/pull/2631
