### ISSUE TITLE
Colony objective creation and completed state issues

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2242]
Teamwork task: [Colony objective creation and completed state issues](https://tw.auroracreation.com/#/tasks/15877231)

## Steps to reproduce

1. Create a new objective action in a colony.
2. Try to add a description to the objective action.
3. You are limited to only 200 characters.
4. Complete the action.
5. Notice the missing fields in the completed state.

## Expected behaviour

* The description should have the same character limit as all other action descriptions of 4,000 characters.
* Action type name should be "Manage objective" (Please make this a global change to the action type name)
* You should see all fields in the completed state of the Manage objective action.

## Actual behaviour

* You are limited to 200 characters for the description field.
* Action type name is showing as "Colony Edit"
* You are not able to see several fields in the completed state of the Manage objective action.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/13691622-9f75-4ca8-8aa5-3e3d40aa5268)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/c6446996-3531-45a5-9fa3-2f0a19934818)

**Comment by AdrianDudko** [comment]
@arrenv this action was not prepared by our team, so I have to treat this as additional work. Estimate to fix all issues: 3h.
