### ISSUE TITLE
Pending transaction counter

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2244]
Teamwork task: [Pending transaction counter](https://tw.auroracreation.com/#/tasks/15877232)

### Story

As a USER, I want to be able to know how many transactions need to be performed when taking an action.

### Description

Currently, when performing a transaction in a colony you get a pending pill/button in the header that gives you the status of the transaction, however, this does not give feedback to the user as to how many transactions need to be performed. We would like to add this functionality to the pill to provide more information for users.

### Design

[Figma link - Header pending button](https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-47116&mode=design&t=PZ54tA4N1UKGNLW0-4)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/d31c92ab-c669-4e76-b499-f7b2ddabf085)

### Acceptance criteria.

- The pending status and button in the header shows the number of transactions in a grouped transaction.
- The number should update as the transactions progress. e.g. if there are 4 transactions in the grouped transaction, and you are on the 3rd, then the number should show as 3/4.
- All other interactions remain the same, i.e. clicking to open the transactions tab in the Userhub.
- Complete should remain as is without the number of transactions.

**Comment by AdrianDudko** [comment]
@joanna-pagepro @CzarekDryl 

Please estimate.
