### ISSUE TITLE
[ADV.PAYMENTS][PAYMENT BUILDER] As a Colony member, I can use an option to UPLOAD CSV in the PAYMENT BUILDER action to add multiple payments at once

### ISSUE THREAD

**Issue by AdrianDudko** [JoinColony/colonyCDapp#2249]
Teamwork task: [[ADV.PAYMENTS][PAYMENT BUILDER] As a Colony member, I can use an option to UPLOAD CSV in the PAYMENT BUILDER action to add multiple payments at once](https://tw.auroracreation.com/#/tasks/15879557)

## Related sub-issues/PR's
- [x] https://github.com/JoinColony/colonyCDapp/pull/2268

## Description
Provides the ability to upload a CSV file to add multiple payments at once instead of doing this one by one. This combines a Batch Payment Action with a Payment Builder action - to simplify the user's experience. 

Scope delivered by Arren: 
https://www.notion.so/colony/Payment-Builder-CSV-Upload-597250c8150548e282426df5c3b29964

## Acceptance criteria

**General requirements**
- Extends the capabilities of Payment Builder action with the option of adding multiple payments at once with a CSV import.
- Adds a button to Upload a CSV . 
	- after clicking the Upload CSV button, an Upload CSV Modal appears.

**Upload CSV Modal**
- User can get a CSV template by clicking on the Download button.
- User can close modal with "X" or by clicking out of the modal
- User can upload CSV file by:
	- Clicking a on "Click to upload" 
		- triggers OS window to choose the file
	- "Drag and drop the file"
		- Desktop only
	- Uses the same interactions as Avatar Upload functionality on User Profile page.
- User should see a progress bar for file upload.
	- User can abort upload progress by clicking on "Trash" icon .
- Uploaded CSV file should be validated by it's max. size (2MB) and max. rows (400 rows).
	- Display a "File structure is incorrect, please use a comma separated CSV." error i.e. to handle non-comma separated formats.
	- User can use "Try again" button to upload another file.
	- On successful upload, the modal should close and the table should be populated.

**Table**
- Adds a new interactions and validations rules.
	- If the uploaded CSV file contains errors, a red frame and an error banner will appear.
	- If the uploaded CSV file contains a token that is not available in the colony, show "Token error" error
		- Show tooltip with information.
		- After clicking "Token error", the user will see a dropdown with tokens available in the colony.
	- The user can delete Payments that have errors and if all errors are removed, the validation errors should disappear.
- Adds a Total Payments counter in the Payment Table
	- Display if more than 6 Payments added
	- Counts all payments (i.e. Rows added)

**Uploading a file if there is already data in the table**
- Upload CSV Modal contains Warning Information
- If the user decides to upload the file, all data in the table will be deleted and replaced with that from the CSV file
	- It does not matter whether the data was added manually or sent from a CSV file

## Notes

**Template updated to include claim delay**
export const CSV = [
  `Recipient,Token Contract Address,Amount,Claim delay (hours)
0x0000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000,200000,24
0x0000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000,100000,12
0x0000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000,50000,6
0x0000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000,5000,1
0x0000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000,5000,1`,
].join('\n');

**Old DownloadTemplate can be found here**
https://github.com/JoinColony/colonyDapp/tree/feature/advanced-expenditures/src/modules/dashboard/components/ExpenditurePage/Batch/DownloadTemplate

## Design

**Additional Button**
https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=22953-329108&mode=design&t=DNuqVArdLCYPLHqo-4
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/390dfaa4a221cfea0b0f25390d0ffbe5.png)
https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=22978-196984&mode=design&t=DNuqVArdLCYPLHqo-4
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/3914880899f11c66c8295d519d71c8ba.png)

**Upload CSV Modal**
https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=22953-335854&mode=design&t=DNuqVArdLCYPLHqo-4
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/391aa629cb9d63c41e33b9cdd4e55a11.png)
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/391b8183e5e11d93f3399d23bb60eae3.png)
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/391cd02502a4f0814b8a9e72a51157b0.png)

https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=22952-248233&mode=design&t=DNuqVArdLCYPLHqo-4
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/391f3508f7c417e416d3347d11e80fdb.png)
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/39207cc2e11026357f4e7620bcfd0467.png)
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/3921a156e7a6d4686f30d35b2d812c2f.png)

**Table**
https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=22952-253260&mode=design&t=DNuqVArdLCYPLHqo-4
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/3926a705fc937d69faad64975dd8cb6b.png)

https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=22952-247810&mode=design&t=DNuqVArdLCYPLHqo-4
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/392be436a818859ff481614ad398472a.png)

**Uploading a file if there is already data in the table**
https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=22952-252913&mode=design&t=DNuqVArdLCYPLHqo-4
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/39330b4eb42da124f1006b5081f31620.png)

**File upload component**
https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1776-8634&mode=design&t=gNbb0RNGtstmcN4A-0
![image.png](https://s3.dualstack.eu-west-1.amazonaws.com/tw-eu-inline/437576/0/0/393ac0ce90a91a9da5e21115034f52ad.png)

**Comment by AdrianDudko** [comment]
@arrenv FYI, please inform me if something is wrong

**Comment by CzarekDryl** [comment]
@arrenv @AdrianDudko Batch payment was merged to `feat/advanced-payments-ui`.

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2268
