### ISSUE TITLE
Styling issue on tabs in production

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2265]
## Steps to reproduce

This has been found in production.

1. Browse to any tabs within the UI, this is found in the:
   - Stakes tab of UserHub
   - Enabled voting reputation extensions tabs
   - Members page tabs

Thanks to Echotango for raising.

## Expected behaviour

* Styling of tabs should match the design.

## Actual behaviour

* You are seeing incorrect styling for active tabs throughout the site.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/1fd0066c-e845-43af-b1e0-60c0b847d720)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/7069bc94-b17a-45cd-97d9-0c9dda71b11b)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/cb1531ac-0e90-4d37-b6bf-b121f27343db)

**Comment by rdig** [comment]
![Screenshot from 2024-05-21 23-21-19](https://github.com/JoinColony/colonyCDapp/assets/1193222/1837f8e4-5ab6-4cfc-81fb-86ad7ba4658d)

At least after the Advanced Payments deployment, I can also confirm this is no longer an issue _(this applies to both `master` and `master-arbitrum`)_

Will close it for now.
