### ISSUE TITLE
Image upload form styling & interaction issues

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2267]
## Description

In production, there are a number of minor UI issues that require addressing within the upload modal of the 'Edit Colony details' and the inline upload form within the User Account to better align the UI with the correct component designs within the Design System. 

Changes should be made to both file upload section and across all responsive sizes. 

**Issue 1: The main button in the modal should say 'Confirm change' as per the Figma design. Relevant only for the Edit Colony details action type**

Button title change: 
<img width="591" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/d347601c-e80d-4718-9495-32906962c26b">

As per Figma:
<img width="427" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/805e662a-4fd9-4ad1-9252-db42b0b37038">

--

**Issue 2: The styling of the error state does not match the component design. Across both upload forms.**

<img width="541" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/01179e51-7086-4d76-ad41-21123e3e9e94">

As per component design in Figma:
<img width="710" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/cd0dc8b0-05f1-4bb3-b142-3608eb77d6c9">
 
 Component link in design system: https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-9638&mode=design&t=UCmEsZubFQMtqi5S-4

--

**Issue 3: When there is a file error, the cancel and confirm buttons should not show in the modal only during the default upload state. The buttons should not show in the error state, only default and complete states. Relevant only for the Edit Colony details action type.** 

<img width="546" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/5c19e56c-5dc1-46c6-bf7d-87719576689d">

-- 

**Issue 4: When I upload an image that is too large and receive the error state, when I try again with an image that is the correct file size it uploads it correctly, but the form breaks again. The page needs a refresh in order for the form to work again.**

Video:
https://jmp.sh/XiUpEUnP

**Comment by rdig** [comment]
For whoever ends up tackling this, issue #4 is not minor, and most likely requires refactoring the upload component.

Also, most likely this will also fix [#2262](https://github.com/JoinColony/colonyCDapp/issues/2262)

**Comment by davecreaser** [comment]
@melyndav @rdig - I couldn't reproduce the fourth issue, and since there seems to be some larger (probably interconnected) issues with the uploader behaviour I think it's best if that fourth point is moved to #2262 

I've fixed the other issues here: https://github.com/JoinColony/colonyCDapp/pull/2296

**Comment by melyndav** [comment]
Hey @davecreaser can you comment on the other PR cross-linking to this one so issue 4 is also included and is not lost given #2296 doesn't cover it? Thanks!
