### ISSUE TITLE
Userhub on mobile breaks the UI

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2286]
## Description

When the userhub is opened on mobile in production, the UI breaks. I can not access the top menu header or navigate away from the userhub when it's open. 

<img width="490" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/dbc719a9-005d-4503-bcf1-afa04a932e65">

## Steps to reproduce

1. Open the userhub while on mobile

## Expected behaviour

* The userhub should display correctly allowing the user to navigate the interface

**Comment by rdig** [comment]
Isn't this one for Pagepro though ?

**Comment by melyndav** [comment]
@rdig I'm not able to tell myself who broke it. It wasn't an issue previously, and I'm just raising it for whoever broke it to fix it.

**Comment by iamsamgibbs** [comment]
Is this still an issue? I cannot recreate it locally or on QA.

<img width="619" alt="Screenshot 2024-05-15 at 08 42 07" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/e7a29c80-0adf-4c3e-a8d7-26b7ecf3863c">

**Comment by melyndav** [comment]
@iamsamgibbs I was still experiencing this issue yesterday when switching between desktop and mobile through inspect.

![Export-1715768273001](https://github.com/JoinColony/colonyCDapp/assets/82127904/90e3cd5f-ce29-4c97-834f-df9584c01f11)

**Comment by iamsamgibbs** [comment]
👍  Just a note to say I recreated this accidentally today, it only happens when opening the userhub when the action sidebar is already open.
