### ISSUE TITLE
Add tooltips to dashboard social and copy icons

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2295]
Teamwork task: [Add tooltips to dashboard social and copy icon](https://tw.auroracreation.com/#/tasks/15899531)

## Description

To enhance the user experience and understanding of icons on the dashboard of a Colony, we would like to add tooltips to explain what the links should be.

The tooltips should appear above the icons to prevent them overlapping the other icons. On mobile, the tooltips don't need to appear.

The copy for each icon should be:
- All external links, including socials should have the copy: "Go to external link"
- Copy contract address icon should be: "Copy contract address"
- Copy colony URL should be: "Copy this colony URL"

In regards to the copy confirmations and as being worked on here https://github.com/JoinColony/colonyCDapp/pull/2201, it would also be good to have the copy confirmation tooltips, please the tooltips on hover, with the same behavior as described in that issue.

[Figma Link](https://www.figma.com/file/gac6xVgGNCAge5Bia933dp/Dashboard?type=design&node-id=4751-26503&mode=design&t=Y3Pu9Fjjn0d1IRpC-4)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/389a78b3-c4ad-49af-8a93-187c00eeaf25)

**Comment by AdrianDudko** [comment]
This should be closed by https://github.com/JoinColony/colonyCDapp/pull/2364
