### ISSUE TITLE
Prevent creating a payment with a locked token

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2299]
## Steps to reproduce

1. Create two colonies with created and locked tokens.
2. Pay from one colony to the other.
3. Now in the receiving colony, create a payment with the locked token from the other colony.
4. The payment will fail, but with no reason shown in the UI.

## Expected behaviour

* We should prevent allowing payment with a locked token. Ideally, as this will also allow it to block motions and expenditures being created for payments with these tokens.
(or)
* At the very least, we should show a human readable error for when the transaction fails. Such as: "This token is locked, payments cannot be made."

## Actual behaviour

* You receive a transaction error when trying to make a payment with a locked token from another colony.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/96889eb9-64ba-4fd8-b893-a5aab70e3d12)

**Comment by rdig** [comment]
So just leaving this for context here, after having a chat with @rumzledz about it.

This is really complex, as:
1. There's not good way (currently) to know of a locked state of a token (or having any reverse relationship between native token and colony)
2. There might and will be tokens that will also trigger this error, without having a locked state on them

There is actually no good, (and optimized) way of determining, and preventing a colony from making this payment.

The only way to actually do it, is via a lambda, which will slow down the payment UI considerably

**Comment by arrenv** [comment]
I had assumed this may have been tricky, but thought maybe we stored all tokens created with colony with a locked/unlocked field, and we could at least account for that. However, noticed that is not the case.

So, at the very least, it would be good to be able to show a clearer error if "colony-token-unauthorised" is the revert error.

**Comment by rdig** [comment]
> or if "colony-token-unauthorised" is the revert error.

This is problematic as well since only "normal" transactions will work with this approach, metatransactions will most likely obscure this error (broadcaster throws it's own errors)
