### ISSUE TITLE
Add ganache rpc validation in advanced user settings

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#230]
Opening this issue to track a feature request in user advanced settings to be able to validate a ganache rpc url.

## Original comment

I'm good with this, at least for now. But we'll most likely have to change it prior to going live.

At the very least we'll need to be able to validate Ganache for dev mode _(which might have any chain id -- we can agree on a "proper" one)_.

Later, it will need to support basically every chain the CDapp will get deployed to

_Originally posted by @rdig in https://github.com/JoinColony/colonyCDapp/pull/159#discussion_r1087251976_

**Comment by rdig** [comment]
Closing as not longer revelant
