### ISSUE TITLE
Updated permissions do not show correctly on completed action

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#2303]
## Steps to reproduce

1. Give custom permissions to a user (for example both funding and administration).
2. The custom permissions toggles will accurately reflect the assigned permissions.
3. Update the custom permissions for the user (for example, remove funding and add root).
4. The custom permission toggles will not accurately reflect the assigned permissions.

https://github.com/JoinColony/colonyCDapp/assets/34915414/50adf23d-58e6-42f2-97bf-bacd44332176

This can also be seen when changing permission tiers:

1. Give 'Payer' permissions to a user.
2. The completed action screen will show that the user has been assigned the payer role.
3. Update the permissions for the user to 'Owner'.
4. The completed action screen will show the custom permission toggles and they will not accurately reflect the assigned permissions.

https://github.com/JoinColony/colonyCDapp/assets/34915414/9f2a7c8d-efb7-44af-9844-e10b02844172

## Expected behaviour

* The custom permission toggles should accurately reflect the assigned permissions.

## Actual behaviour

* The custom permission toggles do not accurately reflect the assigned permissions.

## Suggestions (optional)

Whenever permissions are updated, the block-ingestor creates a ColonyAction with the `SetUserRoles` type.

It appears that the roles stored here are currently only recording the change in permissions rather than the current permissions state. This means, if 'funding' is set to true in the first action, then it is left unchanged in the second action, it won't have changed and thus appears as false in the recorded action.

Either block-ingestor should be changed to store the roles as they currently are, or CDapp should be changed to fetch the ColonyRole permissions or work through the history of changes to reach the correct state of permissions. If there is no reason for block-ingestor to store the change, it is likely simpler to make the change there - the only complication is that the contract events only emit the changes in permissions, so the previous set of permissions would need to be fetched first to accurately reflect the current state.

**Comment by rdig** [comment]
Is this a UI issue or a DB one ?

Can you confirm that the permissions are (or aren't) being correctly set in the database ?

**Comment by iamsamgibbs** [comment]
Permissions are being correctly set in the database for ColonyRole, which is the most important bit, so no problem there.

But, we also create a ColonyAction for the UI in the database each time a permission is changed. The roles recorded in the action currently store the change in permission, rather than the current state. (Not sure if this is intended or not).

For example, if I have a user with all permissions, then I remove role_0, role_1 and role_3, the contract events that get emitted are for changing those permissions to false. `{ role_0: false, role_1: false, role_3: false }`.

So it gets recorded in the ColonyAction in the database like this:
```
          "roles": {
            "role_0": false,
            "role_1": false,
            "role_2": null,
            "role_3": false,
            "role_5": null,
            "role_6": null
          }
```

Currently the CDapp completed action is just using this to display the permissions, so role_2, role_5 and role_6 appear to be false as the value is null, even though the user still has those permissions.

So we can either fix this in block-ingestor by checking the permission state for the other roles which haven't changed and providing the full current set of permissions in the action, or we can fix it on the CDapp side either by fetching the ColonyRole set of permissions from the database, or fetching the previous changes in permissions from the ColonyActions to and going through them to get to the current state (which feels very messy).
