### ISSUE TITLE
Advanced Payments API: Release expenditure stage via motion

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#2333]
## Specification

This has already been implemented by @iamsamgibbs in #1984 but my work on #2302 uncovered some issues with the way we handle multicall motions, including releasing a stage.

The good news is that there is another contract method we can call to reduce some of the complexity - https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/extensions/StagedExpenditure.sol#L97. 

### Description

This issue is to modify the saga and block-ingestor handlers in order to make the release stage flow functional again.

Release stage motion should set the relevant slot claim delay to 0, and claim all payouts for this slot.

**Comment by rdig** [comment]
Title is misspelled. Should be "motion" (vs. "moion") :smiley:
