### ISSUE TITLE
Create advanced payment using Staked payments

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2344]
### Story

As a USER, I would like to be able to create advanced payments by staking.

### Description

Allows contributors to create advanced payment types by staking their own tokens, meaning they don’t require “Payer” permissions or above. Funding the payment however, will still require either “Payer” permissions or another supported decision method.
This feature adds more flexibility to manage funds and resources in an efficient, open, and trustless way.

### Design

[Figma link - Staking to create](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=20686-371289&mode=design&t=VpKEEaoPkwkovddh-4)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/79f6170f-2b44-4be6-a215-4c187b7b5824)

[Figma link - Validation if not enough tokens](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=23853-196834&mode=design&t=VpKEEaoPkwkovddh-4)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/0dfd94fd-b46a-47e5-888d-b23915ee00e0)

[Figma link - Card for payment created with staking](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=23657-195751&mode=design&t=VpKEEaoPkwkovddh-4)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/273bab4e-c9c0-43db-bfb4-4293fb281a31)

### Acceptance criteria

- **Staking flow**
    - Decision method
        - Adds an additional decision method to Advanced payment types called “Staking”.
            - Supported advanced payment types:
                - Payment builder
                - Split payments
                - Staged payments
        - If the “Staking” decision method is selected then on creating the payment the Staking modal will open.
        
    - Staking modal
        - Modal to view the required stake amount and stake to create the advanced payment action.
        - Cancel closes the modal and does nothing. You can also click out to close the modal.
        - Clicking on “Create payment” will trigger a series of transactions to stake and create the payment.
            - If the user does not have enough locked tokens, then it will trigger transactions to approve the users tokens and activate the required amount of tokens. There is a saga for it here - https://github.com/JoinColony/colonyCDapp/blob/feat/advanced-payments-ui/src/redux/sagas/expenditures/createStakedExpenditure.ts
            - It will stake the required tokens for creating the payment.
            - On successfully staking, the payment will be created.
        - Validation
            - If the user does not have enough tokens to stake, a validation callout will show in the modal. The “Create payment” button will be disabled in this case.
            
    - Staking details
        - Upon creating a payment with “Staking”, the “Create” pill when clicked on will show that the payment was created using the staking method.
        
    - Returning stakes
        - The user who staked should receive their stake back when the first payment is made.
        - For stakes that are not automatically returned, they should be claimable in the Userhub stakes tab.

**Comment by AdrianDudko** [comment]
Closed by [feat: create staked expenditure #2340](https://github.com/JoinColony/colonyCDapp/pull/2340)
