### ISSUE TITLE
General team missing name after colony creation

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2348]
## Steps to reproduce

This has been happening a few times in production, and has required manual updates to fix. I have not been able to replicate in dev yet.

The last reported occurrences of this happened in these two colonies (both manually fixed):
- `0x5EC18F374846b725586bca75D88282c90486C0BA`
- `0x125a7F086Ef3913f3C91D42d09FaB633fE5FfD3a`

This is resulting in the General team not appearing anywhere in the app, such as in team selection, meaning Fund transfers are not able to be done between teams.

## Expected behaviour

* The General team should be created on colony creation in all cases.

## Actual behaviour

* The General team is not being created on new colony creation in some cases.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/9a4eaffd-5070-4f9d-8e17-796526f1a676)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/7d6278ea-ba2d-462d-8480-25c0a7894f51)

**Comment by rdig** [comment]
Has this been observed with more colonies or just this one ?

**Comment by arrenv** [comment]
> Has this been observed with more colonies or just this one ?

I mentioned two in the issue, so, at least these two.

I have also checked the database and can see these colonies have the same issue, which, I will fix now.

`0x21cE5BFAaC255a9f0A6BbA63c353a919aaD72C12`
`0x24bFa2Df18DA2eB747C78B6C1dF54a54F9e9015d`
`0x995cd542337F0a09A4Ba778120f181d11287DF5A`
`0x47d986206141763Ee805b685DD67361c4d2b649A`

I also just created a new Colony and got the same issue - 

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/f299bfb1-507e-43c5-8a64-0e65a70c2a38)

**Comment by rdig** [comment]
Can't replicate this locally, so might be a chain specific issue. I'll investigate

**Comment by rdig** [comment]
Fixed via https://github.com/JoinColony/colonyCDapp/actions/runs/9019941311/job/24783957177
