### ISSUE TITLE
Adding new tokens to manage tokens is crashing the app

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2351]
## Steps to reproduce

1. Create a Manage token action.
2. Add a new token.
3. Enter in a token address into the input field.
4. The app crashes during the token address validation.

## Expected behaviour

* The token address should validate and allow you to add a token.

## Actual behaviour

* The token address is not validating and is instead crashing the app.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/3667a623-95a2-480d-aeb8-41b17a2d72df)

**Comment by rdig** [comment]
I fixed this when deploying to Arbitrum via https://github.com/JoinColony/colonyCDapp/commit/e5a6a96f0066ab1be8a2187a7a67fb07f83392fc

Where did you spot the issue ? If it's QA it's fine, if it's prod, some sort of mixup is going on

**Comment by arrenv** [comment]
> I fixed this when deploying to Arbitrum via [e5a6a96](https://github.com/JoinColony/colonyCDapp/commit/e5a6a96f0066ab1be8a2187a7a67fb07f83392fc)
> 
> Where did you spot the issue ? If it's QA it's fine, if it's prod, some sort of mixup is going on

It originally happened in production on the colony I just set up, then was able to replicate it on `master`. I have just done a hard refresh in production and it is working for me know there.

**Comment by rdig** [comment]
It sounds like a caching issue, but this was deployed over two weeks ago, plus it's on `master` for close to a week.

Closing this as a caching issue.
