### ISSUE TITLE
New Colony creation empty states

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2357]
## Description

The desktop versions activity feed tables on both the dashboard and activity page have UI issues in the empty state.

Dashboard activity table:
<img width="822" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/c9aa3608-9c37-4371-a903-5779dd69eed0">

Activity feed table:
<img width="1362" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/0d42b0e6-7b3b-46a8-88b4-75d28aeb803d">

Mobile are showing correctly:
<img width="516" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/ca57fec8-1520-456b-9af8-46086ab5d7d9">

## PR scope

The formatting of the empty state for both tables should match Figma component and all other empty states of tables across the CDapp for desktop and tablet sizes:
<img width="1085" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/8710aed8-774b-463b-a748-1d3e14942600">
 
 
 Component link: https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-24348&mode=design&t=sRylii2P0KDKCZC5-4

**Comment by davecreaser** [comment]
Hey @melyndav is this still reproducible for you? I've just taken a look and it all seems good to me:

<img width="1728" alt="Screenshot 2024-05-22 at 11 43 17" src="https://github.com/JoinColony/colonyCDapp/assets/38098203/4091169c-d16f-49e6-aa27-d0bb6f77877a">

<img width="1728" alt="Screenshot 2024-05-22 at 11 43 39" src="https://github.com/JoinColony/colonyCDapp/assets/38098203/119cca8c-ec87-404d-9c53-ecf417610331">

**Comment by melyndav** [comment]
Heya @davecreaser it's live in production if you go visit the metacolony.

<img width="1337" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/644c0385-3e36-4f43-a9a5-443e2bee6504">

<img width="2162" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/e1a74ae2-fc5e-4626-9117-10d2127cd9e1">

**Comment by davecreaser** [comment]
@melyndav A true mystery! It's working on production for me too haha. Which browser are you on? I'm on chrome. I bet this is a classic case of browsers being fun?

![Image](https://github.com/JoinColony/colonyCDapp/assets/38098203/4852e4b2-6f1f-44f2-a2f0-006d362051b3)

**Comment by melyndav** [comment]
> @melyndav A true mystery! It's working on production for me too haha. Which browser are you on? I'm on chrome. I bet this is a classic case of browsers being fun?
> 
> ![Image](https://private-user-images.githubusercontent.com/38098203/332841338-4852e4b2-6f1f-44f2-a2f0-006d362051b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODg5MTcsIm5iZiI6MTcxNjM4ODYxNywicGF0aCI6Ii8zODA5ODIwMy8zMzI4NDEzMzgtNDg1MmU0YjItNmYxZi00NGYyLWEyZjAtMDA2ZDM2MjA1MWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE0MzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZTNhMTZmYTdkYjMzMzIxYzlkMWNkNWZjYTY4ZGM4ZThjYzVkZTRjZTY0YzAyMTNlNTE3Nzk5NzdmMjIzZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8LVdmp-TOzMfT8cns2mZgzQM6M7CmKlZherAB7u1zzQ)

Firefox on osx.
