### ISSUE TITLE
Use accurate title and description in the Transactions tab.

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2369]
## Steps to reproduce

1. Ensure MetaTx is enabled.
2. Create a Payment builder action.
3. Execute the payment.
4. Check the transactions tab for the Payment builder transaction.
5. Check all other transactions labels

## Expected behaviour

* The title should be transaction title.
* The description should be the custom action title with a fallback to the action metadata.
* The details should align, regardless if MetaTx was used or not.

## Actual behaviour

* The title and description are not correct.
* If using MetaTx, the details are showing incorrectly.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/3c8385c0-e351-4f78-97d6-71fb239422c2)

**Comment by rdig** [comment]
@jakubcolony can you sneak in the fix for this before deploying Advanced Payments ?

**Comment by jakubcolony** [comment]
yep will fix all metatx messages today

**Comment by jakubcolony** [comment]
This should be resolved by #2390.
