### ISSUE TITLE
Inconsistent callout card styling in modals

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2371]
Teamwork task: [Inconsistent callout card styling in modals](https://tw.auroracreation.com/#/tasks/15912175)

## Steps to reproduce

1. Create a Payment builder action.
2. Go through each of step until you get to the Fund payment step.
3. Select a decision method, and note the style of the callout card.
4. Continue on until you get to the Release payment.
5. Select a decision method, and note the style of the callout card.

## Expected behaviour

* The styling of the callout cards should be consistent and match the design.

[Figma design: Modal callout](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?node-id=21075-278120&t=BoFmrH0DLojBRxZR-4)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/54374ed3-78f9-455a-b6ae-e68b0b7fc7fd)

## Actual behaviour

* The styling of the callout cards is inconsistent across modals.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/3dc92152-74ff-47cf-b394-d7eaa814278e)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/f0a84971-da29-4873-9038-a6220c019d6f)

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2403
