### ISSUE TITLE
Disable and show a loading state during transactions

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2372]
**Teamwork task:** [Disable and show a loading state during transactions](https://tw.auroracreation.com/#/tasks/15907590)

## Steps to reproduce

1. Create a Payment Builder action.
2. Get to the Fund step.
3. Click and fund the payment and complete the transactions.
4. Notice the Fund button will still be clickable.
5. Click on it again, the modal will open and you will be able to fund again.

## Expected behaviour

* The action button on each stage should be disabled with a loading state to prevent duplicate transactions.

## Actual behaviour

* You are able to click the same stage action button, even though the transaction had already be triggered and completed successfully.
* I was able to fund the payment twice.

![button-loading-state](https://github.com/JoinColony/colonyCDapp/assets/33682027/3163628a-602d-4a16-8175-1745494a79d7)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/c6d07ca0-fc5f-4e69-a49c-a0912600610c)

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2375
