### ISSUE TITLE
Simple Payments  not working on QA environment 

### ISSUE THREAD

**Issue by marcocolony** [JoinColony/colonyCDapp#2377]
## Steps to reproduce

1. Access the [QA Environment ](https://arbitrum-sepolia.colony.io/)
2. Login with a MetaMask wallet
3. Select a colony where the user has at least payer permissions  
4. Create a new action
5. Select *Simple payment*
6. Select the Permissions decision method
7. Enter payment details
8. Create payment and sign the transaction.

## Expected behaviour

- After the transaction is signed, the action is finalized
- Funds are transferred

## Actual behaviour

- After the transaction is signed, the action is not finalized.
- The button reverts from “Pending” to “Create payment” after some time.
- The button is still clickable allowing for the transaction to be triggered again.
- Funds are not transferred.

![image](https://github.com/JoinColony/colonyCDapp/assets/165801260/4cb53a26-268d-4861-9842-1d63cb956389)

![image](https://github.com/JoinColony/colonyCDapp/assets/165801260/c88f93dd-8f9b-4dbf-91be-a6d55fc7f5ad)

**Comment by rdig** [comment]
Culprit here is `CreateActionMetadata` which I guess either fails or just doesn't know how to handle the case for the expenditure

![Screenshot from 2024-05-15 16-58-43](https://github.com/JoinColony/colonyCDapp/assets/1193222/62c0f372-a7e0-490d-98ba-fe3ddd5448cb)
![Screenshot from 2024-05-15 16-58-51](https://github.com/JoinColony/colonyCDapp/assets/1193222/4d02231f-d29a-4b5d-92b9-74b64d3191ce)
![Screenshot from 2024-05-15 16-58-54](https://github.com/JoinColony/colonyCDapp/assets/1193222/12871c81-1289-4666-9df0-8a66da54b0a3)

I suspect this is just a simple case of deploying the new/latest version of Auth Proxy, but waiting on @jakubcolony to confirm

**Comment by jakubcolony** [comment]
I can confirm this is a bug with block-ingestor creating an `EDIT_EXPENDITURE` action instead of `PAYMENT`. A good example of what #2317 will attempt to solve.

**Comment by jakubcolony** [comment]
@marcocolony should be fixed in QA

**Comment by marcocolony** [comment]
@jakubcolony can confirm 🙌 
<img width="1800" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/165801260/19059532-f956-4366-903a-30cb6a71767a">
