### ISSUE TITLE
Payment builder not working on QA environment

### ISSUE THREAD

**Issue by marcocolony** [JoinColony/colonyCDapp#2378]
## Steps to reproduce

1. Access the [QA Environment](https://arbitrum-sepolia.colony.io/)
2. Login with a MetaMask wallet
3. Select a colony where the user has at least payer permissions
4. Create a new action
5. Select Payment builder
6. Select the Permissions decision method
7. Enter payment details
- One row  
8. Create payment and sign the transaction.

## Expected behaviour

- After the transaction is signed, the action is finalized
- Funds will be claimable after the claim timer ends.

## Actual behaviour

- After the transaction is signed, the action is not finalized.
- Error message shows up on user hub

![image](https://github.com/JoinColony/colonyCDapp/assets/165801260/21f8b8b3-635f-466c-a90f-56e5cd043b27)

![image](https://github.com/JoinColony/colonyCDapp/assets/165801260/29be6c33-85eb-4169-a7c1-f9243bc25265)

**Comment by rdig** [comment]
This has nothing to do with the payment builder, and all to do with the contracts, and it's basically what's blocking the deployment of advanced payments.

@jakubcolony / @area are already working on this.

PS: @jakubcolony I've assigned this to you

**Comment by jakubcolony** [comment]
@marcocolony I believe this is now resolved, please let me know if you think there's still anything outstanding.
