### ISSUE TITLE
Master: Member dropdown not showing data 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2381]
The members dropdown within the action side panel isn't showing any data. I can not test actions that have this input completely. 

<img width="700" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/52e9b279-5d82-4bbd-a4a3-9c5d92935bd5">

## Steps to reproduce

1. Create a new action that has a member select in it i.e Simple payments
2. Select the members field to trigger the dropdown
3. The members dropdown shows with only the search input and returns no user data

## Expected behaviour

1. The members dropdown across all action types should display data correctly 

## Actual behaviour

1. The dropdown displays no data with only the input visible

**Comment by rdig** [comment]
I was just about to write that I wasn't able to replicate :)

Glad you figured it out
