### ISSUE TITLE
Payment fund step is missing in flow due to multiple funding actions

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2399]
Teamwork task: [Payment fund step is missing in flow due to multiple funding actions](https://tw.auroracreation.com/#/tasks/15917249)

## Steps to reproduce

1. Create an Advanced payment action.
2. At the Funding step, fund the payment twice. You should be able to do it by clicking the button twice.
3. Continue to the next step.
4. Click back in the funding step.

## Expected behaviour

* You should see the multiple funding history items.

There are designs for how this should be handled, which has been done as a part of this PR - https://github.com/JoinColony/colonyCDapp/pull/2362

### Default state - no transaction selected ([Figma Link](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?node-id=24360-198210&t=EUQa9sGw8YIooUJj-4))

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/0944951a-3402-4acb-8a00-9f11f5f808ee)

### Selected state - on clicking on a transaction ([Figma Link](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?node-id=24360-198981&t=EUQa9sGw8YIooUJj-4))

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/d6232065-5cc4-4308-be41-6dc0e81bf2ad)

## Actual behaviour

* The payment had two or more fund requests, but no history was shown.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/0e5ec018-7a0c-4fb3-83fd-d00b2bf8448e)

**Comment by CzarekDryl** [comment]
@arrenv I've already implemented this in this [PR](https://github.com/JoinColony/colonyCDapp/pull/2362). This is how it looks:

https://github.com/JoinColony/colonyCDapp/assets/76940796/dfd24f8d-473b-4056-b8a7-ccef57c3bb1a

**Comment by arrenv** [comment]
@CzarekDryl Thank you. The one you have is for motions, does it support permission based ones as well?

**Comment by AdrianDudko** [comment]
@arrenv I think we can close this, right?

**Comment by arrenv** [comment]
Yes, closing now.
