### ISSUE TITLE
Status is showing as "Failed", when payment was "Canceled"

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2404]
Teamwork task: [Status is showing as "Failed", when payment was "Canceled"](https://tw.auroracreation.com/#/tasks/15917176)

## Steps to reproduce

1. Create a Payment builder action.
2. Cancel it right away.
3. Navigate to the activity feed and check the status pill. Which, will say "Failed".

## Expected behaviour

* A canceled Payment builder action should show the status as "Canceled".

## Actual behaviour

* A cancelled Payment builder action is showing as "Failed".

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/3477f504-681f-432d-97ad-ff31db7b40f8)

This is the action:

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/341a6dfe-53ec-4944-bc89-f301efdbc902)

**Comment by joanna-pagepro** [comment]
@arrenv this is how it looks like on a design: https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?node-id=4102-615966&t=b7BuWnyOopl8j1zQ-4
Are you sure that this should be changed? If so, should the `Canceled` pill look the same as the `Failed` pill?
