### ISSUE TITLE
Cancelling adv. payment modal update

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2406]
Teamwork task: [Cancelling adv. payment modal update](https://tw.auroracreation.com/#/tasks/15917184)

## Steps to reproduce

1. Create a Payment builder action using Permissions decision method.
2. Cancel it right away.
3. Notice the content and button of the modal.

## Expected behaviour

* We should update the copy in the modal before locking the payment so that it can work in multiple cases. New copy:
  - Title: "Cancel this payment"
  - Description: "This action cannot be undone. You will not be penalized for canceling the payment, any stakes made will be returned."
  - Button: "Yes, cancel payment"

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/03d71d1d-7324-4a6a-b52c-130b7a5b2c7b)

## Actual behaviour

* The cancel modal does not accurately represent what is happening or being done. i.e. there are no users stakes.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/57e47286-68f4-4611-a0f7-83b11b04b598)

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2455
