### ISSUE TITLE
Inconsistent balances across the UI

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2408]
## Steps to reproduce

1. Create a Payment builder action and fund it, don't release it.
2. Go to the balances page and pay attention to the balances updating.
3. Start to create a new Simple payment action.
4. Check the available funds from token drop down.

You will notice that there are multiple balances shown throughout the process. It would be good to understand the difference between the initial loaded value and the available funds in the token selection drop down.

## Expected behaviour

* The balances should be correct and consistent.
* Ideally, it would be good if the inclusion of funded expenditures don't load separately in the UI, to avoid confusion.

## Actual behaviour

* Balances are inconsistent between initial load, loaded state and available funds.

![token-updating-inconsistent](https://github.com/JoinColony/colonyCDapp/assets/33682027/b0f636c6-0254-41aa-ade8-4ac96195ae77)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/d9a9d36d-fc50-480f-b2c0-972be7bf4993)

**Comment by jakubcolony** [comment]
@arrenv do we want to include balance held in expenditures in "Available funds"? Considering those cannot be used for payments/transfers unless pulled out of the funding pots.

I'm surprised however to see the difference between funds table showing 511k vs. available funds showing a lower value so that needs to be investigated.

**Comment by arrenv** [comment]
@jakubcolony The expenditures balance should not be included in the "Available funds", which seems to be the case.

So, this is mostly about understanding why there is a difference with 511k vs. available funds and to rectify that and to hopefully get rid of the changing of the value on the balances page on load, which is confusing for users. It would be better to wait for them to both load then just show one value, then to show two different values while loading.
