### ISSUE TITLE
Currency conversion is not working and is wrong in production

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2418]
## Steps to reproduce

1. Add funds to a colony with value, examples included in screenshots USDC, ETH, and ARB.
2. Check the balance of funds in the users denominated currency.
3. The values are either incorrect or missing.

## Expected behaviour

* The currency conversions should show a value if it has a value.
* The currency conversion value should show correctly.

## Actual behaviour

* Token values are not being shown, when a value exists.
* Token values are showing wrong, if a value does exist.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/8ccf02c5-1e42-465b-a679-2412add82484)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/68548f7f-98ff-40f7-85b0-3be5cb6814e5)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/99e36765-2d16-4390-b502-aa7963c568c0)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/54f0b6a7-483e-4c04-bf13-f3ad9b6de49a)

**Comment by rdig** [comment]
Needs to be investigated but I suspect this to be Coingecko limitation for Arbitrum

**Comment by davecreaser** [comment]
Looking into this now, it looks like on production it's calling coingecko to get a price like this:

`https://api.coingecko.com/api/v3/simple/token_price/xdai?contract_addresses=0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9&vs_currencies=eur&x_cg_demo_api_key=`

Correct me if i'm wrong, but on production it should be using arbitrum one as the asset platform, so using:

`https://api.coingecko.com/api/v3/simple/token_price/arbitrum-one?contract_addresses=0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9&vs_currencies=eur&x_cg_demo_api_key=`

The contract address is from Arbitrum, so when it's called using xdai the contract address is wrong and everything is coming back as 0 value.

@rdig if this sounds right, i'll work on correcting the asset platform in these urls

**Comment by arrenv** [comment]
> Looking into this now, it looks like on production it's calling coingecko to get a price like this:
> 
> `https://api.coingecko.com/api/v3/simple/token_price/xdai?contract_addresses=0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9&vs_currencies=eur&x_cg_demo_api_key=`
> 
> Correct me if i'm wrong, but on production it should be using arbitrum one as the asset platform, so using:
> 
> `https://api.coingecko.com/api/v3/simple/token_price/arbitrum-one?contract_addresses=0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9&vs_currencies=eur&x_cg_demo_api_key=`
> 
> The contract address is from Arbitrum, so when it's called using xdai the contract address is wrong and everything is coming back as 0 value.
> 
> @rdig if this sounds right, i'll work on correcting the asset platform in these urls

If that is the case, then that does seem like a straight forward solution :) perhaps it should be an environment variable.

**Comment by davecreaser** [comment]
I think I've got it working using the environment variables that we currently have (network_id) and updating the asset_platform map that we use in the coingecko config to handle all the possible network_ids that we currently support. I'll check with the other devs to see what they think.
