### ISSUE TITLE
The Colony Overview popover's Transactions content is going out of bounds

### ISSUE THREAD

**Issue by rumzledz** [JoinColony/colonyCDapp#2423]
## Steps to reproduce

1. Visit a Colony you've joined
2. Create at least one Transaction
3. Open the Colony Overview popover
4. Click on the Transactions Tab

## Expected behaviour

The Transactions tab contents should be contained within the boundaries of the popover container.

## Actual behaviour

The Transactions tab contents are overflowing.

![image](https://github.com/JoinColony/colonyCDapp/assets/50642296/a6bcca76-86c8-4536-baee-193cfb1f8405)

**Comment by rdig** [comment]
I think @jakubcolony was looking for a fix for this, or already did it maybe
