### ISSUE TITLE
The app crashes if you initiate a payment from the Balances page

### ISSUE THREAD

**Issue by rumzledz** [JoinColony/colonyCDapp#2424]
## Steps to reproduce

1. Visit your Colony's Balances page i.e. [colonyName]/balances
2. Click any token's meatball menu button
3. Click "Make payment using this token"

## Expected behaviour

The Action Form should come up and the form type should be Simple Payment

## Actual behaviour

The app crashes.

https://github.com/JoinColony/colonyCDapp/assets/50642296/744983e4-6fe8-420f-b1b3-128796305b1d

## Console errors

![image](https://github.com/JoinColony/colonyCDapp/assets/50642296/b92d7f2f-a611-43ee-aea9-5e6f0189c181)

**Comment by rdig** [comment]
When submitting bugs please also capture the dev tools since the relevant errors are most likely captured in there

**Comment by rumzledz** [comment]
> When submitting bugs please also capture the dev tools since the relevant errors are most likely captured in there

Noted! I shall add that in now ✍️
