### ISSUE TITLE
[Multi-sig] feat: implement the signee widget

### ISSUE THREAD

**Issue by bassgeta** [JoinColony/colonyCDapp#2429]
### Notes
(_edited 13.06 by @AdrianDudko_)
- This ticket is for handling the Multi-sig motion process by the Pagepro team.
- Only the Mint Token action is supported at the time of starting work on the Multi-sig motion process.
- [TW task (only for internal Pagepro usage)](https://tw.auroracreation.com/#/tasks/15603915)
- [Scope (the most up-to-date version)](https://www.notion.so/colony/Multi-sig-Permissions-6aaf0b95309f4754a243d54e8d9c4189)
- [Design (the most up-to-date version)](https://www.figma.com/design/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?node-id=21336-81382&t=sIiA7EMUN554c8pr-4)
- Related issues/PR's 
    - https://github.com/JoinColony/colonyCDapp/pull/2489
    - 

### Story

As a *user viewing a multi-sig motion*, I want to see relevant information and be able to approve it if possible.

### Description

We need to first determine the required role for the motion. The potential signatories are all the members with relevant roles in the motion's `createdIn` domain and **ALL** the role holders in the `Root` domain. The list is paginated by clicking `Load more` (so we can create a new gql query for this, we can check if it's possible to ramp up the caching as a lot of these members will be fetched already).

For displaying the threshold data, we need to get the current role signees from the motion data (we need to determine what this property will be called) and fetching the domain's multi-sig threshold from the backend.

We should be constantly polling/subscribe to the motion query. The signees are displayed on the top
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/d173a61c-f110-4006-b1ce-f2c3f1217cd4)

We need to filter these users out from the others so we don't display them twice. Make sure not to display users which have rejected it as potential signees.

### Design

[Figma link](https://www.figma.com/file/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?type=design&node-id=20450-34928&mode=design&t=iqzIcnoziy1lwDp6-4)

![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/509c810d-9b80-48cf-895c-cdc9aa0eb82c)

### This issue is complete when...

- [ ] The correct number is shown as the required threshold (so we need to check domains that have a custom one, majority approval or inheriting from colony)
- [ ] Potential signees are shown in the widget, the list being paginated
- [ ] The signees are shown on top, followed by all potential signees 
- [ ] Upon clicking `Approve`, the vote gets added to the motion and the user is now a signee

**Comment by AdrianDudko** [comment]
Hi @bassgeta, if you don't mind, we will use this issue to work on [Multi-sig Permission - Motion Process](https://www.figma.com/design/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?node-id=21140-145629&t=uVT0JmEaSFBYcO5e-4). I will update the task with some additional info.

**Comment by AdrianDudko** [comment]
@bassgeta Great, thank you 👌  @CzarekDryl will stay in touch with you, as he will be working on this on our end :D
