### ISSUE TITLE
Staking Advanced Payments Extension

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2434]
Teamwork task: [Staking Advanced Payments Extension](https://tw.auroracreation.com/#/tasks/15924180)

## Related issues/PR's

- [ ] https://github.com/JoinColony/colonyCDapp/pull/2386

### Story

- As a USER, I would like to be able to create advanced payments by staking.
- As a USER, I would like to be able to install, deprecate and uninstall the Staking Advanced Payments extension.
- As a USER, I would like to see know what the Staking Advanced Payment is and what is it used for.
- As a USER, I would like to be able to manage the Staking Advanced Payments extension.

### Description

Users will be able to create advanced payments by staking as a new action type to be used within a colony. Enabling this extension will add the new decision method “Staking” to Advanced Payment types including Payment builder, Split payments, and Staged payments to allow anyone to start the payment process by staking their own tokens.

### Design

Extension details page - [Figma Link](https://www.figma.com/design/6qONTE1uD9K4yoIbfFzidg/Extensions?node-id=736-13870&t=vPkF3ZfomdCFcufq-4)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/503d535b-9269-4a13-963c-c2f0850cb04e)

Settings page - [Figma link](https://www.figma.com/design/6qONTE1uD9K4yoIbfFzidg/Extensions?node-id=1188-11839&t=vPkF3ZfomdCFcufq-4)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/7190b23a-ba96-46b6-a599-b5108d6cadd0)

Uninstall warning - [Figma link](https://www.figma.com/design/6qONTE1uD9K4yoIbfFzidg/Extensions?node-id=1188-11839&t=vPkF3ZfomdCFcufq-4)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/9db26b48-4a0b-4252-89ce-eabb0a36ffe2)

## Acceptance Criteria

- **General requirements**
    - Should be in alignment with desktop/tablet/mobile design from Designs.
    - Should use existing components and styles where possible for consistency.

- **Extension tabs update**
    - Add to all extensions.
    - Move the tabs up the top.

- **Extension details page:**
    - The extension icon and name are correct as of the design.
    - Extension type:
        - Payments.
    - Overview:
        - Description
            
            Allows contributors to create advanced payment types by staking their own tokens, meaning they don’t require “Payer” permissions or above. Funding the payment however, will still require either “Payer” permissions or another supported decision method.
            
            This feature adds more flexibility to manage funds and resources in an efficient, open, and trustless way.
            
            Payment types supported:
            
            Payment Builder: Provides a highly flexible way to construct a complicated payment involving multiple recipients receiving a number of different tokens at different times.
            
            Split Payments: Divide an amount of funds between a set of recipients equally, unequally or based on proportion of selected recipients reputation.
            
            Staged Payments: A payment broken down into separate milestones which may be released separately. Useful for example to make partial payments upon delivery of agreed project milestones.
            
        - How the extension works
            - Users can select a supported payment type based on the required structure of the payment
            - Provide details of the payment, such as, team to pay funds from, recipients, amounts, tokens, delays, etc.
            - Decision Method: Choose the "Staking" decision method to create the payment process.
            - To create the payment, users will need to stake some of their own funds. Acting as a safeguard against frivolous or spam payments.
            - The rest of the payment process will be the same as usual for these payment types.
            - If the payment is approved, the creator will receive their full stake back on first payment.
            - However, if it is determined that the payment goes against the organization, it can be canceled, and the user canceling can decide to release or punish the creator’s stake. If punished, the creator will lose their original stake amount and equivalent reputation.
        - Useful for:
            - Increasing autonomy in your team without compromising security.
            - Providing a way for members of your team to make payment requests.
        - Supporting guides and documentation
            - Staking Advanced Payments - https://docs.colony.io/use/making-payments/staking-payments (not done)
    - Extension details:
        - Developer: Colony
        - Permission: “Payer” or “Funding” & “Administration” custom permissions.

- **Extension settings**
    - Required Stake
        - The percentage of the team’s reputation, in token terms, that is required to create an Advanced Payment.
        - Validation
            - Should be a positive number, can be a decimal. If not:
                - Please enter a positive number
            - Should be less then or equal to 50%.
                - Please enter a percentage less than or equal to 50%.
    - Users without "Owner" permission - [Figma link](https://www.figma.com/design/6qONTE1uD9K4yoIbfFzidg/Extensions?node-id=1258-1922&t=vPkF3ZfomdCFcufq-4)
        - The view for most users will show a read-only state for the value.
        - The "Save settings" button will not be visible.

- **Installation**
    - After installing, the extension’s status will change to “Installed”.
    - Streaming payments page will only become available once the has been at least one stream created within the colony.

- **Deprecation**
    - Users with the “Root” permissions can deprecate the extension.
    - When deprecated, all active payments can continue and stakes can be claimed.
    - No new payments can be created with staking.

- **Uninstall**
    - Users with the “Root” permissions can deprecate the extension.
    - Uninstall modal:
        - Extension message:
            - “Uninstalling this extension will remove the functionality to be able to create payments through staking. Ensure you understand the potential risks before continuing.”
        - Warning messages:
            - “Please ensure that all funds in processes associated with this extension are claimed by their owners before uninstalling. Not doing so will result in permanent loss of the unclaimed funds.”
    - All past payment actions created using this extension will remain accessible through the colony’s and users transaction history.
    - On uninstalling, all users stakes will be lost if not claimed.

- **Staking flow**
    - Decision method
        - Adds an additional decision method to Advanced payment types called “Staking”.
            - Supported advanced payment types:
                - Payment builder
                - Split payments
                - Staged payments
        - If the “Staking” decision method is selected then on creating the payment the Staking modal will open.
    - Staking modal
        - Modal to view the required stake amount and stake to create the advanced payment action.
        - Cancel closes the modal and does nothing. You can also click out to close the modal.
        - Clicking on “Create payment” will trigger a series of transactions to stake and create the payment.
            - If the user does not have enough locked tokens, then it will trigger transactions to approve the users tokens and activate the required amount of tokens.
            - It will stake the required tokens for creating the payment.
            - On successfully staking, the payment will be created.
        - Validation
            - If the user does not have enough tokens to stake, a validation callout will show in the modal. The “Create payment” button will be enabled in this case, but clicking will re-reveal the validation message.
    - Staking details
        - Upon creating a payment with “Staking”, the “Create” pill when clicked on will show that the payment was created using the staking method.
    - Releasing payments
        - The user should be able to select the “Payment creator” decision method in the “Release payment” modal.
        - On selecting the "Payment creator" option, the info card will appear explaining the next step, as of the design.
        - On clicking “Release payment”, the payment will be released right away and/or start the claim delay process.
        - After releasing a payment with the “Payment creator” option, the “Release” pill when clicked on will show that the payment was released using the payment creator decision method.
    - Returning stakes
        - The user who staked should receive their stake back when the first payment is made.
        - For stakes that are not automatically returned, they should be claimable in the Userhub stakes tab.

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2474
