### ISSUE TITLE
Userhub transactions overflow issue

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2457]
## Steps to reproduce

Note: This was noticed in production

1. Perform some transactions.
2. Open up the UserHub Transactions tab.
3. Notice the transactions items overflowing the Userhub container.

## Expected behaviour

* Transaction items should not be overflowing the Userhub container.

## Actual behaviour

*  Transactions items are overflowing the Userhub container.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/08a3175d-1247-457d-9f84-d340702991b3)

**Comment by rdig** [comment]
I suspect this was introduced alongside #2376

Maybe @davecreaser can confirm

**Comment by davecreaser** [comment]
It does seem most likely. Strange that it wasn't caught then too, I'm interested to see what's causing it tbh!

**Comment by jakubcolony** [comment]
Could this possibly be a transaction that's missing a i18n title? It then uses the key as a fallback which could cause overflow

**Comment by arrenv** [comment]
> Could this possibly be a transaction that's missing an i18n title? It then uses the key as a fallback which could cause overflow

I did think this as well, but was lazy and did not scroll down far enough in my transaction list. Alas, I have done so and found the following. Can we add a max width and ellipsis to this title and description @davecreaser (or whomever picks this up) so that it does not overflow in these cases.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/5dc7af9a-10ae-4b6a-961a-c4720a11a476)
