### ISSUE TITLE
[Manage Tokens] Feat: Implement Completed Action Screen

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#2460]
### Story

As a user I want to be able to manage the approved tokens in my colony. After creating a `Manage tokens` action, I should see the completed action screen with a table showing the approved tokens including tokens which were added or removed by the action.

### Description

The `manageTokens` handler on the block-ingestor will need to create a new colony action in the database. The colony action model will need new field(s) for tokens added / removed / approved in order to show these in the completed action component.

The Completed Action component in the CDapp will need updating to show a new `ManageTokens` completed action component. The completed action should reflect the figma design and show a table of the approved tokens showing if any were added / removed as part of this action.

### Design

[Figma link](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?node-id=5708-399455&t=CfgM3TQk3K0vgqYl-4)

### This issue is complete when...

- [ ] The `manageTokens` block-ingestor handler creates a new colony action
- [ ] The `ColonyAction` model is updated with new fields
- [ ] The Manage Tokens completed action has the necessary data to display the approved tokens table correctly

**Comment by rdig** [comment]
Should this be closed ?
