### ISSUE TITLE
Payment builder feature global change

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2493]
## Description

To streamline our features for users, the 'Payment builder' feature is being renamed 'Advanced payment'.

All references globally including action types, metadata, activity feeds and extensions need to be renamed. 

Some examples of where the payment builder is currently referenced:

Actions dropdowns:
<img width="365" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/19b7f171-db9c-4524-96e5-f55ae7a90e7d">
 
 Action:
<img width="388" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/41311211-3721-467c-8f87-f5051e5a41fa">

**Comment by melyndav** [comment]
@bassgeta FYI 👍

**Comment by rdig** [comment]
@mmioana after you finish your current work, please pick this one up
