### ISSUE TITLE
User & token pop over optimisations to handle permission pills 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2496]
## Description 

As part of the new multi-sig feature, two permissions pills can now be shown on user cards per each team to display the permission types the user holds. 

As a result, some UI design changes have been made to **all user types** on **all responsive sizes**. 

Note: The width of these cards on mobile should not be changed.

Currently: One permission pill shows next to the reputation and team info at the bottom of the user pop over: 

<img width="392" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/d402ad36-6e7c-43e1-aecc-edf31c363901">

New changes: Permission pills now show the icon only along with some minor UI changes
<img width="457" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/1fff276c-31f4-464d-9be5-4ed41ba7319e">

## Token pop overs

Also, a slight width change has been made to the token pop over to allow more token information to show.

<img width="923" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/c9d8adc6-4c3c-4fe7-8121-ece1dbfa23de">

https://www.figma.com/design/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?node-id=21146-169728&t=X0HP5W6dgMdlyOeP-4

## Figma

Within the Figma annotations the required UI changes and interactions to each card type have been spec'd out.

<img width="1564" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/02378043-fd16-4fdb-aa93-ea7cd7d78f9d">

https://www.figma.com/design/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?node-id=21146-170334&t=X0HP5W6dgMdlyOeP-4

**Comment by melyndav** [comment]
@bassgeta FYI 👍

**Comment by rdig** [comment]
CLosed by #2649
