### ISSUE TITLE
Get rid of  fetchable data concept

### ISSUE THREAD

**Issue by chinins** [JoinColony/colonyCDapp#25]
From Raul: "I think there's a good case to be made to get rid of the whole fetchable data concept and it's not really relevant to us anymore"

This comes from `FetchableData.ts` file. Raul is still thinking about it so for now it's on hold. For Raul to decide if we are going with it.

`export class FetchableDataRecord<R> extends Record<Shared>(defaultValues)`

**Comment by rdig** [comment]
Closed by #27
