### ISSUE TITLE
Remove default 1 comment value from Agreements widget

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2505]
## Steps to reproduce

1. Go to a colony dashboard.
2. Ensure there is an agreement.
3. Notice that, even with comments not currently being present, the comment icon shows a 1.

## Expected behaviour

* The comment icon and number can be hidden for now.

## Actual behaviour

* You are able to see a default 1 value for the comment number.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/7e162041-3839-4639-96bd-324a7c35f55c)

**Comment by SeanAverS** [comment]
Hello, 

I am interested on working on this. Could I please be assigned? Thank you.
