### ISSUE TITLE
Mint tokens motion does not claim new tokens

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2506]
## Steps to reproduce

1. Create a motion to mint tokens.
2. Go through the process to ensure it passes.
3. Finalize the motion.
4. Check the balance of the Colony, it would not have changed.
5. Check the incoming funds page, it will show the newly minted tokens, available to claim.

## Expected behaviour

* Mint tokens actions, regardless of decision method, should claim the tokens on execution.

## Actual behaviour

* Newly minted tokens are not claimed when using Reputation decision method.
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/e4e2d449-cda6-4f4b-964b-a1dcdb4c65f6)

   #### Minted tokens claimed with permissions
   ![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/c0a151d1-4cf7-4b3c-a652-c03aaab2de70)

   #### Minted tokens with motion incoming funds
   ![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/0a14cfa3-0542-45cf-9600-b4f59131e1c6)

**Comment by jakubcolony** [comment]
This will most likely require a multicall motion, please ping me if you're planning on taking this issue to ensure it doesn't impact the expenditures multicall motions

**Comment by jakubcolony** [comment]
Closing this issue in favour of #2913
