### ISSUE TITLE
Loading icon misaligning in transactions tab

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2520]
## Steps to reproduce

1. Perform a transaction using Metamask i.e. not a Dev wallet.
2. Don't sign the transaction.
3. Click on the Pending button to load up the transactions tab in the Userhub.
4. Notice the loader icon pushes the status pill down.

## Expected behaviour

* We should add this loader into the Pending status pill.

## Actual behaviour

* The loader is just added ad hocly in the UI, resulting in the UI being disjointed.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/26a99824-28e1-46c4-a826-f9aa86d6e6ef)

**Comment by codeseker** [comment]
working on this issue

**Comment by rdig** [comment]
Hey @codeseker thank you for your PR

We'll give it a review then merge it

**Comment by iamsamgibbs** [comment]
Reassigning this to @Nortsova as the current open PR has stalled.
