### ISSUE TITLE
[Multi-sig] feat: implement filtering over multi sig motions in the action list

### ISSUE THREAD

**Issue by bassgeta** [JoinColony/colonyCDapp#2523]
### Story

As a user viewing a colony I want to be able to filter multi sig motions according to their status.

### Description

The statuses:
```
- Open
    - The action has been created and has not met the required number of approvals.
    - The action has met the required number of approvals, but has not been finalized.
- Passed
    - The action has met the required number of approvals, and has been finalized.
- Rejected
    - The action was rejected or cancelled.
```

It may prove tricky to filter them properly, so this should be tackled after the groundwork has been laid by #2522 
Filtering will be done entirely on the UI, similar to how we handle motion states.

Open - `isExecuted` and `isRejected` are false
Passed - `isExecuted` is true, `hasActionCompleted` is true
Rejected - `isRejected` is true

### This issue is complete when...

- [ ] Users can filter over all motion types and get relevant multi-sig results

**Comment by bassgeta** [comment]
Mea culpa, I forgot to update this issue before handing it over. Luckily, the changes required are simpler than the previous ones

The correct requirements are:
```
- Open
    - The action has been created and has not met the required number of approvals.
    - The action has met the required number of approvals, but has not been finalized.
- Passed
    - The action has met the required number of approvals, and has been finalized.
- Rejected
    - The action was rejected or cancelled.
```

Instead of the old ones:
```
- Approval
    - The action has been created and has not met the required number of approvals.
- Rejection
    - The action has been created and has not met the required number of approvals and a rejection has also been triggered, but has also not met the required number of approvals.
- Finalize
    - The action has met the required number of approvals, but has not been finalized.
- Passed
    - The action has met the required number of approvals, and has been finalized.
- Failed
    - The action was rejected.
```

I've updated the issue, but dropping a comment here for posterity :)

**Comment by joanna-pagepro** [comment]
@bassgeta I don't see `isSuccess` field in `action.multiSigData` or anywhere else in the `action` object. Can you check this and update the description if needed?

**Comment by bassgeta** [comment]
> @bassgeta I don't see `isSuccess` field in `action.multiSigData` or anywhere else in the `action` object. Can you check this and update the description if needed?

I've updated it, we have renamed the field into `hasActionCompleted` so it's more verbose, we can use that one instead of `isSuccess`
