### ISSUE TITLE
Refactor `GasStation` to support arbitrary statuses

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#253]
We want to be able to add arbitrary statuses (avoiding the word "messages", since it's already used in that context) to the Gas Station popover. Those should be controlled from within sagas. Currently, the Gas Station only shows wallet transactions / messages

![image](https://user-images.githubusercontent.com/112586815/217378270-802b4809-457c-4f08-ab1e-653cdc44b7b1.png)

**Comment by rdig** [comment]
@jakubcolony can you refresh my memory on why we wanted this? As it feels like this is not relevant anymore, but it might just be me forgetting
