### ISSUE TITLE
Agreements missing on agreements page

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2530]
## Steps to reproduce

Seemingly, no other way to reproduce but to create agreements and see if it happens again.
You can check the Betacolony here - https://app.colony.io/beta/agreements - and you will see only one agreement, which I have just created. But in the past another agreement has been created and the transaction can be loaded manually, but, does not appear in the list.

This is the working one: https://app.colony.io/beta/agreements?tx=0xd7b88d1fccfa50a1ba532c2ae9c66bc3226d2994343aef931e7bcd8a5ef69434

This is the missing agreement: https://app.colony.io/beta/agreements?tx=0xb68baa890a1a6a0eb451b13c759b0691831dd95436c9ceab58038b901b7001e2

## Expected behaviour

* All agreements that have passed the staking threshold, should appear on the agreements page.
* At the same time, we would like to ensure that Agreements appear in the activity feed.
* It would also be good if these worked off of subscriptions, so new ones show up without having to reload.

## Actual behaviour

* Agreements that have passed are not showing on the agreements page.

    #### Showing only one on the page
    ![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/853bd541-81ae-4a09-83ef-8ab4f2d6c6da)

  #### Missing one can be found and loaded manually
  ![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/abfd3021-0824-4e65-a3cf-f3f55d750c3e)

**Comment by arrenv** [comment]
@mmioana As an addition to reviewing and fixing the feed on the Agreements page. We would like to also ensure that Agreements appear in the Activity feed page as well.

**Comment by mmioana** [comment]
@arrenv do we want to show all agreements in the Activity feed or only the ones that have passed?

**Comment by arrenv** [comment]
> @arrenv do we want to show all agreements in the Activity feed or only the ones that have passed?

Can we please show all agreements, excluding ones that are below the 10% staking threshold.

**Comment by mmioana** [comment]
Sure, @arrenv 
Also one question regarding your screenshot. I noticed the subtitle that says "Decision by arren" and "Decision" Action Type
![image](https://github.com/user-attachments/assets/ff089745-12e2-4845-b9b7-d2bed7eb7bf8)
Should these be updated to "Agreement by {user}" and "Agreement"?

**Comment by arrenv** [comment]
@mmioana Good pickup, yes, it would be great if this was "Agreement by ...". Thank you.
