### ISSUE TITLE
Loading Agreements page has failed queries

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2531]
## Steps to reproduce

This was discovered in this colony in production: https://app.colony.io/boston/agreements, I have not been able to replicate on other colonies yet.

1. Go to the agreeements page.
2. Open up the Network tab in your browser dev tools.
3. Check the failed queries for `GetColonyContributor`.
4. Wait ~30 secs for them to load.

Something is failing well, as in, it does eventually load, but perhaps the issue can be looked into and resolved.

The latest agreement is loading quickly and fine on the dashboard.

## Expected behaviour

* Queries should not fail multiple times before working.

## Actual behaviour

* Loading agreements takes a long time with 3 failed queries.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/2c2c6134-a6e0-46d2-abb1-6d28c38556f3)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/37a7ec41-3125-4c4c-9c9c-e314ca038554)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/772049ff-df83-4f14-a87b-e4248a7c85f7)

**Comment by iamsamgibbs** [comment]
I'm going to close this out, I have been unable to recreate this locally. @arrenv has also re-tested and confirmed this is no longer occurring on production, so has possibly been resolved by a recent PR (most likely #2814 )
