### ISSUE TITLE
Missing details for creating an advanced payment in the Stakes tab

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2536]
## Steps to reproduce

1. Ensure you have the Staking advanced payments extension enabled.
2. Create an advanced payment (Payment builder) action.
3. Use the staking decision method to create it.
4. Check the action details in the Userhub Stakes tab.

This PR https://github.com/JoinColony/colonyCDapp/pull/2340 adds the UI to be able to create Advanced payments using staking. Although, you should be able to replicate with the pseudo UI on this feature branch [feat/advanced-payments-ui](https://github.com/JoinColony/colonyCDapp/tree/feat/advanced-payments-ui)

## Expected behaviour

* The title of the action should show in the Stakes tab for an expenditure created using staking.
* The metadata of the action should include the action details.
* The status pill should be accurate.

## Actual behaviour

* The title of the action is missing.
* The Metadata of the transaction is missing.
* Status pill is missing.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/c33a5239-9ffb-4076-9ffc-2eab7bc8fb51)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/23e22751-9518-4650-b001-94349752aad6)

**Comment by rdig** [comment]
Closed by #2704
