### ISSUE TITLE
The app crashes on mobile view when you view a transaction that's ready to be Finalized

### ISSUE THREAD

**Issue by rumzledz** [JoinColony/colonyCDapp#2538]
## Steps to reproduce

1. Enable the "Reputation weighted" extension and use the "Testing governance" preset
2. Create a Simple Payment and choose the "Reputation" decision method
3. Support the stake and submit the Max staking amount
4. Run the following commands to forward the time:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"evm_increaseTime","params":[3600],"id":1}' localhost:8545
curl -X POST --data '{"jsonrpc":"2.0","method":"evm_mine","params":[],"id":1}' localhost:8545
```
5. Reload the page

## Expected behaviour

The app should not crash.

## Actual behaviour

The app crashes.

![mobile_crash](https://github.com/JoinColony/colonyCDapp/assets/50642296/01287269-6f7d-4834-90b1-92e35f7bd3d6)

## Console errors

![image](https://github.com/JoinColony/colonyCDapp/assets/50642296/1c18d2da-faf3-43ad-b97f-18ddbaafe4e4)

**Comment by melyndav** [comment]
Hey @rumzledz the scope doesn't include fixing the auto fail when you go then attempt to finalize the transaction, does it? 

<img width="461" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f07f4fff-019e-4236-9a8e-381d0f802ae9">
