### ISSUE TITLE
Permissions field not properly reset when changing members in action sidebar

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#2547]
## Steps to reproduce

1. Create a new `Manage permissions` action.
2. Fill out the entire form ensuring you select a member and a permissions type. (Note the table at the bottom providing details on the selected permission).
3. Change the `Member` field to select a different member.

## Expected behaviour

* The new member is selected and the selected permission remains selected.

## Actual behaviour

* The new member is selected and the selected permission visually appears to still be selected in the field, but the value has actually been cleared - the details table at the bottom of the sidebar will disappear and you will get a validation message when attempting to submit the form.

https://github.com/JoinColony/colonyCDapp/assets/34915414/c0aec897-ad82-48e7-bb90-3e1bfd46382e

**Comment by iamsamgibbs** [comment]
Does this need to reassigned to @rumzledz if it is being tackled as part of #2565 ?

**Comment by mmioana** [comment]
Yes, totally @iamsamgibbs! 👍

**Comment by rumzledz** [comment]
This has been addressed as part of #2565. Please refer to the testing steps of that issue for the intended behaviour.

**Comment by rumzledz** [comment]
This has already been dealt with in cycle 195 so I will be removing this from cycle 197 👌
