### ISSUE TITLE
Modal input: active state styling issue

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2550]
## Description

Currently in production, the input fields in both the for the 'Withdraw tokens used for decision making' and 'Activate tokens for decision making' modal have the incorrect styling for the active input state. Both modals are triggered from the 'balance' tab on the user hub.

The PR should make this input consistent with other input fields globally. 

<img width="532" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/ff897b76-e224-4283-b9c0-22cb6fa9f87a">

<img width="521" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/cdb15b2b-2efa-4f36-9c25-986b8c1d9e72">

The correct styling for an input as per Figma: 

Current hover state:
<img width="297" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/31b22f79-9198-4a70-a319-cd207c637449">

Current typing state:
<img width="297" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/6bee3da2-52d8-412a-ac08-cad47d4d72bb">

## Figma
https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-502&t=jq5MBgShUQbmJr33-4

**Comment by Nortsova** [comment]
This issue is related only to Firefox; it works well in Chrome
