### ISSUE TITLE
Permissions decision method showing in Adv. Payments Funding

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2556]
Teamwork task: [Permissions decision method showing in Adv. Payments Funding](https://tw.auroracreation.com/#/tasks/15957134)

## Steps to reproduce

1. Ensure Reputation decision method is active.
2. Create a Payment builder action.
3. Disconnect and switch to a user who does not have permissions.
4. On the funding step, you will be able to select permissions and trigger it, however nothing will happen in the UI.

## Expected behaviour

* You should not have the Permissions decision method as an option in the Adv. Payments funding step if you don't have the relevant permissions, "Funding" on the contracts.

## Actual behaviour

* You are able to select the Permission decision method in the Adv. Payments funding step, even if you don't have any permissions.

![fund-permissions-wrong](https://github.com/JoinColony/colonyCDapp/assets/33682027/376a954e-ca26-4706-8b5b-dce96fdc7626)

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2585
