### ISSUE TITLE
Funding with Reputation timer is missing

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2557]
Teamwork task: [Funding with Reputation timer is missing](https://tw.auroracreation.com/#/tasks/15957130)

## Steps to reproduce

1. Create a Payment builder action.
2. Use Reputation decision method to fund the the payment. (In my case I was connected with an account that did not have permissions or enough reputation).
3. Check the timer that should appear next to the Funding pill, it will be stuck in a loading state.

Note: I tested this yesterday and saw the timer fine, the user had permissions and reputation though. Jakub also reported the same issue. However, in his clip he had both reputation and permissions.

## Expected behaviour

* The timer for Funding with a motion should appear next to the Funding pill.

## Actual behaviour

* The timer next to the Funding stage when Funding with a motion does not appear. I waited over 5 minutes.
* Seems to only work if you reload the page.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/cc6f8ace-e2e5-431c-b874-5a6c44aaec62)

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2585
