### ISSUE TITLE
Funding a motion not auto updating on failure

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2561]
Teamwork task: [Funding a motion not auto updating on failure](https://tw.auroracreation.com/#/tasks/15957129)

## Steps to reproduce

1. Create a Payment builder action.
2. Use Reputation decision method to fund the the payment.
3. Don't stake the payment and let it fail.
4. Notice that the UI will not auto-update, you can still stake (but it will fail), and you need to reload to see it change and be able to try funding again.

## Expected behaviour

* The motion should fail and update the UI if the motion fails, so that it can be tried again.

## Actual behaviour

* The UI is stuck in the same state even if the timer has run out and the motion failed.
* The only way to fix it and try to fund again is to reload the page.

![not-auto-updating-failed](https://github.com/JoinColony/colonyCDapp/assets/33682027/d421fa75-7a19-4e36-9ac6-d3863dfffaf4)

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2585
