### ISSUE TITLE
Issue when returning to Funding step, with motion vote to fund

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2562]
Teamwork task: [Issue when returning to Funding step, with motion vote to fund](https://tw.auroracreation.com/#/tasks/15957131)

## Steps to reproduce

1. Ensure Reputation decision method is active.
2. Create a Payment builder action.
3. Trigger a vote, but staking both in Oppose and Support fully.
4. Vote either way, although, I voted in Support.
5. Reveal, then Finalize.
6. You will quickly get a flash to be able to claim your stake if you are able to claim as the user.
7. You will then move to the Release step.
8. Click on the previous Funding step.
9. The details will be incorrect, there are two cards, you won't see your stake, or be able to claim your stake.

Note: there is also a ridiculous amount of requests that resulted in the app crashing and causing a 404.

## Expected behaviour

* Returning to the Funding step should show the the correct details.
* Returning to the Funding step should allow you to claim, if you have a stake or reward and have not claimed yet.
* Finalizing should try and return users stakes in one transaction, if possible.
* There should not be so many requests happening.

## Actual behaviour

* The details in the Funding step are incorrect.
* You are not able to claim funds as someone who has funds to claim.
* There are a a lot of requests that causes the app to crash.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/c1ba7ec5-28e4-4cab-b902-0fdd8f2f514b)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/dcd19a35-b0bc-42a9-a8ff-2b63bb1e6c47)

**Comment by CzarekDryl** [comment]
@arrenv I've fixed UI issue, but I can't reproduce bug with claiming. The action is fetched every few seconds, that's why there are so many requests, I'm not sure if we can do anything about it. Maybe someone from the colony team could take a look at it?

https://github.com/JoinColony/colonyCDapp/assets/76940796/36e55132-2287-41ad-bd67-47ec60dc39f3

**Comment by arrenv** [comment]
@CzarekDryl Thank you for taking a look.
@jakubcolony You also noticed the number of requests, do you have any thoughts on this at all?

**Comment by AdrianDudko** [comment]
Closd by https://github.com/JoinColony/colonyCDapp/pull/2585
