### ISSUE TITLE
Missing translation and metadata in UserHub Stakes tab

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2564]
## Steps to reproduce

1. Create a Payment builder action.
2. Ensuring you have Reputation decision method enabled.
3. Fund the payment using the Reputation decision method.
4. Check the transaction in the Transactions tab of the UserHub.

## Expected behaviour

* The title should be transaction's custom title.
* The description should be the custom action title with a fallback to the action metadata.
* All details should be correct.
* It should either:
          * Link to the relevant Advanced payment, or
          * Should link to the "linked" motion view as of the design here - https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?node-id=24280-198587&t=21FkwrMm6ANcL8LC-4, or
          * Should not be linked and clickable.

## Actual behaviour

* You see a missing translation text.
* You see a generic metadata link.
* You can click on the transaction.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/addac129-7431-43d0-8a19-4035e70fe67b)

**Comment by jakubcolony** [comment]
@arrenv in case of `FUND_EXPENDITURE_MOTION`, there is no custom title available. What should we show instead?

Could you also provide the copy for the metadata for that transaction?

**Comment by arrenv** [comment]
@jakubcolony I was hoping it could be the "Custom title" of the expenditure being funded. And, for the second line it would be metadata line, however, maybe that should be "Funding the payment"

If that is not possible, then we can use more general text for the title i.e. "Funding payment". And for the second line use, "Using Reputation decision method"

**Comment by rdig** [comment]
Closed by #2772
