### ISSUE TITLE
The "Select member" field tooltip is not fully visible on the Payment Builder form

### ISSUE THREAD

**Issue by rumzledz** [JoinColony/colonyCDapp#2580]
## Steps to reproduce

1. Open the Action Form and set it to Payment Builder
2. Hover your mouse pointer over the "Select member" field

## Expected behaviour

The tooltip is fully visible.

## Actual behaviour

The tooltip is not fully visible.

![Screenshot 2024-06-19 at 16 31 30](https://github.com/JoinColony/colonyCDapp/assets/50642296/9638bef6-507d-445d-9e57-f897f7b805e1)

**Comment by melyndav** [comment]
Hey @rumzledz I raised for the tooltip to be removed on all 'select member' fields. It shouldn't be there at all, and I believe it's already been handled in another PR? I'm not sure the exact PR number to quote.

**Comment by rumzledz** [comment]
Apologies @melyndav !! I shall close this now!
