### ISSUE TITLE
Make `chainId` an `Int` in all schemas (to be consistent).

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyCDapp#2615]
This is only so that we won't forget.

**Comment by rdig** [comment]
Why is this necessary? 

We specifically made this change to accommodate arbitrum https://github.com/JoinColony/colonyCDapp/pull/2293

**Comment by chmanie** [comment]
Oh sorry, then it should be String everywhere. Right now it's number sometimes and String in other cases.
I don't have a preference there as long as it's consistent
