### ISSUE TITLE
Clicking on Oppose to quickly breaks motions flow

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2640]
Teamwork task: [Clicking on Oppose to quickly breaks motions flow](https://tw.auroracreation.com/#/tasks/15975060)

## Steps to reproduce

1. Create a new action with the Reputation decision method.
2. Start with 100% staking the "Support" the action, before the transactions finish, click on the "Oppose" option.
3. The "Support" transactions should finish, now, try to stake in "Oppose".
4. You will be locked in the UI, with no ability to switch to "Support" and no option to stake in "Oppose".
5. You have close the action and reopen it to get it to work again.

## Expected behaviour

* You should not get blocked in the UI when switching between staking options.
* One option would be to disable these tabs, if there is an active staking transaction.

## Actual behaviour

* The ability to stake is locked if you switch staking options on a motion in the middle of 100% staking a transaction.

![locked-supporting](https://github.com/JoinColony/colonyCDapp/assets/33682027/b8172df6-032a-40c9-a62a-e188bf1b29d3)

**Comment by CzarekDryl** [comment]
@arrenv I've tested it on master branch like 20 times and it was working every time. Could you please test it once more on master branch? 

https://github.com/JoinColony/colonyCDapp/assets/76940796/344cc280-30c3-4800-a2d4-52b43f1fc361

**Comment by arrenv** [comment]
@CzarekDryl I can see now that this has been resolved by this PR from last month - https://github.com/JoinColony/colonyCDapp/pull/2490

Looks like it had just not made it into the few branches I was testing last week.

Closing now.
