### ISSUE TITLE
Payment amount value regression for motions

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2642]
## Steps to reproduce

1. Create a new Simple payment action.
2. Enter an easy to track value, e.g. 1
3. Select the Reputation decision method (permissions works fine)
4. Create the payment.
5. Notice that on the created screen, the amount will now be 1.0101, however, it should be 1.

This was previously fixed in this PR - https://github.com/JoinColony/colonyCDapp/pull/1388

## Expected behaviour

* The amount should show the amount being paid to the recipient, excluding the network fee.
- It should use the live network fee while created or during the motion, then the payments stored network fee after successful payment.

## Actual behaviour

* The total payout shows with the amount being paid to the recipient in addition to the network fee.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/f7c1a683-a956-4c7f-b5aa-bbe7319eacce)

**Comment by arrenv** [comment]
For whomever picks this up, we would like to include the network fee as a separate field and figured this issue may be a good chance to tackle that. So, please reach out in regards to designs and spec for it if you feel it is suitable to include it.

**Comment by iamsamgibbs** [comment]
Temporarily adding the blocked label - waiting on design confirmation - can hopefully pick it back up on Thursday / Friday
