### ISSUE TITLE
GraphQL codegen doesn't pick up changes in `schema.graphql`

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#265]
The codegen script runs alongside the `amplify` image and is configured to watch for any changes to `*.graphql` files but it doesn't recognise changes to `schema.graphql` (since the schema is only fetched once at the beginning).
If any changes are made to the schema, the `amplify` image has to be restarted which isn't very convenient.

**Comment by willm30** [comment]
Sounds fine to me, mind if I close?
