### ISSUE TITLE
Crypto-to-fiat: User Hub Bank details Updates

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2659]
## Description

This issue covers only the bank details and corresponding modals.

## Bank details

- [ ] Font weight for 'Bank, address and currency information' title should have a 500 font weight. 

<img width="332" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/b193ee92-9ed0-49e4-a18a-61b21b671456">

- [ ] Styling of the not started pill should match Figma and include the icon and correct colour tokens.

<img width="131" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/cd1fd2b3-64cd-4a7a-ac9a-f846e097c68b">

- [ ] When I add my bank details, completing all the modal steps. The UI does not update even after receiving the toast confirmation. And I can go ahead and select 'Add details' again with a blank modal. 

<img width="1304" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/70d13bdf-9999-4fa7-aebd-4e4b8dbe6822">

- [ ] After I refresh after completing the modal steps, the details do not show at all in the UI so I'm unable to check the completed state along with pills etc. 

<img width="1305" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/0477dab8-5725-488c-a74e-b7c637628d91">

### **All modals** 

- [ ] Padding between the 'X' close and the step pills should match Figma. 

<img width="132" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/5ed6dd6f-1fae-41e9-a991-bdc235217ebd">

- [ ] All heading sizes do not match Figma sizing

<img width="270" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/9eca105e-2f2d-4f32-af6f-a8ad7962deb8">

- [ ] All subheadings sizes and font colours do not match Figma

<img width="450" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/65635091-f247-47f1-b228-d2b6c7f24988">

- [ ] Bottom CTA's should have correct top and bottom padding that match Figma

<img width="557" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/dd128f60-fd9d-4834-97fe-8f06bae22139">

### **Personal details modal** 

- [ ] Country dropdown should match component styling

<img width="487" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/99c6cfa8-004b-4e81-9c80-8c70a0bc5ec4">

- [ ] All error states should match Figma copy and also the first name should be a required field

<img width="470" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/b31e9ff3-b3f3-484b-a6f0-e23cc84aeb67">

### **Terms modal**

- [ ] Can we slightly increase the modal height so we can disable the scrollbar inside the Bridge widget?

<img width="555" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/c32a5538-723d-462d-a9ef-7187f07aaf21">

### **Contact details modal**

- [ ] Address is spelled incorrectly

<img width="116" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/394f6fa5-1070-4ac2-bb93-94decf1d54e1">

- [ ] Spacing between the address section doesn't align with Figma

<img width="467" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/14e86f7f-6f83-44a9-9e0c-eff206bb1bcc">

- [ ] Is it possible to format the input for the birthdate so the - are added when the user types to help avoid validation errors?

<img width="470" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/5a81a2f3-8a2c-4b7a-b9a9-ad01aae60bf9">

- [ ] The date field doesn't throw an error when the date format is left without the - format

<img width="468" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/b1544da5-b3cd-4b05-9418-43d3ed79bdf4">

- [ ] All fields are required in this step which isn't currently present. 

<img width="466" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f3e66308-8a06-4aab-a3f5-e7f97c3bd4bb">

- [ ] State field when shown doesn't have the correct styling.

<img width="466" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/01704357-60b5-40b0-9a87-3fc993d0a0cd">

- [ ] Error states have a number of styling issues including overlapping the CTA's.

<img width="462" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/7cddece3-5837-48f2-90fa-8edc8c6a66a5">

### **Bank details modal**

- [ ] The ability to go back to the previous step is missing.

<img width="517" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/9069a291-60b5-49ba-819e-9f0c466af06f">

- [ ] Payout currency field should use the existing dropdown component styling with the right placeholder copy. 

<img width="501" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f2cdc66c-e4cd-46e4-8f8a-d407c4eff7ab">

- [ ] Correct padding between inputs need to be added.

<img width="486" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/6ad537f9-d6a0-4954-9372-6fcd9ba129c1">

- [ ] If EU is selected as the currency, the country input needs the right placeholder label to inform the user what the field is for.

<img width="477" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/57a4ea46-97ad-4c5b-8407-28c3df069076">

- [ ] All errors should have the correct copy.

<img width="486" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/1037839d-26a8-4eba-9b98-910b22c64684">

- [ ] I can input one letter into the full name, and it's accepted. Is there a min char we need as per the API?

<img width="465" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/260ba2bf-7039-4c79-b12d-e221b1dcee43">

Same with the bank. I'm guessing there are no one letter banks.

<img width="506" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/cbb2e784-e738-4747-8e39-c36debcbe075">

**Comment by jakubcolony** [comment]
I believe this has now been resolved by #2741 and other PRs, feel free to reopen if that's not the case @melyndav

**Comment by melyndav** [comment]
> I believe this has now been resolved by #2741 and other PRs, feel free to reopen if that's not the case @melyndav

Thanks @jakubcolony 👍
