### ISSUE TITLE
Crypto-to-fiat: Drains history table UI fixes

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2662]
## Description

This issue covers the transaction table that requires some minor adjustments to align it with other table styling. I haven't been able to test the default state yet, so more issues my come with this. . 

- [ ] The status arrow should show by default, it's currently not showing, and the user do not know it's available for sorting. The table should stay by default sorted by date, so no change here. 

<img width="146" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f0c957a3-0d7b-418f-99f6-4df72a790ea1">

- [ ] Mobile table styling should match Figma designs on mobile

**Current**
![Screenshot 2024-07-29 at 12 24 20](https://github.com/user-attachments/assets/8fa675b4-9ea6-4e1a-9800-a0d4d2446bef)
**Figma**
![Screenshot 2024-07-29 at 13 57 19](https://github.com/user-attachments/assets/b94f93c6-8369-4ae3-b190-cd43b3aa4659)

**Comment by rumzledz** [comment]
@melyndav number 6 might be problematic because I don't think our tables are configured to show an arrow for the column that's not responsible for the current sort order

**Comment by jakubcolony** [comment]
Hi @melyndav, I edited the issue to remove the following points that have already been resolved by other PRs:

- [x] Amount column styling needs to match Figma with a weight and colour change.

<img width="140" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/4af8ab4c-ba95-495c-944e-8e034dfe4a8e">
 
- [x] Date column text should match Figma.

<img width="156" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/ba7d21e4-01f8-40d1-87d1-44898059efe0">


- [x] Status pills font should match Figma (these are existing components, so these can be pulled from other tables).

<img width="134" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/d38b5f6c-7815-4874-81ce-3e2ea4d45c86">

- [x] Can we add a text-blue-400 hover state to the external links?
<img width="167" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/ac908e42-875b-4f73-bae9-6d72f8eb55e5">

**Comment by melyndav** [comment]
Thanks for updating @jakubcolony 👍

**Comment by rdig** [comment]
@Nortsova is this similar to #2695 ? If so, it might be a good idea to increase the scope here, and fix **all** tables, not just the one in C2F
