### ISSUE TITLE
Hackathon: New user hub tab UI/UX Updates

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2665]
## Description

As part of the hackathon, the following updates are required to the new user hub functionality. As I can't complete a transaction, I'm unable to see the completed states etc so will test these at a later date. 

- [ ] When selecting the Max option, the amount doesn't correspond with the balance shown.

<img width="438" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/1ec560e5-797e-4dbe-b6ef-7fb55cef9406">

- [ ] Hover state is missing from the Max text button (should be text-blue-300).
<img width="58" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/7372272d-dafa-408a-9ec1-7a47fea9c425">

- [ ] Font weight of both values should match Figma

<img width="166" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/e4004b59-e87c-4906-a50f-b91648972caf">

- [ ] Correct currency icons are missing for both USDC and EU etc.

<img width="76" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/04a5d5b1-29b6-43c7-9813-124658259a6e">
 
- [ ] All validation variables is missing

<img width="434" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/09d5116e-982c-4b3a-ab6e-b625eb876155">

- [ ] Tooltips are missing on the transaction fee tables

<img width="36" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/4cad01c1-749b-4b96-9c2e-1330c880c47b">

- [ ] Transaction fee text should be a lighter gray token to match Figma

<img width="127" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/b638e7ba-fc04-4d87-b762-795a47b4b9e3">

**Comment by jakubcolony** [comment]
> I'm sure this is a known issue, but there is no checking if the validation steps have been completed as I have not completed validation but can go straight into using the feature.

@melyndav I extracted the above into its own issue - #2953

**Comment by rdig** [comment]
@mmioana can we get an estimate on this for the remaining work you're doing in #2980 ?
