### ISSUE TITLE
Fix token icon in TokenPopover

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2667]
## Steps to reproduce

1. Go to a colony Balances page.
2. Click on the native token for the colony.
3. Notice the blue verification icon next to the token name, where there should be a lock icon if the token is locked.

## Expected behaviour

* The icon should actually be the lock icon, if the token is locked.

## Actual behaviour

* The lock icon is shown as a verified icon in the TokenPopover.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/388094c4-83f2-4d85-a268-afcf29b094e1)

**Comment by rdig** [comment]
Closed by #2649
