### ISSUE TITLE
Manage Permissions completed action screen shows incorrect permissions

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#2672]
## Steps to reproduce

1. Enable the reputation weighting extension.
2. Create a manage permissions action. Assign a user payer permissions in general via permissions.
3. Create a second manage permissions action. Select the same user and assign admin permissions in general. This time select the reputation decision method.

## Expected behaviour

* The motion details show the correct permissions to be assigned.

## Actual behaviour

* The motion details show only the change in permissions. (i.e. going from payer to admin only enables one extra permission)

<img width="1064" alt="Screenshot 2024-07-08 at 15 35 49" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/2c8f9873-0baf-4157-82b5-98553bb590ca">

## Suggestions

For permissions we store a historic role model, we may need to do something similar for this or create a pending permission change model or something.

(The same will need to be implemented for multi-sig - maybe check with Arren how important this fix is for master and whether all the work can just be done on the multi-sig branch)

**Comment by iamsamgibbs** [comment]
Just a note to say this is still an issue on master even after multi-sig has been merged:

<img width="1065" alt="Screenshot 2024-09-10 at 10 57 17" src="https://github.com/user-attachments/assets/82b09b44-3206-4939-a965-55b8a1244aec">

**Comment by rdig** [comment]
@iamsamgibbs do you want this pulled into the current cycle ?

**Comment by iamsamgibbs** [comment]
Sure! It isn't necessarily urgent, it has been an existing bug in the app for a while now, but definitely worth fixing it up. I thought it might have been tackled as part of the multi-sig work as I think it does work correctly with multi-sig motions as far as I can remember.
