### ISSUE TITLE
Token picker in Manage tokens action should hide existing tokens

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2673]
Teamwork task: [Token picker in Manage tokens action should hide existing tokens](https://tw.auroracreation.com/#/tasks/15984536)

### Description

With the recent Manage tokens action updates (https://github.com/JoinColony/colonyCDapp/pull/2396), we now have the great addition of being able to provide users with a list of known tokens in the dropdown list, making it easier for users to add the tokens they want to support.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/d92e8bf8-573a-4c57-b463-6388205f5b19)

We would like to make an improvement to this feature to improve the user experience even more. Currently, when you have a token already in the list, you can select that token again, which, results in a duplicate token error. Additionally, it creates a more cluttered list of tokens to choose from.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/53cd7b9a-0de9-4a2a-be3b-751f1a1db942)

So, as an enhancement, we would like to make sure that if the token already exists in the table, then it should not appear in the dropdown list as a duplicate. We will need to ensure that this filtering factors in the adding and removing of tokens from the table.

Additionally, if you do happen to add a duplicate token regardless, then you are not able to change that token and instead have to remove the row first.

### Design

Showing the "USDT for Local Development" not in the drop down list, as it is already in the table.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/dc3655f9-9d80-4853-ad96-65ddcfb99271)

### This issue is complete when...

- [x] The token picker in Manage tokens action should hide tokens already in the table.
- [x] If there is a duplicate token, you should be able to open the token picker again, rather then having to remove the row first.

**Comment by AdrianDudko** [comment]
Closed with https://github.com/JoinColony/colonyCDapp/pull/2692
