### ISSUE TITLE
[MASTER] Table pagination is broken across all responsive sizes 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2695]
## Description

On master, all tables have broken pagination. The pagination should be displayed inside the table container and not outside. It is showing across desktop, tablet and mobile. Looks like it was introduced in PR #2583.

**Dashboard:**

<img width="841" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/b187a017-3066-436b-babb-3587c81c9dad">

**Activity feed:** 

<img width="1329" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/e7adccf4-0e95-4f43-b2ba-34a03c5f10a6">

**Responsive:**

<img width="696" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/6e782665-e697-419f-b322-d80ceed65ac0">

### Figma

What it should be as the Figma design system component: https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1776-8565&t=JazItdUIdCedG0rv-4

**Comment by rdig** [comment]
Sadly not, it just focused on the C2F Transfer History table, so it just fixed "part of" it.

We'll still keep it open until it's fixed

**Comment by melyndav** [comment]
Thanks, @rdig! If we can remember to add it to a cycle soon-ish that would be great. As it's still broken and looking not the greatest but more for the sake of it being lost well down the issue line given it was raised in July.

However, did raise an issue about the pagination here - https://github.com/JoinColony/colonyCDapp/issues/3633

I wonder if they can be bundled?! I'll leave it with you ☺️

**Comment by melyndav** [comment]
Thanks for this fix @mmioana 🙌
