### ISSUE TITLE
[Multi-sig] Mobile scrollable modals don't have bottom padding

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#2698]
## Steps to reproduce

1. Try to open a filter & sort modal
<img width="301" alt="Screenshot 2024-07-12 at 08 21 10" src="https://github.com/user-attachments/assets/708c8877-fd59-4fac-8e50-8404a0a0b3a5">

<img width="296" alt="Screenshot 2024-07-12 at 12 07 35" src="https://github.com/user-attachments/assets/c4d16697-7416-4ac7-9488-c28a19de306e">

2. The content of the modal scrolls from the very bottom border of the modal

## Expected behaviour

* The modal should show a bottom padding when content is scrollable

## Actual behaviour

* The modal has no bottom padding when content is scrollable

## Suggestions 

* You can use the `withPaddingBottom` when instantiating a Modal component. However content must be updated to not have an extra bottom padding

**Comment by rdig** [comment]
@bassgeta is this still relevant?
