### ISSUE TITLE
Skeleton loader for Split payment percentage

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2703]
Teamwork task: [Skeleton loader for Split payment percentage](https://tw.auroracreation.com/#/tasks/15999718)

## Steps to reproduce

1. Create a Split payment using the Reputation distribution method.
2. Add a few recipients.
3. Create the payment.
4. Notice the loading state of the recipients table.

This PR https://github.com/JoinColony/colonyCDapp/pull/2396 will likely need to be merged first.

## Expected behaviour

* There should be a skeleton loader on the percentage field.

## Actual behaviour

* There is no skeleton loader on the percentage field of the table. Instead it is showing as 0% while loading.

![image](https://github.com/user-attachments/assets/439a1aef-fe40-4bdc-8fd9-d33023ebc027)

**Comment by joanna-pagepro** [comment]
@arrenv I think that this is already fixed. Can you check? (feat/advanced-payments-ui)

**Comment by AdrianDudko** [comment]
@arrenv let me know if that's safe to close this :)

**Comment by arrenv** [comment]
Yep, closing now.
