### ISSUE TITLE
Button loading on Staking Advanced payments

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2705]
Teamwork task: [Button loading on Staking Advanced payments](https://tw.auroracreation.com/#/tasks/15999719)

## Steps to reproduce

1. Make sure you have Staking advanced payments extension enabled.
2. Create a Split payment with Staking decision method.
3. In the staking modal click the "Create payment" button and notice the loader.

## Expected behaviour

* The buttons should be consistent with other button loading states. [Figma design](https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1801-431&t=d3kZ7dB3nz9kqDTn-4)

![image](https://github.com/user-attachments/assets/f5731cb7-9aac-45eb-a8b4-d57e84ecfb06)

## Actual behaviour

* The loading state of the button shows a spinner.

![image](https://github.com/user-attachments/assets/6389cbac-dd14-4487-afbd-93c7db9d0fe5)

**Comment by AdrianDudko** [comment]
Fixed by https://github.com/JoinColony/colonyCDapp/pull/2732
