### ISSUE TITLE
bug: can't finalize a simple payment voting reputation motion

### ISSUE THREAD

**Issue by bassgeta** [JoinColony/colonyCDapp#2714]
## Steps to reproduce

1. Run your dev env, populate it
2. Install the voting reputation extension
3. Go to create a simple payment motion from any team to anybody
4. Fully support it and forward the time by 5 minutes
5. Try to finalize the motion
![image](https://github.com/user-attachments/assets/96312acd-a493-4576-bff9-9dcbdd5bb2ef)
6. The transaction throws a generic error saying `Transaction has failed`
![image](https://github.com/user-attachments/assets/2e2077be-b1dd-40ca-ade6-a9b4e21af5df)

## Expected behaviour

The motion should finalize and the payout should complete. The OneTxPayment extension is working with this as a multi-sig motion, if it's of any help.

## Actual behaviour

The transaction errors out.

**Comment by area** [comment]
Spoken to Kerry about this, but this is because the gas supplied is hard-coded (via the block ingestor) and is not enough.

**Comment by rdig** [comment]
Closing in favor of #2572
