### ISSUE TITLE
Staking Payment claim period error copy is misleading

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyCDapp#2728]
### Issue

Error message claiming factional zero is less then zero _(Ie: `0.1 < 0`)_

### Reproduce
- Install (if not already installed) the Staking Payment Extension
- Create a new staking payment (via Advanced Payments)
- Ensure you've selected the "Staking" decision method
- Enter a "zero fractional" value for the claim delay (`0.1`, `0.2`, etc)

### Screenshot

![Screenshot from 2024-07-17 20-44-34](https://github.com/user-attachments/assets/43800bd4-2a4e-4ef8-a5d1-4289850bf39a)

### Resolution

@arrenv might want to chime in regarding specs, and regarding if we actually want to allow fraction hour values to be entered, but:
- if we do, fix this to allow factional values
- if we don't update the error copy to reflect the actual issue at play

**Comment by arrenv** [comment]
@rdig Where are you seeing this, this should have been resolved by this PR that was merged last week - https://github.com/JoinColony/colonyCDapp/pull/2435

**Comment by rdig** [comment]
On #2704 but perhaps it might not have been rebased in while?

@davecreaser please rebase your #2704 all I'll retest

**Comment by davecreaser** [comment]
@rdig I've rebased #2407, but only onto the advanced-payments-ui branch (since that's where this work is needed). I don't think #2435 is on that branch yet though, and I'm not sure what the rebasing schedule is for that branch as it's mostly used by PagePro.

**Comment by davecreaser** [comment]
@rdig Rebased, and indeed the issue has already been fixed so this ticket can be closed :)
<img width="691" alt="Screenshot 2024-07-19 at 16 04 48" src="https://github.com/user-attachments/assets/8b93c7bb-faf0-4feb-917a-ab6ef17c590a">

**Comment by rdig** [comment]
Very nice. Glad it got resolved. Thanks for taking care of this.
