### ISSUE TITLE
Remove double modals for verification and KYC

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2729]
## Steps to reproduce

1. Navigate to the users account page `/account/crypto-to-fiat`
2. Click the "Start KYC" page.
3. Complete your personal details and continue.
4. Accept the terms.
5. It will now open the KYC modal over the other modal.

## Expected behaviour

* We should only have one modal level, i.e. the background modal should close when the KYC modal opens.
* The "Start KYC" button should be conditional, opening up the user to the step they are up to in the process.
    - The text of the button should change to "Continue KYC" if they are past the first step.
    ![image](https://github.com/user-attachments/assets/dff37940-daea-4040-a5cd-02b403394d48)

## Actual behaviour

* The KYC modal loads over the top of the previous modal.

![image](https://github.com/user-attachments/assets/706a4eb8-60cd-41ef-a108-1840bd246a3e)

**Comment by jakubcolony** [comment]
It's fixed in the `hackathon` branch, just waiting for a prod deployment
