### ISSUE TITLE
Staged Payments Extension Page

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2735]
### Story

- As a USER, I would like to be able to create Staged payments.
- As a USER, I would like to be able to install, deprecate and uninstall the Staged payment extension.
- As a USER, I would like to see know what a Staged payment is and what is it used for.
- As a USER, I would like to be able to manage the Staged payment extension.

### Description

Users will be able to create Staged payments as a new action type. There are no custom settings for this extension, it simply allows for stage payment actions to function.

### Design

Extension details page - https://www.figma.com/design/6qONTE1uD9K4yoIbfFzidg/Extensions?node-id=1908-20779&t=0erzmsIl24U0qnXq-4

![image](https://github.com/user-attachments/assets/3a0df359-6e00-4ce5-a8ec-0c7fedfbd81d)

## Acceptance Criteria

- **General requirements**
    - Should be in alignment with desktop/tablet/mobile design from Designs.
    - Should use existing components and styles where possible for consistency.

- **Extension details page:**
    - The extension icon, images, and name are correct as of the design.
    - Extension type:
        - Payments.
    - Overview:
        - Description
            
            The Staged Payments extension enhances the payment options for your team by introducing a flexible, milestone-based payment option. This feature allows payments to be segmented into distinct milestones, each of which can be released independently upon hitting or achieving those milestones.
            
            This method not only ensures better management of project funds and accountability but also provides increased security and confidence for both contributors and payment creators.
            
            Suitable for various scenarios such as project-based payments, periodic salary disbursements, budgeting, and target-based payments, making it a valuable addition to any team’s financial management toolkit.
            
        - How the extension works
            - User creates a “Staged payment” action.
            - User can add the various stages of the payments as “Milestones” with a description and token amount for each milestone.
            - Getting approval and funding the payment is the same as other Advanced payment actions where you go through a Review and Funding step. The difference is in the Release step.
            - Each of the individual milestones in the payment can be released separately at any time, with the intention that they are released only when those milestones have been achieved.
            - If some of the milestone are not delivered, that payment can be canceled and those undelivered milestones will remain unpaid.
        - Useful for:
            - Making payments upon delivery of agreed project milestones.
            - Creating periodic payments, where pre-approved funds can be released as agreed.
            - Target based payments, where funds can be paid when a target has been achieved.
        - Supporting guides and documentation
            - Staged Payments - https://help.colony.io/en/articles/9626927-staged-payments
    - Extension details:
        - Developer: Colony
        - Permission: “Payer” or “Arbitration” custom permissions.

- **Extension settings**
    - There are no extension settings.

- **Installation**
    - Users with the “Root” permissions can install the extension.
    - After installing, the extension will initialise right away and the status will change to “Enabled”.

- **Deprecation/re-enabling**
    - Users with the “Root” permissions can deprecate/re-enable the extension.
    - When deprecated, all active Staged payments can continue.
    - No new Staged payments can be created.

- **Uninstall**
    - Users with the “Root” permissions can uninstall the extension.
    - Uninstall modal:
        - Extension message:
            - “Uninstalling this extension will remove the functionality to be able to create Staged payments. Ensure you understand the potential risks before continuing.”
        - Warning messages:
            - “Please ensure that all funds in processes associated with this extension are claimed by their owners before uninstalling. Not doing so will result in permanent loss of the unclaimed funds.”
    - All past payment actions created using this extension will remain accessible through the colony’s and users transaction history.

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2832
