### ISSUE TITLE
Issues with Userhub active transactions

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2739]
## Steps to reproduce

1. Create an action with the Reputation decision method.
2. Ensure you don't have enough approved tokens.
3. Stake on the motion, but don't sign the first transaction.
4. Check the Userhub for the current transaction, notice the spinning loaders.
5. Reject the transaction, check the loading spinners again.
6. Retry the transaction.

Note: @chmanie is working on this component, I'm not sure if this has been resolved. But keeping a record of this specific issue.

## Expected behaviour

* Only one transaction should be active at once.
* If you reject, non active transactions should not continue loading.
* Retrying the transaction should retry the transaction. i.e. open the users connected wallet for execution.

## Actual behaviour

* There are two loading spinners when you open the transaction.
* If you reject, the 3rd step transaction keeps it's loading spinner.
* Retrying the transaction does nothing, but keeps the loaders spinning.

![tx-loading-issues](https://github.com/user-attachments/assets/c30e5912-f5b2-4b6b-b2d0-905737c2881d)

**Comment by chmanie** [comment]
I'll try this in my PR and see if it's resolved

**Comment by chmanie** [comment]
It is not completely resolved in my PR. I created #2760 which at least fixes the double loading spinner. The transaction refactor should resolve Retry and the other inconsistencies.
This will be fixed for good once all actions are moved to #2528.
