### ISSUE TITLE
C2F: User account area prod UI fixes 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2741]
## Description

These UI issues have been picked up after testing production, and some may be a duplicate of previous issues raised (before major changes to the flow happened). Please disregard any that have been resolved.

### KYC Personal details modal

1. Additional space is required between the close X and the stepper component to not only match Figma but make this modal consistent with global modals. 

2. Padding needs to be adjusted between the last field of the form and the button row. Also, padding needs to be adjusted between the CTA's and bottom of the modal (again, to align it globally). 

<img width="755" alt="image" src="https://github.com/user-attachments/assets/7c28740c-0088-4b0d-869e-aefe9cfec07d">

3. Error states - Can we align these closer to the copy provided in Figma for a nicer UX? 

<img width="208" alt="image" src="https://github.com/user-attachments/assets/6136ae76-4379-489a-a109-bc38ee9a4b04">

Figma:

<img width="424" alt="image" src="https://github.com/user-attachments/assets/5818439c-6c2d-4f8c-861e-e9030a2dcef6">

4. The p copy after the heading should be text-gray-600

<img width="474" alt="image" src="https://github.com/user-attachments/assets/5652b5ee-268a-4fff-9ab6-d183d8692c1e">

## KYC Terms modal

Can you please kindly adjust the modal height to accommodate the Bridge embed, so the scrollbar isn't triggered inside the modal. 

<img width="469" alt="image" src="https://github.com/user-attachments/assets/f91598b9-f21c-4125-a2e2-faf41d306d8e">

## Completing the KYC modal

Upon completion of the KYC steps and after closing the bridge modal, the UI doesn't give any feedback at all about the status of my verification or that, in fact, I've completed it. This is confusing because I think I need to go back into the KYC flow because nothing is returned. Can we have a solution here that provides the issue with an update upon the bridge modal closing without making the user refresh manually. 

<img width="1357" alt="image" src="https://github.com/user-attachments/assets/a91132d3-cfd8-4dc2-9fb0-690f8ad0f781">

## C2F page 

1. Can we add a capital O to 'Optional'? This is an error in Figma, so apologises on this. 

<img width="105" alt="image" src="https://github.com/user-attachments/assets/1eee13d5-dbda-4065-a89d-fc3170a9dc21">

2. The loading indicator is no longer centre aligned in the user account area (happy for this to be raised in a sep issue)

![Export-1721379709141](https://github.com/user-attachments/assets/3e7bbbfb-df1d-4572-98db-a1d545f651bd)

3. Approved pill is using the wrong colour tokens (looks like it's using team colours and not primary colours)

<img width="148" alt="image" src="https://github.com/user-attachments/assets/dcf6138c-0299-456c-ad0b-1d7f6b0e3944">

4. 'Bank, address and currency information' title should be a medium font weight. 
<img width="389" alt="image" src="https://github.com/user-attachments/assets/a9b1eb5f-9976-408f-a663-113b7602d5da">

## Bank details modal 

1. Same issues with regards to p colour as the KYC modal, should match Figma and be text-gray-600

<img width="506" alt="image" src="https://github.com/user-attachments/assets/da670051-1aaf-4f18-ba65-ad933a276ed8">

2. Padding between inputs should align with Figma.

<img width="480" alt="image" src="https://github.com/user-attachments/assets/dc41cd60-bd26-461a-90e5-8878f87d8e86">

3. Padding between input and the bottom of the modal (same as the KYC) should also match Figma.

<img width="532" alt="image" src="https://github.com/user-attachments/assets/f9813d35-21d2-4961-a95b-b37e38579492">
 
 4. For this modal only, please remove the stepped navigation pills and match the padding between the 'X' close and the heading to this version of the modal here: https://www.figma.com/design/C2grfQysdsYXz0j4rADR6K/Crypto-to-Fiat?node-id=5245-21254&t=bCVgC5ImOijNpbQW-4
 
 
<img width="513" alt="image" src="https://github.com/user-attachments/assets/69f41df3-badd-4ac4-a45f-ebed7641cd47">

5. This selected state for the input should match the design system component (no blue text and incorrect font size)

<img width="470" alt="image" src="https://github.com/user-attachments/assets/8c3cc185-a7ed-4c29-a930-bf084ae4b96c">
 
 
 Component link: https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=2706-1485&t=MkbiMKMM96kcL0sB-4
 
 6. Errors on empty states should match the Figma copy. The invalid error should show when an invalid input is provided by the user, but the empty state should tell the user the field  is required. 
 
 
<img width="454" alt="image" src="https://github.com/user-attachments/assets/6c773d58-b1e5-420f-9318-51cf631debd0">

Examples of empty inputs:

<img width="715" alt="image" src="https://github.com/user-attachments/assets/87ac710e-a284-4b21-b142-5af09b69406b">

7. Toast should not display behind the bg overlay when the modal is active

<img width="515" alt="image" src="https://github.com/user-attachments/assets/00d1b7dc-8cbb-439d-9717-ef3ecf2e3fc7">

8. Can the toast please provide more contextual information with both the toast header and text included. Please remove the :(

Heading: Something went wrong
Text: Your bank details could not be updated at this time 

**I couldn't submit bank details so will need to continue QA once this is possible**

**Comment by jakubcolony** [comment]
> Completing the KYC modal
> Upon completion of the KYC steps and after closing the bridge modal, the UI doesn't give any feedback at all about the status of my verification or that, in fact, I've completed it. This is confusing because I think I need to go back into the KYC flow because nothing is returned. Can we have a solution here that provides the issue with an update upon the bridge modal closing without making the user refresh manually.

Opened #2751 to add an additional KYC status that would cover the "waiting time"
