### ISSUE TITLE
Crypto-to-fiat: Saving bank details should update after completing

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2743]
## Steps to reproduce

1. Go through step 2 Bank details of the Crypto to fiat setup process.
2. Complete the fields in the modal and submit.
3. The confirmation toast will show up, but the status, button, and step details will remain in the same state.
4. You are able to add your details again.

## Expected behaviour

* The step should update automatically with the correct status, fields and state of the button on submission.
* We should handle loading states on the submission button consistent with other modals with the text "Pending" and the spinner.

## Actual behaviour

* There is no changes to the status, button, and step details on submission.
* I was able to complete the form twice, however, it would not close the modal and showed an error in the background.
* There are no loading states on the button on submission.

![bank-details-update](https://github.com/user-attachments/assets/dee0f45d-2812-4064-a97e-4c2175228e3f)

![bank-details-error](https://github.com/user-attachments/assets/23e9e44e-4857-4a6d-b392-7d6928bc3c26)

**Comment by rumzledz** [comment]
This has inadvertently been included in #2774
