### ISSUE TITLE
[Multi-sig] Manage Permissions can only be created by users with permissions in `root`

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#2768]
Previously, the Manage Permissions saga was built with the understanding that `root` permissions are required to assign permissions in the `root` domain, and `root` or `architecture` permissions are required to assign permissions in a sub-domain.

The missing piece from this is that `root` or `architecture` permissions are required in **the parent domain** of the sub-domain you are assigning permissions in. Currently the UI will let you attempt to create this action if you have permissions in the sub-domain you are assigning permissions in, but the contract call will fail.

As it currently stands we only have one parent domain, so this issue is to ensure the following is true about the Manage Permissions action:
- Assigning permissions in the `root` domain is only possible as a user with `root` permissions
- Assigning permissions in a sub-domain, is only possible as a user with either `root` or `architecture` permissions in the `root` domain.
- Assigning permissions in a sub-domain is not possible if you only have permissions in the sub-domain and don't have permissions in the `root` domain.

- [ ] The "missing permissions" error banner should show as expected.
- [ ] The "submit" button should be disabled as expected.
- [ ] The saga should be reworked as necessary.
- [ ] The voting reputation motion saga should be checked (Presumably the encoded action should be created in the root domain too - not sure if this is currently the case)
- [ ] The multi-sig saga should be checked. The permissions for this are slightly different. `root` is required when assigning roles in the `root` domain - the same as permissions. But only `architecture` can be used when assigning roles in a sub-domain, users with `root` permissions are unable to vote or create the action in a sub-domain. (Check what the contracts allow for when managing permissions in a sub-domain if the action is created in the sub-domain)

This should be done on the `feat/multi-sig` branch due to the permissions refactor on this branch.

Additionally, a possibly related issue: If you create a multi-sig motion for managing permissions for a user in a subdomain, but create the motion in `General`, you cannot finalize it.

Additional related fixes and reworks here are:
- Multi-sig motions do not have a concept of createdIn domain, all the users in the impacted domain can vote. That means that if you create a motion that moves funds from a domain, all the permission holders in that domain are eligible. With voting reputation you could create that in General, but the contracts don't enforce this, so we shouldn't either. We should remove created in for all multisig motions, they are created in the affected domain
- If a domain has majority threshold for the threshold type, we don't need to count all the permission holders from the parent domain into the threshold (they however are potential signees)

**Comment by rdig** [comment]
@bassgeta is this still relevant? Do you want it put in the current cycle?

**Comment by Nortsova** [comment]
Thanks @iamsamgibbs for detailed issue. 

Here is also could be relevant to this:

1. Assign admin to amy in Andromeda
2. Assign payer to amy in General
3. Login as amy
4. Create "Manage permissions" action in Andromeda

![Image](https://github.com/user-attachments/assets/1c766bd7-e65a-4548-9804-f5c0fa644d45)
