### ISSUE TITLE
[UI] Upload avatar button not in sync with designs - low prio

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#2775]
### Story

As a user, I want the be able to change my avatar.

### Description

When going to the Account > Profile page, the Avatar section shows the Image uploader component. However, we should display a Primary button `Change avatar` and a link to remove the avatar

Currently ❌ 
<img width="674" alt="Screenshot 2024-07-26 at 10 19 15" src="https://github.com/user-attachments/assets/b25fc352-2c55-4e57-a128-2747710bed6a">

### Design

[Figma link](https://www.figma.com/design/0Fi3AaDlr3LAXBfsOXBGyk/User-Account?node-id=6401-11214&t=zrLn68QyOhyJF1Gq-0)

### This issue is complete when...

- [ ] There is a simple button in place to upload the avatar
- [ ] There is a link to remove the uploaded avatar

**Comment by melyndav** [comment]
Hey @mmioana - this issue can be closed as it's been added to this new issue - #2872

**Comment by rdig** [comment]
Closing
