### ISSUE TITLE
Example: Unable to log in with MetaMask wallet

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2778]
## Steps to reproduce

1. Create an Advanced payment action.
2. Add a row to the table.
3. Click the upload CSV template.
4. Note if there is a warning message or not.

This should have been resolved in this PR https://github.com/JoinColony/colonyCDapp/pull/2440, which I assumed would be in `master`, although this was tested while on QA, which is where I had the issue.

## Expected behaviour

* The warning message should appear if there is any data in the table at all when opening up the CSV upload modal.

## Actual behaviour

* The warning message for overriding table data is not showing if you have not previously uploaded a file.

![warning-message-not-appearing](https://github.com/user-attachments/assets/aefa6abf-3661-4ba2-b1a3-a51496de019e)

**Comment by arrenv** [comment]
I looked at some history, and it just looks like it has not been merged into `master` yet. I shall close this for now.

**Comment by rdig** [comment]
Do note if investigating this that #2590 changed the format and format validation of the default CSV file
