### ISSUE TITLE
Permission in details card when funding and releasing payments

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2779]
Teamwork task: [Permission in details card when funding and releasing payments](https://tw.auroracreation.com/#/tasks/16019596)

## Steps to reproduce

1. Create an Advanced payment action.
2. Complete the details of the payment and proceed through the payment process.
3. Go to Funding the payment step and select the Permissions decision method in the Funding modal.
4. Note the info card, it currently has hardcoded the "Payer" permissions type.
5. Complete the funding process and continue to the Release step.
6. Go to Release the payment step and select the Permissions decision method in the Funding modal.
4. Note the info card, it currently has hardcoded the "Payer" permissions type.

## Expected behaviour

* The Permission listed in the info card should show the users actual permission.

## Actual behaviour

* The Payer permission is hard coded into the info card.

![image](https://github.com/user-attachments/assets/ae2a97f8-ccab-46a5-8ff0-5d96b85a660e)

![image](https://github.com/user-attachments/assets/4a0dac12-422a-4771-9d83-e0054457f936)

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2981
