### ISSUE TITLE
[Multi-Sig] User Info Popover Icons do not account for inherited permissions

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#2783]
## Steps to reproduce

Step 1 - Assign a user payer permissions in a sub domain
Step 2 - Assign the same user owner permissions in general
Step 3 - Open their user info popover, hover over the permissions icon for the sub domain.

## Expected behaviour

* The "admin" permissions tooltip should show as whilst they only have the payer permissions in the sub-domain, they have inherited the other admin permissions from the root domain.
* Inherited permissions should show with the text "(inherited)" after the relevant permission.

![image](https://github.com/user-attachments/assets/a0d60b72-e052-4caa-8fef-558b98471ce7)

## Actual behaviour

* The "payer" permissions tooltip shows

## Suggestions (optional)

This same issue occurs when assigning multi-sig permissions.

 
<img width="517" alt="Screenshot 2024-07-26 at 14 27 32" src="https://github.com/user-attachments/assets/2c72382d-059a-4939-8352-50b416d68c57">

<img width="494" alt="Screenshot 2024-07-26 at 14 27 36" src="https://github.com/user-attachments/assets/d2514729-9872-4bfc-a54b-6334fc222e2b">

<img width="465" alt="Screenshot 2024-07-26 at 14 27 40" src="https://github.com/user-attachments/assets/dcaad26f-ce16-4be1-a288-9836dddd328f">

**Comment by bassgeta** [comment]
Talked with @arrenv and decided that the following should display:
1. If the user doesn't have any inherited permissions in a domain, and they have a bundle, display:
`This member has the {bundle} permission bundle that includes the following permissions:`

2. If the user has custom permissions and no inherited permissions, display:
`This member has the following permission types:`

3. If the user has custom + inherited or just inherited permissions display:
`This member has the following permission types:`

at the start of the tooltip.

All inherited roles have the `(inherited)` appendix
