### ISSUE TITLE
[Bug] The "All teams" filter on the permissions page is broken

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#2784]
This was previously fixed in #2485

But I suspect it was broken as a result of changes in #2708

## Steps to reproduce

1. Assign permissions to a user in a sub domain
2. Refresh and navigate to the permissions page
3. Make sure the "All teams" filter is selected

## Expected behaviour

* All users with permissions should show

## Actual behaviour

* Only users with permissions in the root domain will show

## Suggestions (optional)

One situation to consider is if a user has `payer` permissions in general and `admin` permissions in a sub-domain. Which category should they appear under? Technically `admin` grants them a wider range of permissions within a single domain, but they are `payer` in general and can use those permissions across any domain. Needs some guidance from @arrenv on how this should be handled.

**Comment by arrenv** [comment]
@iamsamgibbs Good pickup!

In regards to which group they should appear in as of your example, it should be based on the permissions they hold in the highest level team. Which gives a greater indication of control across teams, and also keeps it consistent as you delve deeper into child teams.
