### ISSUE TITLE
[Bug] The permissions page does not take "inherited" roles into account for users who have specific permissions

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#2785]
## Steps to reproduce

1. Assign payer permissions to a user in a sub domain
2. Assign admin permissions to the same user in the root domain
3. Navigate to the permissions page and select the sub domain in the team filter

## Expected behaviour

* The user should show under the `admin` category, whilst they have been explicitly assigned `payer` permissions, they will have inherited the other permissions required to perform `admin` actions.

## Actual behaviour

* The user will show under the `payer` category.

## Suggestions (optional)

The "inherited" pill could show exactly which permissions have been inherited, in the example above only the `Architecture` role would be inherited. This is probably more relevant when singular custom permissions have been assigned in the sub-domain and the root domain.

**Comment by Nortsova** [comment]
It should be solved in scope of - https://github.com/JoinColony/colonyCDapp/pull/2950

**Comment by Nortsova** [comment]
sorry it was misunderstanding, here is solution - https://github.com/JoinColony/colonyCDapp/pull/2971

**Comment by rdig** [comment]
@Nortsova did #2971 fix this issue? then please close it

**Comment by iamsamgibbs** [comment]
@rumzledz has just come across it where the member even has "Admin" permissions in the sub-domain:

![permission-issue](https://github.com/user-attachments/assets/e3b67a5b-cb61-46ce-891c-7a891285e4cc)

**Comment by rdig** [comment]
@Nortsova this has been active for a almost 3 months now. Please figure out it's status: either close it if it's not relevant, or put in a fix for it

**Comment by iamsamgibbs** [comment]
@Nortsova Not sure why this issue was closed?

The issue is still occurring as described in the original description on master.
 
<img width="731" alt="Screenshot 2024-10-14 at 14 40 52" src="https://github.com/user-attachments/assets/7909aa68-6085-4d32-a6b4-7772f6b573f8">

Unrelated, but also appears there has been a regression on the user popover component as the reputation points styling has broken.
