### ISSUE TITLE
User menu bar pushed down by calamity banner

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2786]
## Steps to reproduce

1. Ensure that the calamity banner is visible in the app.
2. Open up the action panel.
3. Note the position of the user menu bar in the header.

## Expected behaviour

* The action panel should not sit over the calamity banner and should move down with the rest of the page.

## Actual behaviour

* Currently the user menu bar is misaligned in the calamity banner due to the presence of the calamity banner.

![image](https://github.com/user-attachments/assets/bb1446d0-0778-4bf3-9af5-fa24c4c1dbfc)

![image](https://github.com/user-attachments/assets/81bd5d86-735e-4938-98c2-e6a110743342)

![user-menu-bar](https://github.com/user-attachments/assets/97f5e8e3-a325-4547-ae0f-2228e213e963)

![image](https://github.com/user-attachments/assets/4966a5fd-3e4f-435c-943b-7bf1df4ce6aa)

![image](https://github.com/user-attachments/assets/79615173-4b74-4b12-83b8-8843770e3d4d)

**Comment by rumzledz** [comment]
I spoke to @jakubcolony about this issue last week. I've basically fixed this already and it's in the `ui/new-navigation-ui` branch.
