### ISSUE TITLE
App is crashing on pagination

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2831]
Teamwork task: [App is crashing on pagination](https://tw.auroracreation.com/#/tasks/16019594)

## Steps to reproduce

So far, this has only been tested and found on QA.

1. Navigate to this colony on QA: `cleanenergy/activity`
2. Click through the pagination to try to get to the end of the list.
3. The app crashes at a certain point with `payouts` being undefined.

## Expected behaviour

* You should be able to go through the full activity feed without the app crashing.

## Actual behaviour

* The app crashes as you paginate through the activity feed.

![pagination-crashing](https://github.com/user-attachments/assets/fa64d9d7-e98f-4fd4-a0d5-b732b09860d3)

**Comment by rdig** [comment]
This is from Split Payments, which is currently on QA, so it should be treated in that context

**Comment by jakubcolony** [comment]
I got the same error while testing on QA:

<img width="1114" alt="image" src="https://github.com/user-attachments/assets/d4c9cd4a-5fb0-4016-aa80-83359a5878e0">

I think this is the offending code:
<img width="535" alt="image" src="https://github.com/user-attachments/assets/dae67d90-6474-4b79-8e64-78c928708494">

I've added extra optional chaining after accessing the 0th element of the `slots` array which should hopefully fix the issue.
