### ISSUE TITLE
Pending button no longer opens transaction tab

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2834]
## Steps to reproduce

1. Create a new transaction.
2. While the pending button is visible, click on it.
3. Note that it now no longer opens up the Transactions tab.

## Expected behaviour

* The pending transaction button in the header, it should open the transactions tab in the Userhub.

## Actual behaviour

* The pending transaction button in the header click no longer works.

![image](https://github.com/user-attachments/assets/4574f42b-d5f1-4452-a302-da1866eeaf68)

**Comment by rdig** [comment]
FIY @chmanie as you might know what's going on here

**Comment by chmanie** [comment]
I'm taking this. When I tested it it also didn't work on master do I thought that's the desired behavior.
