### ISSUE TITLE
Transaction rejecting, cancelling and retrying behavior issues

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2835]
## Steps to reproduce

1. Ensure you are connected via a wallet where you can reject the transaction i.e. Metamask.
2. Create a new action.
3. Fill in the details and include a description (not essential, but creates multiple transactions in the group).
4. Click to create the transaction.
5. Reject the transaction in your wallet.
6. Note the status change of the Transaction status button in the header.
7. Click the "Retry" button.
6. Note the status change of the Transaction status button in the header.
8. Click the "Yes" button.
9. Note that the transaction will cancel.
6. Note the status change of the Transaction status button in the header.

## Expected behaviour

* The Transaction status button should not show "Completed" if the transaction is rejected or cancelled, it should just disappear.
* Retrying a transaction should trigger the users wallet with the transaction they are retrying.
* There should no be secondary "Yes/No" and cancel option after clicking "Retry".
* The initial error should not be visible and then change to the other generic error.
* We should show a more helpful error, rather then the generic one.
* The transaction should show the correct title and description.
    - The title should be the transactions actual custom title, with a fallback to the Action type.
    - The description should be the actions metadata.

## Actual behaviour

* Transactions status is showing as "Completed" even if rejected or cancelled.
* Retrying a transaction does not retry the transaction.
* After clicking "Retry", the UI shows "Yes / No" option, "Yes" cancels the transaction, "No" changes to a "Cancel" option. This is misleading and not really useful as it only appears after clicking "Retry" and only shows because "Retry" does nothing.
* A more useful error shows and then disappears to a less helpful generic error.
* The details of the transaction are wrong. It is showing "Expenditure Payment", and a missing translation.

[transaction-issues.webm](https://github.com/user-attachments/assets/8461b043-beeb-4359-85c3-88b3e8375cf2)

![image](https://github.com/user-attachments/assets/bbde6776-d36b-4e90-837c-dd5810fc7a5e)

![image](https://github.com/user-attachments/assets/dffb8f73-afb2-46da-b55a-1e060f466f8e)

![image](https://github.com/user-attachments/assets/c48fd127-cc41-4610-b311-2f53fa34007d)

**Comment by rdig** [comment]
FIY @chmanie as you might know what's going on here

**Comment by chmanie** [comment]
This is a pretty wild mix of stuff, so @arrenv be prepared for some questions.

I'm assigning this to me
