### ISSUE TITLE
Metatransactions not working on QA

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2836]
## Steps to reproduce

1. Ensure Metatransaction is enabled in your Advanced user account settings.
2. Try to perform a transaction.
3. Note that you will be required to pay for gas.

    _Note: This is very likely that same issue as resolved with this hotfix https://github.com/JoinColony/colonyCDapp/pull/2812, either it has not made it's way into this branch on QA, or it is something else._

## Expected behaviour

* Metatransactions should work on QA if the user has it enabled.

## Actual behaviour

* Despite being enabled, Metatransactions is not working on QA.

    ![image](https://github.com/user-attachments/assets/784b7bac-761f-4612-a0ab-f81c32286a50)

    ![image](https://github.com/user-attachments/assets/6909ec2e-ba35-4437-a7d4-131336983d22)

**Comment by rdig** [comment]
Correct, this was solved by #2812 and the feature that's on QA doesn't include that yet
