### ISSUE TITLE
Amount placeholder width breaks on non-numeral input

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2838]
Teamwork task: [Amount placeholder width breaks on non-numeral input](https://tw.auroracreation.com/#/tasks/16043634)

## Steps to reproduce

1. Create a new Simple payment action.
2. Enter a non-numeral non-decimal value into the amount input field.

Note: this was discovered on QA while testing Advanced Payments, I have confirmed that this is not currently in master.

## Expected behaviour

* You should not be able to enter a non-numeral non-decimal into the field.
* The field width should not change when entering non-numeral non-decimal

## Actual behaviour

* Amount placeholder width breaks on non-numeral non-decimal input.

![image](https://github.com/user-attachments/assets/8b521120-4df3-4b6f-9187-f0649ca7449d)

**Comment by AdrianDudko** [comment]
@arrenv  The fix for this issue is in https://github.com/JoinColony/colonyCDapp/pull/2719/
