### ISSUE TITLE
Orange backgrounds are showing up on all tabs

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2839]
## Steps to reproduce

This is happening on QA at the moment, it seems strange that it keeps coming back. You can see it on all tab pages, such as Members, account area.

## Expected behaviour

* The tabs should match the design.

## Actual behaviour

* The tabs background is currently showing as orange.

![image](https://github.com/user-attachments/assets/fc218898-080c-4f9c-b43a-9bc8e4c1fe97)

**Comment by rdig** [comment]
This is only QA, and it's because it hasn't been rebased

**Comment by melyndav** [comment]
Can confirm this is on master as of today @rdig 

<img width="561" alt="image" src="https://github.com/user-attachments/assets/56d98170-9a15-4382-9e57-1ee2e3096eb8">

**Comment by rdig** [comment]
Will prioritize it then

**Comment by melyndav** [comment]
> Will prioritize it then

Thank you! :)
