### ISSUE TITLE
Redo action does not include member

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2840]
Teamwork task: [Redo action does not include member](https://tw.auroracreation.com/#/tasks/16019592)

## Steps to reproduce

1. Create a Simple payment action.
2. On the completed actions screen, click the kebab menu.
3. Click the "Redo action" option.
4. Note that all fields are copied, except the Member field.

## Expected behaviour

* The member field should also be copied over when redoing an action.
* Redo action should be visible in the activity feed kebab menu as well.
* Redo action should be available for all Advanced payment options, including Staged and Split.

## Actual behaviour

* The member field is not pre-filled when using the redo action option.
* The redo action option should also be available from the activity feed for payment related actions as of the original spec.
* Redo action is missing from Advanced payment actions, including Staged and Split.

![image](https://github.com/user-attachments/assets/98de3f23-9ac6-4d2b-9e30-c46b5fb7312c)

![image](https://github.com/user-attachments/assets/f509c6ac-b9f4-4441-9e0f-1a58849322af)

![image](https://github.com/user-attachments/assets/6f995e48-071d-4d5f-b05d-a7e1bd5e15cf)

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2925
