### ISSUE TITLE
Manage reputation action is not working

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2841]
## Steps to reproduce

1. Create a new Manage reputation action.
2. Award or Remove reputation.
3. Enter the details for the action.
4. Confirm and execute the transaction
5. Note the transaction will succeed, however, the action will not redirect and the will be an Apollo error in the console.

## Expected behaviour

* Manage reputation actions should not be failing in the UI if they are succeeding.
* Transactions that happened should show up in the activity feed.
* Actions that happened should load in the action panel.

## Actual behaviour

* Manage reputation actions are succeeding, however, they fail in the UI.
* Trying to open past succeeded Manage reputation transactions from the Transactions tab opens a 404 action.
* Manage reputation actions are not appearing in the activity feed.

![image](https://github.com/user-attachments/assets/a8c369c8-9015-4cbb-8343-cdf7a0fa1f91)

![image](https://github.com/user-attachments/assets/4655b46c-54ec-4519-a710-bb83bbc9128c)

![image](https://github.com/user-attachments/assets/e64917c9-8907-4ae1-ba69-29ac80e5e8cd)

**Comment by rdig** [comment]
This works in production, so it's only on the Advanced Payments branch in QA, but I'm not closing this issue, since this might not be a rebase problem

![Screenshot from 2024-08-02 21-10-36](https://github.com/user-attachments/assets/0ec57b2c-e902-435e-86ac-94c54cbf3877)

**Comment by arrenv** [comment]
Closing, as seems resolved after @jakubcolony's rebase.
