### ISSUE TITLE
Split payments table loading state on newly created action

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2843]
Teamwork task: [Split payments table loading state on newly created action](https://tw.auroracreation.com/#/tasks/16019593)

## Steps to reproduce

1. Create a split payment.
2. Select the Reputation percentage distribution type.
3. Select users with reputation.
4. Create the action.
5. Note the loading state of the split payment table.

Note, it seems to only happen the first time, it can be repeated by changing the order and members in the split payment

## Expected behaviour

* You should see the skeleton loader, and no other state prior to showing the actual values.

## Actual behaviour

* I have seen multiple things happen here.
    - One variation is that I saw the all 0 values, and no skeleton loader.
    - Another variation, I saw one row in the table, and over a few seconds each additional row loaded in.

[loading-split.webm](https://github.com/user-attachments/assets/fe555558-3b0f-4b5e-baa3-3ffd2b8b125a)

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2983
