### ISSUE TITLE
[Dashboard] Total in and out card - lambda function to compute values

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#2844]
### Story

- As a USER I want to understand how much money went in and out of the colony’s treasury in the past month

### Description

Given the focus on financial actions and tools, we want to display the in/out funds on a monthly/weekly basis.

## Implementation

We need to implement a lambda function that computes the Income/Payments for a domain within a specific timeframe.
For the payments, we need to retrieve all ColonyActions of payment type.
We need to index ColonyAction based on the type.
For the income, we can use 

### This issue is complete when...

- [ ] Payments and income values are retrieved for a domain in a specific timeframe splitted by month/week

[Figma link](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4859-36367&t=3YmH0OCdhMXflaYC-0)
[Figma link empty state](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4867-40639&t=3YmH0OCdhMXflaYC-0)

**Feature branch**: `feat/enhanced-dashboard`

**Comment by rdig** [comment]
@mmioana same with this one, please add an estimate
