### ISSUE TITLE
[Dashboard] Total in and out card - add monthly in/out chart

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#2845]
### Story

- As a USER I want to understand how much money went in and out of the colony’s treasury in the past month

### Description

Given the focus on financial actions and tools, we want to display the in/out funds on a monthly basis.
The chart should use the selected domain colors

## Implementation
For this issue it would make sense to use either
- [nivo.rocks](https://nivo.rocks/) - Check this https://nivo.rocks/storybook/?path=/story/bar--diverging-grouped
- or [chart.js](https://www.chartjs.org/docs/latest/)
- or [recharts](https://recharts.org/en-US/)

Relies on the data retrived by the lambda function implemented in **[Dashboard] Total in and out card - lambda function to compute values**

### This issue is complete when...

- [ ] Dashboard page includes a 'Total in and out' card displaying the data in a bar chart using the selected domain colors
- [ ] Hovering over a bar chart should show the value of the period in the user’s nominated currency.
- [ ] As a new month starts, it will show the new month with no values until payments or incoming funds have happened in that month.

[Figma component](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4878-89693&t=SNW5sWiyJk5omQMX-0)
[Figma link](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4859-36367&t=3YmH0OCdhMXflaYC-0)
[Figma link empty state](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4867-40639&t=3YmH0OCdhMXflaYC-0)

**Feature branch**: `feat/enhanced-dashboard`

**Comment by mmioana** [comment]
After the exploration done in this [devbox](https://codesandbox.io/p/devbox/reactjs-playground-forked-fmgjvn?file=%2Findex.html&welcome=true), proposal would be to continue with **chart.js**

**Comment by rdig** [comment]
@mmioana please add an estimate to this one

**Comment by mmioana** [comment]
@rdig I added a higher estimate only due to the transition from chart.js to nivo.rocks
