### ISSUE TITLE
Pending button styling breaks in Adv. payments modal

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2862]
Teamwork task: [Fixes before split payment release](https://tw.auroracreation.com/#/tasks/16025768)

## Steps to reproduce

1. Create an advanced payment action.
2. Continue through the flow and Fund or Release the payment.
3. In the Funding or Release modal note the styling of the confirm button while pending.

## Expected behaviour

* The button styling should be consistent and as of the design.

## Actual behaviour

* The styling of the button breaks while the transaction is pending.

![image](https://github.com/user-attachments/assets/7fce0227-f03e-46e8-ab4a-82454b65ba62)

![button-change](https://github.com/user-attachments/assets/50925e57-0e1a-4faf-86ca-3164f5fe93f5)

**Comment by melyndav** [comment]
Can this loading button be added for the cancel model within Advanced payments? There's no consistency with the modals in actions. 

<img width="670" alt="image" src="https://github.com/user-attachments/assets/a99d8895-bcf7-45bf-968a-ced647561abe">
