### ISSUE TITLE
Transactions are persistent across users/wallet accounts

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2864]
## Steps to reproduce

1. Connect as one user in the app and ensure you have performed some transactions.
2. Go to the Userhub > Transactions tab.
3. Note the transactions in the list.
4. Now, switch wallet accounts to another user.
5. Return to the Userhub > Transactions tab.
6. Note that the transactions will be from the previous user.
7. Reload the page.
8. Return to the Userhub > Transactions tab.
9. Note that the transactions will now be updated.

## Expected behaviour

* When switching accounts in the app, you should not be able to see the transactions from the previous users.
* You should not have to reload the app in order to update the UI.

## Actual behaviour

* Transactions are persistent across users when switching accounts.

![transactions-by-user](https://github.com/user-attachments/assets/1f1eabfc-f52e-47d1-aee6-438f7b6ede16)

**Comment by rdig** [comment]
Another one in which I ping you @chmanie 

Let me know if this is migrations related so I can help

**Comment by chmanie** [comment]
![Refresh types](https://imgs.xkcd.com/comics/refresh_types.png)
