### ISSUE TITLE
Bug: [QA ENV] The Member page tabs are using the wrong colour

### ISSUE THREAD

**Issue by rumzledz** [JoinColony/colonyCDapp#2877]
## Steps to reproduce

1. Head over to our QA environment: https://arbitrum-sepolia.colony.io/
2. Visit any Colony you've joined
3. Go to the Members page

## Actual behaviour

The tabs are using the wrong colours

## Expected behaviour

The tabs should be using `bg-base-white`

## Actual behaviour

**Comment by rdig** [comment]
This is no longer relevant
