### ISSUE TITLE
Bug: On tablet view, the loading skeletons of the Latest Activity table can still be viewed when the Sidebar is currently visible

### ISSUE THREAD

**Issue by rumzledz** [JoinColony/colonyCDapp#2878]
## Steps to reproduce

1. Visit any Colony you've joined
2. Set the viewport to mobile
3. Bring up the Sidebar
4. Reload the page

## Expected behaviour

You should not be able to view the skeleton loaders because the sidebar should naturally have a higher layout position.

## Actual behaviour

You can see the Latest Activity table's skeleton loaders even when the Sidebar is currently visible:

![master loading](https://github.com/user-attachments/assets/89850fdd-5413-435f-84bb-08655e4ffb7c)

**Comment by rdig** [comment]
talk to @mmioana and @rumzledz before tackling this

**Comment by iamsamgibbs** [comment]
I've checked this and can confirm it is still happening on master:

https://github.com/user-attachments/assets/5a545eb2-6a05-4391-9da9-c29ab42c6f86

**However**, it is not happening on the new navigation branches:

https://github.com/user-attachments/assets/d526c2ab-7bf7-45e2-86a6-56469493e2ab

So I think we can close this as it will be resolved by that.
