### ISSUE TITLE
Advanced payment funding motion, UI did not update despite Staking succeeding

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2882]
## Steps to reproduce

1. Create an Advanced payment or any other action with Reputation decision method.
2. If doing an Advanced payment take the advanced payment to the funding step and use the Reputation decision method.
3. I fully staked in support.

Note: This was tested on QA, but did not happen every time, but happened more than once.
Note: I just found this to also happen on a Simple payment motion as well on production.

## Expected behaviour

* The UI should update after successfully staking.
* You should not get locked into the Support or Oppose tabs if you switch during a transaction.

## Actual behaviour

* The UI did not update after successfully staking, I had to reload the app in order to see the status of the motion change.
* The screenshot shows the staking succeeding in the transactions tab, but the staking widget with no update.
* I also ran into a previous issue where I could switch from "Support" to "Oppose" options while the transactions where in progress, and "Stake" button was disabled. Resulting in me not being able to stake again until reopening the action.

![image](https://github.com/user-attachments/assets/3e04bc6b-a6df-44c9-a456-e2b50b4ebb7e)

![image](https://github.com/user-attachments/assets/6fa9f2a4-d574-42a6-82ec-f946a621b598)

[locked-staking-voting.webm](https://github.com/user-attachments/assets/e466c85e-76e6-414d-bc81-ee0ca4cd09b0)

**Comment by CzarekDryl** [comment]
@arrenv I wasn't able to fix this staking error, it seems to be a problem with the transaction or saga. Function gets stuck on  `await asyncFunction(values);` in `ActionForm` component. Can someone from your team take a look at this?
<img width="677" alt="image" src="https://github.com/user-attachments/assets/4dc28355-ad93-444e-b4c2-746ef2278d89">

**Comment by arrenv** [comment]
Thanks @CzarekDryl 

@rdig Were you able to replicate the same issue?

**Comment by rdig** [comment]
I was not able to replicate the saga "hang" issue. 

But sure we'll take a look at it

**Comment by jakubcolony** [comment]
Following a discussion and a call with Czarek, I was able to pinpoint the hang issue.

To reproduce, you need to create a funding motion and fail it (e.g. by staking both sides and voting no). The next motion you create should exhibit the issue.

The UI update after staking is triggered by onSuccess callback in the [ActionForm](https://github.com/JoinColony/colonyCDapp/blob/master/src/components/shared/Fields/Form/ActionForm.tsx#L73). For some reason, the `await asyncFunction` call never completes when staking subsequent funding motions. You can see the before/after logs in my console, note the last staking transaction is missing the "after" log:

https://github.com/user-attachments/assets/4bf15251-8f2e-41a9-9f09-87529317de91
