### ISSUE TITLE
[New Navigation]: Colony Page Sidebar mobile view

### ISSUE THREAD

**Issue by rumzledz** [JoinColony/colonyCDapp#2884]
## Description

Currently, only the tablet and above version of the Colony Page sidebar has been implemented, UI-wise. This issue tackles its mobile view version.

## Acceptance Criteria

> [!NOTE]
> The Colony Search component will be implemented separately by @Nortsova as part of her OKR 🙌 

* [ ] It should follow the [Figma designs](https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=3931-18867&t=IYZleyvogHCEE3d2-4)

![Image](https://github.com/user-attachments/assets/4fd07ea3-c402-4fdc-a1eb-74aebc909e7b)

**Comment by rdig** [comment]
@rumzledz please add an estimate to this one
