### ISSUE TITLE
Add a claim delay warning on Staged payments

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2899]
Teamwork task: [Add a claim delay warning on Staged payments](https://tw.auroracreation.com/#/tasks/16035753)

## User story

As a USER, I want to be made aware of Staged payments that have a low claim delay timer.

## Description

Due to the extremely high claim delay value we set for Staged payments, we don't show this in the UI for each payment. However, there is a possibility that the claim delay is edited and reduced. In this scenario, we should show a warning to users.

## Design

- [Figma link - Design of claim delay timer](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?node-id=26187-216669&t=SrEjADE0CuVbASHB-4)
![image](https://github.com/user-attachments/assets/23a8850e-7372-4968-8610-9d15bc133ef0)

## Acceptance criteria

- Claim delay warning
    - Claim delay threshold, less then 30 days.
    - Show an icon to indicate an issue with a payment row.
    - There should be a tooltip for the error icon, with the claim delay timer as of the design.

**Comment by AdrianDudko** [comment]
Closed by https://github.com/JoinColony/colonyCDapp/pull/2990
