### ISSUE TITLE
[Multi-sig] Add notices for incorrect colony version

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2918]
## Steps to reproduce

1. Ensure you have a colony on version 15 or lower.
2. Install Multi-sig extension.
3. Create a new Manage permission action to award Multi-sig permission.
4. The action will fail for no discernable reason.

## Expected behaviour

* The user should be made aware that they cannot use multi-sig until they upgrade their colony.
* We should show a validation message when selecting the Authority type when assigning permissions.
* We should show an error banner on the multi-sig extensions page.

![image](https://github.com/user-attachments/assets/ea6b639a-ccfc-4fce-b18d-29af9ca7a8ec)

[Figma link for extension banner](https://www.figma.com/design/6qONTE1uD9K4yoIbfFzidg/Extensions?node-id=2187-15952&t=vw4fNCGsF36Bp7Ow-4)

![image](https://github.com/user-attachments/assets/aff55307-3e27-4722-b966-8dbee990792a)

## Actual behaviour

* Trying to assign multi-sig permissions to users on colony network version 15 or lower fails with no UI errors.

![image](https://github.com/user-attachments/assets/2cebcfeb-55e6-4360-ace2-8b7391b38c68)

**Comment by bassgeta** [comment]
There has been a lot of work already done on this [here](https://github.com/JoinColony/colonyCDapp/pull/2361/files#diff-c9b729ba88276c82efc4ab03b7967a5abdc06d7acf42db582f7b87df0bed2a26), so as agreed, we will be postponing this until we merge both branches into `master` and then realign all necessary extension installation flows.
To alleviate double transactions, we will be adding the "Permissions needed" banner back, done [here](https://github.com/JoinColony/colonyCDapp/pull/2926)
