### ISSUE TITLE
[Multi-sig] Transaction auto triggered when loading multi-sig ext. (without required permissions)

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2919]
## Steps to reproduce

Note: I can understand why this is being done, but, it does not work if you don't have permissions and you don't get any feedback as to why.

1. Remove permissions from the Multi-sig extension.
2. Navigate to the Multi-sig extension page.
3. A transaction will automatically be triggered, with no context as to why or what it is for.

## Expected behaviour

* There should not be any auto triggered transactions when loading a page.
* You should see the missing permissions banner if there are permissions missing, that only users with the right permissions can trigger.

## Actual behaviour

* You get an auto triggered transaction when navigating to the Multi-sig extension page, which, does not have it's required permissions.
[auto-transaction.webm](https://github.com/user-attachments/assets/b2c073a2-2736-4d94-9c07-d3ed664fd59f)

* The errors if you visit the page if you don't have the required permissions.
![image](https://github.com/user-attachments/assets/18196352-448e-4eff-99ba-0e2b78689679)

* Result of switching connected wallet while on the page, without reloading. This also locked me into the account, as it would auto trigger the transaction and that failed transaction prevented me from disconnecting my wallet. I have to navigate away, reload the app, then disconnect the wallet.
![image](https://github.com/user-attachments/assets/23ca1e28-4419-4599-9c95-87fa07910e85)

**Comment by rdig** [comment]
We found something similar that @bassgeta has been tracking as it can actually cause a infinite loop generating permission transactions

**Comment by rdig** [comment]
Closed by #2926
