### ISSUE TITLE
[Master] Agreements: Remove draft and create a new agreement modal broken padding

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2934]
## Description

On master, there is an issue with a modal within the create agreements section that are not currently in production. 

### Issue : Remove draft and create a new agreement modal broken padding on desktop and mobile

On all responsive sizes, the modal to remove a draft agreement and create a new agreement has broken padding. Padding should be consistent with all other global modals on desktop and mobile. 

<img width="1613" alt="image" src="https://github.com/user-attachments/assets/588838c3-fa54-4d6a-8e4f-51b33a937947">

<img width="521" alt="image" src="https://github.com/user-attachments/assets/d56b9548-e721-4942-ba49-3eb142babf11">

## Steps to reproduce

1. Create a draft agreement on master 
2. Go to the agreements page on both desktop and mobile
3. Select 'Create new agreement' button
4. The broken modal will show on the respective device 

## Expected behaviour

* The modal should display on all responsive sizes without the broken padding

**Comment by iamsamgibbs** [comment]
Looks as though this got fixed up somewhere along the way since this issue was created.

![Image](https://github.com/user-attachments/assets/a7003f85-758d-469a-993a-33f9abef030f)
![Image](https://github.com/user-attachments/assets/25a14b0f-cffd-4cb2-a3ef-5e1feecb3971)
