### ISSUE TITLE
Number of decimals for converted non-blockchain currencies

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2935]
## Steps to reproduce

1. Ensure you have funds in a colony that has a value.
2. Ensure you have a currency selected that is not blockchain based.
3. Note the number formatting.

## Expected behaviour

* All non-blockchain based converted currencies should have 2 decimal places.
* For all non-blockchain based converted currencies we should not abbreviate until over 9 digits.

![image](https://github.com/user-attachments/assets/5e726cb7-a7d6-44da-aea4-9314f68d800a)

## Actual behaviour

* All non-blockchain based converted currencies, have 5 decimal places. Having more then 2 is not typical number formatting for non-blockchain currencies that people typically use everyday. This makes it harder to read.

![image](https://github.com/user-attachments/assets/2c6a2a3c-931a-4caf-8d67-007a0d0bf703)

**Comment by rdig** [comment]
Closed since it was fixed by #3126
