### ISSUE TITLE
Motions and Permission Funding breaking

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2937]
Teamwork task: [Motions and Permission Funding breaking](https://tw.auroracreation.com/#/tasks/16035773)

## Steps to reproduce

Prerequisite: 
1. Go to file `src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx`
2. Disable conditional logic at `line 132` so that button loading state does not appear.

![image](https://github.com/user-attachments/assets/b9108909-6984-481d-b928-6395bc5c05a5)

1. Ensure you have the Reputation decision method enabled.
2. Create a new Advanced payment action.
3. Get all the way to the Funding step and open the funding modal.
4. Set the Decision method to Reputation.
5. Do the following as quickly as possible.
6. Click the Fund payment button a number of times.
7. Quickly set the Decision method to Permissions.
8. Click the Fund payment button a number of times.
9. You can slow down now.
10. The UI should update to the release stage.
11. Return to the Funding stage and interact with the widgets.
12. Note the split sections and broken interactions.

## Expected behaviour

* The permission and reputation options should all be in the one card, not two separate cards.
* Only one item should be selectable at a time, across both permissions and reputation.

## Actual behaviour

* The permission and reputation options are separated into two different sections.
* Two items seem to be highlighted at the same time in the permissions section.
* Clicking on different permission items does not seem to change the card, although, I am not sure if it is just because the info is the same. Perhaps when they are combined, it will be more evident that info is changing.
* Despite failing motions, the card title says that it has passed and has been executed. It should say "Action failed and cannot be executed.

![image](https://github.com/user-attachments/assets/13395bde-49f3-4c7d-a90f-d667711f57ce)

* When clicking on motions, the whole UI jumps around.

[broken-motions.webm](https://github.com/user-attachments/assets/20fd9c47-f8d4-4359-bfde-d31e0241b95a)

* We are showing the completed state of failed motions now, so, we can get rid of the copy functionality on failed motions.

![image](https://github.com/user-attachments/assets/1f0bb322-2b1e-4e13-aa62-21b71848a868)

* The initial loading state is broken. No items should auto load, they height of the rows should be consistent and not jump once the status has loaded in.

![image](https://github.com/user-attachments/assets/f02505e3-6266-4092-a7a5-0964e7d2603b)

Additional broken UI.

![image](https://github.com/user-attachments/assets/876d53ce-8143-49b3-b919-d20ecc7d2f54)

![image](https://github.com/user-attachments/assets/6679cf72-f917-41c0-bfa6-73d32fdc4c46)

![image](https://github.com/user-attachments/assets/e884e565-4f7d-458c-aab0-bf41b4f0b393)

**Comment by rdig** [comment]
Is this one for us or for Pagepro ?

**Comment by arrenv** [comment]
This is for Pagepro, I have labelled it correctly.
