### ISSUE TITLE
Handle storing annotations in db

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#295]
This might be handled by actions, coordinate with Jakub.

But, as an outline, we need to store the annotation in the db since we're no longer using IPFS.

Upload the annotation directly in the saga (https://github.com/JoinColony/colonyCDapp/pull/261#discussion_r1118717660).

Places to do this in motions:

ObjectionModal

You will also need to coordinate the wiring in of the Objection display in motions, which depends on annotations:

![Image](https://github.com/JoinColony/colonyCDapp/assets/64402732/330d42d1-3166-4ce3-b7dc-c1c31e0cb29a)

It looks like this in the dapp, at ActionPageMotionContent.tsx
![Image](https://github.com/JoinColony/colonyCDapp/assets/64402732/89aef9f1-710c-4f3c-80ff-e9e2087a4fb7)

**Comment by rdig** [comment]
Note that we'll have to eventually also store the annotation data on IPFS to accommodate the decentralized part of the CDapp.

Please that into account when designing the data model _(if necessary, might not be)_

**Comment by willm30** [comment]
Work on this should wait until we've had a call to sync on the best approach.

**Comment by willm30** [comment]
Work on annotations completed and merged
