### ISSUE TITLE
[C2F] Formatting on IBAN input and correct error validation UX

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2961]
## Description
There is no validation on incorrect formatting for the IBAN input field when the CTA button is selected, and only shows after it's been selected with a toast, which is inconsistent with the rest of the validation UX and does not indicate to the user what specifically the issue is and how to resolve it.

Example: When I enter (dummy data for screenshot purposes) IBAN details in that follow the format from my bank which includes spacing, no validation is shown upon selecting the CTA:

<img width="467" alt="image" src="https://github.com/user-attachments/assets/c8505305-3415-4a23-bc8e-21fc1fdfa1b4">

Toast with generic error:

<img width="463" alt="image" src="https://github.com/user-attachments/assets/b1903930-e125-49b9-9e56-5e98d274b619">

However, if I input the incorrect SWIFT format, validation is provided.

<img width="545" alt="image" src="https://github.com/user-attachments/assets/d79bc79b-2860-444b-b1e8-e3cf7ce89e71">

### **Scope:** 
Add validation to match the accepted IBAN format from the API (no spacing between numbers and digits). Add inline to the form when the CTA is selected to ensure consistency in the error state UX.

Remove the toast validation. 

All updates should be made across all responsive sizes.

**Comment by melyndav** [comment]
Related issue: #2963

**Comment by rdig** [comment]
Two things here:
- we'll need specs for IBAN validation _(alternatively we'll need more time to research the ISO standards)_
- the toast validation still needs to be present, since we need to capture any errors communicating with the bridge API

**Comment by melyndav** [comment]
@rdig good point. We will confirm with the API what the validation for the spec.

**Comment by arrenv** [comment]
I have run a couple of tests on the API, and it seems as though the API requirements are:
- "Must be alphanumeric, without spaces."

This seems only relevant for `iban.account_number` and `iban.bic`. Spaces did not seem to be an issue for US accounts.

**Comment by rdig** [comment]
There's 3 things to consider here:
- bridge's requirements
- actual [IBAN ISO 13616 (revised edition)](https://cdn.standards.iteh.ai/samples/81090/ab77d634b898429f99ee4b13ab8ffe8a/ISO-13616-1-2020.pdf) standard format
- our specs

Because in the end it only matters what we want to validate against, since we can have a setup like this:
1. validate IBAN using our spec (let's say something more complex, five groups of four chars, first group needs to contain letters at position 0 and 1 -- country, followed by two numbers, then the remaining four groups must include only numbers)
2. after we validate the above, we can format it in a format that bridge accepts (in this case, basically just remove the spaces)

As long as we come up with specs for validation, we're all good to go

**Comment by arrenv** [comment]
@rdig Great, that gives us more freedom on our side. He is the spec.

- Account type: US
    - Account number
        - Must be alphanumeric.
            - Validation message: “Please enter only letters and numbers.”
        - Spaces should be supported, allowing users to easily copy and past in values.
        - Should validate the length to be between 6 to 17 digits as of general practices influenced by guidelines from NACHA and the UCC.
        - Attention should be given to ensuring the API sent values are formatted to abide by the service provider API requirements.
    - Routing number
        - Must be alphanumeric.
            - Validation message: “Please enter only letters and numbers.”
        - Spaces should be supported, allowing users to easily copy and past in values.
        - Should validate the length to be exactly 9 digits as defined by the ABA Routing Number Policy and guidelines from the Federal Reserve.
        - Attention should be given to ensuring the API sent values are formatted to abide by the service provider API requirements.

- Account type: IBAN
    - IBAN
        - Must be alphanumeric.
            - Validation message: “Please enter only letters and numbers.”
        - Spaces should be supported, allowing users to easily copy and past in values.
        - Should validate the length to be a minimum of 15 and a maximum of 34 alphanumeric characters as defined in ISO 13616-1:2007.
        - Attention should be given to ensuring the API sent values are formatted to abide by the service provider API requirements.
    - BIC
        - Must be alphanumeric.
            - Validation message: “Please enter only letters and numbers.”
        - Spaces should be supported, allowing users to easily copy and past in values.
        - Should validate the length to be 8 or 11 alphanumeric characters as defined in ISO 9362:2014.
        - Attention should be given to ensuring the API sent values are formatted to abide by the service provider API requirements.
    - Country
        - Selectable list including all ISO 13616-1 countries that officially use the IBAN system.
        - Countries should be in full name.
        - As the user types in a character, it should jump to best match countries in the list.
            - Matching should be by prefix search.

**Comment by arrenv** [comment]
Good pickup, I have updated it.

**Comment by jakubcolony** [comment]
@arrenv Spotted this while testing #3474, shouldn't both the account and routing numbers be digits only? From my research letters are not allowed.

**Comment by arrenv** [comment]
Thanks @jakubcolony, looks like a fell victim to some lazy cut and paste. Fixed now.

I have also added the SWIFT one one.
