### ISSUE TITLE
[Manage permissions]: wrong autofill role in action sidebar form

### ISSUE THREAD

**Issue by Nortsova** [JoinColony/colonyCDapp#2967]
## Steps to reproduce
1. Assign the Admin role to Amy for the Andromeda project.
2. Assign the Payer role to Amy for the General project.
3. Attempt to reassign the Payer role to Amy in the Andromeda project.

This issue is presents both in the master branch and in the multi-sig branch.

## Expected behaviour

1. Assign the Admin role to Amy for the Andromeda project.
2. Assign the Payer role to Amy for the General project.
3. The Admin role should be automatically filled.

## Actual behaviour

<img width="286" alt="image" src="https://github.com/user-attachments/assets/eaae2706-a653-4fc6-9f96-d2a4e558e05c">
<img width="616" alt="image" src="https://github.com/user-attachments/assets/c5cf45dd-0834-4859-a41a-edf02b06f42e">

## Suggestions (optional)
I believe this issue may occur because nested roles are handled differently on the frontend, using different helpers. It might be beneficial to unify the role management logic in one common place.

**Comment by rumzledz** [comment]
This is fixed as part of #2339
