### ISSUE TITLE
Approving tokens for staking fails with non colony created tokens

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2976]
## Steps to reproduce

1. Navigate to the Metacolony in production.
2. Open the UserHub.
3. In the Balance tab click the Activate button.
4. Try to activate some tokens.
5. Note the first transaction will fail.

Testing colony created native tokens is working fine.

It has worked for Shapeshift in the past with FOX, however, it is currently not working.

## Expected behaviour

* You should be able to approve and activate non colony created tokens in the Metacolony.

## Actual behaviour

* There is a transaction error when trying to approve and activate non colony created tokens for staking.

```
Send error: invalid BigNumber string (argument="value", value="[object Object]",
code=INVALID_ARGUMENT, version=bignumber/5.7.0)
```

![image](https://github.com/user-attachments/assets/89232334-316d-49f7-b398-ea20383b5b8a)

**Comment by rdig** [comment]
This was a issue related to Metatransactions specifically, yet your original bug  report makes no mention of that.

Please try to submit better bug reports as this caused me to lose significant time investigating related issues and delayed fixing this by quite a lot

**Comment by arrenv** [comment]
> This was a issue related to Metatransactions specifically, yet your original bug report makes no mention of that.
> 
> Please try to submit better bug reports as this caused me to lose significant time investigating related issues and delayed fixing this by quite a lot

Wouldn't this have involved me investigating the issue, all I did was report the bug, including the error and how to reproduce it. I followed the bug report template.
