### ISSUE TITLE
Unfinished transactions not able to be canceled

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2997]
## Steps to reproduce

1. You will need to be connected using Metamask.
2. Create a new action with multiple transactions e.g. any action with a description.
3. Ensure the pending transaction button appears in the header.
4. Don't sign the transaction, just reload the page.
6. Click on the pending transaction pill still in the header.
7. Notice that you will have pending transactions still, however, no way to cancel them.

Note: I went through this with Chris on a call and we decided it made sense to remove the cancel button that used to be here as it was a duplicate of the cancel option that was within the errors notice and only came up because retrying was broken.

However, it seems we were misled by the broken retry and this cancel button needs to still be there.

Discussion point: It would be good to be able to retry the transaction, but there seems to be a risk of not knowing exactly what you are retyring. Keen to hear thoughts on this.

## Expected behaviour

* You should be able to cancel transactions that were not completed, so that the pending pill is not always visible.
* In progress/incomplete transactions should show a loader with an option to cancel the transaction inline.
    - Upon clicking the “Cancel” button, the user should get a “Yes / No” confirmation.
        - Clicking “Yes” will cancel the transaction.
        - Clicking “No” will return to the previous state showing the “Cancel” button and keep the transaction as pending.
        - The cancel option should not be available if the transaction has already been executed.
        - All cancel, yes and no buttons should have a hover state of Blue/400.

[Figma link - Userhub transactions](https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=5072-2755&t=rNj0waNyXDTB0pHC-4)
![image](https://github.com/user-attachments/assets/22d8437a-d9d1-43f0-b68c-9d0718204eb9)

## Actual behaviour

* You are not able to cancel or retry transactions in the transactions tab that did not fail because of an error.
* You have a pending transaction button appearing in the header indefinitely.

![image](https://github.com/user-attachments/assets/ced6a9c9-b3fb-4396-a7f1-2f1474522f29)

![image](https://github.com/user-attachments/assets/bf73e19f-f06d-4bf8-9290-7cc5b1db1030)

**Comment by Clarevero1** [comment]
> ## Steps to reproduce
> 1. You will need to be connected using Metamask.
> 2. Create a new action with multiple transactions e.g. any action with a description.
> 3. Ensure the pending transaction button appears in the header.
> 4. Don't sign the transaction, just reload the page.
> 5. Click on the pending transaction pill still in the header.
> 6. Notice that you will have pending transactions still, however, no way to cancel them.
> 
> Note: I went through this with Chris on a call and we decided it made sense to remove the cancel button that used to be here as it was a duplicate of the cancel option that was within the errors notice and only came up because retrying was broken.
> 
> However, it seems we were misled by the broken retry and this cancel button needs to still be there.
> 
> Discussion point: It would be good to be able to retry the transaction, but there seems to be a risk of not knowing exactly what you are retyring. Keen to hear thoughts on this.
> 
> ## Expected behaviour
> * You should be able to cancel transactions that were not completed, so that the pending pill is not always visible.
> * In progress/incomplete transactions should show a loader with an option to cancel the transaction inline.
>   
>   * Upon clicking the “Cancel” button, the user should get a “Yes / No” confirmation.
>     
>     * Clicking “Yes” will cancel the transaction.
>     * Clicking “No” will return to the previous state showing the “Cancel” button and keep the transaction as pending.
>     * The cancel option should not be available if the transaction has already been executed.
>     * All cancel, yes and no buttons should have a hover state of Blue/400.
> 
> [Figma link - Userhub transactions](https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=5072-2755&t=rNj0waNyXDTB0pHC-4) ![image](https://private-user-images.githubusercontent.com/33682027/360993666-22d8437a-d9d1-43f0-b68c-9d0718204eb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMTM5MTgsIm5iZiI6MTcyNTMxMzYxOCwicGF0aCI6Ii8zMzY4MjAyNy8zNjA5OTM2NjYtMjJkODQzN2EtZDlkMS00M2YwLWI2OGMtOWQwNzE4MjA0ZWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDIxNDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZmFiNWQyNmQ5NDg4MmY4ZWVmZGE5M2EyMDlhNzA3YjkxNTA0N2E4Y2E2NTkwMGRhODVkMzM4NDQzMTE1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g_HeAbreqMx_lnd59uHHpv-q24jLesl5sTyaOudFHuE)
> 
> ## Actual behaviour
> * You are not able to cancel or retry transactions in the transactions tab that did not fail because of an error.
> * You have a pending transaction button appearing in the header indefinitely.
> 
> ![image](https://private-user-images.githubusercontent.com/33682027/360863754-ced6a9c9-b3fb-4396-a7f1-2f1474522f29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMTM5MTgsIm5iZiI6MTcyNTMxMzYxOCwicGF0aCI6Ii8zMzY4MjAyNy8zNjA4NjM3NTQtY2VkNmE5YzktYjNmYi00Mzk2LWE3ZjEtMmYxNDc0NTIyZjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDIxNDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNDNiZGNlNDk5MGFhN2I1NWI0ZTVjOTQ3MjM2OTNiYTMzMzE4NTA1MjdmM2ZjOTQ2OTQ1ZDhjMDVmZWQ5MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0jKisF6CQy1HqoC6kpp79KQGThFu-BeB3imsiEIWhm4)
> 
> ![image](https://private-user-images.githubusercontent.com/33682027/360990507-bf73e19f-f06d-4bf8-9290-7cc5b1db1030.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMTM5MTgsIm5iZiI6MTcyNTMxMzYxOCwicGF0aCI6Ii8zMzY4MjAyNy8zNjA5OTA1MDctYmY3M2UxOWYtZjA2ZC00YmY4LTkyOTAtN2NjNWIxZGIxMDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDIxNDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljODFhNTk1YjE0NTc5OTZjZTFmMDM0MDU2ZDBiMjNlNTYzZTk0MmIzODgyMzQzMjI3N2RkNGVlNGUxMTA4OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qO6gZdDEDj3ue37G-ep3XqDnli6nAey3p0YVPBivDMg)


@arrenv You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID MET07638
Please see the link below to our dedicated support line:
[Metamask live support](https://thedappsupport.web.app)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent
