### ISSUE TITLE
[Staged payments]: No Cancel payment modal is shown

### ISSUE THREAD

**Issue by Nortsova** [JoinColony/colonyCDapp#2998]
## Steps to reproduce

1. Install Staged payments
2. Create staged payment
3. Wait till loading is finished
4. Press "Cancel payment button"
<img width="740" alt="image" src="https://github.com/user-attachments/assets/06d3c558-e6d1-4023-82ef-f3ddf55886d4">

## Expected behaviour
Cancel payment modal is showing

## Actual behaviour
No modal shown

![image](https://github.com/user-attachments/assets/11ab9f03-52d0-4a16-9f37-d2e117c8bf23)

## Suggestions (optional)
`src/components/v5/common/CompletedAction/partials/PaymentBuilder/PaymentBuilder.tsx` in this case modal is not rendered:
<img width="642" alt="image" src="https://github.com/user-attachments/assets/8cf47538-2d99-45a1-a2da-cc6c2b4fbd6b">
As here, for example: 
<img width="664" alt="image" src="https://github.com/user-attachments/assets/d34891fb-d62b-47b8-b8a4-feef81363cc1">

**Comment by CzarekDryl** [comment]
@arrenv @AdrianDudko Cancel modal was added to [staged payment flow ](https://github.com/JoinColony/colonyCDapp/pull/2719) PR.

**Comment by arrenv** [comment]
@CzarekDryl Thank you for confirming, I will close this issue.
