### ISSUE TITLE
Notifications: Create Magicbell user

### ISSUE THREAD

**Issue by davecreaser** [JoinColony/colonyCDapp#3004]
### Story

As a *user*, I need a *user created for me in Magicbell*, so that *the Magicbell system can send me notifications in the Colony App*

### Description

Each user in our system should have a corresponding user in the magicbell system, so that we can send notifications to them. The magicbell user must have a unique user id, which in our case can just be the wallet address.

When the app loads / users log in, we should check if the user has a notifications data object with a Magicbell unique user ID. If not, then it means that they have not yet had a Magicbell user made. In this case, we should create the user, and then once that has finished, update the user in our system to include notifications data with their Magicbell unique user ID.

### This issue is complete when...

- [ ] Users have Magicbell users created for them if needed when the app loads / they log in.

**Comment by rdig** [comment]
Closed by #3045
