### ISSUE TITLE
Notifications: Render a list of notifications

### ISSUE THREAD

**Issue by davecreaser** [JoinColony/colonyCDapp#3007]
### Story

As a *user receiving notifications*, I want to *see my list of notifications*, so that *I am informed about what is going on in my colonies*

### Description

When a user opens the notifications list from the user hub, they should see a list of all of their notifications. The list should ideally use pagination or lazy loading as you scroll so it doesn't load everything at once. This ticket includes all screen sizes, but does not include marking as read, or the indicator for how many unread notifications there are.

### Design

[Figma link](https://www.figma.com/design/0Fi3AaDlr3LAXBfsOXBGyk/User-Account?node-id=6754-9622&t=DbRYLaxphOdTpK4N-4)

![Image](https://github.com/user-attachments/assets/00f102f5-77cc-4a89-b8e9-b9f08770fd7f)

### This issue is complete when...

- [ ] Users can browse a list of their notifications.

### Suggestions 

* It is probably a good idea to use the Magicbell in built components / hooks / contexts for this. In my prototype I had a lot of success using `MagicBellProvider` to wrap the app in a Magicbell context, as well as `useNotifications` from Magicbell to fetch the notification store, and the `NotificationList` component to handle the infinite scrolling etc.

**Comment by rdig** [comment]
Closed by #3167
