### ISSUE TITLE
Notifications: Send notification on simple payment made with permissions

### ISSUE THREAD

**Issue by davecreaser** [JoinColony/colonyCDapp#3010]
### Story

As a *user*, I want to *receive a notification when a simple payment is made*, so that *I am kept informed*

### Description

When a simple payment is made using permissions decision method, a notification should be created in Magicbell. The recipients of this notification should be everybody who is in the colony who has notifications turned on, and does not have this colony muted, as well as a separate notification for the recipient of the funds.

### This issue is complete when...

- [ ] Notifications are created when a simple payment is made with permissions

### Suggestions (optional)

* In my opinion, this notification should be sent from the block ingestor.

**Comment by rdig** [comment]
Closed by #3055
