### ISSUE TITLE
UserHub Transactions Errors Styles Break on Medium Viewport Width

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyCDapp#3056]
When viewing the UserHub transactions list at a resolution above `720px` and below `768px`, the error state for the transaction gets wrapped up almost on a single vertical line _(see screenshot)_.

This is most likely the fault of some `flexbox` configuration that acts upon this resolution range and does not shrink accordingly

![Screenshot from 2024-09-03 12-48-18](https://github.com/user-attachments/assets/3015cf1d-f9cd-4668-a687-e75cc0e2b4d5)

I do want to note however that anything below `720` and above `768` works as expected

![Screenshot from 2024-09-03 12-48-10](https://github.com/user-attachments/assets/2adce4d8-414a-4d93-a6f7-7b9337fe932f)
![Screenshot from 2024-09-03 12-48-45](https://github.com/user-attachments/assets/6272ddcc-7923-43d2-a7c8-db734a56c7c9)

**Comment by Ashit743** [comment]
@rdig I would love to work on this bug, I am new to this code base could you describe steps for reproduction, thanks!

**Comment by Ashit743** [comment]
@rdig, I'll start working on this.
