### ISSUE TITLE
It is impossible to assign permissions to a user in the root domain if they already have permissions in a sub-domain

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#3070]
## Steps to reproduce

Step 1 - Assign 'Payer' permissions to Fry in Andromeda
Step 2 - Create a manage permissions action and attempt to assign 'Admin' permissions to Fry in General

## Expected behaviour

It should be possible to submit the form without validation errors.

## Actual behaviour

The "This user already has these permissions" shows.

<img width="674" alt="Screenshot 2024-09-10 at 10 52 50" src="https://github.com/user-attachments/assets/0f40907d-150e-4c3b-8182-b4935c2228e9">

## Suggestions (optional)

@rumzledz has done a lot of work on this lately and it has been working previously, possibly broken by a multi-sig rebase before it was merged. Hopefully an easy fix 🤞

**Comment by Nortsova** [comment]
Hey I tested it and what I see:

Payer permissions in Andromeda
<img width="860" alt="image" src="https://github.com/user-attachments/assets/88751c33-c241-441b-8c0a-d6f6ca9ddb80">
Admin permissions in General
<img width="868" alt="image" src="https://github.com/user-attachments/assets/6b08e6ad-de65-4f17-885f-10449103ab7f">

But I believe these test steps don't include a "redo" button, that actually causing this issue: https://github.com/JoinColony/colonyCDapp/issues/3344

**Comment by iamsamgibbs** [comment]
Thanks @Nortsova - looks like this has been resolved at some point!

I've tried recreating the original issue as described, tested using the redo button, tested with and without the multi-sig extension installed and I can't recreate it. So I will close the issue, especially as there are a couple of other permission form issues open.
