### ISSUE TITLE
[Navigation] UI/UX feature branch review

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3086]
## Description 

Really fantastic work @rumzledz, @Nortsova  & @iamsamgibbs  and everyone else who has contributed and reviewed the [ui/new-navigation-ui] branch. I've reviewed the work completed to-date, with the following minor UI/UX requests identified.

Not tested: 
- Help & feedback component 
- Dark mode
- User account nav + tab removal

## Inside a Colony

1. I changed the colony name, but the nav or the switcher did not update across any size.

<img width="613" alt="image" src="https://github.com/user-attachments/assets/2000a696-3bb2-464e-bd3c-8abc252eebbb">
<img width="499" alt="image" src="https://github.com/user-attachments/assets/f2fc6bd4-e6b0-4bf8-816d-620ad0dd2c04">

Mobile:
<img width="514" alt="image" src="https://github.com/user-attachments/assets/4200d9a4-3396-407d-be98-e2a36f7a9f8a">

---

2. When the switcher is active on the desktop version, the highlight on the left side nav bar should remain active in the select state. Currently, it only shows on hover. 
<img width="508" alt="image" src="https://github.com/user-attachments/assets/b1e6142c-dbc6-41c6-b04c-c3c3446e3e8d">

---

3. The padding between the colony switcher and first nav item should be 32px + the additional top padding on the first navigation item that handles the hover on desktop:
<img width="348" alt="image" src="https://github.com/user-attachments/assets/d18cafee-5f51-45c7-a9d0-915d432a9a32">

---

4. Activity feed should be 'Activity' as per Figma across all sizes.

<img width="482" alt="image" src="https://github.com/user-attachments/assets/ad4ebaec-ee7e-48d1-88db-6c7780e9a3ca">

---

5. The padding between the navigation and main content should be maintained at 32px as per production on desktop. 

<img width="318" alt="image" src="https://github.com/user-attachments/assets/744b8aa4-375a-4d70-b9d7-44f1ae198ca2">

---

6. There's additional padding around the content container, causing the actual content to display at 1096px.

<img width="1669" alt="image" src="https://github.com/user-attachments/assets/18c6cdc3-4cb1-4808-b751-320e4e6acec7">

---

7. The number of contributor cards on the members page at desktop/tablet sizes should be reduced to from 4 to 3 as per the original designs to accommodate the extra width of the nav and reducing any issues with permission pills in the individual member cards:

https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=4481-10663&t=IWFwNfDd3Nnbi4w7-4

---

8. I updated the colony logo, but the switcher logo didn't get updated after completing the action:

<img width="707" alt="image" src="https://github.com/user-attachments/assets/b0bc5d21-a52a-4f75-9611-9c71e5c60235">

Even with a reload or colony switch, the logo doesn't update:

<img width="515" alt="image" src="https://github.com/user-attachments/assets/5586d61e-419e-43ec-be6c-7a794772ce8c">

On mobile:

<img width="464" alt="image" src="https://github.com/user-attachments/assets/e2c93c04-81ef-42bf-8570-fe9e5376d63f">

---

9. On mobile, when I select the 'Finances' dropdown, the menu closes and takes me to the 'Balances' page without allowing me to see the menu items below the Finances section first. I can't get to incoming funds unless I go back into the menu again.

---

10. The 'Create new colony' button doesn't work on all sizes.

<img width="501" alt="image" src="https://github.com/user-attachments/assets/723a7eb9-3dad-4120-9056-4b8d955cdb49">

---

11. Padding between page title and content doesn't match Production on desktop. 

<img width="1441" alt="image" src="https://github.com/user-attachments/assets/45e91d11-64b2-4c49-81ed-decbe457a215">
 
 
Every inside page should be consistent with 32px as per Figma:
 
<img width="1388" alt="image" src="https://github.com/user-attachments/assets/d8d5a697-29f8-46e8-bf32-ebac579b5b7a">

---

12. The very top container padding has also been changed too and is causing padding misalignment of the user pills on the top right when an action is triggered.

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/e2a9aef9-bbb8-4adc-ae20-13a9b82b29ff">

<img width="718" alt="image" src="https://github.com/user-attachments/assets/423a0369-107c-42b2-8ccd-25bd522bff35">

As per production:

<img width="1484" alt="image" src="https://github.com/user-attachments/assets/c69876d9-4ecf-416a-9d8f-08177f2756fb">

## Outside the colony (wallet disconnected)

1. The styling of the disconnected icon is slightly off compared to Figma.

<img width="106" alt="image" src="https://github.com/user-attachments/assets/761ffcbc-4498-4117-8856-e0473d42d8fe">

---

2. On mobile, there's some funky duplication of menu items on the settings pill (which may need to be a separate PR). 

<img width="466" alt="image" src="https://github.com/user-attachments/assets/732cb172-d701-4b11-8a78-a626424a2058">

## Outside a Colony (no colonies joined or created)

1. The styling of the 'No colonies joined' including padding and the icon should match Figma. Also, the button doesn't go anywhere. 

<img width="388" alt="image" src="https://github.com/user-attachments/assets/95cf984d-614a-4164-9049-e139c93329dd">

Also on mobile:

<img width="516" alt="image" src="https://github.com/user-attachments/assets/98d80318-c316-478c-83a8-3bc14a989c47">

**Comment by rdig** [comment]
Hey @melyndav great extensive review. Can you please move this to the feature branch PR itself? https://github.com/JoinColony/colonyCDapp/pull/2911

That way nothing gets lost in between all the issue, and this way, the issues raised here can be tackled as part of the whole feature, and not a separate issue on itself.

**Comment by melyndav** [comment]
@rdig no problems! I've added the review there and will close this. Thanks!

**Comment by rdig** [comment]
I already said there https://github.com/JoinColony/colonyCDapp/pull/2911#issuecomment-2348989584 but I'll say it here as well. Thank you so much! :)
