### ISSUE TITLE
`useCurrentBlockTime` hook is broken in dev

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#3113]
## Steps to reproduce

The issue is most notable in streaming payments, however it should be also reproducible on `master`:

1. Create an advanced payment.
2. See errors in the console:

<img width="633" alt="image" src="https://github.com/user-attachments/assets/3e0385ca-980f-4f3c-b746-8063db0a36be">

Looks like `ethersProvider` is missing `getBlock` method after changes from https://github.com/JoinColony/colonyCDapp/commit/fec0d0a6e9dd5d609dd3d7c1e9e5b0a55fefef8f.

**Comment by Nortsova** [comment]
Without error: 
Login to wallet (could be dev wallet)
Reload page
Create advance payments (usually error shown on the last screen)
It will be no error

To see error:
Reload page
Disconnect wallet
Connect wallet
Create advance payments (usually error shown on the last screen)
See error in console

![getblock-error](https://github.com/user-attachments/assets/dcfb39ec-a810-4bf5-bc47-3b6896801db8)

**Comment by jakubcolony** [comment]
To add onto @Nortsova's findings, it seems to have been an existing issue when you reconnect your wallet, however before the changes from the aforementioned commit, it would start working again after a page refresh. After the changes the issue persist across page refreshes.
