### ISSUE TITLE
[Dashboard] Top contributors chart values don't add up to 100%

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#3119]
### Issue
We need to check from where this rounding issue is coming from, given the sum of all values shown in the chart don't add up to 100%.

Eg. 
![Image](https://github.com/user-attachments/assets/91827989-2429-4214-880a-1b5af8ef52b7)
The sum of reputations will add up to 99.97%

### Implementation details
We need to check where the reputation is computed - probably in the `updateContributorsWithReputation` lambda

### This issue is complete when...

- [ ] The reputation percentages shown in the chart add up to 100%

**Comment by mmioana** [comment]
Depends on https://github.com/JoinColony/colonyCDapp/issues/2861

**Comment by chmanie** [comment]
I assigned myself as this is the last issue in this cycle that doesn't have an owner yet :D

**Comment by chmanie** [comment]
I would suggest to not touch the lambda as this is a UI issue based on how we present the numbers (2 digits). I'll try to apply your suggestion to add the remaining bits to the biggest number

**Comment by mmioana** [comment]
Totally agree with you it's better to do the change in the UI - the implementation details was more of a thought.

So this problem could arise even if there are more contributors/teams than 4.
Consider for eg. having these reputation values 

```
[
    84.0685,
    6.89305,
    1.23005,
    1.5565,
    1.04601,
    1.0505,
    1.05,
    1.0005,
    0.84089,
    0.60039,
    0.500005,
    0.161605,
]
```
or even these
![Screenshot 2024-09-24 at 10 21 15](https://github.com/user-attachments/assets/1c63bc29-5f8d-4425-b2d9-dd693f125ada)

So we should make sure for the entire array of chart data, the values are adding up to 100%
