### ISSUE TITLE
The team filter dropdown is showing elements behind it

### ISSUE THREAD

**Issue by rumzledz** [JoinColony/colonyCDapp#3127]
## Steps to reproduce

1. Check out to a branch that is based on `feat/enhanced-dashboard`
2. Go to the Colony Dashboard
3. Narrow down the browser width so some of the team buttons are hidden
4. Click the team filter ellipsis

## Expected behaviour

The background colour should be #FFFFFF

![image](https://github.com/user-attachments/assets/3a5885e9-4582-4f5e-b5c5-f3850215a312)

## Actual behaviour

There is no background colour and so the components behind them are visible:

![Screenshot 2024-09-18 at 21 36 14](https://github.com/user-attachments/assets/f849152b-af58-4e07-910c-f4f06b5110e4)

Either that or maybe it's a z-index thing?

**Comment by rdig** [comment]
closed by #3177
