### ISSUE TITLE
Add action panel and timeline skeleton loading state

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3129]
Teamwork task: [Add action panel and timeline skeleton loading state](https://tw.auroracreation.com/#/tasks/16079633)

### Description

In order to improve the experience for users during general app usage and in this spec specifically the loading of the action panel, we would like to add a skeleton loader to the action panel content and timeline.

Currently, the action panel has two separate loading spinners for actions, once for the whole action panel, and another for the timeline, leading to a incongruent experience every time you open the panel.

![image](https://github.com/user-attachments/assets/2a2d0652-ad20-42f4-874d-08756cccf723)

![image](https://github.com/user-attachments/assets/cf9347c4-d3ad-42f5-a7d4-62a3af8a3fff)

### Design

[Figma link - Action panel loading state](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?node-id=26993-210663&t=Warn18mp4NDAa8O0-4)

![image](https://github.com/user-attachments/assets/25bdcb90-130f-4ef2-828f-1444897ea64e)

## Acceptance criteria
- [ ] Remove existing spinners.
    - [ ] The initial full panel spinner and loading text should be removed.
    - [ ] The initial loading spinner in the action timeline should be removed.
- [ ] New skeleton loader.
    - [ ] The action panel opens with a more congruent skeleton loading state as designed.
    - [ ] The action content can still load in before the action timeline.
    - [ ] Responsiveness is handled with consistency to mobile designs.
    - [ ] The skeleton loader should not increase the loading at all.
    - [ ] The skeleton loader should appear right away.

**Comment by AhmadMahmoodRana** [comment]
download
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)
