### ISSUE TITLE
[Dashboard] Cron lambda triggered as expected

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#3130]
This issue is only for deploying the cron lambda to QA env to check the cron lambda developed for storing the previous balance [2858](https://github.com/JoinColony/colonyCDapp/issues/2858) gets triggered on the cron schedule

```
 "DailyScheduleRule": {
            "Type": "AWS::Events::Rule",
            "Properties": {
                "ScheduleExpression": "cron(0 1 * * ? *)",
                "Targets": [
                    {
                        "Arn": {
                            "Fn::GetAtt": [
                                "LambdaFunction",
                                "Arn"
                            ]
                        },
                        "Id": "ScheduledLambda-cacheDomainBalance"
                    }
                ]
            }
        },
```

**Comment by rdig** [comment]
Don't really feel good raising Dev issues for Devops tasks.

In lieu of anything else we might use this, although it's not really fit for purpose. 

I'm sure we can do better here.

**Comment by mmioana** [comment]
@rdig should I transfer this issue?

**Comment by mmioana** [comment]
I'm putting this on hold until we have the green light to deploy to `QA`

However I did create a test cron lambda, and the condition seems to be legit, as well as the `LambdaInvokePermission`

**Comment by rdig** [comment]
Closed as it was deployed
