### ISSUE TITLE
[Dashboard] Reputation chart legend improvements

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#3135]
For smaller desktop viewport, the legend takes more than 2 rows of legend items

![Image](https://github.com/user-attachments/assets/0d3b069b-9662-4ace-b2a4-ac261c9990f1)
![Image](https://github.com/user-attachments/assets/2393797d-d50d-4029-a89d-41bdf599902f)

@arrenv I tried to tackle in this PR [3116](https://github.com/JoinColony/colonyCDapp/pull/3116) truncating the team/contributor name if it takes more than `12` characters (if we assume to have `20` characters and have letters that take more space, for sure we'll end up not being able to show more than 2 teams)

So I created this issue to define how we want to proceed for the legend items to tackle all possible edge cases if we want only 2 rows of legend items

**Comment by chmanie** [comment]
I can take this once we have more info.

**Comment by mmioana** [comment]
After talking with @arrenv, on smaller desktops (and even on mobile), it will not be a problem to have more than 2 rows for the legend items, given the reputation card shrinks based on the available container space (1/3 on desktop), so I will close this issue @chmanie 😁
