### ISSUE TITLE
Streaming animation decimals length

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3139]
Teamwork task: [Streaming animation decimals length](https://tw.auroracreation.com/#/tasks/16079632)

## Steps to reproduce

1. Create a stream with a decimal rate per second.
2. Note the animation of the Available to claim for the stream.

## Expected behaviour

* Zeros should still be shown in the streaming animation for a smoother animation. As of the example - https://codesandbox.io/p/sandbox/bold-feather-xfh4q3

[streaming-animation-example.webm](https://github.com/user-attachments/assets/99171d05-24ec-4593-b8e0-ff9f6fbc0ed4)

## Actual behaviour

* The number of decimals are changing in the streaming animation, resulting in the jumping animation.

[streaming-animation.webm](https://github.com/user-attachments/assets/0ef91717-b52d-4177-ad31-2eba82960e3a)

**Comment by joanna-pagepro** [comment]
It will be fixed in this PR - https://github.com/JoinColony/colonyCDapp/pull/3018

**Comment by AdrianDudko** [comment]
@arrenv FYI,  as @joanna-pagepro mentioned above, this should be done in https://github.com/JoinColony/colonyCDapp/pull/3018 (merged) . Let me know if you still see problem reported in this issue.

**Comment by AdrianDudko** [comment]
@arrenv let me know if this one can be closed :)

**Comment by arrenv** [comment]
Yep, looks solved, closing now.
