### ISSUE TITLE
Handling duplicate staged payment releases

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3144]
Teamwork task: [Handling duplicate staged payment releases](https://tw.auroracreation.com/#/tasks/16079630)

## Steps to reproduce

1. Create a new Staged payment.
2. Pay one of the milestone payment using Reputation.
3. Go through the motion process to Support, but don't finalize the motion.
4. Create another payment for the same milestone using Permission.
5. Now, return to the previous motion and finalize it.
6. Note, after the transaction completes the milestone payment will disappear.

## Expected behaviour

* You should be able to see the history of all milestone payments in the action timeline.
* You should be able to see which decision method was used for each milestone payment made.

## Actual behaviour

* You are not able to see all payment actions made for the same staged payment item.
* History in the timeline is going missing.

[multiple-staged-step.webm](https://github.com/user-attachments/assets/5bb7ccd5-3f87-4d35-b659-898a9339a8fe)

**Comment by CzarekDryl** [comment]
@arrenv It seems to me that this was corrected by Jakub during the staged payment refactor. Could you please check this?

**Comment by arrenv** [comment]
Yes, confirming this issue has been resolved. Closing now.
