### ISSUE TITLE
FEATURE: Help & Feedback Widget functionality

### ISSUE THREAD

**Issue by rumzledz** [JoinColony/colonyCDapp#3148]
## Description

We are currently using [Intercom](https://www.intercom.com/) as our way to get feedback and messages from our users and we are using Google Tag Manager to integrate their app into ours. With the current setup, all we have to do is provide a value for the `GOOGLE_TAG_MANAGER_ID` env variable to enable the integration.

This Issue is about having our own custom triggers for displaying their widget. This will not cover extra/custom functionalities within their widget.

## Acceptance Checklist

* [ ] Clicking the Help & Feedback button should toggle the Intercom widget
* [ ] Clicking outside Widget should dismiss it
* [ ] If the integration is blocked, clicking the Help & Feedback button should take the user to https://help.colony.io/ on a new tab

**Comment by rdig** [comment]
Closed by #3159
