### ISSUE TITLE
Crypto to fiat: IBAN error clarification

### ISSUE THREAD

**Issue by Nortsova** [JoinColony/colonyCDapp#3158]
## Steps to reproduce

1. Pass KYC and go to the bank details form
2. Fill IBAN with account number (without country code)
3. See an error
![image](https://github.com/user-attachments/assets/94644b45-ec13-4331-a781-c1a05e780e3e)

## Expected behaviour

If country code was not provided show an error: "IBAN should start with a 2 letter country code"

## Actual behaviour

Generic error:
![image](https://github.com/user-attachments/assets/94644b45-ec13-4331-a781-c1a05e780e3e)

P.s. this error text approved by @melyndav

**Comment by rdig** [comment]
This will be solved by #2961 

Closing
