### ISSUE TITLE
[Dashboard] Newly created transaction remove previous query param

### ISSUE THREAD

**Issue by Nortsova** [JoinColony/colonyCDapp#3176]
## Steps to reproduce
![query-string-cleaned](https://github.com/user-attachments/assets/bc3fc382-63da-407b-b233-7b38ce9fe3b7)

1. Navigate to the dashboard and select the team (domain id = 2) 
2. Create any transaction
3. After a new transaction is created it has the "tx={hash}" query string
4. And this new query string removed the "team=2" query
5. This means after new transaction is created and the motion modal is closed you would be redirected to the general, not selected domain 

## Expected behaviour
- Selected team and query string for team should not disapear

## Actual behaviour
- New tx=hash rewrite previous team=2 param

## Suggestions (optional)
Instead of navigating and creating new URL we can just use URLSearchParams to add new param, and we can unify this solution for all actions:
<img width="352" alt="image" src="https://github.com/user-attachments/assets/9a05d9b7-dfe7-4263-9a96-50f8776990ef">

**Comment by rdig** [comment]
Closed by #3200
