### ISSUE TITLE
Whole app rerender on state change

### ISSUE THREAD

**Issue by Nortsova** [JoinColony/colonyCDapp#3179]
## Steps to reproduce

1. Add console log to `src/Entry.tsx`
2. Add console log to `src/routes/Routes.tsx` 

![rerender-bug](https://github.com/user-attachments/assets/63b52ae8-5648-4efa-b96d-954037080201)

## Expected behaviour
The app shouldn't trigger rerendering components if the state was not changed

## Actual behaviour
Every component rerendered

## Suggestions (optional)
This is quite a wide task, and we probably shouldn't memoize everything in our app, but if we could find a nice solution to it - that would be great!

**Comment by rdig** [comment]
Closed by #3178
