### ISSUE TITLE
Notifications: Incoming funds claimed notification

### ISSUE THREAD

**Issue by davecreaser** [JoinColony/colonyCDapp#3190]
### Story

Example: As a *user with notifications enabled*, I want to *see a notification when incoming funds are claimed in my colonies*, so that *I am kept informed about the balance of my colonies updating*

### Description

When incoming funds are claimed by a colony, a notification should be sent to any users in the colony who have notifications enabled, and this colony not muted.

### This issue is complete when...

- [ ] A notification is sent to colony users when incoming funds are claimed

**Comment by bassgeta** [comment]
Bumped it to an 8 @davecreaser since for us to exclude minting tokens, we need to do some digging/refactoring for motion creation to use multi-call, since we currently claim funds after we finalize a mint tokens motion.
Gonna try and do that via a multicall and see what happens!
