### ISSUE TITLE
Notifications: Clicking a notification should take it to the relevant action

### ISSUE THREAD

**Issue by davecreaser** [JoinColony/colonyCDapp#3194]
### Story

As a *user receiving notifications*, I want to *be taken to the relevant action when I click a notification about an action*, so that *I can see more details about the action*

### Description

When a user clicks on an action or mention notification, it should open the relevant action in the action sidepanel, and at the same time, mark the notification as read.

### This issue is complete when...

- [ ] Action and mention notifications open the action sidepanel with the correct action when clicked

**Comment by rdig** [comment]
Closed by #3251
