### ISSUE TITLE
[Dashboard] fetchDomainBalance lambda returns values without decimals

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#3196]
I still can't get any value other than `.00` to show at the end of a payment, but as mentioned before I don't think that is related to any changes here and will hopefully be resolved by other branches getting merged in, so approving this one!

<img width="270" alt="Screenshot 2024-09-26 at 20 15 25" src="https://github.com/user-attachments/assets/5a59f660-8f77-4c73-b7a0-a25c8a2494fd">
<img width="268" alt="Screenshot 2024-09-26 at 20 16 17" src="https://github.com/user-attachments/assets/44d76173-d32c-4600-876c-712de2aa29ae">
<img width="267" alt="Screenshot 2024-09-26 at 20 17 01" src="https://github.com/user-attachments/assets/a623d4eb-81f8-4815-975a-808c189f8c23">
<img width="269" alt="Screenshot 2024-09-26 at 20 17 51" src="https://github.com/user-attachments/assets/bfee44e3-18c5-4212-b043-a251c475eb06">

_Originally posted by @iamsamgibbs in https://github.com/JoinColony/colonyCDapp/pull/3126#pullrequestreview-2332163959_

**Comment by rdig** [comment]
Closed by #3197
