### ISSUE TITLE
Port Over Colony Creation Wizard

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyCDapp#32]
- Port over the components
- Should live in `components/common`
- Determine if the wizard design refresh (ask Product about it) can be integrated in this issue, or will it require a separate one

Note that this is blocked by https://github.com/JoinColony/colonyCDapp/issues/30

**Comment by willm30** [comment]
@arrenv Should the wizard design refresh be incorporated into this issue, or should I open a separate one to handle later?

**Comment by rdig** [comment]
@willm30 note that:
- it no longer needs to include the "username" registration transaction (as that will be handled differently)
- note that this will need to pass an empty string to the `registerUserLabel` call for a colony name, as we are no longer registering them on chain
- pass an empty string for an IPFS metadata hash, as we are not registering them in the dapp
- ideally, this would just have to send the transactions out, without any graphql queries, but since the block ingestor who handles that part is not set up yet, you'll have to use the mutation to also create the colony _(copy the usage from the `temp-data-creation` script)_
