### ISSUE TITLE
[C2F] IBANs with spaces are accepted by the frontend but not by the backend

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyCDapp#3201]
When using spaces in the IBAN in C2F it passes the frontend validation but the backend (probably bridge) is erroring.

## Steps to reproduce

Probably impossible to reproduce locally as EUR payments are not possible in the sandbox.

We can however reproduce the following:

- Go through the C2F flow until you can add your IBAN (EUR)
- Paste an IBAN with spaces

## Expected behaviour

* The frontend should not allow spaces in the IBAN

## Actual behaviour

* The frontend is allowing spaces in the IBAN

**Comment by rdig** [comment]
Just a heads up yhat we have this issue that should account for and fix this #2961

So I'd say we should tackle the one I've linked to in lieu of this

**Comment by chmanie** [comment]
Oops didn't know the other one existed. Even better, closing this
