### ISSUE TITLE
[Dashboard] Pre-select actively selected domain in pages that have a domain filter

### ISSUE THREAD

**Issue by rumzledz** [JoinColony/colonyCDapp#3203]
## Description

When a user selects a team using the Team Filter, this filter should persist in other pages of the same Colony that are using the same Team Filter component.

## Acceptance Checklist

* [ ] The selected team in the Teams Filter should be pre-selected when visiting another page of the same Colony that uses the same Team Filter component
* [ ] The selected team filter should be cleared after visiting a non-Colony page or by visiting another Colony

**Comment by rdig** [comment]
Closed by #3204
