### ISSUE TITLE
[Dashboard] Team reputation widget meatball menu UI fixes

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#3210]
### Issue

The meatball menu should change when a parent team is selected, since the same menu items are not relevant to contributors/ members. It should show 'View members' that opens up the members page with the parent team filter already selected applied. 

Currently:
<img width="470" alt="image" src="https://github.com/user-attachments/assets/27437881-31d9-481e-b19a-8879fc0c871a">

Figma:
<img width="502" alt="image" src="https://github.com/user-attachments/assets/298bd87f-74c5-4f68-ae84-efc5502ada83">

Link in Figma: https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=6830-36359&t=cXj2gpagsBjz8b9Q-4

**Comment by rdig** [comment]
Closed by #3228
