### ISSUE TITLE
[Dashboard] Funds cards row UI/UX fixes

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#3213]
### Issues

- [x] The styling of the create team box such as the font size and padding between the icon should match Figma. 

Currently: 
<img width="298" alt="image" src="https://github.com/user-attachments/assets/da36423d-39b6-4811-90bf-61e550a447a3">

Figma:
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/85644397-9442-499f-b86f-2dbc8a028769">

---

- [x]  When individual teams are selected, they should go to the 'Balances' page with the selected team applied. Currently they just have a hover state and don't link anywhere.

<img width="549" alt="image" src="https://github.com/user-attachments/assets/5207a9c0-488e-4691-beff-f6568b9f38e3">

---

- [x]  The 'Create team' card shouldn't apply when a parent team is selected. It should only show where there are no parent teams in the colony.

Currently showing:

<img width="775" alt="image" src="https://github.com/user-attachments/assets/d1c60931-c313-4634-bfc7-e7114c93965e">

As per Figma:

<img width="1276" alt="image" src="https://github.com/user-attachments/assets/b7abf91c-0002-462d-b6dd-4e638adc328d">

**Comment by rdig** [comment]
Closed by #3236
