### ISSUE TITLE
[Dashboard] Team/domain filter UI fixes

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#3214]
### Issues

- [ ] On desktop, the padding below the team label doesn't match Figma and the text is positioned off centre. 

A comparison in Figma to help highlight the difference: 

<img width="1451" alt="image" src="https://github.com/user-attachments/assets/06c908ac-e5c2-4b28-b38a-15924c323f55">

1. The positioning of the top and bottom of the labels are different
2. The overall height is slightly different by a few pixels.
3. There is no gray border on the selected items with coloured backgrounds (screenshot below is showing border in local dev)
<img width="1035" alt="image" src="https://github.com/user-attachments/assets/9107987e-21d2-4d3d-a72e-7de715e168b2">
4. There is a missing hover state on 'All teams' and individual teams. Currently, there's only a hover state for the '+' menu item. 

---

- [ ]  On mobile, there should be no scroll bar showing at all (screenshot is in Firefox). 

<img width="544" alt="image" src="https://github.com/user-attachments/assets/45f272ba-355b-4403-8c25-95297057c44f">

<img width="599" alt="image" src="https://github.com/user-attachments/assets/89228da5-dbf8-486f-90d7-7309a9893207">

<img width="308" alt="image" src="https://github.com/user-attachments/assets/c970ed16-ca96-4018-8328-9d281451ca06">

As per Figma:

<img width="981" alt="image" src="https://github.com/user-attachments/assets/f1419d6a-beeb-4740-8a8d-50598f8b5e94">

---

- [ ]  On mobile, there are some styling issues on the two corner navigations.

<img width="79" alt="image" src="https://github.com/user-attachments/assets/ccf63dc7-6da5-453c-81dd-b1b8cdfb7a2b">

**Comment by rdig** [comment]
closed by #3233
