### ISSUE TITLE
[Dashboard] Other pages UI fixes

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#3219]
### Issues

- [x] All inside pages have lost their page titles on both desktop and mobile:

<img width="1428" alt="image" src="https://github.com/user-attachments/assets/e3e0fd9b-48b6-47a1-88d3-1a92d380c31d">

How they should sit per Figma:

https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=6760-67520&t=cXj2gpagsBjz8b9Q-4

How the padding should be:

<img width="1543" alt="image" src="https://github.com/user-attachments/assets/84c6cabf-5a66-40aa-baeb-fa44ec939a2c">

Link to Figma with redlines: https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=6760-57700&t=cXj2gpagsBjz8b9Q-4

---

- [x]  Additional padding has been added under subtitle sections between tables across most pages.

Currently in production, note the padding between the table title and filter section and the table content:

<img width="1367" alt="image" src="https://github.com/user-attachments/assets/4295060d-4852-4e9b-b6a6-791e1507b2b5">

Currently in this branch:

<img width="1336" alt="image" src="https://github.com/user-attachments/assets/908f17dc-4952-4abf-b73a-cbdc75e4b165">

What it should be as per the design system components:

<img width="1147" alt="image" src="https://github.com/user-attachments/assets/9ed8506b-c86e-405a-8c9d-73f48d4feab1">

 
 This needs correcting on both desktop and mobile on the following pages:
 
-  Balances
- Incoming funds
- Agreements

---

- [x]  When switching between 'Teams' and 'Incoming funds' the Team page content jumps despite having the same main container width. Recording for better display:

![Export-1727698014446](https://github.com/user-attachments/assets/e3198223-f5c6-45c0-9ded-1fd765ca1f01)

**Comment by Nortsova** [comment]
Last one is not an issue, it is just scroll appears on teams page:

![Image](https://github.com/user-attachments/assets/b971c54a-8aa8-4d01-900b-e6c8d5e29504)

**Comment by rdig** [comment]
Closed by #3257
