### ISSUE TITLE
Funding Advanced payment with a motion does not update

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3243]
## Steps to reproduce

1. Create a new Advanced payment action.
2. Go all the way through the Funding step.
3. Use the Reputation decision method to fund the payment.
4. Stake it 100% in Support.
5. Note the status of the motion does not update.

## Expected behaviour

* The staking widget should update on successful staking.

## Actual behaviour

* The motion status did not update and the staking widget remained in a disabled state after staking 100%.
* Closing the action and reopening it showed the correct state.

![image](https://github.com/user-attachments/assets/8eb0b43a-c6d9-4425-a785-46e274e8a545)

**Comment by jakubcolony** [comment]
@arrenv I tried replicating it on a couple of funding motions in different scenarios but could not reproduce. Are you seeing this issue consistently? 

https://github.com/user-attachments/assets/d18d8350-abeb-4a6c-8cfe-0e3e89429dc5

**Comment by arrenv** [comment]
Thank you @jakubcolony, I have tested this a few times now and it has not happened again. Closing for now.
