### ISSUE TITLE
Making payment twice after release

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3246]
## Steps to reproduce

1. Create a new Advanced payment action.
2. Complete the process all the way to the Release step.
3. Release the payment and complete the 2 transactions with the second being to release the available to claim funds.
4. Note the UI will update and close the modal, but the "Make payment" button will be visible and clickable.

## Expected behaviour

* The "Make payment" button should be in the "Pending" state until all Release transactions have been completed to prevent the double transaction.

## Actual behaviour

* The "Make payment" button is visible and clickable even after completing the transaction in release.

[make-payment-twice.webm](https://github.com/user-attachments/assets/9ac1a62e-a437-475b-b402-962cac888bf7)

**Comment by jakubcolony** [comment]
Resolved via https://github.com/JoinColony/colonyCDapp/pull/2384/commits/170fc966cda4485c09e86273edab39fff5b96cd2
