### ISSUE TITLE
bug: manage reputation action description has different values than the action description

### ISSUE THREAD

**Issue by bassgeta** [JoinColony/colonyCDapp#3253]
## Steps to reproduce

1. Create a `Manage reputation` action, awarding some points to a user.
2. Notice that the action table title has a lower number than the action description in the sidebar
![image](https://github.com/user-attachments/assets/4ae1267b-9d16-4732-b6db-c7c6a9f5c14c)

## Expected behaviour

The numbers should match

## Actual behaviour

The numbers sadly do not match

## Suggestions (optional)

If it's gonna be possible, we could unify these descriptions at least partially

**Comment by rdig** [comment]
Will this be fixed by @iamsamgibbs 's #3307 ?

**Comment by iamsamgibbs** [comment]
I think it might actually, I'll boot up the branch and test it shortly.

**Comment by iamsamgibbs** [comment]
🎉  Will add an extra testing step for this to my PR

<img width="780" alt="Screenshot 2024-10-14 at 12 03 52" src="https://github.com/user-attachments/assets/570d2a55-69a1-4f45-93e7-37d19412d0b0">
