### ISSUE TITLE
[Dashboard] With the teams filter persisted, going back will render the initial empty route

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#3263]
### Issue

When navigating, having the team/domain filter active, on the back navigation, also the initial empty route is being rendered (the one without the domain parameter)

This happens because initially the empty route, without domain, is being rendered, then the domain filter is applied as search param and the route gets re-rendered.

Below you can see the behaviour in action

https://github.com/user-attachments/assets/abb027e1-98eb-45b6-9407-a7424214d4cd

**Comment by rdig** [comment]
@mmioana is this needed for the initial deployment ? If so, make sure to add it to the cycle

**Comment by mmioana** [comment]
Sorry @rdig I have missed your comment. No, this is not necessarily needed for the initial deployment, but would be great for this bug to be fixed, as it's making the back navigation to not work as expected

**Comment by rdig** [comment]
It's added to the current cycle either way, however I'm fine if we merge this after the deployment
