### ISSUE TITLE
Multi-sig extension installation states

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3266]
## Steps to reproduce

Note: I am aware of this PR (https://github.com/JoinColony/colonyCDapp/pull/3114), however, have not tested it or seen if it has any impact regarding this issue.

1. Ensure this multi-sig extension is uninstalled.
2. Install the extension.
3. Only sign the first transaction.
4. Note the extension settings are greyed out and disabled.
5. Sign the second transaction.
6. Note that the extension still shows it is installed and not enabled.

## Expected behaviour

* We should show an indication to users that the extension is being enabled, as opposed to only graying out and disabling the fields. We could use the pending loading state button in place of the installation button. Or, use skeleton loaders.
    - To make a decision here, I would like to understand if there is a reason for the options to be grayed out and disabled.

## Actual behaviour

* When the extension is setting permissions, the UI is in a disabled state, but there is no indication that something is happening.
* After enabling the extension, the extension still shows as Installed, as opposed to Enabled.

![image](https://github.com/user-attachments/assets/26714ae4-2172-48bf-ac2c-9f6105fc3f9a)

![image](https://github.com/user-attachments/assets/7f165b33-88bb-404b-93f1-3293138dab3d)

**Comment by iamsamgibbs** [comment]
Closing this as neither myself nor @Nortsova have been able to recreate this. (I have seen it a bunch recently, but can't recreate it at all today on master, so a recent PR must have fixed it.) Will keep an eye out for it and re-open this if it pops up again.
