### ISSUE TITLE
Staged payments claim delay flashing

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3270]
## Steps to reproduce

Note, this issue was previously resolved in the Staged payment flow PR.

1. Create a new Staged payment action.
2. Create a few files tone payments.
3. Complete the payment and watch for the loading state.
4. Note that the claim delay value flashes before the action fully loads.

## Expected behaviour

* You should have a smooth transition between the creation and completed view of the staged payment action.

## Actual behaviour

* You get a flashing of the advanced payments table and thus the large claim delay value that is required for staged payments to work.

![Screenshot_20241004-150523](https://github.com/user-attachments/assets/8cfe0547-980a-49f6-8339-e0b58fdd9e9a)

Thanks to Etienne for testing.

**Comment by jakubcolony** [comment]
Resolved in #3279
