### ISSUE TITLE
Claim stakes pending button

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3288]
## Steps to reproduce

1. Create an Advanced payment action.
2. Get to the Funding step and use the Reputation decision method to fund.
3. Stake and go through the motion process, including finalizing.
4. Now, claim the stakes of the motion.
5. Note the pending button changes and does not go away.

Pending remains.
Close and reopen and it will disappear.

## Expected behaviour

* The pending button should dissappear after the creations has completed.

## Actual behaviour

* A different Claim stakes pending button appears with broken spacing, after the actual pending button disspears.
* The additional Claim stakes pending button stays until the action is reloaded. 

[pending-button.webm](https://github.com/user-attachments/assets/e25a0c61-9f22-4c08-a2f5-334e4f4ef3af)

**Comment by jakubcolony** [comment]
Resolved in #3279
