### ISSUE TITLE
Skeleton loading states on dark mode

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3293]
Teamwork task: [Skeleton loading states on dark mode](https://tw.auroracreation.com/#/tasks/16115953)

## Description

Currently, the skeleton loaders when shown in dark mode match the light UI only and don't align with the dark mode colour tokens. 

Having a supported dark state for the skeleton loaders would make the UI in dark mode more cohesive. The scope of this issue is to add support for dark mode using the specified values in [Figma](https://www.figma.com/design/Jn8wu7cmMceG0z7uBjU51s/Dark-mode?node-id=26721-8076&t=CLYLv4HTQQWPTnR4-4). 

The current implementation for light mode should be applied for dark mode across all responsive sizes. 

This is a low priority issue. 

<img width="414" alt="image" src="https://github.com/user-attachments/assets/1402fb60-b064-4c2a-b9a6-a72012cdd9e7">

### Figma link: https://www.figma.com/design/Jn8wu7cmMceG0z7uBjU51s/Dark-mode?node-id=26721-8076&t=CLYLv4HTQQWPTnR4-4

**Comment by rdig** [comment]
Shouldn't this go Pagepro ?

**Comment by adam-strzelec** [comment]
@melyndav I checked in the app and loading skeleton displays with exactly the same colors as in Figma. Both in dark and light mode. I don't quite understand what you mean. Did you mean gradient color? 🙂

**Comment by melyndav** [comment]
Hey @adam-strzelec, when dark mode is active, I want the skeleton loader to match the dark tokens above. Currently, it shows the lighter token and doesn't match with the dark theme. So dark mode needs a custom colour when active.

<img width="312" alt="image" src="https://github.com/user-attachments/assets/7fa4802d-0144-4f93-b51c-98bd466fd1bb">

<img width="362" alt="image" src="https://github.com/user-attachments/assets/920085ad-6222-44b9-a499-93e3b2a277ed">

**Comment by adam-strzelec** [comment]
@melyndav Something like that?
Before:

![Screenshot 2024-10-17 at 15 07 28](https://github.com/user-attachments/assets/8d88401d-8ced-44b2-85be-c3facd69cdec)

After:

![Screenshot 2024-10-17 at 15 08 09](https://github.com/user-attachments/assets/4d8b45fa-33cc-4bc9-85b0-1e19b788850b)
