### ISSUE TITLE
Add a character counter input field to the 'Colony Name' field to maintain consistent UX across the application.

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3294]
Teamwork task: [Add a character counter input field to the 'Colony Name' field to maintain consistent UX across the application](https://tw.auroracreation.com/#/tasks/16114645)

## Steps to reproduce

1. Start "Create colony" flow
2. Enter some chars in the Colony name field

## Expected behaviour

*  The 'Character Counter' is shown on the 'Colony Name' field

## Actual behaviour

* The 'Character Counter' isn't shown on the 'Colony Name' field

<img width="1534" alt="image" src="https://github.com/user-attachments/assets/670747c7-42b1-4ef3-a766-e75b78091a5f">
<img width="1376" alt="image" src="https://github.com/user-attachments/assets/803a2cb1-0f8d-4728-a0b8-9889e4e0a5a0">

**Comment by rdig** [comment]
I actually don't know the spec here.

@arrenv should the character counter show up on the _Colony Name_ input field ?

**Comment by arrenv** [comment]
@rdig It was not included in the original design for the _Colony name_ field, but, the idea is that any fields with a character limit should have them, which, I suppose should be all if not most. It should appear once they reach 75% of the limit.

The component for it is here - https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-517&t=GOYMSjHA0E8W5lWZ-4

This could ne assigned to Pagepro.
