### ISSUE TITLE
Search doesn't work on the "Select a colony"  - left sidebar 

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3295]
## Steps to reproduce

1. Open left sidebar
2. Click on the Colony icon
3. Enter the existing colony name in the Search field

## Expected behaviour

* Search  works on the "Select a colony"  - left sidebar 

## Actual behaviour

* Search doesn't work on the "Select a colony"  - left sidebar 
<img width="851" alt="image" src="https://github.com/user-attachments/assets/72a60235-72b4-4991-bea3-69829813ebf9">

<img width="791" alt="image" src="https://github.com/user-attachments/assets/f904eea5-1a1b-4cae-834c-c4a31248928e">

**Comment by arrenv** [comment]
@olgapod The search works, but there is definitely an issue. For example in my recording below, you can see that it matches the first word in "Planet Express" up to "Plane", but does not match if you do the full "Planet". Additionally, searching by the second word "Express", matches up to "Ex", but does not when you do "Exp".

[search-issue.webm](https://github.com/user-attachments/assets/274254d1-ae02-42e9-824c-393d0e61ce7d)

**Comment by rdig** [comment]
Check if it's still valid with the new navigation

**Comment by iamsamgibbs** [comment]
I've checked this in the figma design and on the UI navigation branch and can confirm search does not exist on the new navigation UI so I am closing this.

![Image](https://github.com/user-attachments/assets/90f0b803-2735-41d6-80c1-78384a64dcd8)

![Image](https://github.com/user-attachments/assets/2ec24f48-c2b8-41c1-925c-b0e235865914)
