### ISSUE TITLE
Loading spinner on action timeline for Adv. payments

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3299]
Teamwork task: [Loading spinner on action timeline for Adv. payments](https://tw.auroracreation.com/#/tasks/16115955)

## Steps to reproduce

1. Create an Advanced payment action.
2. Note, the loading spinner in the right hand side action timeline.

## Expected behaviour

* The skeleton loader should remain until the content loads as opposed to both the skeleton and the loading spinner.

## Actual behaviour

* The loading spinner appears in the action timeline, which should be timeline.
* You see both the skeleton loader and loading spinner on motions.

[loading-wheel.webm](https://github.com/user-attachments/assets/6524de6a-ca86-4353-837e-416ef2673496)

![image](https://github.com/user-attachments/assets/9e4ab673-3f20-4ba7-a8e9-0066835edd46)

**Comment by jakubcolony** [comment]
Hey @arrenv, the screen recording shows a simple payment motion so could this be a motion-specific issue and not advanced payments? I think I'm seeing the correct behaviour on QA:

![adv-payment-loading](https://github.com/user-attachments/assets/d7bc6184-cd66-455b-b6c8-1981eeeba75b)

**Comment by arrenv** [comment]
@jakubcolony I knew there was something funky there, when verifying, I seemed to only be able to replicate it on Adv. payments, but I seemingly ignored my own recording.

It seems fairly inconsistent, I just went and tested it again and am now getting it in the content area.

It seems unrelated to this PR, so, I will raise with Pagepro.

![image](https://github.com/user-attachments/assets/64318344-b63f-4e61-ae06-96fc710a024d)

**Comment by adam-strzelec** [comment]
@arrenv @jakubcolony I noticed that the problem occurs when you create action with reputation method. This might not be so easy to fix, since the content on the right only starts loading once the content on the left has been rendered. I'll have to think about how to fix that.
