### ISSUE TITLE
Staking decision method not working

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3301]
## Steps to reproduce

1. Ensure you have the Staking Advanced Payments and reputation.
2. Create an new Advanced Payment action.
3. Select the Staking Decision method.
4. In the modal, click to create the payment.
5. Note, that the pending state stays and no transaction is triggered.

## Expected behaviour

* You should be able to stake to create an Advanced payment.

## Actual behaviour

* Staking to create an advanced payment does not work, you get stuck in a pending state with no transaction being triggered.

![image](https://github.com/user-attachments/assets/36de93f0-e738-4b2b-a144-5b35906e4896)

**Comment by jakubcolony** [comment]
Fixed in #3279
