### ISSUE TITLE
Dynamic permission text is missing in Payment callout

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3303]
## Steps to reproduce

1. Create a Staged payment action.
2. Get all the way to the payment step and pay a milestone.
3. Select the "Permission" decision method.
4. Note the text in the info callout card and the `{permission}` showing in place of the users permission being used.

## Expected behaviour

* The users permission being used should dynamically show in the decision method callout text.

## Actual behaviour

* Description no longer shows the users permissions being used.

![image](https://github.com/user-attachments/assets/7589a227-1802-4a9a-8274-a72a4e8f07cf)

**Comment by jakubcolony** [comment]
I fixed the role not showing, but the copy seems to be about funding and not releasing. Could you help with the correct version?

<img width="497" alt="image" src="https://github.com/user-attachments/assets/2d1a2e8e-e35e-4777-b846-813fb159671b">
