### ISSUE TITLE
[Create Colony Flow]: Incorrect message is shown for a taken URL in the "Custom Colony URL" field

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3309]
## Steps to reproduce

1. Go to the "Create a colony" page
2. Enter an already existing URL in the "Custom Colony URL" field
3. Observe the message displayed

## Expected behaviour

* The message "This colony URL is already taken" should be displayed when entering an existing URL

## Actual behaviour

* The message "URL available" is incorrectly shown even though the URL is already taken

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/b060c9ff-67dd-4c31-a1ad-fa3868796359">

**Comment by olgapod** [comment]
https://github.com/user-attachments/assets/83a8a4ee-fdc1-4b62-ac97-d12e75517e8c

**Comment by rdig** [comment]
I think there's a delay in validation happening here
