### ISSUE TITLE
[Create Profile]: Unclear validation message shown in username field 

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3312]
## Steps to reproduce

1. Open create the user profile
2. Open Create your Colony profile
3. Enter special characters (spaces and special symbols) in the username field
4. Observe the validation message displayed

## Expected behaviour

*  We might show a more specific message, e.g. "Only letters and numbers allowed"

## Actual behaviour

* The message "A valid username is required" is displayed, which is unclear

<img width="1352" alt="image" src="https://github.com/user-attachments/assets/89b175a4-dc3d-4d2d-b143-f1ddc48e78bc">

**Comment by rdig** [comment]
I wouldn't call this a bug per se, but I do agree that the message can be improved.

Also it's not only "letters and numbers", as it can also be dashes, plus there's also a length restriction.

**Comment by iamsamgibbs** [comment]
@arrenv can you confirm the validation message for this input? `A valid username is required. Usernames can only contain letters, numbers or dashes and must be between X and X characters long.`?

**Comment by arrenv** [comment]
Thanks Sam, please have it set to: "Usernames can contain letters, numbers or dashes and be between 3 and 30 characters."
