### ISSUE TITLE
[Create Colony Flow]: Header isn't shown on mobile 

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3315]
## Steps to reproduce

1. Navigate to the "Create a Colony" form
2. Observe that the header section is missing

## Expected behaviour

* The header should be displayed at the top of the form, showing the relevant information

## Actual behaviour

* The header is missing

## Environment:

* Device: iPhone 15 Pro Max
* OS: iOS 17.2
* Browser: Safari

* <img width="471" alt="image" src="https://github.com/user-attachments/assets/350d6436-cb12-4ffa-827e-c4f676b2cd55">

<img width="430" alt="image" src="https://github.com/user-attachments/assets/77b2549e-0428-44aa-a7d1-1a32879176f9">

https://www.figma.com/design/j0VEfFryOkmjrVVq2PItso/CDapp-Landing-page-%2B-Beta-Launch?node-id=16401-11409&node-type=frame&t=easmZYWbbomtSAKt-0

**Comment by rdig** [comment]
Why did you close this ?
