### ISSUE TITLE
[Payment Flow] Clarify fee validation logic in payment process

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3336]
### Story

Update the payment validation logic to include a comment or explanation about the inclusion of the network fee in the validation process

### Description

Example: During the colony creation wizard, there is an activity indicator for pending transactions, but there is no indicator of other async operations (e.g. for the DDB) in between these transactions. It's important that the indicator remains visible until all async activity is finished, because otherwise, the user has no feedback that they're waiting for something to finish; they might leave the wizard or refresh the page, leading to frustration.

<img width="1156" alt="image" src="https://github.com/user-attachments/assets/0dcfee81-7c0d-42c3-9bfe-5a8f59be1a5b">

**Comment by rdig** [comment]
@arrenv do you want to handle this? _(given we have a feature down the line that will actually expose the network fee)_

If you still do want to handle in the mean time, then how? _(I assume just an updated error message)_

**Comment by arrenv** [comment]
Thanks @rdig, yes there is a feature upcoming for handling this better, but, we should already have specific validation for this as of this PR: https://github.com/JoinColony/colonyCDapp/issues/2279

**Comment by rdig** [comment]
Assuming @olgapod is using the lastest `master`, this might be a regression

**Comment by jakubcolony** [comment]
The validation works (it includes network fee when checking for sufficient funds), hence the "bug" report - otherwise @olgapod would be allowed to make a payment of 225 tokens that would fail on the tx level. I think this is closer to an enhancement request so updated the label.

**Comment by jakubcolony** [comment]
Can confirm the validation still works, so looks like it's just the error message that needs fixing.
