### ISSUE TITLE
Multi-sig permissions extension installation issues

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3337]
## Steps to reproduce

1. Install the Multi-sig permissions extension.
2. Note that during the installation, the transaction will fail.
3. Reload the app.
4. Note that the extension will be installed, and enabled but the permissions banner will appear.
5. Note that the status will say Installed and not Enabled.
6. Deprecate the extension.
7. Reenabled the extension again.
8. Note that the permission banner will appear again.

## Expected behaviour

* When installing the Multi-sig permissions extension, it should be enabled and assign the correct permissions in one flow.
* The transaction should not fail during installation.
* The status should be accurate. Raised here https://github.com/JoinColony/colonyCDapp/issues/3266

## Actual behaviour

* Installing the Multi-sig permissions extension fails.
* You should not have to manually assign permissions to the extension.

[multi-sig-permissions.webm](https://github.com/user-attachments/assets/4d9a618f-edc7-4820-822c-ae9926c8c736)

**Comment by iamsamgibbs** [comment]
Just noting, this is partially fixed by #3349 and the remainder will be fixed by #3430, both of which are assigned to myself.
