### ISSUE TITLE
[Payment Flow] Amount field validation fails when team name is modified

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3346]
## Steps to reproduce

1. Open the simple payment
2. Select General team and Amount of 300
3. Select another team where total credit is less than 300
4. Pay attention to the amount field

## Expected behavior

* The amount field validation should work properly, regardless of whether the team name is modified

## Actual behaviour

* The amount field validation fails or does not trigger when the team name is changed

https://github.com/user-attachments/assets/cd97c0d1-95af-40a7-9428-43f392fcc539

**Comment by rumzledz** [comment]
Can you please retest this one @olgapod ? I cannot seem to replicate it:

![Image](https://github.com/user-attachments/assets/8d6ea8b3-9d18-428a-89c4-8401797bc8fb)

**Comment by olgapod** [comment]
@rumzledz Thank you for checking; the bug is no longer reproducible for me either
