### ISSUE TITLE
[Dashboard]: Padding between title and table

### ISSUE THREAD

**Issue by Nortsova** [JoinColony/colonyCDapp#3353]
## Steps to reproduce

This issue was found in this PR:
https://github.com/JoinColony/colonyCDapp/pull/3257#issuecomment-2393667391

After a discussion with @melyndav we realise that it was a bug in the design, so now it should be 14px between title and tables.

## Expected behaviour
14px between title and table

## Actual behaviour

16px between title and table

**Comment by rdig** [comment]
Closed by #3354
