### ISSUE TITLE
[Dashboard] Total, total in and total out values not updating

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#3359]
### Issue

Payment updates in the UI required reloading the dashboard to see all the totals in the finance cards and total in and out widget to update. This is confusing because the recent activity updates, but everything else doesn't.

**Comment by mmioana** [comment]
I have increased the initial estimation from `4` to `10` as it involved more changes than initially anticipated

**Comment by rdig** [comment]
Closed by #3368
