### ISSUE TITLE
[All Members]"View on Noexplorer" link isn't opening the page

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3362]
## Steps to reproduce

1. Navigate to the "Members" page
2. Click the three dots next to a member's name
3. Select "View on Noexplorer" from the dropdown menu
4. Observe that the page does not open as expected.

## Expected behaviour

* Clicking the "View on Noexplorer" link should open the relevant page in Noexplorer

## Actual behaviour

* The link does not open any page, or no response is triggered

<img width="1420" alt="image" src="https://github.com/user-attachments/assets/5946e51d-8697-462f-b772-65ffc3af1632">

**Comment by rdig** [comment]
This is not a bug, it's the expected functionality.

Noexploer is the name we use for local development and doesn't have a URL since it doesn't exist.

In a production environment this gets changed to the relevant chain's block explorer.
