### ISSUE TITLE
Navigation & Breadcrumbs: Padding adjustments for horizontal alignment 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3367]
## Description

During the second round of QA testing for the new navigation and dashboard features, it was identified, on desktop and tablet, that the breadcrumbs didn't align horizontally with the left navigation colony switcher and the right user header.

<img width="1349" alt="image" src="https://github.com/user-attachments/assets/feb41e31-8d0e-4259-9fc4-b1a475489e67">

In order to align these horizontally, the following padding changes require updating. 

Ideal result:
<img width="1364" alt="image" src="https://github.com/user-attachments/assets/02071e0f-f443-47cb-9d37-aadb75c47878">

## Navigation

1. Increase the top and bottom padding across all nav variations from 18px to 20 px (desktop and tablet only). This included connected, colony creation, profile creation, not connected, user account variations. 

The hover behind the colony logo and switcher should remain connected and aligned to the logo and colony name etc.

Top:
<img width="1120" alt="image" src="https://github.com/user-attachments/assets/9b36363a-4bf6-48f2-bd15-84766b9d6b0d">

Bottom:
<img width="270" alt="image" src="https://github.com/user-attachments/assets/6bf309cc-7980-4857-a675-10ea806c7e41">

All in one shot:
<img width="696" alt="image" src="https://github.com/user-attachments/assets/02e14c44-be49-4264-9191-cdf5d0acc5b5">

## Figma link for nav component
https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=3820-16569&t=XyG7xfSJbdVHn3DI-4

---

2. Reduce the padding between the colony switcher and the first menu item from 32px to 30px. This requires to be updated across only the connected and user account variations

<img width="1084" alt="image" src="https://github.com/user-attachments/assets/f014c38e-e9f3-4296-a7cd-82c3de1d6bd7">
<img width="300" alt="image" src="https://github.com/user-attachments/assets/b35fb887-c22e-442c-af1c-f00944b34407">

Do not update for the colony creation and colony profile versions, as they have a 40px padding and should remain the same.

<img width="413" alt="image" src="https://github.com/user-attachments/assets/f1276a77-46c4-4c98-8447-39f4b5e47418">

This update should only be made for desktop breadcrumbs and not mobile.

## Breadcrumbs

To align the breadcrumbs vertically in this space, I have added a 10px padding to the top of my Figma component. 

<img width="630" alt="image" src="https://github.com/user-attachments/assets/78f3469e-c724-47d1-8538-2e29a7c2acb2">

However, my component is not built in the same method, so the adjustment here needed is at your discretion. 

<img width="1425" alt="image" src="https://github.com/user-attachments/assets/3d48a366-ba0e-40b6-bc92-953fefc5df69">

## Figma link for breadcrumbs 

https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4870-44687&t=Kq8UCrtG4vMoawxj-4

Mock for the design showing the alignment: https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=7071-38304&t=Kq8UCrtG4vMoawxj-4

**Comment by rdig** [comment]
@rumzledz or @mmioana where are we fixing this, in Nav or Dashboard ?

**Comment by rumzledz** [comment]
> @rumzledz or @mmioana where are we fixing this, in Nav or Dashboard ?

@rdig Apologies I just saw your comment! This will have to be done in Dashboard since the Nav branch doesn't have the new and shiny breadcrumbs. But me and Ioana spoke and we've decided that it can wait when both Dashboard & Nav are on `master`

**Comment by rdig** [comment]
Closed by #3419
