### ISSUE TITLE
[UI]: User popover cuts off the reputation percentage points

### ISSUE THREAD

**Issue by Nortsova** [JoinColony/colonyCDapp#3381]
## Steps to reproduce
User popover cuts off the reputation percentage points

Step 1. Open Permissions page
Step 2. Click on any user

## Expected behaviour
It should not overflow the content. 

## Actual behaviour

![image](https://github.com/user-attachments/assets/39d23c9d-e6b8-4006-91b7-5aae6c9695b8)

**Comment by rdig** [comment]
Closed in favor of #3424
