### ISSUE TITLE
[Member permissions] 403 Error when assigning duplicate permissions to a user

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3395]
## Steps to reproduce

1. Navigate to the Permissions page
2. Assign a specific permission (e.g., "Admin") to a user (e.g., Amy) in Team Andromeda
3. Attempt to assign the same permission ("Admin") to the same user (Amy) in Team Andromeda
4. Observe the 403 error message displayed

## Expected behaviour

* The system should allow the assignment of duplicate permissions without errors

## Actual behaviour

* 403 Forbidden error is displayed, and the permission assignment fails

<img width="1776" alt="image" src="https://github.com/user-attachments/assets/fe59e633-8504-4b97-b846-663f0e0b44be">

**Comment by rdig** [comment]
So duplicate permissions should not pass validation in the first place, so there's definitely something wrong here

**Comment by iamsamgibbs** [comment]
99% certain this is resolved by #2749 - will confirm whilst testing it.

**Comment by iamsamgibbs** [comment]
Can confirm this is resolved by #2749 

<img width="671" alt="Screenshot 2024-10-28 at 17 21 18" src="https://github.com/user-attachments/assets/44ed5d3b-e414-4bce-8405-3f7083a1364c">
<img width="674" alt="Screenshot 2024-10-28 at 17 24 00" src="https://github.com/user-attachments/assets/802e8c39-97de-4ca5-ad5c-a9e6f4191abe">
