### ISSUE TITLE
[Payment flow] Colony address incorrectly displayed in Search results

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3399]
## Steps to reproduce

1. Open Create action
2. Click on the "Choose action type"
3. Paste the data on the search field "0xDDd0F70f5450837f1104C6d8b626E423dC6c3425"

## Expected behaviour

* The search input should only show relevant options
## Actual behaviour

* Colony address incorrectly displayed in Search results

<img width="1260" alt="image" src="https://github.com/user-attachments/assets/4bf76de0-603a-473b-9a05-933c8d11b85d">

**Comment by rdig** [comment]
Nice find

**Comment by iamsamgibbs** [comment]
This also affects all "Select team" fields

![Image](https://github.com/user-attachments/assets/9e22aed7-b8fe-429d-9d5b-29380d185987)
