### ISSUE TITLE
Redo staged payment option is not checking whether extension is enabled 

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#3420]
## Steps to reproduce

1. Install the Staged Expenditure extension.
2. Create a staged payment.
3. Uninstall the extension.
4. In the payment you created, click on the three dot menu and select "Redo action".

## Expected behaviour

Good question - hopefully @arrenv or @melyndav could help with the expected behaviour, whether it is disabling the Redo action button or showing a warning similar to this:
<img width="699" alt="image" src="https://github.com/user-attachments/assets/dce6a817-6602-4277-9d12-6b9a359c8049">

Or maybe something else.

## Actual behaviour

Action form opens with Staged payment action selected (even though it's not available as an option). Attempting to create the payment throws a transaction error.

**Comment by arrenv** [comment]
@jakubcolony Good pickup, if we could show the error callout as of your screenshot, that would be a more expected and useful flow then just hiding the redo action option.

The text could be the same: "Staged payments requires the Staged payment extension to be enabled  View extension"

**Comment by rdig** [comment]
Redo-ing actions seem to have issues generally. We've found this last week #3382

We might need to look deeper into this feature
