### ISSUE TITLE
Regressions: User Cards UI

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3424]
## Description

In production, the multi-sig changes to the user cards have been regressed, resulting in narrow user cards that cut off core reputation percentage information. 

This impacts ALL user card types across desktop and tablet screens. Mobile is not impacted. 

**Currently, in production:**

<img width="396" alt="image" src="https://github.com/user-attachments/assets/fbf5636a-ef0a-45cf-92c8-ff9b527ad11a">

<img width="386" alt="image" src="https://github.com/user-attachments/assets/5f21108f-6559-47af-b479-2789e767c328">

<img width="452" alt="image" src="https://github.com/user-attachments/assets/99fb63ed-f4d3-40a9-81e0-561c84463fd9">

**Mobile (not impacted):**

<img width="418" alt="image" src="https://github.com/user-attachments/assets/d358ce3b-df5c-4d3f-b9f3-ec4ef5fc5d10">

## Figma design system link

Correct design, padding and component width: 

https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-42685&t=sxtrkAPRYCuEUtGs-4

Multi-sig design file with annotations: https://www.figma.com/design/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?node-id=21336-80055&t=FZRUvPnkmhKbVaZ1-4

**Comment by rdig** [comment]
This was already raised here #3381 _(we caught it last week during an unrelated PR review)_

But I'm going to close that in favor of this

**Comment by melyndav** [comment]
Ahh, I am blind! Skimmed the issue list but went straight past it. Thanks @rdig. 👍
