### ISSUE TITLE
[Permission]  UI nisleadingly indicates payment operation is accepted despite insufficient permissions

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3426]
## Steps to reproduce

1. Activate multi-sig Permissions
2. Log in as a user with custom -  Administaration permission 
4. Make advanced payment
5. Open funding popup and press "Fund Payment" button
6. Observe the system response

## Expected behaviour

* If the user does not have the correct permissions, the system should prevent the action from proceeding
* The UI should display a clear error message indicating that the user does not have the necessary permissions to perform this action

## Actual behaviour

* No clear feedback is provided to the user about the lack of permissions, leading to confusion

https://github.com/user-attachments/assets/29ccf99f-3e45-41a3-9596-a3589f9ae534

**Comment by melyndav** [comment]
Hey @olgapod can you raise these types of UI/UX issues first in the QA kanban board? We need to review from Product and design standpoint, and also create any designs in Figma first, otherwise there is no solution provided for the dev to implement.
