### ISSUE TITLE
[Permissions] Users without "Payer" permission can make Advanced, Staged and Split Payments

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3427]
## Steps to reproduce

1. Log in as a user who does not have the "Payer" permission
2. Open Advanced, Staged or Split Payments
3. Attempt to create and execute an Advanced, Staged Payment or Split Payment
4. Observe that the system allows the payment to be processed

## Expected behaviour

* Users without the "Payer" permission should not be able to initiate or complete Advanced or Split Payments

## Actual behaviour

* Users without "Payer" permissions are currently able to initiate and complete Advanced and Split Payments without any restrictions or error messages

<img width="1772" alt="image" src="https://github.com/user-attachments/assets/fc4df805-cb4b-4ec5-b8fd-18205e00894a">

**Comment by arrenv** [comment]
@olgapod You need "Administration" (contract level) permissions to create Advanced payments.

"Payer" permissions is a bundled permission that includes "Administration", "Arbitration", and "Funding" contract level permissions.

As Amy has the "Mod" permissions, which includes the "Administration" permission, this is expected behavior.

I can understand that there is a little bit to get your head around here with permissions, and we need to make it clearer and easier to understand for users. This bundling of permissions is our first big experiment towards this.

**Comment by olgapod** [comment]
@arrenv I noticed that Amy, who has a Custom (Arbitration) role, is able to create Advanced payments. Could you please confirm if this is the expected behavior?

<img width="1772" alt="image" src="https://github.com/user-attachments/assets/95cd55ca-df5e-4609-8692-ddb4ff057375">

**Comment by arrenv** [comment]
> @arrenv I noticed that Amy, who has a Custom (Arbitration) role, is able to create Advanced payments. Could you please confirm if this is the expected behavior?

In your screenshot, you are showing them using the "Staking" decision method, which, yes they should be able to do.

Additionally, to see what is actually happening on the contracts you can check here - https://github.com/JoinColony/colonyNetwork/blob/6d8204416a0c7b362f1141ec3df524abef1a86f9/contracts/colony/ColonyAuthority.sol

And you can refer to the spec as well - https://www.notion.so/colony/Permissions-407a985723de48acabfdbc40da962427

**Comment by olgapod** [comment]
@arrenv thanks for documentations

**Comment by iamsamgibbs** [comment]
I don't believe this to be an issue. On the contract side, `Administration` is the only permission role created for creating an Advanced Payment, Split Payment or Staged Payment. When using the "Permissions" decision method we are checking for the `Administration` role, and this seems to be working as intended.

<img width="799" alt="Screenshot 2024-10-28 at 12 37 21" src="https://github.com/user-attachments/assets/b513d5f0-a6a2-4263-bf1a-b30ce9831b0d">

<img width="884" alt="Screenshot 2024-10-28 at 12 38 05" src="https://github.com/user-attachments/assets/f58c041f-8a57-4379-96cd-18247542df88">

When using the `Staking` decision method, you are not required to have the `Administration` role and as such any user is able to create a staked expenditure.
