### ISSUE TITLE
[Actions] Long title names overflow in mobile view on Activity Screen

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3433]
## Steps to reproduce

1. Open the application on a mobile device (e.g., iPhone 15)
2. Open Actions draw and add "12312321312312312312312312312313123123123123412341234124312" title name
3. Fill in all action and save
4. Open Activity page
5. Notice that the title name overflows and does not fit properly within the activity row

## Expected behaviour

* Long titles should either be truncated with an ellipsis (...) or should wrap onto the next line without overflowing out of the designated area

## Actual behaviour

Long titles overflow and extend out of the designated container,

<img width="461" alt="image" src="https://github.com/user-attachments/assets/ce3c0dd6-38b9-4cef-aabc-80155bd9b286">

**Comment by rdig** [comment]
Nice catch! :100:
