### ISSUE TITLE
[Actions] "Redo Action" missing from dropdown menu on Activity draw

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3434]
## Steps to reproduce

1. Create a team
2. Click on an activity to open its details
3. Open the dropdown menu located on the top-right corner of the details panel
4. Observe that the "Redo Action" option is missing

## Expected behaviour

* The dropdown menu should include an option for "Redo Action" that allows users to perform additional related actions directly from the activity details draw

## Actual behaviour

* The "Redo Action"option is not present in the dropdown menu

<img width="1685" alt="image" src="https://github.com/user-attachments/assets/4bf9d452-7e8c-4fc2-ab09-c5e08860968d">
<img width="250" alt="image" src="https://github.com/user-attachments/assets/9a7f2639-43e6-44bb-8344-960884e45a0d">

**Comment by arrenv** [comment]
@olgapod The redo action is intentionally left off of this action as well as various others. The original intent for this feature is only for actions that are repeatable. Which, at this stage is mostly for financial based actions.

So, at the moment, there is no need to add it to the create a team action.
