### ISSUE TITLE
[Actions] Title isn't disappear after changing the actions type

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3435]
## Steps to reproduce

1. Open create "Siple payment" actions draw
2. Fill in title
3. Click on the "Actions type" and select "Create a team" actions
4. Pay attention on title

## Expected behaviour

* The title should disappear or reset when the action type is changed to ensure that the new action type does not retain the old title

## Actual behaviour

* The title remains visible and does not reset after changing the action type

https://github.com/user-attachments/assets/b7d8f2b8-71d7-4202-a692-f938def3b459

**Comment by rdig** [comment]
I don't think this is a bug.

The title is custom and can be anything, for any action, so given that It's fine that it doesn't change.

**Comment by melyndav** [comment]
Just confirming that @rdig is correct. This isn't a big and was intended to be kept as the user switched between action types.
