### ISSUE TITLE
[Simple payment] When i make payment to other colony we don't get colony label and name

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3436]
### Description

When attempting to make a payment to another colony, the recipient field does not display the colony label or name. Instead, only the address is shown, which can be confusing for users trying to verify the correct recipient colony. The recipient should display both the colony label and name for clarity.

<img width="1492" alt="image" src="https://github.com/user-attachments/assets/08ac88ac-e58e-4cc3-9d41-7b029dc76bd3">

**Comment by rdig** [comment]
This is not a bug, just was never implemented, so what you're asking for here is more like a "feature request"

There's actually a good argument for not having this in: you might not want to "expose" that a colony lives under that address (or a user, or extension, etc)

**Comment by olgapod** [comment]
@rdig I see thanks
