### ISSUE TITLE
The bridgeXYZMutation lambda throws an error after adding Bank details for the first time

### ISSUE THREAD

**Issue by rumzledz** [JoinColony/colonyCDapp#3442]
## Steps to reproduce

1. Go to the Crypto to fiat page http://localhost:9091/account/crypto-to-fiat
2. Verify your account
3. Add your bank details

## Expected behaviour

The app automatically refetches your KYC status, correctly updates your Bank details status and assigns you a liquidation address.

## Actual behaviour

The app automatically refetches your KYC status but the rest of the process fails due to the following exception:

<img width="1800" alt="Screenshot 2024-10-23 at 21 48 31" src="https://github.com/user-attachments/assets/888a547c-345d-4cf5-8c24-81db2de9e87c">
 
The error happens here:

```js
const checksummedLiquidationAddress = utils.getAddress(
    externalAccountLiquidationAddress,
);
```

<img width="686" alt="Screenshot 2024-10-24 at 00 05 40" src="https://github.com/user-attachments/assets/999a68d2-bba9-4536-88fb-df5313282b3c">

But after refreshing the page, your Verification, Bank details & Liquidation address information are all updated properly.

**Comment by rdig** [comment]
Maybe ping @jakubcolony on this one as well
