### ISSUE TITLE
[Crypto to fiat] Spaces aren't trimmed in the IBAN field

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3444]
## Steps to reproduce

1. Open manage account - Crypto to fiat
2. Open "Add Bank details" form
3.  Navigate to the IBAN input field and enter (PL43 1020 4027 0000 1702 0000 0000)
4. Submit the form

## Expected behaviour

* Spaces should be automatically trimmed from the IBAN input

## Actual behaviour

* The IBAN is accepted with spaces, causing validation issues

<img width="1169" alt="image" src="https://github.com/user-attachments/assets/49ab3b4c-7b3f-47c8-b8bc-27466f58100a">

**Comment by iamsamgibbs** [comment]
There is already an issue for this @olgapod :) #2961

**Comment by rdig** [comment]
Closing this in favor of #2961
