### ISSUE TITLE
[Crypto to fiat]After clicking update details button, fields are empty (make UX adjustments)

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3445]
## Steps to reproduce

1. Set up Crypto to fiat
2. Open Crypto to fiat -> Bank details -> Update details
3. Observe the fields

## Expected behaviour

* Fields should display the added info. Make UX adjustments

## Actual behaviour

* Fields appear empty after clicking the "Update Details" button

<img width="1204" alt="image" src="https://github.com/user-attachments/assets/84fd4275-bbba-4da3-947c-1700c8e471fd">

**Comment by jakubcolony** [comment]
Just adding a note from our conversation in Discord, this is currently expected since we do not store the user's existing bank details (and neither we get them from Bridge) which was agreed after weighing all the options

**Comment by rdig** [comment]
Closing this as it's expected
