### ISSUE TITLE
[Dashboard]Fit colony name in 20 symbols on mobile without cutting

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3447]
## Steps to reproduce

1. Open the application on a mobile device
2. Navigate to the colony dashboard
3. Check the display of the colony name

## Expected behaviour

* The colony name should fit within 20 characters without being cut off, maintaining readability on mobile screens

## Actual behaviour

* The colony name is currently cut off, displaying an ellipsis after a few characters (e.g., "Wayne Enterpris...")

<img width="457" alt="image" src="https://github.com/user-attachments/assets/7912c5ff-78fa-4565-bd1b-93e244ad572d">

**Comment by rdig** [comment]
I am not confident enough in saying which way is correct here.  As far as I'm concerned design allotted spacing can be decoupled from backend limits, so I want to say this is fine.

However I think that @melyndav should weigh in here as she's have a more definitive answer for you here.

As a side note, "mobile" can mean a wide array of widths, so even if we fix it for your example, smaller screen size will still run into this issue.

**Comment by mmioana** [comment]
@olgapod thanks for opening this issue and keeping an eye on the readability 🙌 

However, given all characters from a font has a different width, it's impossible to make sure we're always going to end up showing only 20 characters on mobile (consider the scenario of having a colony with a name with many `w` characters which should be the widest)

Also, it's good to keep in mind the max-width for mobile is `428px`, but we should also consider handling smaller widths.
https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1776-34873&node-type=canvas&t=M6lo8FprnxqCNZe8-0


With this being said, I will close this issue, at least for the moment. Let me know if you have any questions @olgapod 🙌 ☀️
