### ISSUE TITLE
[Dashboard] The "Create Team" block should be clearly visible with sufficient contrast

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3448]
## Steps to reproduce

1. Navigate to the colony dashboard
2. Pay attention to the "Create Team" block 

## Expected behaviour

* The "Create Team" block should be clearly visible with sufficient contrast

## Actual behaviour

* The block is not easily noticeable due to poor contrast, making it hard to see

<img width="1581" alt="image" src="https://github.com/user-attachments/assets/ee21bf9f-6731-415f-a02a-23909149b151">

**Comment by mmioana** [comment]
After having a discussion with @melyndav, we decided to comment out this card for the moment until we do a full accessablity audit later on

So for the implementation just comment the following lines
```
      {isAddNewTeamVisible && (
          <WidgetCards.Item
            variant="dashed"
            icon={Plus}
            title={
              <div className="text-xs">
                {formatText({ id: 'dashboard.team.cards.createTeam' })}
              </div>
            }
            onClick={onNewTeamClick}
            className="justify-center uppercase text-gray-200"
          />
        )}
```
in the `FundsCards.tsx`
