### ISSUE TITLE
No "Change action" confirmation modal when switching away from Advanced / Staged / Split payments

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#3466]
## Steps to reproduce

1. Create an advanced / staged / split payment and fill out some of the fields
2. Change to a different action type

## Expected behaviour

* The "Do you wish to change action?" modal should appear

## Actual behaviour

* The action is changed without confirmation

Note the intended behaviour at the end of the video when switching away from Simple payment:
https://github.com/user-attachments/assets/ca7d5db3-3ef8-48bf-9e46-24eaa51e5e74

## Suggestions (optional)

This is possibly due to the way validation is done on these actions as it is done on submit rather than on change, but this is just a hunch. If this is the case then it may be a fiddly issue to resolve.

**Comment by iamsamgibbs** [comment]
Hmm actually I can't recreate this again now (even though there is video proof in the issue of it not working). Whoever picks this up, check it is actually broken on master first.

**Comment by Nortsova** [comment]
I checked it on master; it works now 🎉 

Advanced payments:
![Image](https://github.com/user-attachments/assets/a0d7e2dd-ddda-4c3a-9aba-c0317156e744)

Split payment:
![Image](https://github.com/user-attachments/assets/4cbab2d6-d0ab-46f9-9f6a-5118b093241e)

Staged payment:
![Image](https://github.com/user-attachments/assets/4b0fd8ec-0c08-43f5-b5db-afc8d1bd1bb9)
