### ISSUE TITLE
Not able to create Advanced payments

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3468]
## Steps to reproduce

Note: I was testing this on a Colony on v15, which I don't think is a big issue. But, still thought I would flag.

1. Create an Advanced payment.
2. Try to complete the transactions.

I then experienced 3 different things when trying to replicate.
1. The app redirected to a 404.
2. The transaction failed as of the second screenshot.
4. The first transaction was signed, but the UI just stayed in the creation panel, and the button reverted from the pending state.

## Expected behaviour

* You should be able to create Advanced payments.
* There should be an error if the contracts are not supported.

## Actual behaviour

* You are not able to create advanced payments as the transactions fail, or nothing happens in the UI at all.

![image](https://github.com/user-attachments/assets/e5ae3125-35cb-4f9c-b98f-6914d0147f6f)

![image](https://github.com/user-attachments/assets/2a7661dc-09ff-4c94-865d-85bbf064b4dd)

![image](https://github.com/user-attachments/assets/4bbd2367-2518-45db-8969-d7fb3ace79ba)

**Comment by rdig** [comment]
I cannot replicate this on the current QA

![Screenshot from 2024-10-25 10-39-15](https://github.com/user-attachments/assets/075651e3-5208-41d3-b0af-e9c74f6d4ea5)
![Screenshot from 2024-10-25 10-39-39](https://github.com/user-attachments/assets/9e1ef91f-c19b-411e-9a5d-c41eec6dae1c)
![Screenshot from 2024-10-25 10-39-49](https://github.com/user-attachments/assets/2dafcc91-d42d-4cb0-8945-dff6ffabb002)
![Screenshot from 2024-10-25 10-39-57](https://github.com/user-attachments/assets/ca24b8ac-17f5-4a87-9579-4829562422e5)
![Screenshot from 2024-10-25 10-40-54](https://github.com/user-attachments/assets/84dd20e9-5fec-4e45-bfab-492f77dfaba7)

By the looks of the error it looks like either the appsync url was not responding or the auth proxy was not connected to the correct endpoint (we had this yesterday during the deployment)

SO this can be two ways: either you tried this while we were in the middle of the deployment, or this might be something intermediate which we need to catch in the act

In the mean time, I'll close this. If we run into this again, we can just re-open it
