### ISSUE TITLE
Colony picker overlaps over header calamity banner

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3469]
## Steps to reproduce

1. Ensure the calamity banner is showing, e.g. upgrade a colony.
2. Click on the colony picker.
3. Note the alignment of the colony picker popup.

## Expected behaviour

* The colony picker should be inline with the button.

## Actual behaviour

* The colony picker is sitting over the header calamity banner.

![image](https://github.com/user-attachments/assets/9e7e68b7-3560-44d1-84f1-be029eeec498)

**Comment by rdig** [comment]
I think both this and #3470 should be tackled at once
