### ISSUE TITLE
Colony picker height is cut off

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3470]
## Steps to reproduce

1. Ensure you have more then 10 colonies joined.
2. Click on the colony picker.
3. Note the colony picker height.

## Expected behaviour

* The colony picker should dynamically fill to match the height of the menu based on number of colonies before requiring scroll.

## Actual behaviour

* The colony picker height is cut off halfway in the screen.

![image](https://github.com/user-attachments/assets/692aa2de-a454-4a84-bc64-e6dc55548198)

**Comment by rdig** [comment]
I think both this and #3469 should be tackled at once
