### ISSUE TITLE
[Members] Instead of a link to the invitation on the members page, there is a link to colony

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3475]
## Steps to reproduce

1. Open the Colony dashboard
2. Navigate to the Members section from the left-hand menu
3. Click the Invite members button
4. Observe that the link provided is the Colony link, not the correct invitation link

## Expected behaviour

* The invite button should provide a link to invite new members, not the Colony link

## Actual behaviour

* The provided link is a Colony link instead of the invitation link

![Uploading image.png…]()

**Comment by rdig** [comment]
If I remember correctly this was not surfaced for a reason, just can't remember why.

@arrenv do you know why ?

**Comment by arrenv** [comment]
@olgapod @rdig Yes, this is intended for the time being while we do more hands on onboarding of new users.

There are discussions currently to review this again, and I have it as an agenda item for the Wednesday product sync.

**Comment by rdig** [comment]
Closing it in the mean time, we'll re-open it as a feature request when the time comes
