### ISSUE TITLE
Include the Mod role in the Permissions field list when the Authority field is set to "Take actions via Multi-Sig"

### ISSUE THREAD

**Issue by rumzledz** [JoinColony/colonyCDapp#3478]
### Description

> [!NOTE]
> This issue is referring to the Manage Permissions form
> <img width="699" alt="image" src="https://github.com/user-attachments/assets/49aa24de-ce22-4ee8-be34-4deb4fc9385d">

Our contracts are allowing you to give a user the "Administration" permission when their authority is set to "Take actions via Multi-Sig" so it makes sense to include the "Mod" permission in the role list.

### This issue is complete when...

- [ ] The Mod role is present in the list of Permissions when the Authority field is set to "Take actions via Multi-Sig"
- [ ] You can confirm that the form can be submitted successfully when you apply the following form values:
- **Authority:** Take actions via Multi-Sig
- **Permission:** Mod

### Potential fix

The following code can be found in `ManagePermissionsForm.tsx`:

<img width="596" alt="image" src="https://github.com/user-attachments/assets/f808452d-70a7-4ceb-8a3a-06fa937562a2">

Removing he following block should fix it 🤞 

```js
if (value === UserRole.Mod) {
  return authority !== Authority.ViaMultiSig;
}
```

**Comment by iamsamgibbs** [comment]
This section of the permissions modal should also be updated.

<img width="522" alt="Screenshot 2024-10-25 at 15 14 32" src="https://github.com/user-attachments/assets/b2755db3-53c1-427a-bbce-0955a126009c">
