### ISSUE TITLE
[Adwanced Payment] Form is disabled after entering letters in the claim delay field

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3485]
## Steps to reproduce

1. Open Create advanced payment 
2. Fill in all fields
3. Enter letters in the "Claim delay" field instead of numbers

## Expected behaviour

* Entering invalid characters should be impossible

## Actual behaviour

* The form becomes disabled, preventing any further input or action

<img width="1536" alt="image" src="https://github.com/user-attachments/assets/85c079ac-7319-403f-870b-bd271156d75b">

**Comment by rdig** [comment]
This was already raised. JoinColony/colonyCDapp/issues/3479

Please don't open duplicate issues
