### ISSUE TITLE
[Dashboard] Tooltips display incorrect behavior on Dashboard screen on mobile

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3486]
## Steps to reproduce

1. Open Dashboart
2. Tap on the "Copy contact address"  and "Copy this colony URL" icons
3. Scroll page up and down several times

## Expected behaviour

* Tooltips should disappear after scrolling up or down

## Actual behaviour

* Tooltips remain visible even after scrolling

https://github.com/user-attachments/assets/df17ba38-158d-45ed-97cd-2cf6de484f29

**Comment by Nortsova** [comment]
Hey @olgapod , thanks for raising this one 🙌 

Seems that I created a duplicate for this issue - https://github.com/JoinColony/colonyCDapp/issues/3493

I believe @rumzledz fix should solve this issue too 🙌
