### ISSUE TITLE
[Actions] layout issue on mobile on the External links section of actions

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3488]
## Steps to reproduce

1. Open Actions 
2. Add External link 

## Expected behaviour

* External links section is shown without issues

## Actual behaviour

*  layout issue on mobile on the External links section of actions

Device: 
iPhone 13 pro max
Design: Component link in the design system: https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-156470&t=yzztt7ii5XwWUYsL-4

<img width="456" alt="image" src="https://github.com/user-attachments/assets/bbecd1d8-faf7-408f-aa98-af71e630f81b">

**Comment by melyndav** [comment]
@olgapod please include Figma links to either the design flows or the components from the design system as reference points for the dev picking up the issue. Here's this one to include in the issue above - https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=3495-475416&t=1Ac9SR0xbl7PsG2k-4

**Comment by melyndav** [comment]
@olgapod Component link in the design system: https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-156470&t=yzztt7ii5XwWUYsL-4

**Comment by olgapod** [comment]
@melyndav thanks, Melynda! I will do it
