### ISSUE TITLE
[Incoming funds] Incoming found don't get from another colony on QA and locally

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3492]
## Steps to reproduce

1. Send tokens from Planet Express to Wayne Enterprises
2. Open Wayne Enterprises -> Finances -> incoming

## Expected behaviour

*  Incoming found get from another colony on QA and locally

## Actual behaviour

*  Incoming found don't get from another colony on QA and locally

**Comment by rdig** [comment]
You need to approve the token before it shows up, it's a mechanism preventing spam tokens from showing up.

To verify this:
- create a manage token action on planex, and verify the wayne token

**Comment by Nortsova** [comment]
hey there! basically, it should work, I just worked on it today in this PR - https://github.com/JoinColony/colonyCDapp/pull/3477 and I was able to see incoming funds coming from both: the metamask account and another colony. I will assign myself and will check if it is still an issue tomorrow with @olgapod 🙌

**Comment by olgapod** [comment]
I realized it wasn't a mistake, thanks for the comments
