### ISSUE TITLE
QA Nav: User account area HR styling in dark mode

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3501]
## Description

The HR that appears on the navigation version when a wallet is connected and the user is in the user account area doesn't match the colour/ weight of the HR that appears inside the Colony. It's only an issue in dark mode. 

Currently, inside a Colony:

<img width="229" alt="image" src="https://github.com/user-attachments/assets/68ef4b69-aabf-47ce-ad33-ec121316d030">
 
 When the user is within the user account area:
 
<img width="236" alt="image" src="https://github.com/user-attachments/assets/4ccc05e0-2d74-40df-a442-0dcaf8a1cb9a">
 
The HR within the user account area should be updated to match the main nav version when the user is inside a Colony. 

 ## Figma links:
 
 Link to navigation component for correct HR styling: https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=3820-17170&t=89MC58REGrHZmYlw-4

**Comment by rumzledz** [comment]
This will be addressed as part of this PR: https://github.com/JoinColony/colonyCDapp/pull/3522

**Comment by melyndav** [comment]
@rumzledz This one can be closed, right? I see it's on QA.

**Comment by rdig** [comment]
Yup, was merged. Good pickup
