### ISSUE TITLE
QA Nav: Can't access C2F within the user account area from the nav 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3503]
## Description

Currently in the QA env, I can navigation to the user account area. When I select the 'Crypto to Fiat ' menu tab, the page content doesn't load, but leaves me on the 'Profile tab'.

I have disabled all ad-blockers. 

<img width="2033" alt="image" src="https://github.com/user-attachments/assets/0bb8a951-2d70-4ad0-9e97-57d1bf6924c5">

Recording:

![Export-1730197035672](https://github.com/user-attachments/assets/603060bd-5b21-4bdd-918f-5ea023726af0)

**Comment by rumzledz** [comment]
We might just need to enable the `CRYPTO_TO_FIAT` feature flag on our QA environment for this to work

**Comment by melyndav** [comment]
@rumzledz this was tested with a new wallet and the C2F page loaded correctly.

**Comment by rdig** [comment]
Can this be combined with [#3507](https://github.com/JoinColony/colonyCDapp/issues/3507) and fixed together ?

**Comment by rumzledz** [comment]
Just a little recap of the conversations about this from yesterday:

### 1. [BUG] We are currently not hiding this Crypto to fiat nav item behind a feature flag

This is now being addressed in PR #3525 

### 2. There is an issue with how Brave Shield interacts with PostHog's way of updating cookies

1. Open the app on an Incognito tab
2. Connect a wallet that's not in the whitelist
3. Access the Crypto to fiat page
4. You are not able to, which is correct ✅
5. Add your wallet to the whitelist
6. Reload the page
7. You are still not able to, which is incorrect 🙅🏻‍♂️
8. Disable Brave Shield
9. Reload the page
10. You are now able to view it  ✅

I suspect that this might also be an issue with other AdBlockers.

However, @rdig mentioned that this might not be an issue in production, as we've set up a reverse proxy on there to prevent it. However, this configuration is not applied in our QA environment.
