### ISSUE TITLE
QA Dashboard: Switching team shifts the main content container

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3513]
## Description

When selecting a team from the dashboard in the new team switcher component, the main content blocks shifts on load. 

![Export-1730205124136](https://github.com/user-attachments/assets/f47dad28-e0d8-45cb-9761-ef6027c0061b)

And for inside pages:

![Export-1730205251665](https://github.com/user-attachments/assets/8a5babdf-490f-43b5-84e7-103f119a42ab)

This appears to be only on desktop. 

## Steps to reproduce

1. Log in with a MetaMask wallet
2. On the Dashboard, select a different team using the new team switcher component.
3. As the content loads, watch the main content container move. 
4, navigate to the teams page.
5. Select the general team.
6. Watch the content move on load.

## Expected behaviour

* All content globally in the main content container should not shift when a different team is selected using the new team switcher component.

**Comment by iamsamgibbs** [comment]
This is happening because the scrollbar is showing / hiding when the content exceeds the page height / when it isn't. So I'm not sure what we can do about this.

**Comment by rdig** [comment]
I'm really not onboard with having customized scrollbars or modifying the native scroll in any way, unless that is a design requirement

**Comment by melyndav** [comment]
@rdig perfectly fine with not having a custom scrollbar. Thanks!

**Comment by arrenv** [comment]
I was curious about this, as I have noticed it as well, it was something I remember solving awhile ago with some CSS trickery. Although, in doing a quick search I found this https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter which has most modern browser support now, so, could be worth adding in.

**Comment by iamsamgibbs** [comment]
Good suggestion Arren, quickly tried this out in the inspector and looks like it would work nicely:

https://github.com/user-attachments/assets/2df6bf35-bac3-4c9f-960c-1e1495569a82

Support looks good enough that we may as well add it, with the awareness that Safari / iOS users will still experience this issue.
