### ISSUE TITLE
QA Dashboard: Follower count on dashboard doesn't match followers tab data and load in very slowly

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3515]
# Issues

### 1. The number of followers shown on the dashboard, doesn't match the actual followers shown on the followers tab of the Members page.

Here you see the dashboard data:

<img width="406" alt="image" src="https://github.com/user-attachments/assets/32534fe0-06d8-404f-8ba3-098fa4133766">
 
 Here you see the data on the followers tab count:
 
 
<img width="1326" alt="image" src="https://github.com/user-attachments/assets/e0c187dd-b210-42a0-8c5b-e099f23a6bf4">

Another example from a different colony:

<img width="415" alt="image" src="https://github.com/user-attachments/assets/6b6993de-eb83-4c2a-a792-e6d44c4a846b">
 
 
 With the actual data being showed on the followers tab of the Members page:
 
 
<img width="368" alt="image" src="https://github.com/user-attachments/assets/5a96f63b-757a-4b64-b614-aeae777a764e">

#### Steps to reproduce

1. View the followers and members count on a dashboard.
2. Navigate to the Members page and check the count being displayed on the tabbed menu component.
3. The followers data doesn't match the dashboard data. 

### 2. When visiting a Colony with a large follower base, the followers on the dashboard load slowly and incrementally. With larger colonies with bigger follower bases, this isn't an ideal experience since it takes 18 seconds from skeleton load to load in 1500 members (the final follower total).

![Export-1730206303289](https://github.com/user-attachments/assets/f70b7f72-ea86-4aa8-be54-5fc39593b118)

#### Steps to reproduce

1. Navigate to a colony with a large follower base. For this test, I use @rdig RC Colony which has 1500 followers.
2. Load the colony and watch after the skeleton loader, the follower count in the top right header load in very slowly. 

## Expected behaviour

* Both the members and followers data displayed on the dashboard should be correct and match across all locations.
* The follower and member data should load in quicker to avoid any wait time or potential confusion on the actual data the colony has to display. 

## Actual behaviour

* The followers data isn't correctly shown on the dashboard.
* Follower count loads in really slowly. 

---

@iamsamgibbs here - Adding an extra issue to this as it overlaps!

The followers page should not have the team switcher.

`The difference between a member and a follower is: a member is someone with reputation or permissions, while a follower is someone who joined the colony.`

Individual teams do not have followers, only the colony as a whole, so we should remove the team switcher here. The same height should be maintained so that the "Members" / "Followers" tabs do not jump up and down when switching tabs.

The follower count should match the follower count on the dashboard and not filter by team even if `?team=3` is manually added to the URL.

![image](https://github.com/user-attachments/assets/0fe6a270-75d1-4999-a92d-e749a80135f9)

**Comment by rdig** [comment]
For whoever picks this up, the "slow load" is a wiring mistake, it should use the count, rather then the actual data

However, for whom wishes to peek behind the curtain, that's how the member data actually loads, in batches of 100
