### ISSUE TITLE
QA Dashboard: Followers count loads in really slow after skeleton loading state

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3516]
## Description

When visiting a Colony with a large follower base, the followers on the dashboard load slowly and incrementally. With larger colonies with bigger follower bases, this isn't an ideal experience since it takes 18 seconds from skeleton load to load in 1500 members (the final follower total). 

![Export-1730206303289](https://github.com/user-attachments/assets/f70b7f72-ea86-4aa8-be54-5fc39593b118)

## Steps to reproduce

1. Navigate to a colony with a large follower base. For this test, I use @rdig RC Colony which has 1500 followers.
2. Load the colony and watch after the skeleton loader, the follower count in the top right header load in very slowly. 

## Expected behaviour

* The follower and member data should load in quicker to avoid any wait time or potential confusion on the actual data the colony has to display. 

## Actual behaviour

* Follower count loads in really slowly.

**Comment by mmioana** [comment]
I will close this one in favor of having both this issue and the initial one from #3515 treated in the same PR to not get into merging conflicts
