### ISSUE TITLE
QA Notifications: UI fixes to the new userhub tab

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3519]
## Description

Issue 1: The new notifications tab in the userhub is missing HR's between each notification item as per the design and other userhub tabs.

Currently, in QA:

<img width="745" alt="image" src="https://github.com/user-attachments/assets/8e0b33ed-0669-4c5c-8fa5-af8bb9d8384d">

Figma design:

<img width="1049" alt="image" src="https://github.com/user-attachments/assets/be964b04-61f3-4935-b15c-b81dc0d2d53a">

## Figma

Link to Figma design - https://www.figma.com/design/0Fi3AaDlr3LAXBfsOXBGyk/User-Account?node-id=6754-9622&t=QSsB9RdPVTORnWg3-4

Lin to design system component: https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-51509&m=dev

---

Issue 2: The 'Mark all as read text' is missing a hover state. Please add a gray-900 to this text when hovered on desktop.

<img width="107" alt="image" src="https://github.com/user-attachments/assets/1c0d9dde-75d2-4dd3-963e-b9fb4480796e">

**Comment by melyndav** [comment]
*Editing this issue to include another minor UI fix to avoid two minor UI issues being raised on the one component.

**Comment by rdig** [comment]
Can't both this and #3667 be merged ?

**Comment by rdig** [comment]
Thank you. Appreciate it!

**Comment by melyndav** [comment]
I have merged this issue with #3667 as they are related and can be all addressed in one PR.
