### ISSUE TITLE
[Arbitrary Txs] Add arbitrary transaction action form

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#3532]
Figma designs: https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=24968-204505&node-type=frame&t=VK5oE9wW19JFFa0k-0
Feature spec: https://www.notion.so/colony/Arbitrary-Transactions-ba4b096b3b664cb09ef65ad35c4331fa

## Description

Add Arbitrary transaction action type to the action form alongside all the required fields and the Contract interaction modal that shows on form submission.

Note: This is UI only, it doesn't need to be wired to any sagas at this point.

<img src="https://github.com/user-attachments/assets/bd301f22-87a5-4706-a727-ca0bc0bd4a72" width="400"/>
<img src="https://github.com/user-attachments/assets/4ab9de65-7bc3-495a-a8f4-7bf12d69a57c" width="400"/>

## Acceptance criteria

- [ ] Both desktop and mobile views adhere to Figma designs
- [ ] It is possible to select any of the available decision methods (permissions, reputation and multi-sig)
- [ ] Contract interaction modal opens on Add transaction click
- [ ] There is the standard validation for common fields (title, decision method, description)

**Comment by rdig** [comment]
I'm deprioritizing this for the current cycle as we have a lot of QA issues to deal with and getting those deployed is highest priority right now.

We'll revisit this in the next cycle.
