### ISSUE TITLE
[Arbitrary Txs] Option to format/unformat ABI JSON

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#3539]
Figma designs: https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=24968-204505&node-type=frame&t=VK5oE9wW19JFFa0k-0
Feature spec: https://www.notion.so/colony/Arbitrary-Transactions-ba4b096b3b664cb09ef65ad35c4331fa

## Description

Depends on the contract interaction modal to be implemented in #3533 

Add option to format/unformat ABI JSON fetched from the API or entered by the user.

This can be achieved by passing options to `JSON.stringify`: https://stackoverflow.com/questions/4810841/pretty-print-json-using-javascript

<img src="https://github.com/user-attachments/assets/a9fb8494-7681-4c0a-88a3-b8c4ade9fd1a" width="400" />
<img src="https://github.com/user-attachments/assets/17efbc21-82d6-4d8d-8679-4a6d89f23a50" width="400" />

## Acceptance criteria

- [ ] Both desktop and mobile views adhere to Figma designs
- [ ] Format JSON pretty prints JSON in the field
- [ ] Unformat JSON removes all whitespace characters from ABI JSON
- [ ] Option is disabled when JSON is invalid

**Comment by Nortsova** [comment]
This one should be handled as part of https://github.com/JoinColony/colonyCDapp/pull/3694
