### ISSUE TITLE
[Payments - QA] Available tokens not displayed correctly during payment in Raul's Colony

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3541]
## Steps to reproduce

1. Navigate to Raul's Colony. https://arbitrum-sepolia.colony.io/invite/rc/5c9caf3e-29c5-43f2-ab77-6bb171e6894d
2. Go to the Balances section and verify that there are tokens available (e.g., 8.1018M RTK).
3. Attempt to create a payment.
3. Add tokens in the Amount field.
4. Select a token from the dropdown in the Amount field.

## Expected behaviour

* The payment panel should display the correct available token balance, allowing the user to complete the payment.

## Actual behaviour

* The token balance is displayed as zero in the payment panel, resulting in an error message indicating "Not enough tokens."
<img width="1414" alt="image" src="https://github.com/user-attachments/assets/292b8bc3-bdb7-48af-ad8a-7ec77241bb67">

<img width="1414" alt="image" src="https://github.com/user-attachments/assets/dd82eec8-c496-4cb2-8246-f8348be38a2d">

**Comment by iamsamgibbs** [comment]
Hmm, I'm not able to recreate this:

<img width="720" alt="Screenshot 2024-11-01 at 15 13 01" src="https://github.com/user-attachments/assets/56c4f844-5c91-4cb6-816d-99ef1f7477d7">

**Comment by rumzledz** [comment]
Not specifically Raul's Colony but I cannot seem to replicate this on QA @olgapod 🤔 I've checked Jakub and Kerry's colonies:

<img width="375" alt="Screenshot 2024-11-06 at 02 10 30" src="https://github.com/user-attachments/assets/188f2dc7-f6e3-49a9-94b1-67c243f74cc0">
<img width="469" alt="Screenshot 2024-11-06 at 02 10 00" src="https://github.com/user-attachments/assets/03676124-5fe3-480a-8f6f-7e2013dad3ca">

**Comment by olgapod** [comment]
Thanks for checking, I also cannot reproduce it today
