### ISSUE TITLE
[Manage account - Mobiel QA] Arrows  should be more centre-aligned on Manage account 

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3542]
## Steps to reproduce

1. Navigate to Advanced Settings on a mobile device.
2. Observe the position of the arrow icons.

https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-9689&t=TNUwTMcnd6u8AU17-4

https://www.figma.com/design/C2grfQysdsYXz0j4rADR6K/Crypto-to-Fiat?node-id=4446-114929&node-type=frame&t=SD0CsH9hoAVCNb60-0

## Expected behaviour

* Arrows  should be more centre-aligned

## Actual behaviour

* There is a slight miss-alignment of the arrow where it should be more centre aligned

<img width="455" alt="image" src="https://github.com/user-attachments/assets/8caecece-32f8-495e-8593-2a74f407f9c0">

**Comment by melyndav** [comment]
Hi @olgapod this is correct as per the design of the component in Figma. However, there is a slight miss-alignment of the arrow where it should be more centre aligned.

However, for all future issues, please cross-check components first in the design system before raising the issue. And as requested, please include Figma links for all UI/UX related issues as reference points for the devs. 

<img width="454" alt="image" src="https://github.com/user-attachments/assets/ee78927f-f2d7-43f2-b363-5f50352fa839">

https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-9689&t=TNUwTMcnd6u8AU17-4

**Comment by olgapod** [comment]
@melyndav I didn't find this design, thanks for the information
