### ISSUE TITLE
[Create colony] Retry option appears after transaction rejection, which should not be allowed

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3549]
##Description
* When a user manually rejects a transaction during the Colony setup process, a "Retry" option is displayed. This can lead to confusion, as retrying should not be possible after a manual rejection.

## Steps to reproduce

1. Start the Colony setup process.
2. Reach the Complete setup.
4. When prompted in any step, manually reject the transaction in the wallet.
5. Observe the "Retry" button displayed in the UI.

## Expected behaviour

* The "Retry" option should not appear if the user rejects the transaction. 

## Actual behaviour

* A "Retry" option appears even though the transaction was rejected, which may mislead users.

<img width="881" alt="image" src="https://github.com/user-attachments/assets/8a8ecc1b-bbc1-4abe-9ee1-4c7be7b71d7d">

https://github.com/user-attachments/assets/5d2a321a-5894-401e-826a-baf49e581df2

**Comment by iamsamgibbs** [comment]
Working on this part of #3707
