### ISSUE TITLE
[QA Dashboard] Total funds bug

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#3555]
## Steps to reproduce

1. Login on QA to the colony with address `0x997B915CaC293D69f14a8a85e660EE87f1523FcD` - `Jakub Colony`
2. On dashboard you'll see the balance has a small negative value
![Screenshot 2024-10-30 at 12 37 53](https://github.com/user-attachments/assets/771417a4-c5d4-4eda-9b7c-80785d5ea9b2)
3. However, if you switch to the finances pages, on the balance you'll notice the total ETH is positive
![Screenshot 2024-10-30 at 12 38 04](https://github.com/user-attachments/assets/0b6b7318-2b8a-43e0-8c25-3a58d94642e1)
But there is no incoming funds - in the past once an incoming funds was claimed, the entry was deleted
![Screenshot 2024-10-30 at 12 38 17](https://github.com/user-attachments/assets/cd0d2f74-4ef6-42fd-bcc1-8ea9e30ef1b7)

4. Also, another bug related to the funds, was found while scraping through the `getDomainBalance` query: if for the `timeframePeriod` you enter a number of days > than the number of days in a month (considering you selected `TimeframeType.DAILY`), as well as if you enter a number of months > than the number of months in a year (considering you selected `TimeframeType.MONTHLY`), you will not have an entry for each expected key.
So the solution would be to use the entire date `yyyy-mm-dd` as key and then adjust the displayed key in the UI.

https://github.com/user-attachments/assets/17fd48aa-0963-42f4-b2b3-e702a187562c

## Implementation details

Given the incoming funds entries are not available for prior to May 2024 - previously when an incoming funds action was claimed, the entry got deleted, we need to change a bit our approach to the balances.

So, in order to get our data right, at least for the overall amounts shown in the Total cards we need to make use of the actual network balance at colony level or domain level.

For this please make use of the following code put in place by @Nortsova in the UI

```
const calculateTotalFunds = async (
  balances: ColonyBalances,
  currency: SupportedCurrencies,
  selectedDomainNativeId: number | undefined,
): Promise<Decimal | null> => {
  let isError = false;
  const funds = balances.items
    ?.filter(notNull)
    .filter(({ domain }) =>
      !selectedDomainNativeId
        ? domain === null
        : domain?.nativeId === selectedDomainNativeId,
    )
    .reduce(
      async (total, { balance, token: { tokenAddress, decimals } }) => {
        const currentPrice = await fetchCurrentPrice({
          contractAddress: tokenAddress,
          conversionDenomination: currency,
        });

        if (currentPrice == null) {
          isError = true;
        }

        const balanceInWeiToEth = new Decimal(balance).div(10 ** decimals);

        return (await total).add(
          new Decimal(balanceInWeiToEth).mul(currentPrice ?? 0),
        );
      },
      Promise.resolve(new Decimal(0)),
    );

  if (isError) {
    return null;
  }

  return (await funds) ?? new Decimal(0);
};

export const useTotalFunds = () => {
  const selectedDomain = useGetSelectedDomainFilter();
  const { colony } = useColonyContext();
  const { currency } = useCurrencyContext();
  const { balances: colonyBalances } = colony || {};
  const [totalFunds, setTotalFunds] = useState<Decimal | null>(new Decimal(0));

  useEffect(() => {
    const getTotalFunds = async (balances: ColonyBalances) => {
      const funds = await calculateTotalFunds(
        balances,
        currency,
        selectedDomain?.nativeId,
      );
      setTotalFunds(funds);
    };

    if (colonyBalances) {
      getTotalFunds(colonyBalances);
    }
  }, [colonyBalances, currency, selectedDomain]);

  return totalFunds;
};
```

Also, for the caching of the total funds we should make a call to the network and estimate the block for which we want to retrieve the data. So in the `cacheDomainBalance` for the `Total` entry we should make use of this code

```
const networkClient = getColonyNetworkClient(network, provider, {
      networkAddress,
    });

const colonyClient = await networkClient.getColonyClient(colonyAddress);

For domain level balance, use the nativeFundingPotId

const { nativeId, nativeFundingPotId } = domain;


const domainBalance = await colonyClient.getFundingPotBalance(
          nativeFundingPotId,
          AddressZero,
        );
```

To estimate the block number from a given point in time to retrieve the total balance value, we should consider that each chain has a constant block time (0.25s for Arbitrum), so to find a block n seconds ago the following formula can be used: 
`currentBlockNumber - n/0.25`

Now for the total in/out balance given we want to cache the value for the timeframe 60 days - 30 days, we can leave the logic how it is, at least for the moment.

And if we're touching all the domain balances, we should also fix the issue with the timeframe keys that can get overridden.

## Expected behaviour

* We need to get the correct total values
* Also the `getDomainBalance` query should retrieve the `timeframe` containing all relevant keys - this however doesn't or shouldn't impact the values for the moment, as we don't query more than `30 days` or more than `4 months` 

## Actual behaviour

* We don't get the right total values
* We don't get all relevant `timeframe` keys if we were to change our `timeframePeriod` query input

**Comment by mmioana** [comment]
I'll schedule a brain storming session with @jakubcolony first to see what's the best approach for retrieving these values

**Comment by rdig** [comment]
What came of the call here? How are you proceeding? 

Since this is a bug that affects Dashboard it needs to be prioritized
