### ISSUE TITLE
QA - Switching currency to CLNY breaks the app 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3557]
## Steps to reproduce

1. Using the hamburger icon in the top right-hand corner of the user header, select CLNY as the currency. 
2. The app breaks and a blank page is shown.
3. Refresh the browser.
4. The app remains broken.
5. Using the address bar, return to the main Colony landing page.
6. Using the Colony switcher, navigate back to the Colony previously used to switch tokens to CLNY.
5. The app remains broken. 

_You can unbrick this by:_

1. Returning to the main landing page
2. Switching to a different currency from the hamburger menu while on the landing page (not CLNY)
3. Using the Colony switcher, navigate back to the Colony previously used to switch tokens to CLNY.
4. The Colony will load, and the user is not bricked.

Switching straight back to CLNY bricks, the app again. 

## Expected behaviour

Switching tokens should not brick the app. All other currencies work correctly.

## Actual behaviour

<img width="2337" alt="image" src="https://github.com/user-attachments/assets/40b03128-ccb3-42dc-a964-e7673699f835">

**Comment by rdig** [comment]
Nice find! :100: 

Looks like someone didn't account for token decimals properly
