### ISSUE TITLE
[Navigation - QA]Withdraw tokens modal overlaps with balance overview panel

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3559]
##Description
* The Withdraw tokens modal appears overlapped with the Balance overview panel, creating a confusing UI and making it difficult to view or interact with either section effectively.

## Steps to reproduce

1. Navigate to the Dashboard on a desktop or laptop.
2. Open the Balance overview panel.
3. Click on the Withdraw button to open the withdraw tokens modal.
4. Open the Balance overview panel.
5. Click on the Withdraw button to open the withdraw tokens modal.

## Expected behaviour

* The Withdraw tokens modal should appear independently without overlapping the Balance overview panel, allowing users to interact with both elements separately.

## Actual behaviour

* The Withdraw tokens modal overlaps with the Balance overview panel

https://github.com/user-attachments/assets/59e1ffa2-c961-429e-801d-9653e89dc0a2

**Comment by melyndav** [comment]
Hey @olgapod this is known, and we are working on a redesign to handle the transactions in modal better. Closing this issue as it will no longer be relevant.
