### ISSUE TITLE
[Create Colony] Input field validation fails when typing quickly

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3565]
## Steps to reproduce

1. Navigate to the Create colony form.
2. Type quickly into the Custom colony URL field word "account" or any other invalid value.
3. Observe whether the validation triggers correctly.

## Expected behaviour

*  Validation should work consistently, regardless of the typing speed, and should provide feedback on invalid inputs.
* The 'CheckColonyNameExists' network request payload should include the full “account” string as entered in the input field
* 
![photo_2024-10-31 08 56 53](https://github.com/user-attachments/assets/0853fd1d-528b-403b-819d-b7315f96b534)

## Actual behaviour

* Validation allows invalid inputs being accepted.

<img width="1259" alt="image" src="https://github.com/user-attachments/assets/b29363aa-8577-49ab-be0e-62647282f345">

**Comment by rumzledz** [comment]
Hi @olgapod 👋 Can you please confirm if this is still an issue? I cannot seem to replicate it:

![Image](https://github.com/user-attachments/assets/62b97e55-c622-4c6b-9fd4-861e049f4a42)

**Comment by olgapod** [comment]
@rumzledz thanks, I also cannot reproduce anymore
