### ISSUE TITLE
[Notifications] Notifications not received on mobile devices

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3569]
## Steps to reproduce

1. Log in to the application on a mobile device.
2. Perform actions that should trigger a notification.
3. Check if the notification appears on the mobile device.

## Expected behaviour

* Notifications should be received on mobile devices in real-time, keeping users informed of important updates.

## Actual behaviour

* No notifications are received on mobile devices, leading to missed updates.

https://github.com/user-attachments/assets/ec60f0ae-581e-4664-9cd5-c2e9f5b01189

**Comment by rdig** [comment]
Notifications are not real time, that is not something we can provide.

There's considerable delay between the action and the notification showing up
