### ISSUE TITLE
Handle motions that belong to an old voting rep extn

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#357]
What are we doing for motions that were installed by a voting rep that's now been uninstalled? 

Clearly we have to do something so they don't appear interactive to the user. 

Just disable the widget?

Or render something else in addition, e.g. some info for the user about why they can't interact with the motion.

Also handle the case in the ActionsList where if two motions have the same native id, they'll display the same state, even if one was created by an uninstalled voting rep version. I.e. "old" motions in the actions list should have their own tag.

**Comment by willm30** [comment]
@rdig Opinion on this?

**Comment by rdig** [comment]
Either render the widget disabled, or just don't render the any widget at all, whatever's easiest.

We'll do a proper solution in the the new UI/IX.

Whatever ends up being chosen, just make sure to leave a comment explaining the choice.
