### ISSUE TITLE
QA Dashboard: Mobile menu doesn't sticky on scroll 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3579]
## Steps to reproduce

1. On mobile, expand a row within with the dashboard's activity feed.
2. Scroll down and watch the dropdown menu move with the scroll and cover the UI.
3. Close the menu.

## Expected behaviour

* The meatball menu on mobile triggered from a row in the activity feed should 'stick' to the meatball menu on scroll. 

1. Scroll up to the 'Team rep' widget.
2. Select the kebab icon.
3. Scroll up and down. The menu will not move on scroll and 'stick' to the correct position.

## Actual behaviour

The meatball menu moves on scroll covering up the UI and activity feed information.

* [Example: A `WALLET_CREATE_ERROR` action is dispatched and the user cannot log in](https://github.com/user-attachments/assets/276efacc-0958-4540-bd79-ac81a2e84b8b)

**Comment by mmioana** [comment]
This needs to be done based on the changes from https://github.com/JoinColony/colonyCDapp/pull/3566
