### ISSUE TITLE
[Nitifications - QA] Missing notifications for incoming funds transactions

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3592]
## Steps to reproduce

1. Make a simple payment and transfer funds to Colony 2
2. Open Colony 2
3. Go to the "Incoming Funds" section of the application.
4. Check the notifications panel for any alerts related to the incoming funds.

## Expected behaviour

* A notification should be generated and displayed in the notifications panel whenever there are new incoming funds for the user.

## Actual behaviour
* No notification is received for incoming funds transactions, leaving users unaware of these transfers.

![1](https://github.com/user-attachments/assets/6a1acfb7-5f99-499e-89b0-419bb194e516)

**Comment by rumzledz** [comment]
Hi @olgapod maybe I'm just not getting this issue properly but I sent some tokens from Planex to Wayne and can verify that the notification is being dispatched for the Wayne Colony:

<img width="1800" alt="Screenshot 2024-11-05 at 02 36 51" src="https://github.com/user-attachments/assets/22c71e20-f8b1-432e-98d1-b3ef6dea3876">
