### ISSUE TITLE
[Actions - QA ]App Crashes on redo of "Manage Reputation" due to invalid BigNumber Error

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3593]
## Steps to reproduce

1. Open Manage reputation action draw.
2. Attempt to redo actions.
3. Observe the app behavior.

## Expected behaviour

* Redo "Manage reputation" action should proceed smoothly without causing any app crash.

## Actual behaviour

* The app crashes, and the console displays an "invalid BigNumber" error

<img width="1473" alt="image" src="https://github.com/user-attachments/assets/24e77981-9851-4361-9519-d4942350c6ac">

<img width="1646" alt="image" src="https://github.com/user-attachments/assets/d16344dc-6db6-4b30-974d-4ca35125d7a7">

**Comment by rumzledz** [comment]
This is now being addressed in PR: https://github.com/JoinColony/colonyCDapp/pull/3587
