### ISSUE TITLE
[Notifications - QA] Mention notifications are sent to the same address as the creator

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3594]
## Steps to reproduce

1. First, log in as both Leela and Amy.
2. As Leela, create a simple payment to Leela.
3. As Leela, create a simple payment to Amy.
4. Check Leela's notifications - there should not be a mention notification about either action.
5. Check Amy's notifications - there should be one mention notification, about the action which sent a payment to Amy.

Check steps on PR https://github.com/JoinColony/colonyCDapp/pull/3394

## Expected behaviour

* Mention notifications are sent to the same address as the creator. Amy's notifications - there should be one mention notification, about the action which sent a payment to Amy.

## Actual behaviour

* Mention notifications are sent to the same address as the creator

**Comment by rumzledz** [comment]
The fix needed to be done on our Block Ingestor: Here's the PR: https://github.com/JoinColony/block-ingestor/pull/293

**Comment by rumzledz** [comment]
Can you also clarify these parts? They seem to be contradictory:

<img width="846" alt="image" src="https://github.com/user-attachments/assets/39cced14-36b3-4cd0-9fc3-544ea38ca699">

**Comment by olgapod** [comment]
@rumzledz Functionality works as expected today, Amy receive 2 notifications, and Leela 1
