### ISSUE TITLE
[Actions - QA] Error displayed after redo multi-sign permission action

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3596]
Uploading 3.mp4…

## Steps to reproduce

1. Enable Multi-sign extentions
2. Open manage permission actions
3. Give User 1 owner role with multi-sign
4. Open Action draw and click on the redo button
5. Select User 2 and click on "Update permissions" button
6. Observe the error
7. Close  action draw
8. Open manage permission actions
9. Give User 2 owner role with multi-sign

## Expected behaviour

* Multi-sign permission setup should complete successfully without displaying errors upon redo.

## Actual behaviour

* An error message is displayed when redo the multi-sign permission setup.

https://github.com/user-attachments/assets/7b724be5-1086-4867-b6b0-d5c8e7ad3fdc

**Comment by rdig** [comment]
Please be more specific when detailing issues.

In this case, yes, you are correct that the form incorrectly validates the new user's permissions.

It is totally possible for a variety of reasons the redo form to have a validation error, so your issue's description is at best vague and at worst misleading.

**Comment by rumzledz** [comment]
It seems that I cannot reproduce this since the form correctly auto-populates a selected member's permissions 🤔 Maybe I can pair up with you at some point tomorrow @olgapod so I can see this 🐞 in action!

![redo ms owner](https://github.com/user-attachments/assets/25d13722-3c9e-4d07-928f-8d6c64b93913)

**Comment by olgapod** [comment]
@rumzledz Thanks for checking. Validation works today as expected
