### ISSUE TITLE
[Notifications - QA]Approval Notification missing for Multi-Sign action

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3597]
## Steps to reproduce

1. First, log in as both Leela and Amy.
2. As Leela, create a simple payment to Leela.
3. As Leela, create a simple payment to Amy.
4. Check Leela's notifications - there should not be a mention notification about either action.
5. Check Amy's notifications - there should be one mention notification, about the action which sent a payment to Amy.

Steps in the task https://github.com/JoinColony/colonyCDapp/pull/3394

## Expected behaviour

* there should be one mention notification, about the action which sent a payment to Amy

## Actual behaviour

* No approval notification is sent upon completion of the multi-sign approval process.

**Comment by rumzledz** [comment]
Please note that the conditional dispatching of Notifications is being addressed here: https://github.com/JoinColony/block-ingestor/pull/293

**Comment by rumzledz** [comment]
I cannot seem to replicate this @olgapod. I am able to receive notifications as Amy throughout the Simple Payment's Multi-sig process:

<img width="705" alt="image" src="https://github.com/user-attachments/assets/854d9ca3-534e-4a29-af97-3046e273f072">

**Comment by olgapod** [comment]
@rumzledz all functionality works as expected today
