### ISSUE TITLE
[Notifications - QA] Notifications not sent for Multi-Sig actions

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3604]
## Steps to reproduce

1. Log in as Leela in one browser, and Amy in another incognito browser. As Leela, install the multisig extension. Set the threshold to be fixed at "2".
2. Give Leela and Amy multisig owner permissions. Check that you receive notifications for these.
3. Create a multisig action. It can be any type of action as long as it is multisig. Check that you receive a notification when this is created.
4. As Amy, add a second approval to the multi sig action. Go back to Leela and check that she received a new notification for the approval. Then finalize the motion as Leela, and check that she also received a notification for that.
5. As Leela, make another multisig motion. Immediately go back to the approval step in the sidebar and remove her approval, then reject the motion. Check that a notification arrived for this rejection.

Steps in the task https://github.com/JoinColony/colonyCDapp/pull/3280

## Expected behaviour

* A notification should be sent to all relevant parties upon the completion of a multi-sig action.

## Actual behaviour

* No notification is sent when the multi-sig action is completed.

**Comment by davecreaser** [comment]
Hey @olgapod, also struggling to replicate this one, could you please check?

I tried a couple of times but the finalized notification always comes through. Thanks!

<img width="677" alt="Screenshot 2024-11-28 at 15 28 13" src="https://github.com/user-attachments/assets/8e995d48-1539-44e3-801b-7ae1fa3e95bc">
<img width="673" alt="Screenshot 2024-11-28 at 15 28 48" src="https://github.com/user-attachments/assets/f35beed3-3554-4622-9f9b-680c24ce70bb">

**Comment by olgapod** [comment]
@davecreaser You are right, I also get all notifications now
