### ISSUE TITLE
[Notifications - QA] Missing notifications for Advanced payments

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3605]
## Steps to reproduce

Open QA environment 
1. User 1 Create an advanced payment and ensure that User 2 is one of the recipients, open User 2 notifications pannel and check that you receive two notifications, one about the advanced payment being ready for review, and one mention.
<img width="801" alt="image" src="https://github.com/user-attachments/assets/88c2816e-ece0-4da2-824b-876933038c05">
<img width="661" alt="image" src="https://github.com/user-attachments/assets/e7b478a5-cebe-4810-be86-b5a4b11cf447">

2. Click on confirm details in the advanced payment's action sidepanel, and check that user2 receive a notification stating that the advanced payment is ready for funding. 
<img width="666" alt="image" src="https://github.com/user-attachments/assets/ca8ebf69-14da-42c6-bfb4-19dc4db0a7ce">

3. Fully fund the payment, and check that you receive a notification stating that the payment is ready for release. 
<img width="797" alt="image" src="https://github.com/user-attachments/assets/23e6df2e-c62d-42b6-9141-f80cd6aeb2fe">
<img width="667" alt="image" src="https://github.com/user-attachments/assets/12c67906-1f11-43f4-94ef-2e1b318aacf0">

4.  Release the payment, and check that you receive a notification stating that the payment has been finalized. 
<img width="796" alt="image" src="https://github.com/user-attachments/assets/5b9b8754-4aa9-4984-ab5f-ea8eed708df4">
<img width="663" alt="image" src="https://github.com/user-attachments/assets/de20df08-251f-43ab-8376-df02067c77fa">

5. Make a new advanced payment, this one without Leela as a recipient. Check that Leela only receives one notification this time (ie. no mention) 
<img width="796" alt="image" src="https://github.com/user-attachments/assets/2bb01611-65ed-416e-acba-5b2b1b04eefa">

6. Cancel the payment, and check that you receive a notification 
<img width="797" alt="image" src="https://github.com/user-attachments/assets/75f7b9f8-6f6d-4d33-885f-586ef7c82f05">
<img width="660" alt="image" src="https://github.com/user-attachments/assets/35e80916-a4d1-4f31-ac0d-8cd6234e02c8">

Steps in the task https://github.com/JoinColony/colonyCDapp/pull/3252

## Expected behaviour

* Users should receive notifications for each key stage in the advanced payment process, including funding, approval, and release.

## Actual behaviour

* Some notifications are missing or not delivered as expected, resulting in incomplete updates for the advanced payment stages.

Original task https://github.com/JoinColony/colonyCDapp/pull/3252

**Comment by rumzledz** [comment]
> Some notifications are missing or not delivered as expected, resulting in incomplete updates for the advanced payment stages.

Hi @olgapod , can you please specify which notifications are missing here? Many thanks!

**Comment by olgapod** [comment]
@rumzledz I added pictures. Take a look at it, please

**Comment by davecreaser** [comment]
Hey @olgapod - is this bug still reproducible for you? During my testing the advanced payment notifications always come through:

<img width="685" alt="Screenshot 2024-11-28 at 12 15 43" src="https://github.com/user-attachments/assets/4d953d2d-2b9b-479b-8d91-8fdea1648dda">

(Tested locally on the master branch as well as on QA. The screenshot here is from QA)

**Comment by olgapod** [comment]
@davecreaser, thank you for checking! It looks work ok now
