### ISSUE TITLE
[Notifications - QA] Incorrect titles displayed in notifications panel

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3606]
## Steps to reproduce

1. Perform actions: 
- Transfer funds
- Mint tokens
- Unlock a token
- Manage tokens
- Create new team
- Edit a team
- Manage reputation
- Manage verified members
- Manage permissions
- Edit Colony details
- Upgrade Colony version
2. Open Notifications panel

The correct titles of notifications are shown in the https://github.com/JoinColony/colonyCDapp/pull/3205

## Expected behaviour

* Notification titles should accurately reflect the corresponding actions taken, providing users with clear and relevant updates.

## Actual behaviour

* Incorrect titles displayed in notifications panel

<img width="1649" alt="image" src="https://github.com/user-attachments/assets/c92ac161-1b73-4296-8163-2bc39264442b">

**Comment by arrenv** [comment]
@olgapod This is accurate to the spec, as can be seen here - https://www.notion.so/colony/Notifications-2c4b006528b64094b8d0741f2fc293bd

However, upon testing this feature, it has been noticed that we can improve the info and layout displayed here. This will come as an enhancement with an updated design and spec.
