### ISSUE TITLE
QA Notifications: Notifications not showing until a hard refresh

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3609]
## Description

After connecting my wallet today and accessing the app for the first time since Friday, my notifications do not show in the UI.

I refreshed, disconnected and re-connected and the notifications continued not to show. 

<img width="2249" alt="image" src="https://github.com/user-attachments/assets/5de2f42c-fc9c-4b8a-943b-10ce20b50b66">

However, after a hard refresh, the UI updates to show the notifications and the correct UI.

<img width="2243" alt="image" src="https://github.com/user-attachments/assets/41627374-a913-43fd-90e9-d135d399f84b">

## Steps to reproduce

1. Ensure you have existing notifications unread in the UI.
2. Connect your wallet.
3. Note the blue alert does not show once connected in the user pill of the user head. 
4. Open the userhub and select the notifications tab. 
5. The notifications tab is empty. 
6. Disconnect your wallet.
7. Navigate back to the original colony and check the UI. The notification alert and tab is not showing/ empty.
8. Do a hard refresh in the browser.
9. The UI updates and shows the alert and notifications within the notifications tab.

## Expected behaviour

* The UI should show the notifications alerts and correct information in the notification tab without requiring the user to perform extra steps to get UI feedback.

## Actual behaviour

* No notifications UI or content shows.

**Comment by rdig** [comment]
This seems eerily similar to what @iamsamgibbs is fixing via [#3508](https://github.com/JoinColony/colonyCDapp/issues/3508)

**Comment by iamsamgibbs** [comment]
> This seems eerily similar to what @iamsamgibbs is fixing via [#3508](https://github.com/JoinColony/colonyCDapp/issues/3508)

Yeah, I suspect this would be fixed by #3586

**Comment by melyndav** [comment]
Perfect @iamsamgibbs thanks for sorting this issue in #3586 👏

**Comment by iamsamgibbs** [comment]
Closing this as I suspect it has been resolved by #3586 but please re-open it if it is still occurring after the QA deployment.
