### ISSUE TITLE
Entering user name in a loop

### ISSUE THREAD

**Issue by vporton** [JoinColony/colonyCDapp#361]
I enter username, then in whatever reason the colonyCDapp asks me to switch account. After this I am again at the page asking to enter username. Infinite loop.

See the video:
https://user-images.githubusercontent.com/2900574/229529338-594c6d27-2e2a-4b91-b8d3-a4f5f8b64301.mp4

**Comment by rdig** [comment]
This is a metamask issue. You need to actually "connect" your metamask account to the dapp, otherwise it won't consider it "active"

This is not something we control, this related to the metamask extension.

**Comment by vporton** [comment]
> This is not something we control

But you could have a better error message.
