### ISSUE TITLE
[Incoming - QA]All funds accepted after pressing a single Accept button

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3612]
## Steps to reproduce

1. Make 2 simple payments and send tokens to the second colony.
2. Open the second colony and go to the "Incoming Funds" page.
3. Identify multiple entries with the "Accept" button available.
4. Click "Accept" on one specific entry.

## Expected behaviour

* Only the selected entry should be accepted after pressing a single Accept button

## Actual behaviour

* All funds accepted after pressing a single Accept button

https://github.com/user-attachments/assets/4e8ce248-0045-4fbf-90dd-b7b356be1b60

<img width="422" alt="image" src="https://github.com/user-attachments/assets/859e36aa-1105-4712-a0ea-65cce131151b">

**Comment by rdig** [comment]
Closing this as it will become part of a new feature
