### ISSUE TITLE
[Notifications - QA] Duplicate Notifications for Extension Installation

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3613]
## Steps to reproduce

1. Go to the "Extensions" page.
2. Install the "Staking Advanced Payments" extension.
3. Install the "Reputation Weighted (Lazy Consensus method)" extension.
4. Check the notifications panel.

## Expected behaviour

* A single notification is sent for each extension installation.

## Actual behaviour

* Two identical notifications are sent for each extension installation.

<img width="1594" alt="image" src="https://github.com/user-attachments/assets/75998b74-7890-4397-baaf-e73533aa6d3b">

**Comment by iamsamgibbs** [comment]
I think this is the expected behaviour. The first notification is for the extension being installed, the second is for the extension being enabled. For most extensions, it is enabled immediately after it is installed which is why the two notifications are sent so close together.

**Comment by olgapod** [comment]
@iamsamgibbs Thanks, for information
