### ISSUE TITLE
[Payment -QA] The new follower isn't displayed in Simple Payment Recipient list

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3632]
## Steps to reproduce

1. Join the New colony 
<img width="1465" alt="image" src="https://github.com/user-attachments/assets/e067802a-1398-4900-991c-a75a2e9ad427">

2. Ownew of colony make a simple payment, click on the Select member button, and enter "Junior" in the search field
<img width="1785" alt="image" src="https://github.com/user-attachments/assets/474220f9-1291-4953-b39b-d2a7554e4120">

## Expected behaviour

* All followers should appear in the recipient list to allow payments to any colony member.

## Actual behaviour

*  The new follower isn't displayed in Simple Payment Recipient list

**Comment by rdig** [comment]
This might be a devops issue, the members seem to not be properly indexed

**Comment by melyndav** [comment]
@olgapod can you please include in your issue that the empty state UI is also missing for the recipient field? I am happy to raise another issue if this should be addressed separately. 

<img width="262" alt="image" src="https://github.com/user-attachments/assets/369feb7b-f430-44fb-aa74-66b184e981b4">

https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-12055&t=zpMwEmhxWT6SHMAW-4
