### ISSUE TITLE
[Payment - QA]The "Create Payment" button should be disabled if user don't have enough funds

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3650]
## Steps to reproduce

1. Enable "Staking Advanced Payments" extension.
2. User with not enough  funds Create a split payment.
2. Open "Create a payment" step.
4. Press "Create payment" button.
3. Observe that the "Create Payment" button remains clickable.

## Expected behaviour

* The "Create Payment" button should be disabled or the modal should be disabled.

## Actual behaviour

* Create Payment button is clickable without sufficient funds for staking

<img width="1199" alt="image" src="https://github.com/user-attachments/assets/495f428b-0b89-4cf3-a382-788864b8aef9">

**Comment by melyndav** [comment]
Hey @olgapod, can you update the image for this issue to the correct one? This screenshot is showing with the 'leave this colony' example and doesn't correlate to the payment behaviour.

**Comment by olgapod** [comment]
@melyndav Thank you for this notice, I changed an issue

**Comment by melyndav** [comment]
Thanks for updating the screenshot @olgapod. We don't disable buttons (globally where possible) to allow the user to get feedback as to why they can't perform an action, and in this case, why they can't create a payment. 

The user can exit by 'cancelling' or closing the modal via the 'X'. 

As a potential improvement here, we could show this error upon selection of the 'Staking' decision method so they do not spend time completing the rest of the payment.

I will log this as a UX improvement in the design kanban, but this issue can be closed.
