### ISSUE TITLE
[Create a team - QA] Error "createdIn must be defined" is shown when attempting to create a new team

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3664]
## Steps to reproduce

1. Navigate to the "Teams" section.
2. Click on "Create new team."
3. Fill in the required fields.
4. Attempt to create the team by clicking the "Create team" button.
5. Observe the error message displayed.

## Expected behaviour

* The team should be created without any errors.

## Actual behaviour

* An error message stating "createdIn must be defined" is shown, and the creation process fails.

<img width="1776" alt="image" src="https://github.com/user-attachments/assets/68ddfad1-b1e5-4bce-beea-b31ad2dffb70">

**Comment by rdig** [comment]
This is the same as all the other issues with the action form and will be fixed by #3659
