### ISSUE TITLE
[UI Motion]: Motion/Transaction not found screen wrong paddings

### ISSUE THREAD

**Issue by Nortsova** [JoinColony/colonyCDapp#3685]
## Steps to reproduce

1. Open any non-existent transaction
http://localhost:9091/planex?tx=0xb9dffd734a299d894844db88308012ec365fd553947d7f5815882cafd15e475b
2. Check the screen: 
3. 
<img width="760" alt="image" src="https://github.com/user-attachments/assets/4cabad6b-3a14-4c0e-8139-c23116d11912">

## Expected behaviour

https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=23947-236394&node-type=frame&t=D9GAyZBPcinVmo4l-0

## Actual behaviour

Not aligned to the Figma design

**Comment by rdig** [comment]
Closing in favor of [#3670](https://github.com/JoinColony/colonyCDapp/issues/3670)
