### ISSUE TITLE
[Dashboard - QA] New Actions not displayed in dashboard "Recent Activity" table

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3692]
## Steps to reproduce

1. Open 2 google accounts with 2 different users in one colony.
2. Go to the Dashboard.
3. Perform any action that should appear in the "Recent Activity" table.
4. Open second browser.
5. Check the "Recent Activity" table to see if the new action is displayed.

## Expected behaviour

* The "Recent Activity" table should display new actions immediately after they are performed.

## Actual behaviour

* New actions are not appearing in the "Recent Activity" table, even after the actions are successfully executed.

<img width="1656" alt="image" src="https://github.com/user-attachments/assets/27ae3370-db2c-4656-a49a-4b109c0995a5">
<img width="1217" alt="image" src="https://github.com/user-attachments/assets/24044649-7c9c-40e1-9c86-647c3ef111f9">

**Comment by jakubcolony** [comment]
Thanks for adding the issue @olgapod, is the expected behaviour mentioned in the specs? Otherwise it would be an enhancement as the activity feed table does not poll for new actions from other browser tabs/users

**Comment by olgapod** [comment]
@jakubcolony I see, thanks for information
