### ISSUE TITLE
When redoing a Manage Permissions action it should be possible to change the permissions type

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#3703]
## Steps to reproduce

1. Create a manage permissions action
2. Redo the action from the completed action screen or the activity feed
3. Change the permissions type

## Expected behaviour

* The permissions type should change

## Actual behaviour

* The permissions type changes then instantly changes back to the previous value

https://github.com/user-attachments/assets/15414ffa-78e7-4ce3-8b03-a0210363a97c

**Comment by rdig** [comment]
We also have [#3481](https://github.com/JoinColony/colonyCDapp/issues/3481) that tackles redo-ing actions, so maybe they can be tackled together

**Comment by rumzledz** [comment]
Hey @iamsamgibbs ! I think this one is already fixed on `master` 👌

**Comment by rumzledz** [comment]
Thanks for rechecking @iamsamgibbs ! This is being handled under PR #3789
