### ISSUE TITLE
Manage Permissions Completed Action screen is broken when assigning multi-sig permissions

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#3714]
## Steps to reproduce

1. Create a manage permissions action
2. Select via multi-sig as the authority type
3. Submit the form

## Expected behaviour

* The completed action screen shows with the correct permissions type shown in the table

## Actual behaviour

* The "Owner" set of permissions is always shown

https://github.com/user-attachments/assets/2e7cf1d9-b3aa-4f04-aa0e-e7cf0dd1f188

**Comment by rumzledz** [comment]
Ah! I think this one was recently fixed in #3828 @iamsamgibbs 🙌

**Comment by iamsamgibbs** [comment]
Nice! Checked and confirm this is fixed on master, nice job @rumzledz
