### ISSUE TITLE
[Payments] Disabled action state not displayed or disappears after opening advanced payment drawer

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3720]
## Steps to reproduce

1. User without permissions open advanced, split, or staged action draw.
2. Fill in the form and Submit.

## Expected behaviour

* Disabled action state is displayed after opening advanced payment draw.

## Actual behaviour

* Disabled action state not displayed or disappears after opening advanced payment draw.

 requirements 
 

https://github.com/user-attachments/assets/f9178f6c-637a-403c-bc53-c06ce8673cae

https://www.notion.so/colony/Advanced-Payments-c0c4ee0436394146a23e305180e6ae21
<img width="641" alt="image" src="https://github.com/user-attachments/assets/c958b5b8-baa8-4ad7-97e8-a9ddb82a2c5d">

**Comment by rumzledz** [comment]
Hi @olgapod ! Can you please retest this on `master` when you get the chance? I feel like this has already been fixed on https://github.com/JoinColony/colonyCDapp/pull/3629

**Comment by olgapod** [comment]
@rumzledz You are right, thanks! I cannot reproduce it anymore
