### ISSUE TITLE
[Actions] Redo action feature is broken on the master

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3748]
## Steps to reproduce

1. Perform any action.
2. Redo the action.

## Expected behaviour

* Redo action feature is worked on the master

## Actual behaviour

* Redo action feature is broken on the master

<img width="1689" alt="image" src="https://github.com/user-attachments/assets/a85c5f88-17fc-4d25-b409-8c9d8d36e922">

**Comment by rdig** [comment]
I don't think that's correct. I suspect you're running the production build, which is trying to fetch coin gecko urls for currency conversions, which cannot function on a local environment.

Please re-test this on master, without a production/preview build

**Comment by olgapod** [comment]
Thanks for comment, I cannot reproduce anymore
