### ISSUE TITLE
[Split payment] App crashes when entering value in the amount field of the Split Payment form

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3751]
## Steps to reproduce

1. Navigate to the Split Payment form.
2. Select Equal distribution.
3. Focus on the Amount field.
4. Enter 0.000000000000001 value into the field.
5. Observe that the application crashes immediately.

## Expected behaviour

* The app should accept numeric input in the Amount field without crashing.

## Actual behaviour

* The app crashes as soon as a numeric value is entered in the Amount field of the Split Payment form.

<img width="1707" alt="image" src="https://github.com/user-attachments/assets/bc1debd5-05fc-4208-8ab9-efca8219e173">
<img width="952" alt="image" src="https://github.com/user-attachments/assets/e3b804bc-95d4-4bd5-a9e3-a20ff4005c53">

https://github.com/user-attachments/assets/1957c1d6-5ee1-42cd-84ff-5fccf1301de4

**Comment by rumzledz** [comment]
Hi @olgapod ! Can you please double check if this is still an issue on `master` ? I seem to be able to enter `0.000000000000001` into the amount field:

<img width="1191" alt="image" src="https://github.com/user-attachments/assets/881a5f89-232c-4fff-9de4-9693e83ea15c">


But the actual issue I'm seeing is this:

<img width="1191" alt="Screenshot 2024-11-27 at 20 00 55" src="https://github.com/user-attachments/assets/79a7805d-95ed-4f50-8663-95f5e6245356">
