### ISSUE TITLE
[UserHub] Metadata for activity is replaced by long code snippets in the UI

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3755]
## Steps to reproduce

1. Leela creates a simple payment with the reputation for Leela.
2. Open UserHub.
3. Click on the View Staked balance.
4. Observe inconsistent formatting and unclear labels.

## Expected behaviour

* Display metadata info.

## Actual behaviour

* Metadata for activity is replaced by long code snippets in the UI.

<img width="1762" alt="image" src="https://github.com/user-attachments/assets/cce8201f-0369-4920-920a-4865409c0e93">
<img width="718" alt="image" src="https://github.com/user-attachments/assets/b22998ed-edca-40b6-b533-7249528d349f">
<img width="706" alt="image" src="https://github.com/user-attachments/assets/d5938404-7f66-4d68-94a9-f345e464b78e">

**Comment by rdig** [comment]
Those code snippets are again, Message Descriptors :)
