### ISSUE TITLE
[UserHub] Transactions from other colonies are being displayed

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3758]
## Steps to reproduce

1. Make simple payment
2. Change colony
3. Open UserHub - Transaktions
4. Klick on the last transaction

## Expected behaviour

* The "Transactions" section should only display transactions associated with the currently active colony.

## Actual behaviour

* Transactions from other colonies are being displayed

<img width="1679" alt="image" src="https://github.com/user-attachments/assets/19e0cf10-5865-451f-9a60-7b2575b141fd">

**Comment by rdig** [comment]
I believe this is the intended functionality, although I'm not quite sure

**Comment by iamsamgibbs** [comment]
Yeah I also think this is the intended functionality, however it will just attempt to open the transaction in the current colony, it should instead redirect to the colony it was created in (which is how the stakes tab currently works)
