### ISSUE TITLE
[Permissions] Decision method not displayed for users with Owner Multi-sig permission in advanced payment setup

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3771]
## Steps to reproduce

1. Disable Staking Advanced Payments extension.
2. Assign Owner Multi-sig permission to Fry.
3. Fry opens Advanced Payment(Split, Staged) and clicks on the Decision Method option.

## Expected behaviour

* Advanced payment - Decision method: Staking
* Staged Payment: The form should have a disabled state.
* Split Payment: The form should have a disabled state.

## Actual behaviour

* The Decision Method option is not displayed.

<img width="1703" alt="image" src="https://github.com/user-attachments/assets/93507342-b18e-416a-8863-c617471989d6">

**Comment by rdig** [comment]
How did you connect/disconnect fry's wallet in between setting the permission and trying to do the advanced payment ?

Seperate tabs? Same tab?

This might actually be a data refresh issue after all

**Comment by olgapod** [comment]
I added one step to reproduce the issue, @rdig could you recheck it, please?

**Comment by olgapod** [comment]
@rumzledz In your video, I can see that Fry has Payer permission in Individual Authority. You should remove it and leave only the Owner permission in Multi-sig Authority.
@jakubcolony I have updated the expected behavior. Could you please review it and confirm if everything is correct?
