### ISSUE TITLE
[Permissions] Disabled state doesn't disappear after changing the decision method and redoing action

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3777]
## Steps to reproduce

1. Enable Staking Advanced Payments extension.
2. Leela make an advanced payment.
3. Fry opens the dashboard and redo Leela's activity action.
4. Change the decision method on Staking.

## Expected behaviour

* Disabled state should disappear and allow making a payment.

## Actual behaviour

* Disabled state doesn't disappear after changing the decision method and redoing action.

https://github.com/user-attachments/assets/1e0db027-01e0-4ad6-8a3e-2ca1efc5f731

**Comment by rumzledz** [comment]
Hey @olgapod , what are the permissions given to Fry in your scenario?

**Comment by olgapod** [comment]
@rumzledz Fry has no permission. I can reproduce it today
