### ISSUE TITLE
QA Dashboard - Newly created teams not showing in the team widget across all pages

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3823]
## Steps to reproduce

1. Create a new team using permissions.
2. Select the meatball menu within the team switcher widget on the dashboard.
3. The new team does not show within the dropdown.
4. Navigate to the Teams page.
5. Note the new team shows in the team cards.

## Expected behaviour

* A newly created team should automatically show in the team widget globally. Mobile is also being impacted.

## Actual behaviour

* The newly created team does not show in the widget, meaning the user can not use the widget correctly. 

Note the activity feed showing the new Space Cheese & Pickle God teams being created, but it's not appearing in the team widget dropdown on the right.

Activity feed:
<img width="1313" alt="image" src="https://github.com/user-attachments/assets/13932784-126c-40ac-9026-874b22b32808">

Teams not showing:
<img width="1321" alt="image" src="https://github.com/user-attachments/assets/717fd62f-de4b-473d-8a04-0cba3597799f">

New teams showing on the teams page:
<img width="894" alt="image" src="https://github.com/user-attachments/assets/65453d9e-478a-4c39-ba7d-677cb47dc41e">

New teams displaying in team selection within actions:
<img width="551" alt="image" src="https://github.com/user-attachments/assets/030b60ad-b387-4cf8-a662-160781a0e379">

**Comment by rdig** [comment]
This is a data refresh issue, the team shows up after a page refresh

**Comment by melyndav** [comment]
@rdig I refreshed multiple times, have created actions, switched Colonies, and I am still not seeing the newly created teams.

**Comment by rdig** [comment]
Here's it being reproduced:

https://github.com/user-attachments/assets/ed04e879-6fe2-4f4d-807d-e2f5658597a8

**Comment by melyndav** [comment]
@rdig I got the information to show, so I will close this. However, it highlights a sorting issue in this widget, so will raise a separate issue for it.

**Comment by rdig** [comment]
Oh yeah, sorting definitely needs improving. Thanks for putting up a issue for it :+1:
