### ISSUE TITLE
QA Dashboard: Incorrect Sorting in the Team Widget

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3829]
## Description

Currently in QA, the teams within the new team switcher are not sorted correctly as per the specs. 

The main visible portion of the component seems to be displaying the teams by created date.

<img width="1306" alt="image" src="https://github.com/user-attachments/assets/1e460637-69ea-46b4-a8ae-fa0cd9f69be6">

The meatball menu, when triggered, appears to be sorting the teams alphabetically. 

<img width="268" alt="image" src="https://github.com/user-attachments/assets/c7397f6f-199b-4d87-b49f-0a7ec9d677dc">

## Expected behaviour

* Sorting of the teams in this widget should be as per the specs across all responsive sizes:

<img width="650" alt="image" src="https://github.com/user-attachments/assets/fcad4200-dc4a-4641-a9cd-3a5c24ea3c4e">

Specs link: https://www.notion.so/colony/Dashboard-Colony-Home-322f296cb46240d3afddeddd7472ddd7?pvs=4#1510ad3cd19280968454fbddf2bb8b16

## Actual behaviour

* Teams are sorted differently between the visible list and the overflow meatball menu, causing confusion and poor UX.

**Comment by iamsamgibbs** [comment]
Hmmm I made a fix for this recently in #3775 so it should be working correctly. Can you check the reputations for all the teams from "Auth team" onwards? (most likely all the new teams have a reputation of 0?) If the reputation matches then they will sort alphabetically. It is coincidence here that the alphabetical teams line up in the meatball menu, there is definitely no specific sorting order for the meatball menu.
