### ISSUE TITLE
[Payment] UI allows users to attempt staking on a motion even if they do not have enough tokens

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3845]
## Steps to reproduce

1. Enable reputation extension with Custom settings(picture1).
2. User has more than 20% Reputation.
3. User should have tokens but fewer than needed for staking.
4. Create simple payment with reputation.

## Expected behaviour

* UI shouldn't allow users to attempt staking on a motion even if they did not have enough tokens.
* "You don't have enough tokens" message is shown on the first step.

## Actual behaviour

* UI allows users to attempt staking on a motion even if they do not have enough tokens

before payment
<img width="1755" alt="image" src="https://github.com/user-attachments/assets/d8fd3469-06ff-4d74-9487-b464ec8e8982">
after payment
<img width="679" alt="image" src="https://github.com/user-attachments/assets/c984399d-74c8-48fa-943e-73af959a8b08">

https://github.com/user-attachments/assets/906ada28-495e-41a6-b67c-11dbef617f18

**Comment by jakubcolony** [comment]
Thanks for looking into this @olgapod.

After all, I don't think there are any issues here.

At the start of your video, you had enough tokens to stake the minimum (1% of 26,326.54). Therefore it makes sense that the "You don't have enough tokens" did not show. It should not be checking if you have enough to stake 100%, just the minimum determined by the **Minimum Stake** parameter of the extension.

Once you staked, you used up all of your non staked tokens and you could not stake any further - and the message was displayed as expected.

**Comment by olgapod** [comment]
@jakubcolony Could you chek please if this behavior correct? 
<img width="702" alt="image" src="https://github.com/user-attachments/assets/bf522e45-a70d-421f-bf71-ad49dcf5af9e"

https://github.com/user-attachments/assets/e6020538-065d-4848-929b-6acff25fce22

**Comment by jakubcolony** [comment]
Looks correct to me. You had 11,000 inactive tokens (total - staked - active) which is ~41% of the required stake. While staking, the UI auto-activated these tokens for you and allowed you to stake all of them. After that, you had no inactive or active tokens left so you got the not enough tokens error.

Do you think there's still some issue in this behaviour?

**Comment by olgapod** [comment]
@jakubcolony I see, thanks a lot for the explanation. I close the issue
