### ISSUE TITLE
[Extensions] Set minimum duration for staking, voting, and reveal phases to prevent payment failures

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3846]
## Steps to Reproduce:

1. Go to the "Reputation Weighted (Lazy Consensus method)" settings under "Extensions."
2. Select Custom settings.
3. Set very low durations (e.g., 0.01 hours) for staking, voting, or reveal phases.
4. Attempt to initiate a payment requiring these steps.
5. Observe the failure during the process.

Expected Behavior: The system should enforce a minimum duration for each phase to ensure the payment process completes successfully.

<img width="1670" alt="image" src="https://github.com/user-attachments/assets/ddc1bc21-f371-469f-a09e-fe8d0ea2d9b5">

https://github.com/user-attachments/assets/d61e5864-5db1-4f8b-867b-1f0143f2e8bb

**Comment by jakubcolony** [comment]
This feels subjective, technically contracts allow setting the duration that low, it could be useful for testing or users interacting with the contracts directly.

This is also a custom setting intended for more advanced users, the majority of users would presumably select one of the recommended presets.
