### ISSUE TITLE
[Arbitrary txs] "Edit transaction" incorrectly render a form

### ISSUE THREAD

**Issue by Nortsova** [JoinColony/colonyCDapp#3866]
## Steps to reproduce
Switch to `feat/arbitrary-txs` branch
Open "Arbitrary transaction" action
Add one transaction:
Contract address: `0xeeeafa86903cf2cb5c74a61d3e67844e226730c0`
<img width="481" alt="image" src="https://github.com/user-attachments/assets/3c9f59b7-ab03-4cdd-a797-5a7c6c34ff7b">

Press "Edit details"
<img width="436" alt="image" src="https://github.com/user-attachments/assets/a9992ab3-32cb-4915-a922-1a7012f4fcc6">

Form should be fully filled:
<img width="489" alt="image" src="https://github.com/user-attachments/assets/f6de35a5-0e75-4bf1-9175-d2f0e990f82e">

## Expected behaviour
The `feat/3732-meatball-arbitrary-txs` branch has this functionality fully working. Please delete  `feat/3732-meatball-arbitrary-txs` when this bug will be fixed, it was already merged, I just pushed it to show the working branch.

## Actual behaviour
And for some reason after merging it to `feat/arbitrary-txs` an issue occurs. During the first render the form unexpectedly calls the "watch" function. Ideally, "watch" should only be triggered by the onChange handler.

## Suggestions (optional)
- I see 2 ways of handling this one:
- 1. Understand the difference between branches and fix it.
- 2. Refactor and replace watch with onChange handler.

**Comment by Nortsova** [comment]
this is the fix, I will speak to @rumzledz about how to keep his fix and make the current fix:
<img width="1334" alt="image" src="https://github.com/user-attachments/assets/9eefdbe7-87b3-4461-abd9-5158be7f9bea">

**Comment by rumzledz** [comment]
Add `keepValues: true`:

**Before:**

```js
reset(mergedValues, { keepDirtyValues: true });
```

**After:**

```js
reset(mergedValues, { keepDirtyValues: true, keepValues: true });
```

Let's see how that goes 🤞
