### ISSUE TITLE
OVERVIEW: Port over and wire up UAC with action sagas

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyCDapp#389]
This issue serves as an overview of the status of the UAC.

- Dialogs ready (UI done, wired up with action sagas, and merged):
  - Transfer funds
  - Mint tokens
  - Unlock token
  - Create a new team
  - Edit team
  - Award reputation
  - Smite reputation
  - Upgrade colony
  - Edit colony
  - Payment
  - Manage whitelist
  - Manage tokens
  - Permission management

- Dialogs not ready:
  - Recovery mode (UI done)

**Comment by jakubcolony** [comment]
Linking #445 

BTW. Is that issue covering only actions or motions too?

**Comment by ArmandoGraterol** [comment]
Only actions

**Comment by rdig** [comment]
Closing as no longer relevant
