### ISSUE TITLE
Investigate slider getting stuck

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#390]
See below. Slider is getting stuck.

## Context

[12d80f71-76b0-46c2-8dc9-15eb07d320ee.webm](https://user-images.githubusercontent.com/18473896/231004309-d78ff8dc-7f5b-43fe-a302-bad7822ebd92.webm)

When I reach the limit and try to go back, the slider doesn't move

_Originally posted by @ArmandoGraterol in https://github.com/JoinColony/colonyCDapp/pull/365#pullrequestreview-1378168725_

**Comment by ArmandoGraterol** [comment]
I haven't been able to reproduce this, so it either has been fixed or we need some really really specific situation for the bug to appear. I'll keep an eye out in case this appears again while working on other issues as I've spent enough time trying to reproduce this.

**Comment by willm30** [comment]
Let's close then
