### ISSUE TITLE
Unlock token form briefly shows incorrect state when submitting

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#3945]
## Steps to reproduce

1. Create an "unlock token" action
2. Submit the form

## Expected behaviour

* Form should proceed to the completed action screen

## Actual behaviour

* Form briefly shows incorrect state before proceeding to the completed action screen

https://github.com/user-attachments/assets/63089a01-8e39-49c5-9d0a-cf9e949f8d05

**Comment by olgapod** [comment]
It seems to me fixed with https://github.com/JoinColony/colonyCDapp/issues/3949
<img width="1702" alt="image" src="https://github.com/user-attachments/assets/fb1325e9-f343-40c3-a186-a557069e2a2f" />

**Comment by rdig** [comment]
Then this can be closed then, right ?

**Comment by olgapod** [comment]
@rdig No sorry, It is still broken locally 
<img width="1686" alt="image" src="https://github.com/user-attachments/assets/ef0036e0-27a2-4b85-bd60-cbd80b9527ea" />

**Comment by olgapod** [comment]
I close this issue because it works for me now 
<img width="1568" alt="image" src="https://github.com/user-attachments/assets/61b6334f-6b88-4cee-9292-9ece7480bf91" />
