### ISSUE TITLE
[PROD] Navigation opens a blank action type

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3987]
## Steps to reproduce

1. Navigate to the dashboard/ activity feed.
2. Select any completed action.
3. From the navigation, select 'Create agreement'.
4. A blank action opens. 

## Expected behaviour

* A blank action should never open now we have implemented the new side panel draw options. This can be removed. When the 'Create agreement' menu is selected with a completed action already opened, the 'Create agreement' action should be triggered. 

## Actual behaviour

* When a completed action is opened and the 'Create agreement' is selected from the main navigation, a blank action side panel opens. 

<img width="1719" alt="image" src="https://github.com/user-attachments/assets/0e1ab178-9aa2-4a4e-9977-740d3b185e2f" />

**Comment by olgapod** [comment]
@melyndav It is a duplicate of https://github.com/JoinColony/colonyCDapp/issues/3890

**Comment by melyndav** [comment]
Ahhh nice pick up, thanks @olgapod. I will close this one.
