### ISSUE TITLE
Fix: staking banner disappearing at 9%

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#451]
## Original Comment

Nice work! I did notice a small details and it's that the motion is appearing when the staking is at 9%:
![FireShot Capture 840 - Colony CDapp - localhost](https://user-images.githubusercontent.com/18473896/233250601-0ff47bf6-923f-4f0e-9b33-6b79e1b5e6f1.png)

The banner disappears and the motion appears in the action list. Surely it's some rounding error somewhere? Knowing how JS can be with math stuff. I'm still approving as this is something small that could be dealt with later if we want to

_Originally posted by @ArmandoGraterol in https://github.com/JoinColony/colonyCDapp/pull/410#pullrequestreview-1393158852_

**Comment by ArmandoGraterol** [comment]
@willm30 This was fixed by your PR https://github.com/JoinColony/block-ingestor/pull/69

It seems like the rounding error caused the staking to go over 10% when we staked 9% on 1 side.
