### ISSUE TITLE
Fix `temp-create-data` script 

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#463]
Following the latest version upgrade of `colony-js`, the `temp-create-data` no longer works and gives the following error:

```
Error: Cannot find module '../node_modules/@colony/colony-js/dist/cjs/contracts/factories/latest/MetaTxToken__factory.js'
```

Fixing it most likely requires finding out where the `MetaTxToken__factory` lives now (@chmanie you might be able to help here) and updating the import in the script

**Comment by chmanie** [comment]
I can indeed help. @jakubcolony can you point me to the script?
