### ISSUE TITLE
Wire in Permission Management dialog with motion components and saga

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyCDapp#483]
With the voting reputation extension enabled, the dialog should now have:
- Motion domain selector.
- Force toggle.
- A "Not enough reputation" message if there's no reputation in the motion domain selected.
- The submit button should change to "Create Motion".
- Of course, on submit it should take you to the motion's page.

How this dialog with the extension enabled looks like in the Dapp:
![Image](https://user-images.githubusercontent.com/18473896/234645220-39972b44-6166-4c05-8c1a-05c1dc3756a6.png)

**Comment by willm30** [comment]
Blocked by #457
