### ISSUE TITLE
Wire in Manage Tokens dialog with motion components and saga

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyCDapp#484]
With the voting reputation extension enabled, the dialog should now have:
- Motion domain selector (**Disabled** as you can only create this motion in Root).
- Force toggle.
- A "Not enough reputation" message if there's no reputation in the motion domain selected.
- The submit button should change to "Create Motion".
- Of course, on submit it should take you to the motion's page.

How this dialog with the extension enabled looks like in the Dapp:
![Image](https://user-images.githubusercontent.com/18473896/234645495-6e47b7b5-250d-4ff4-a09c-56c08192e0d3.png)

**Comment by jakubcolony** [comment]
I think it's also blocked by #434
