### ISSUE TITLE
Port Members Page: Components & Routes

### ISSUE THREAD

**Issue by danbr** [JoinColony/colonyCDapp#51]
## Description

- Port over the necessary components, (which should live in components/common)
- Update and introduce new route

**Comment by rdig** [comment]
Please sync with @jakubcolony on this, as he has some plans around refactoring the whole Routes system to better align with react-router v6

**Comment by rdig** [comment]
Yes, please do, as we will no longer have `WalletRequiredRoute` wrapper component, or a wrapper component for a route _at all_ due to both react-router v6's requirements and us finally shedding some legacy baggage _(ie: no longer requiring `ethereal` wallets or instant JWT auth)_
