### ISSUE TITLE
How to store tokens IDs for planned Carbon extension?

### ISSUE THREAD

**Issue by vporton** [JoinColony/colonyCDapp#513]
After several unsuccessful tries in the past, I finally got `colonyCDApp` compiled and working well on my PC. I am going to create an extension to account carbon over [this smartcontract](https://github.com/vporton/carbon-flow). This extension will be done under [that grant](https://builder.gitcoin.co/#/chains/1/registry/0x03506eD3f57892C85DB20C36846e9c808aFe9ef4/projects/314).

It is anticipated that using the extension, the DAO will be able to create one or more carbon tokens identified by a non-negative number (ID).

I have a question: Where can I store the list of several (usually one, but sometimes more) IDs? If the IDs are lost, it is possible to recover them by watching the colony contract (and related contracts) at EtherScan, but that is not easy. So, I need some kind of a small "DB" to store these numbers. Please, advise how to store them.

BTW, this smartcontract is useful not only for accounting carbon, but also for example for accounting salary bonuses in a big company, or anything that can be minted out of an unlimited pool.

**Comment by chmanie** [comment]
Hey @vporton! At this moment we can't support the storage of data of third-party extensions within the CDapp. We might offer a framework of some kind for that in the future but there are no immediate plans for it. For the time being you'd need to set up a persistent storage mechanism yourself. Feel free to get in touch with me any time if you have further questions.
