### ISSUE TITLE
Implement `onError` in UAC dialogs

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#580]
Currently, if there's an error in a saga triggered by a UAC dialog, if the form in question doesn't implement the `onError` option, the form will never know there's been an error in the saga and thus neither will the user. 

This issue is to go through every form and ensure it handles saga errors correctly. 

This can be simulated by manually throwing an error inside the saga:

```
// some-saga.ts

throw new Error('random error to test how form responds')

```

This issue can be split up on a per-form basis to keep prs short and sweet.

**Comment by willm30** [comment]
I would saw this is low priority for current iteration of CDapp. It should definitely be considered as part of the new UI, but pure saga errors can usually be avoided in dev. 

I make the distinction between a "pure saga error", for which the user would receive no visual feedback if we don't respond to it, and an error occuring in a saga that results from a metamask/chain error. The user would receive visual feedback here via the gas station, and these are more common in production. So long as the user has some visual indication there's been an error, they can close the dialog or refresh the browser and try again, and won't be left waiting assuming that nothing's wrong.

**Comment by willm30** [comment]
Related: https://github.com/JoinColony/colonyCDapp/issues/1018

**Comment by rdig** [comment]
Closing as no longer relevant
