### ISSUE TITLE
Filter 0 claims from unclaimed motion stakes

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#614]
Currently, a claim of 0 will show up in the stakes tab, but be unclaimable. This shouldn't be in the claims list at all.

## Context

 Should a claim of 0 tokens show up in the list for the stakes tab? if you go to the transaction, the claim button is disabled.
 
<img width="369" alt="Screenshot 2023-06-05 at 12 47 57 PM" src="https://github.com/JoinColony/colonyCDapp/assets/71563622/5884d4d4-8ec3-4315-a776-4e4820c195dc">

<img width="246" alt="Screenshot 2023-06-05 at 12 47 44 PM" src="https://github.com/JoinColony/colonyCDapp/assets/71563622/504bdf05-32c7-4c74-9ac9-2558c6c084e6">

_Originally posted by @Julianahlk in https://github.com/JoinColony/colonyCDapp/issues/591#issuecomment-1577220063_

**Comment by ArmandoGraterol** [comment]
@willm30 

I'll take this but for the record, you can get a 0 claim by enabling the extension with a 50% voter reward, fully stacking 1 side and then lose with that side

**Comment by willm30** [comment]
@ArmandoGraterol Nice one. Can we please ensure that the motion isn't included at all in the colony's `motionsWithUnclaimedStakes` array, not just that it's filtered out in the client. I.e. we check for it both when the motion is finalized in the block ingestor, and where we handle the logic in the `fetchMotionState` lamda, and if the claim is 0, don't include.
