### ISSUE TITLE
Permissions dialog missing Permissions-based error msg

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#661]
If you have a user without permissions try and access the permissions dialog, they can, but they won't be able to do anything and there's no message as to why. I'm expecting to see the labels that say "Permissions: X, Y, Z needed"

![Image](https://github.com/JoinColony/colonyCDapp/assets/64402732/ee2b21e2-ac50-4d2a-81f1-8a3e67faaefa)

**Comment by Julianahlk** [comment]
@willm30 which branch did find this in? In master, a user is not able to get to the permissions dialog without the architecture role. If this is QA, would the fix just to be bring over the code from Master?

<img width="431" alt="Screenshot 2023-06-20 at 7 42 12 PM" src="https://github.com/JoinColony/colonyCDapp/assets/71563622/4ec82ddf-928d-4d63-a0a2-46633e6d1d20">

**Comment by willm30** [comment]
@Julianahlk QA was recently rebased on master and redeployed so if it's not present on master I'd also not expect to see it in QA--but always worth double checking. In any case, happy if it's already been fixed 😄

**Comment by Julianahlk** [comment]
@willm30 closing this as it looks like its fixed on QA now as well.
