### ISSUE TITLE
Locked token is not showing up as locked if it's not the colony's native token

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#717]
Colony A makes a payment to Colony B in Colony A's (locked) native token.
Colony B adds Colony A's native token to its tokens list, and claims the incoming funds. Now you can see Colony A's native token in Colony B's token balances. 
However, it does not show it as a locked token, even though it is. 

## TODO

-- What is the correct behaviour here?
-- In what sense is the token locked if I can use it to pay another colony?
-- Why do we currently only show the locked icon beside the colony's native token, and not check to see if every token is the native token of some colony which may also be locked?

**Comment by rdig** [comment]
Closing as no longer relevant
