### ISSUE TITLE
Contributor without user profile not displaying correctly

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#757]
Make a payment to an address that is not joined to the colony, and also doesn't have a user profile (e.g. another colony).

There are a few places where this address won't show up correctly:

1. The user picker in the Manage Permissions dialog

![Image](https://github.com/JoinColony/colonyCDapp/assets/64402732/6b423ca0-d0c1-477d-a5cc-11b0340857c6)

2. The members popover:

![Image](https://github.com/JoinColony/colonyCDapp/assets/64402732/6e487184-25a0-4bb5-81c5-cf0e188b1e59)

We should be able to see the address in both cases.

**Comment by rdig** [comment]
Closing as no longer relevant
