### ISSUE TITLE
Improve "Add Safe" step 1 validation

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyCDapp#812]
> When you change from one chain to another with a valid safe address in the input, the status message Safe found on X chain will appear for some milliseconds before being replaced by the correct "This safe doesn't exist in this chain". Unfortunately, I haven't been able to fix this after trying several approaches, if you guys have any ideas then they are 100% welcome.

![Image](https://user-images.githubusercontent.com/18473896/253295183-a87d687b-d99f-44fc-9017-83aed2b0f312.png)

**Comment by thomassdk** [comment]
Closed via #812
