### ISSUE TITLE
Add custom title based on the action to Default Action / Motion pages

### ISSUE THREAD

**Issue by thomassdk** [JoinColony/colonyCDapp#888]
Currently, actions / motions don't get a custom title based on the action, but instead use the following fallback message:
```
`Transaction - {transactionHash} | Colony - {colonyName}`,
```

Once the page is loaded, it should change the title of the action/motion page to one based on the action.

This should be based on the work done in #774

**Comment by rdig** [comment]
Closing as this was already implemeted
