### ISSUE TITLE
Add centralised / decentralised switch on the advanced tab

### ISSUE THREAD

**Issue by chinins** [JoinColony/colonyCDapp#91]
Introduce URL input fields on the advanced tab

Figma specs
https://www.figma.com/file/UzfpoAvGUS6c14du7Y39sCYm/User-Settings?node-id=2006%3A2262&t=UQ8bPdlPZH9PuXhS-0

Waiting fro Arren's input about updated specs - check & start when the specs are finalised.

Until #79 is merged into master, brach off of that PR.

**Comment by rdig** [comment]
@arrenv doesn't know the specs

We just need the toggle for now and a input for the RPC endpoint, that's it.

Anything else can come at a later date.

**Comment by chinins** [comment]
> @arrenv doesn't know the specs
> 
> We just need the toggle for now and a input for the RPC endpoint, that's it.
> 
> Anything else can come at a later date.

What I meant here is UI specs, right now in figma there are 2 switches and we were talking with Arren about having only one. He should confirm/update UI for it. In the initial issue #33 you say yourself `Introduce URL input fields on the advanced tab (ask Product about them)`, which I did and Arren needs to update/confirm what we are doing.

**Comment by rdig** [comment]
Arren can't confirm or update what inputs need to be on the page since "we" are the ones that decide what goes in there.

And currently there's still debates as to what exactly we're going to need for the decentralized version. 

So for now, as to not block this issue any longer, just add the toggle and the RPC input.

**Comment by arrenv** [comment]
@chinins The design with the two toggles are correct, as they are not dependent on one another. You can use each one separately. So, the current design should still be relevant.

**Comment by chinins** [comment]
Cancelling as i'm including it in #79
