### ISSUE TITLE
Store all `UInt256` in DB as string

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#918]
In Solidity, one of the data types is `UInt256` (unsigned 256-bit integer, i.e. a very large number). In Javascript, the `number` data type can only represent integers up to 2^53 – 1 ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)). 

Therefore, if we store `UInt256` values in the database as `Int`, implying a conversion to a javascript `Number` type beforehand, we run the risk of overflow. Generally, this risk is quite small, but nevertheless, it would be an easy win to avoid it entirely by storing all `UInt256` values as strings in the db.

This issue is to enforce this consistently across the CDapp and block ingestor by ensuring that every value contract-level `UInt256` is stored as a `String`, not an `Int`, in the db. 

A hint for what to look for in the block ingestor would be all event arguments that are assumed to be a `BigNumber`. This is highly likely to be a `UInt256` on the contracts.

**Comment by rdig** [comment]
Closing as not relevant anymore
