### ISSUE TITLE
Create enum for use with Icon component rather than string literals

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#92]
Currently, when using the `Icon` component, you pass the name of the svg you want to use as a string literal to the `name` prop, like so:

![iconeg](https://user-images.githubusercontent.com/64402732/203316775-135aab5f-c514-4980-a408-7ee8a6de0441.png)

Going forward, we should use an `enum` to capture all of the options we currently have available and use that to reference the desired svg. Something like:

``` jsx
<Icon name={ICONS.caretRight} />
```

Per this comment: https://github.com/JoinColony/colonyCDapp/pull/83#discussion_r1028524688

**Comment by rdig** [comment]
We also need to investigate if the loader we're using to process SVGs is adequate going forward, as we haven't looked at that in ages

**Comment by rdig** [comment]
No longer relevant
