### ISSUE TITLE
Members query needs to support array for `domainID` for filtering

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#920]
### Story

As a USER, I want to be able to filter and query members in multiple teams at the same time.

### Description

In order to allow the querying of members by multiple teams for listing, sorting and filtering we need to be able to support multiple `domainID`'s in the members query:

Used here `src/components/common/Members/Members.tsx` Line 84

```
  const { data, loading: loadingMembers } = useGetMembersForColonyQuery({
    skip: !colony?.colonyAddress,
    variables: {
      input: {
        colonyAddress: colony?.colonyAddress ?? '',
        domainId: selectedDomain || COLONY_TOTAL_BALANCE_DOMAIN_ID,
        sortingMethod,
      },
    },
    fetchPolicy: 'cache-and-network',
  });
```

Which, will likely need to be used for filtering here or similar - `src/components/frame/v5/pages/MembersPage/hooks.ts`

This filter list also needs to be updated to show the actual teams in a Colony.

### Design

Design that supports the requirement of this functionality:

 - [Figma Link - Members page team filtering](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=2286%3A197006&mode=design&t=oeILWWbYCaeDb5NS-1)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/c4939f1b-d9fe-45df-8073-e28203519780)

### Acceptance Criteria
- [ ] I should be able to return a list of members on the members page from multiple teams at the same time.
- [ ] The list in the filter widget should accurately show the domains in the Colony.

**Comment by jakubcolony** [comment]
@arrenv This feels very much related to https://github.com/JoinColony/colonyCDapp/issues/276, the current implementation of the members query is pretty limited and will not return more than 100 members all while being rather slow, so I think that any modifications to the query (including this one) should be done after we tackle that issue.

**Comment by willm30** [comment]
@jakubcolony Query performance is better after [I refactored it](https://github.com/JoinColony/colonyCDapp/pull/756). Pagination does still need to be thought about, potentially with refactoring to the reputation miner endpoints.

These issues, though, aren't specific to the new UI so I suggest we delegate them for an OKR next quarter or similar, where we can actually sit down and find a good solution.

**Comment by willm30** [comment]
#929
