### ISSUE TITLE
Apply new UI to MembersPopover

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#921]
### Story

As a USER, I want to be able to view the details of other members in a Colony.

### Description

We have details that should appear in the MemberPopover when hovering over a member avatar in a Colony, you can test this by hovering over the avatars on the members page (http://qa-app.colony.io/colony/test6/members).

This was built with mock data, however, this mock data has been removed and now needs to be wired up so that all the details are wired up correctly.

There are cases where a member won't have any Permissions, Reputation in teams, and/or About details. So, we need to handle any combination of these details appearing or not. At the moment, there is a padding issue if the current not wired up details are missing, as showing in the Current state below.

**Change to layout**
There is a need to change the layout of the MemberPopover to make it more compatible with Members being in multiple teams and having different reputation and permissions in different teams. To handle this, we have combined the Reputation and Permissions sections in the Popover and now show both in line, as of the screenshot and Figma link in the Design section. This will need to be updated. Note: the permission pill in this design uses the new Permissions abstraction layer as spec'd here, so may only be UI for now until that is complete and can be wired up - https://www.notion.so/colony/Tiered-user-friendly-Permissions-2c854481658541b387d1944454693f7b?pvs=4.

**Current state:**

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/ec3978fa-be49-4fe9-b30a-911b800e6c46)

Implementation can be found in this file `src/components/v5/shared/UserAvatarPopover/partials/UserInfo.tsx`

### Design

Design that supports the requirement of this functionality, this includes the updated layout changes:

 - [Figma Link - MembersPopover ](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=839%3A42780&mode=design&t=uLg9HY71P0L6xCTB-1)

![Image](https://github.com/JoinColony/colonyCDapp/assets/33682027/7146a82d-d891-474e-8dc6-b0aa42ac64b1)

### Bonus
There are designs to implement contributor type badges, however, this will likely require storing these states in the database, which makes it a more complicated feature then originally spec'd and thus has been deprioritized. Please review briefly the accuracy of this and whether it is a simple implementation or not.

> NOTE: this was intended to be a UI feature for simplicity, but requires getting the full list of members when loading the members page. This also means showing a members contributor type anywhere else is not possible without also getting the full list of members to determine if they fall in the bounds of each type. The likely requires storing the contributor type in the database, which would also require it being updated with each reputation updated. This likely makes it more complicated then initially intended, so if this is found to be the case when looking into it, then it can be left for now and should be removed from the UI

- List of contributor types
    - Top
        - Show members classified as Top
        - Top 20% reputation holder in the Colony
    - Dedicated
        - Show members classified as Dedicated
        - Top 40% reputation holder in the Colony
    - Active
        - Show members classified as Active
        - Top 60% reputation holder in the Colony
    - New
        - Show members classified as New
        - Earned reputation in the last 30 days in the Colony
    - Verified
        - Shows verified contributors
    - General
        - Shows contributors who don’t match any of the above

_Note: The following linked design and screenshots show the old MemberPopover layout, but the top section is still accurate._
 - [Figma Link - Member Contributor Types](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=2226%3A199537&mode=design&t=oeILWWbYCaeDb5NS-1)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/1d600758-47c1-46e3-b371-e8b538224733)

### Acceptance Criteria
- [x] You should be able to see a members reputation in teams that they have reputation in.
- [x] You should be able to see a members permissions they have in Root.
- [ ] The popover should handle any combinations of user details.
- [ ] The MemberPopover layout updates have been made.

**Comment by rdig** [comment]
@arrenv is this still relevant, as from a quick look, everything in this issue has already been implemented via various PRs ?

**Comment by arrenv** [comment]
Yes, closing as way out of date now.
