### ISSUE TITLE
Wire up "Disconnect Wallet" Button

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#945]
### Story

As a USER, I would like to be able to disconnect my wallet from Colony.

### Description

This should be pretty straight forward, however, it was difficult for the external team to get it working at the time with the changes to Onboard.js. All this issue requires is ensuring the "Disconnect wallet" button in the user dropdown menu actually disconnects the users wallet.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/465b5761-c953-41cf-80b7-3de9a9d4c2ec)

### This issue is complete when...

- [x] Clicking the "Disconnect wallet" button should disconnect the users wallet.

**Comment by naynovi** [comment]
https://github.com/JoinColony/colonyCDapp/assets/23479095/0e683af8-dd85-4f3b-aa59-0d35e66016db

If you authenticate with the wrong network, you cannot disconnect your wallet. 
When you clear to reauthenticate you cannot do so and get stuck.

**Comment by rdig** [comment]
@naynovi Cannot replicate your findings.

I can connect to any network, disconnect the wallet, switch networks, reconnect, disconnect, and so on again.

[Screencast from 2024-02-06 09-52-10.webm](https://github.com/JoinColony/colonyCDapp/assets/1193222/bfcc6d19-5b87-4fa5-89c8-9c148a424b77)

**Comment by naynovi** [comment]
thanks Raul, I have given more context t the issue in a new post.
