### ISSUE TITLE
Standardise code formatting 

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#96]
Currently we don't have a standardised approach towards code formatting.
In both Dapp and CDapp, we rely on `.editorconfig` and eslint rules (which is actually discouraged: https://typescript-eslint.io/docs/linting/troubleshooting/formatting), in block-ingestor there are just eslint rules which also seem to be different than the ones in the CDapp.
We don't have a project specific prettier config which is one popular solution.
This issue is to investigate and provide a better code formatting in the CDapp and block-ingestor repositories. The way this should be done is that there's no manual action from the developer required to fix those and code that doesn't adhere to the rules is prevented from being pushed.
@rdig fyi, feel free to comment

**Comment by willm30** [comment]
FYI, I've been using a `.prettierrc` file with the following:

```json
{
  "singleQuote": true,
  "trailingComma": "all"
}
```
and a `.prettierignore` with:

```
*.css
*.graphql
*.json
```
Which does the trick.

**Comment by jakubcolony** [comment]
Hey @willm30, my setup is very similar, I think it does a good job together with prettier defaults regarding line lengths, etc. We'd just have to make sure it doesn't conflict with the existing linting.

I also have a similarly looking `.prettierignore` but the reason I set it up is because without it I was introducing many formatting changes to existing code, maybe this is also something to have a look into and make `.graphql` and `.json` files compatible with whatever formatting setup we end up with?
