### ISSUE TITLE
Wire multiple OneTxPayments payments to new UI

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#979]
### Story

As a USER, I would like to be able pay multiple people a single payment at one time.

### Description

The contracts are currently able to handle multiple simple payments, we would like to be able to support this functionality in the UI by adding an array of simple payments. This should require modifying the `payment.ts` saga to be able support multiple payments as well as wiring up the UI to the updated saga.

### Design

- [Figma link - Multiple Simple payments](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=2729%3A244356&mode=design&t=eRA8ZvbO7kl03cSQ-1)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/fc98f7a8-c0b3-4be9-a47f-9a7559da693b)

### This issue is complete when...

- [x] Update `payment.ts` saga to be able to support multiple simple payments.
- [x] Make relevant changes to block ingestor
- [ ] Correctly wire up new Simple payments UI to the updated saga.

**Comment by rdig** [comment]
Closing this as being superseded by Advanced Payments
