### ISSUE TITLE
Implement multicall transactions on a new colony creation

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#986]
### Description

We would like to incorporate the new multi-call functionality available from [v11 of the contracts](https://github.com/JoinColony/colonyNetwork/releases/tag/glwss2) into CDApp. First off, we would like to implement this when creating a colony by reducing the required number of transactions.

### Implementation
In the case where you are creating a new colony with a new token (screenshot below) you can do the transactions `Create Token`, `Create Colony`, and `Deploy Token Authority` into a (new) function called `createColonyForFrontend`. Then `setTokenAuthority` and `setTokenOwner` can not be combined with multicall. The `Add extension` transaction remains its own, but the two giving permissions to the extension can be combined into one with multicall. This should result in 4 total transactions, down from the 8 as shown.

End result:
 - 1: Creating new Colony
 - 2: Setting up native token
 - 3: Setting up token control
 - 4: Adding payment extension
 - 5: Setting up permissions

One thing to note for the extension steps, is that the last two need the address of the extension which is only available after the extension contract has been created.

For other combinations of colony creation transactions, the same logic can be applied i.e. to determine what can be combined through the contracts, it is wherever methods are in the same contract file, with the additional requirement that if the function ends up doing something that's needed for a second call, then they cannot be combined.

#### Current transaction list
![Screenshot 2023-01-17 163909](https://user-images.githubusercontent.com/33682027/212945456-e1cf7319-0a81-4ede-a32e-0c17110f113c.png)

#### Proposed transaction list
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/bc94eb16-6012-4c13-9a55-246b6a7ae2c5)

### Bonus points
Look into other actions where multiple transactions are required and implement multicall there as well.

**Comment by rdig** [comment]
Closing as this is already done.

See the `createColonyForFrontend` method on the Colony contract, as well as the `colonyCreate` saga: 
- https://github.com/JoinColony/colonyCDapp/blob/master/src/redux/sagas/colony/colonyCreate.ts#L139-L143
- https://github.com/JoinColony/colonyCDapp/blob/master/src/redux/sagas/colony/colonyCreate.ts#L203-L213
